In [ ]:
import xml.etree.ElementTree as ET
tree = ET.parse(r"20250113_025803.xml")
root = tree.getroot()

In [34]:
import pandas as pd

In [30]:
# Create a list to store dictionaries representing each item
Item_List = []
# Iterate through each <item> element
for item_elem in root.findall('<Items>'):
    item_dict = {}
    item_dict['id'] = item_elem.get('id')
    for child_elem in item_elem:
        item_dict[child_elem.tag] = child_elem.text
    Item_List.append(item_dict)

In [31]:
df = pd.DataFrame(Item_List)

In [32]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
import xml.etree.ElementTree as ET
tree = ET.parse(r"PIES File.xml")
root = tree.getroot()

In [61]:
# Create a list to store dictionaries representing each item
Item_List = []
# Iterate through each <item> element
for item_elem in root.findall('.Item MaintenanceType'):
    item_dict = {}
    item_dict['id'] = item_elem.get('id')
    for child_elem in item_elem:
        item_dict[child_elem.tag] = child_elem.text
    Item_List.append(item_dict)

In [63]:
Item_List

[]

In [29]:
df_1 = pd.DataFrame(Item_List_1)

In [30]:
df_1

Empty DataFrame
Columns: []
Index: []