In [6]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np
import os
import pandas as pd
import json

In [7]:
folder_path=r"C:\03_FBG_Work\89_Autocare_Extract\VCdb"

In [8]:
import os
import zipfile
import json
import pandas as pd

dataframes = {}

# Get all ZIP files and sort by filename
zip_files = sorted(
    [f for f in os.listdir(folder_path) if f.endswith('.zip')],
    reverse=True  # Latest name comes first
)

if not zip_files:
    print("No ZIP files found.")
else:
    latest_zip_name = zip_files[0]
    latest_zip_path = os.path.join(folder_path, latest_zip_name)
    print(f"Loading from latest ZIP file (by name): {latest_zip_name}")

    with zipfile.ZipFile(latest_zip_path, 'r') as z:
        for file_name in z.namelist():
            if file_name.endswith('.json'):
                try:
                    with z.open(file_name) as f:
                        data = json.load(f)

                    df = pd.json_normalize(data)
                    key = os.path.splitext(os.path.basename(file_name))[0]
                    dataframes[key] = df

                except json.JSONDecodeError as e:
                    print(f"JSON decoding failed for {file_name}: {e}")
                except Exception as e:
                    print(f"Failed to load {file_name}: {e}")

Loading from latest ZIP file (by name): AutoCare_VCdb_NA_MDHD_enUS_JSON_20250529.zip

In [9]:
df=(dataframes['BaseVehicle']
.merge(dataframes['Vehicle'],how='outer')
.merge(dataframes['Make'],how='outer')
.merge(dataframes['Model'],how='outer')
.merge(dataframes['VehicleType'],on='VehicleTypeID',how='outer')
.merge(dataframes['VehicleToEngineConfig'],on='VehicleID',how='outer')
.merge(dataframes['EngineConfig'],on='EngineConfigID',how='outer')
.merge(dataframes['Valves'],on='ValvesID',how='outer')
.merge(dataframes['Aspiration'],on='AspirationID',how='outer')
.merge(dataframes['EngineDesignation'],on='EngineDesignationID',how='outer')
.merge(dataframes['EngineVIN'],on='EngineVINID',how='outer')
.merge(dataframes['VehicleToDriveType'],on='VehicleID',how='outer')
.merge(dataframes['DriveType'],on='DriveTypeID',how='outer')
.merge(dataframes['EngineBase'],on='EngineBaseID',how='outer')
.merge(dataframes['FuelType'],on='FuelTypeID',how='outer')
.merge(dataframes['VehicleToBrakeConfig'],on='VehicleID',how='outer',suffixes=('_VehicleToBrakeConfig','_VehicleToBrakeConfig2'))
.merge(dataframes['BrakeConfig'],on='BrakeConfigID',how='outer')
.merge(dataframes['BrakeSystem'],on='BrakeSystemID',how='outer')
.merge(dataframes['Region'],on='RegionID',how='outer')
.merge(dataframes['VehicleToClass'],on='VehicleID',how='outer',suffixes=('_VehicleToClass','_VehicleToClass2'))
.merge(dataframes['Class'],on='ClassID',how='outer')
.merge(dataframes['VehicleToWheelbase'],on='VehicleID',how='outer',suffixes=('_VehicleToWheelbase','_VehicleToWheelbase2'))
.merge(dataframes['WheelBase'],left_on='WheelbaseID',right_on='WheelBaseID',how='outer')
.merge(dataframes['VehicleToBodyStyleConfig'],on='VehicleID',how='outer',suffixes=('VehicleToBodyStyleConfig','VehicleToBodyStyleConfig2'))
.merge(dataframes['BodyStyleConfig'],on='BodyStyleConfigID',how='outer')
.merge(dataframes['BodyType'],on='BodyTypeID',how='outer')
.merge(dataframes['EngineVersion'],on='EngineVersionID',how='outer')
)
df

,BaseVehicleID,YearID,MakeID,ModelID,VehicleID,SubmodelID,RegionID,Source_x,PublicationStageID,PublicationStageSource,...,WheelBaseID,WheelBase,WheelBaseMetric,VehicleToBodyStyleConfigID,BodyStyleConfigID,Source,BodyNumDoorsID,BodyTypeID,BodyTypeName,EngineVersion
0,140370.0,2010.0,40.0,6969.0,238575.0,20.0,3.0,None,4.0,OE Publication,...,69.0,160.5,407.7,292235.0,51.0,None,7.0,28.0,Cab & Chassis,N/A
1,140370.0,2010.0,40.0,6969.0,238575.0,20.0,3.0,None,4.0,OE Publication,...,69.0,160.5,407.7,292235.0,51.0,None,7.0,28.0,Cab & Chassis,N/A
2,140370.0,2010.0,40.0,6969.0,238575.0,20.0,3.0,None,4.0,OE Publication,...,69.0,160.5,407.7,292234.0,104.0,None,11.0,34.0,Stripped Chassis,N/A
3,140370.0,2010.0,40.0,6969.0,238575.0,20.0,3.0,None,4.0,OE Publication,...,69.0,160.5,407.7,292234.0,104.0,None,11.0,34.0,Stripped Chassis,N/A
4,123140.0,2009.0,71.0,22644.0,200021.0,20.0,1.0,None,4.0,VCDB Batch,...,4.0,U/K,U/K,201107.0,108.0,None,4.0,40.0,U/K,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656310,165517.0,1973.0,40.0,30642.0,333367.0,20.0,1.0,None,1.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656311,165544.0,1963.0,40.0,30645.0,333394.0,20.0,1.0,None,1.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656312,178544.0,2022.0,47.0,27431.0,394441.0,20.0,1.0,None,1.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656313,179526.0,2025.0,47.0,21521.0,412702.0,20.0,2.0,None,1.0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1065.0,164.8,418.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_All=df[['BaseVehicleID',"VehicleTypeName", 'YearID','MakeName','ModelName','BlockType', 'Cylinders','Liter','ValvesPerEngine','CC','CID','FuelTypeName','AspirationName','EngineDesignationName','EngineVINName','DriveTypeName','RegionAbbr','BodyTypeName','WheelbaseID','WheelBase','WheelBaseMetric','EngineVersion','BrakeSystemName']] #"ClassName",
df_All = df_All.drop_duplicates().reset_index(drop=True)
df_All

,BaseVehicleID,VehicleTypeName,YearID,MakeName,ModelName,BlockType,Cylinders,Liter,ValvesPerEngine,CC,...,EngineDesignationName,EngineVINName,DriveTypeName,RegionAbbr,BodyTypeName,WheelbaseID,WheelBase,WheelBaseMetric,EngineVersion,BrakeSystemName
0,140370.0,Medium/Heavy Truck,2010.0,Dodge,Ram 4000,V,8,5.7,16,-,...,HEMI,-,AWD,MEX,Cab & Chassis,69.0,160.5,407.7,N/A,Power
1,140370.0,Medium/Heavy Truck,2010.0,Dodge,Ram 4000,V,8,5.7,16,-,...,HEMI,-,RWD,MEX,Cab & Chassis,69.0,160.5,407.7,N/A,Power
2,140370.0,Medium/Heavy Truck,2010.0,Dodge,Ram 4000,V,8,5.7,16,-,...,HEMI,-,AWD,MEX,Stripped Chassis,69.0,160.5,407.7,N/A,Power
3,140370.0,Medium/Heavy Truck,2010.0,Dodge,Ram 4000,V,8,5.7,16,-,...,HEMI,-,RWD,MEX,Stripped Chassis,69.0,160.5,407.7,N/A,Power
4,123140.0,Medium/Heavy Truck,2009.0,International,3200,V,8,6.4,32,6369,...,MaxxForce 7,-,U/K,USA,U/K,4.0,U/K,U/K,N/A,U/K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656310,165517.0,Medium/Heavy Truck,1973.0,Dodge,S600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN
656311,165544.0,Medium/Heavy Truck,1963.0,Dodge,W500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN
656312,178544.0,Medium/Heavy Truck,2022.0,Chevrolet,LCF 6500XD,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,USA,NaN,NaN,NaN,NaN,NaN,NaN
656313,179526.0,Medium/Heavy Truck,2025.0,Chevrolet,Express 4500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,CAN,NaN,NaN,NaN,NaN,NaN,NaN
656314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,164.8,418.5,NaN,NaN

In [26]:
datetext=latest_zip_name.split("_")[-1].split(".")[0]

In [ ]:
df_All.to_excel(fr"Output\{datetext}_Autocare_VCdb_MDHD.xlsx", index=False, engine='openpyxl',sheet_name='Autocare_VCdb')

In [ ]:
df = df[(df['MakeName'].str.contains("Thor Motor Coach", regex=False, na=False, case=False)) | (df['MakeName'].str.contains("Winnebago", regex=False, na=False, case=False))]
df = df[df['YearID'] > 2019]

df_filtered=df[['YearID','MakeName','ModelName','Liter', 'Cylinders','BlockType','FuelTypeName','BrakeSystemName',"VehicleTypeName"]] #"ClassName",
df_filtered = df_filtered.drop_duplicates()
df_filtered

In [ ]:
df.columns

In [ ]:
df.ModelName.unique()