In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
from selenium.webdriver.common.action_chains import ActionChains
warnings.filterwarnings("ignore")
import os

In [11]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://shop.advanceautoparts.com/')

## Extraction of Comments

In [10]:
cols_comment =[ "Part Number", "Product Name", "Title", "Comments","Star", "Review Date"] #,'Review_Mentions','Standards'
df = pd.DataFrame(columns=cols_comment)
count=0

In [12]:
numbers=["18-180",
"26-160",
"55-121",
"XC22",
"XC26"
]

In [15]:
for s in range(len(numbers)):
    driver.get("https://shop.advanceautoparts.com/")
    searchbox=driver.find_element(By.ID,"search-input")
    searchbox.click()
    searchbox.send_keys(numbers[s])
    searchbox.send_keys(Keys.ENTER)
    sleep(4)
    driver.find_elements(By.CLASS_NAME,"css-141bbgw")[0].find_element(By.CLASS_NAME,'css-1bwgs0x').click()
    sleep(4)
    print(driver.find_element(By.CLASS_NAME,"css-tvrt7a").text)
    try:
        for j in range(500): 
            print (j)
            check1=driver.find_elements(By.CLASS_NAME,"css-50kmc7")[-1].text
            for i in range(5):   
                df.loc[count,"Part Number"]= driver.find_element(By.CLASS_NAME,"css-tvrt7a").text
                df.loc[count,"Product Name"]= driver.find_element(By.CLASS_NAME,"css-1vorsr4").text
                df.loc[count,"Star"]= int(driver.find_elements(By.XPATH, '//div[contains(@class, "css-1nqas9f")]//span[@aria-label]')[i].get_attribute('aria-label').split(" out")[0])
                df.loc[count,"Title"]= driver.find_elements(By.CSS_SELECTOR,'[class="css-1nqas9f"]')[i].find_element(By.CSS_SELECTOR,'[class="css-sske0x"]').text
                df.loc[count,"Review Date"]= driver.find_elements(By.CSS_SELECTOR,'[class="css-1nqas9f"]')[i].find_element(By.CSS_SELECTOR,'[class="css-1fco2k9"]').text
                df.loc[count,"Comments"]= driver.find_elements(By.CSS_SELECTOR,'[class="css-1nqas9f"]')[i].find_element(By.CSS_SELECTOR,'[class="css-uw7cx0"]').text
                count=count+1
            element = driver.find_element(By.CSS_SELECTOR,'[class="css-9dfio9"]')
            actions = ActionChains(driver)
            actions.move_to_element(element).perform()
            element.click()
            sleep(2)
            check2=driver.find_elements(By.CLASS_NAME,"css-50kmc7")[-1].text
            if check1==check2:
                break
        clear_output(wait=True)
    except:
        pass
        clear_output(wait=True)
    driver.get("https://shop.advanceautoparts.com/")
    sleep(1)

Part # XC26
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [16]:
df

,Part Number,Product Name,Title,Comments,Star,Review Date
0,Part # 18-180,TRICO Flex Flex Beam 18'' Wiper Blade: Durable...,Works good,Fits my car well!,5,Submitted 2 days ago
1,Part # 18-180,TRICO Flex Flex Beam 18'' Wiper Blade: Durable...,Works good,Fits my car really well.,5,Submitted 2 days ago
2,Part # 18-180,TRICO Flex Flex Beam 18'' Wiper Blade: Durable...,Works better than any other brand,Leaves windshield clear and clean very good wi...,5,Submitted 5 days ago
3,Part # 18-180,TRICO Flex Flex Beam 18'' Wiper Blade: Durable...,Wipers,Great product reasonably priced,5,Submitted 7 days ago
4,Part # 18-180,TRICO Flex Flex Beam 18'' Wiper Blade: Durable...,Wipers,Good product reasonably priced,5,Submitted 7 days ago
...,...,...,...,...,...,...
4534,Part # XC26,Carquest XtraClear Premium Beam 26'' Wiper Bla...,yes,works well,4,Verified Buyer - Submitted 8 years ago
4535,Part # XC26,Carquest XtraClear Premium Beam 26'' Wiper Bla...,Nice wipers,These wipers work well. Instructions are very ...,5,Verified Buyer - Submitted 8 years ago
4536,Part # XC26,Carquest XtraClear Premium Beam 26'' Wiper Bla...,Specified part wouldn't fit,This wasn't a good experience. Used store's ap...,1,Verified Buyer - Submitted 8 years ago
4537,Part # XC26,Carquest XtraClear Premium Beam 26'' Wiper Bla...,good wiper performance / no streaks ... for va...,see above,5,Verified Buyer - Submitted 8 years ago
4538,Part # XC26,Carquest XtraClear Premium Beam 26'' Wiper Bla...,NaN,NaN,NaN,NaN

In [28]:
OFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Data Scraping - Amazon data\AAP"
from datetime import date
Date=str(date.today()).replace("-","")
Source="AAP_"
search_text="Wipers"
with pd.ExcelWriter(OFolder+'\\'+f'{Date}_{Source}ProductReviews_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Reviews')

## Extraction of Data

In [ ]:
list=driver.find_elements(By.CSS_SELECTOR,'[data-testid="dog-ear"]')
len(list)

19

In [34]:
cols =['Sl.No'] #,'Review_Mentions','Standards'
df = pd.DataFrame(columns=cols)
count=0

In [65]:
dols=driver.find_elements(By.CLASS_NAME,"css-15cggpf")
cents=driver.find_elements(By.CLASS_NAME,"css-2izyy6")
titles=driver.find_elements(By.CLASS_NAME,"css-cm8roc")
PNS=driver.find_elements(By.CLASS_NAME,"css-scvhiv")
Links=driver.find_elements(By.CSS_SELECTOR,'div.css-195wmup a.css-vurnku')
for dol,cent,title,PN,Link in zip(dols,cents,titles,PNS,Links):

    df.loc[count,"Sl.No"]=count
    df.loc[count,'Price']=float(dol.text+cent.text)
    df.loc[count,'PartNumber']=PN.text.split("#")[1]
    df.loc[count,"Title"]=title.get_attribute('title')
    df.loc[count,'Link']=Link.get_attribute('href')
    count=count+1

len(df)

455

In [66]:
df

,Sl.No,Price,PartNumber,Title,Link
0,0,10.99,SP-532-X,Motorcraft Spark Plug,https://shop.advanceautoparts.com/p/motorcraft...
1,1,7.49,SP-497-X,Motorcraft SPARK PLUG,https://shop.advanceautoparts.com/p/motorcraft...
2,2,16.99,SP-580-X,Motorcraft SPARK PLUG,https://shop.advanceautoparts.com/p/motorcraft...
3,3,12.99,SP-594,Motorcraft Enhance Engine Performance with Rel...,https://shop.advanceautoparts.com/p/motorcraft...
4,4,3.79,R83TS,ACDelco Conventional Spark Plug,https://shop.advanceautoparts.com/p/acdelco-co...
...,...,...,...,...,...
450,450,11.55,F1000605042ACD,ACDelco Spark Plug,https://shop.advanceautoparts.com/p/acdelco-sp...
451,451,32.66,F20434135809MTR,Motorcraft SINGLE LEAD SPARK PL,https://shop.advanceautoparts.com/p/motorcraft...
452,452,38.26,F20431351199MTR,Motorcraft SINGLE LEAD SPARK PL,https://shop.advanceautoparts.com/p/motorcraft...
453,453,18.29,355H,ACDelco Specific FitSpark Plug Wire,https://shop.advanceautoparts.com/p/acdelco-sp...
454,454,21.80,F20432139054MTR,Motorcraft Single Lead Spark Pl,https://shop.advanceautoparts.com/p/motorcraft...