# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

from janitor import xlsx_table

# 2. Defining the Product Information and Location

In [2]:
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\17_Agility_Autoparts'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\17_Agility_Autoparts\Inputs'
filename="Agility Interchange.xlsx"
df=pd.read_excel(IFolder+'\\'+filename)
#df=xlsx_table(IFolder+'\\'+filename,sheetname="Photos", table="Data_List")
df

,Spectra Part #,Delphi Part #,Carter Part #,OE Part Number,Applications,Agility interchange,Agility interchange 2
0,-------,-------,2396,NaN,"Ford 300 (1963), Ford B600 (1980-1986), Ford B...",NaN,NaN
1,-------,-------,3082,NaN,Replacement element for bowl filters- used wit...,NaN,NaN
2,-------,-------,156385,NaN,NaN,NaN,NaN
3,-------,-------,156386,NaN,NaN,NaN,NaN
4,FPW2,FA10002,888159,"4688 376, 5179 977AA","Chrysler Town & Country (1991-1995), Dodge Car...",4065030.0,NaN
...,...,...,...,...,...,...,...
3687,-------,-------,P77587M,7702042251,"Toyota RAV4 2019-2023, Venza 2021-2023, Lexus ...",NaN,NaN
3688,-------,FG2326,P77588M,JL3Z9H307G,Ford F-150 2018-2020,NaN,NaN
3689,-------,-------,P77589M,ML3Z9H307C,Ford F-150 2021-2023,NaN,NaN
3690,-------,-------,P77590M,84592594,"Chevrolet Equinox 2018-2019, GMC Terrain 2018-...",NaN,NaN
3691,NaN,NaN,P77538M,68409160AE,Ram 1500 2019-2020,NaN,NaN

In [3]:
df['Spectra Part #']=df['Spectra Part #'].fillna("-------")
df['Delphi Part #']=df['Delphi Part #'].fillna("-------")
df['Carter Part #']=df['Carter Part #'].fillna("-------")
df['OE Part Number']=df['OE Part Number'].fillna("-------")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3692 entries, 0 to 3691
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Spectra Part #         3692 non-null   object
 1   Delphi Part #          3692 non-null   object
 2   Carter Part #          3692 non-null   object
 3   OE Part Number         3692 non-null   object
 4   Applications           2440 non-null   object
 5   Agility interchange    44 non-null     float64
 6   Agility interchange 2  5 non-null      float64
dtypes: float64(2), object(5)
memory usage: 202.0+ KB

In [5]:
cols=df.columns
cols

Index(['Spectra Part #', 'Delphi Part #', 'Carter Part #', 'OE Part Number',
       'Applications', 'Agility interchange', 'Agility interchange 2'],
      dtype='object')

In [6]:
cols1 =['Sl.No'] #,'Review_Mentions'
df1= pd.DataFrame(columns=cols1)

In [7]:
count=0

for j in range(2):
    print(cols[j])
    for i in range(len(df)):
        if "-------" not in str(df.loc[i,cols[j]]):
            df1.loc[count,"Sl.No"]=count+1
            df1.loc[count,"Part Number Type"]=cols[j]        
            df1.loc[count,"Part Number"]=str(df.loc[i,cols[j]])
            count=count+1

Spectra Part #
Delphi Part #

In [8]:
df1

     Sl.No Part Number Type Part Number
0        1   Spectra Part #        FPW2
1        2   Spectra Part #        FPW1
2        3   Spectra Part #        FPW3
3        4   Spectra Part #        FPW4
4        5   Spectra Part #        FPW5
...    ...              ...         ...
3753  3754    Delphi Part #     HM10043
3754  3755    Delphi Part #      FG2255
3755  3756    Delphi Part #      FG2130
3756  3757    Delphi Part #      FG2270
3757  3758    Delphi Part #      FG2326

[3758 rows x 3 columns]

In [9]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://apdi.mycarparts.net/home')

In [10]:
cols2 =['Sl.No'] #,'Review_Mentions'
df2= pd.DataFrame(columns=cols2)
count=0

In [15]:
from tqdm import tqdm
for i in tqdm(range(2050,len(df1))):
    print(i)
    search_bar=driver.find_element(By.CSS_SELECTOR,'[placeholder="Part Number"]')
    search_bar.click()
    p=df1['Part Number'][i]
    search_bar.send_keys(p)
    search_bar.submit()
    sleep(1)
    es=driver.find_elements(By.CSS_SELECTOR,'[style="border-left: 0; border-right: 0"]')
    ds=driver.find_elements(By.CSS_SELECTOR,'[class="link"]')
    for e,d in zip(es,ds):
        df2.loc[count,"Sl.No"]=count
        df2.loc[count,"Agility Interchange"]=e.text.split('\n')[0]
        df2.loc[count,"Agility Product"]=e.text.split('\n')[1]
        df2.loc[count,"Part Number Type"]=df1.loc[i,"Part Number Type"]     
        df2.loc[count,"Part Number"]=df1.loc[i,"Part Number"]
        df2.loc[count,"index1"]=i
        df2.loc[count,"Interchange_BrandPartNumber"]=d.text.split("\n")[0]
        df2.loc[count,"Brand"]=d.text.split("\n")[1].split(": ")[1]
        count=count+1
    search_bar.clear()
    clear_output(wait=True)

100%|██████████| 1708/1708 [32:04<00:00,  1.13s/it]

In [16]:
colls=['Sl.No','index1','Part Number Type','Part Number',"Interchange_BrandPartNumber",'Brand','Agility Product','Agility Interchange']
df2=df2[colls]

In [17]:
df2

,Sl.No,index1,Part Number Type,Part Number,Interchange_BrandPartNumber,Brand,Agility Product,Agility Interchange
0,0,0.0,Spectra Part #,FPW2,FPW2,Spectra Premium,Fuel Pump Wiring Harness,4065030
1,1,1.0,Spectra Part #,FPW1,FPW1,Spectra Premium,Fuel Pump Wiring Harness,4065034
2,2,1.0,Spectra Part #,FPW1,FPW15,Spectra Premium,Fuel Pump Wiring Harness,4065032
3,3,3.0,Spectra Part #,FPW4,FPW4,Spectra Premium,Fuel Pump Wiring Harness,4065031
4,4,4.0,Spectra Part #,FPW5,FPW53,Spectra Premium,Fuel Pump Wiring Harness,4065033
...,...,...,...,...,...,...,...,...
3416,3416,3733.0,Delphi Part #,FG1140,FG1140,Delphi,Fuel Pump Module Assembly,4010640
3417,3417,3737.0,Delphi Part #,FG1652,FG1652,Delphi,Fuel Pump Module Assembly,4011409
3418,3418,3739.0,Delphi Part #,FG2317,FG2317,Delphi,Fuel Pump Module Assembly,4011518
3419,3419,3740.0,Delphi Part #,FG2479,FG2479,Delphi,Fuel Pump Module Assembly,4010554
3420,3420,3752.0,Delphi Part #,HM10030,HM10030,Delphi,Direct Injection High Pressure Fuel Pump,4032017

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [18]:
with pd.ExcelWriter(OFolder+'\\'+f'ProductDetails_'+"Agility2"+'.xlsx') as writer:  # doctest: +SKIP
    #df.to_excel(writer,index=False, sheet_name='Raw')
    df.to_excel(writer,index=False, sheet_name='Raw')
    df1.to_excel(writer,index=True, sheet_name='others')
    df2.to_excel(writer,index=False, sheet_name='Part_details')

# 99. Archived Codes