# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

In [2]:
# !pip install -U pip setuptools wheel
# !pip install -U spacy
# !python -m spacy download en_core_web_sm
# import spacy

# nlp = spacy.load("en_core_web_sm")

# 2. Defining the Product Information and Location

In [31]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][72]
print(search_text)
Source="Amazon"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

filename=Source+'ProductLinks_'+search_text+'.xlsx'
df1=pd.read_excel(IFolder+'\\'+filename)
imagepath=fr"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\{search_text}\ProductImage"
if not os.path.exists(imagepath):
    os.makedirs(imagepath)
df1

                           Product Name
0                         Ignition Coil
1               Windshield Washer Pumps
2                 coupler trailer locks
3   Adjustable Trailer Hitch Ball Mount
4                        Vacuum Cleaner
..                                  ...
68                  Drum Brake Tool Kit
69                  Brake Spring Pliers
70               swing away hitch mount
71                      Garage Products
72                        Oxygen Sensor

[73 rows x 1 columns]
Oxygen Sensor

     Unnamed: 0                                 Links  Name       ASINs
0             0  https://www.amazon.com/dp/B000XETMW0   NaN  B000XETMW0
1             1  https://www.amazon.com/dp/B00GYG3R2W   NaN  B00GYG3R2W
2             2  https://www.amazon.com/dp/B000CF3W9O   NaN  B000CF3W9O
3             3  https://www.amazon.com/dp/B00EZQK9RY   NaN  B00EZQK9RY
4             4  https://www.amazon.com/dp/B000CF3WOY   NaN  B000CF3WOY
..          ...                                   ...   ...         ...
495         496  https://www.amazon.com/dp/B07D9JRW4T   NaN  B07D9JRW4T
496         497  https://www.amazon.com/dp/B07DHGN425   NaN  B07DHGN425
497         498  https://www.amazon.com/dp/B08KRWBQB4   NaN  B08KRWBQB4
498         499  https://www.amazon.com/dp/B09191YCM2   NaN  B09191YCM2
499         500  https://www.amazon.com/dp/B0CR31F6JT   NaN  B0CR31F6JT

[500 rows x 4 columns]

In [9]:
Linklist=["https://www.amazon.com/dp/B0843CPBCZ",
"https://www.amazon.com/dp/B0843CQDS4",
"https://www.amazon.com/dp/B0BKQZSRLP",
"https://www.amazon.com/dp/B0BTTYN6WN",
"https://www.amazon.com/dp/B0843CPXZR",
"https://www.amazon.com/dp/B0BTTYWFGN",
"https://www.amazon.com/dp/B0843CW16D",
"https://www.amazon.com/dp/B0843CQFRT",
"https://www.amazon.com/dp/B0843D1DSD",
"https://www.amazon.com/dp/B0843CV98Z",
"https://www.amazon.com/dp/B0843D1QDV",
"https://www.amazon.com/dp/B0843CV983",
"https://www.amazon.com/dp/B0843D88MX",
"https://www.amazon.com/dp/B0843D1DQV",
"https://www.amazon.com/dp/B0843CPBB7",
"https://www.amazon.com/dp/B0843D56R1",
"https://www.amazon.com/dp/B0843CQ9GR",
"https://www.amazon.com/dp/B00LEBK96O",
"https://www.amazon.com/dp/B0BTTXRGMH",
"https://www.amazon.com/dp/B0B15LZQ74",
"https://www.amazon.com/dp/B0843D6G3B",
"https://www.amazon.com/dp/B0843D2QGW",
"https://www.amazon.com/dp/B0843CTC2Q",
"https://www.amazon.com/dp/B0843CYX5D",
"https://www.amazon.com/dp/B0843CT6D6",
"https://www.amazon.com/dp/B0843CWLVL",
"https://www.amazon.com/dp/B0843D88NM",
"https://www.amazon.com/dp/B0843CZRF7",
"https://www.amazon.com/dp/B0BTTZRFCR",
"https://www.amazon.com/dp/B0BTTYBFNQ",
"https://www.amazon.com/dp/B001BADC58",
"https://www.amazon.com/dp/B00LEBKDOC",
"https://www.amazon.com/dp/B0843CZRBL",
"https://www.amazon.com/dp/B0843CQDR9",
"https://www.amazon.com/dp/B0BTTZT6DS",
"https://www.amazon.com/dp/B0843D2NSW",
"https://www.amazon.com/dp/B003BZQY7Y",
"https://www.amazon.com/dp/B0B1W3HFJZ",
"https://www.amazon.com/dp/B0843CW9W7",
"https://www.amazon.com/dp/B0843CZRCH",
"https://www.amazon.com/dp/B0843D22H3",
"https://www.amazon.com/dp/B0843D648T",
"https://www.amazon.com/dp/B0843CPXZ1",
"https://www.amazon.com/dp/B0BTTZ9YWK",
"https://www.amazon.com/dp/B0843CWLX7",
"https://www.amazon.com/dp/B0843D648D",
"https://www.amazon.com/dp/B00PSJ51XE",
"https://www.amazon.com/dp/B0BTV1ZZYV",
"https://www.amazon.com/dp/B0843CWLT8",
"https://www.amazon.com/dp/B0843CW16H",
"https://www.amazon.com/dp/B0843CW15G",
"https://www.amazon.com/dp/B00LEBK978",
"https://www.amazon.com/dp/B0843CWMXP",
"https://www.amazon.com/dp/B001DGEY1Q",
"https://www.amazon.com/dp/B0843CRXDF",
"https://www.amazon.com/dp/B0843D4FZW",
"https://www.amazon.com/dp/B0844S4XJR",
"https://www.amazon.com/dp/B0843CQDTQ",
"https://www.amazon.com/dp/B0BTTYBFFF",
"https://www.amazon.com/dp/B01HBHF1S0",
"https://www.amazon.com/dp/B0843D1Z31",
"https://www.amazon.com/dp/B0BTTYTFL3",
"https://www.amazon.com/dp/B0843CWMYQ",
"https://www.amazon.com/dp/B0BTTY844R",
"https://www.amazon.com/dp/B0BTTY585Y",
"https://www.amazon.com/dp/B0843CT6DR",
"https://www.amazon.com/dp/B0843CQBCS",
"https://www.amazon.com/dp/B0BTTYC4YG",
"https://www.amazon.com/dp/B0843CQFRK",
"https://www.amazon.com/dp/B0843CWMYR",
"https://www.amazon.com/dp/B000CB3X4W",
"https://www.amazon.com/dp/B0843CWC7K",
"https://www.amazon.com/dp/B0BTTY43TP",
"https://www.amazon.com/dp/B0BTV1HL55",
"https://www.amazon.com/dp/B0009IK5QW",
"https://www.amazon.com/dp/B0BTTY29KZ",
"https://www.amazon.com/dp/B0843CZN2X",
"https://www.amazon.com/dp/B0843D1QCG",
"https://www.amazon.com/dp/B0B15NKQVG",
"https://www.amazon.com/dp/B0843CT6C6",
"https://www.amazon.com/dp/B001DGKN2A",
"https://www.amazon.com/dp/B0BWLYK1GJ",
"https://www.amazon.com/dp/B0BTTZSLL6",
"https://www.amazon.com/dp/B09HSRSD7L",
"https://www.amazon.com/dp/B0843D2QFY",
"https://www.amazon.com/dp/B0843D755C",
"https://www.amazon.com/dp/B0843CRXCS",
"https://www.amazon.com/dp/B0BKR2D9Q2",
"https://www.amazon.com/dp/B0843CW36S",
"https://www.amazon.com/dp/B01HBHF6M6",
"https://www.amazon.com/dp/B0843CW9X5",
"https://www.amazon.com/dp/B0843D1QCP",
"https://www.amazon.com/dp/B0BWLW36G4",
"https://www.amazon.com/dp/B0843CQDRL",
"https://www.amazon.com/dp/B00LEBKI1A",
"https://www.amazon.com/dp/B0843CR1BM",
"https://www.amazon.com/dp/B00LEBKHL6",
"https://www.amazon.com/dp/B0843D4FVM",
"https://www.amazon.com/dp/B0843D1SL1",
"https://www.amazon.com/dp/B099DL9CNH",
"https://www.amazon.com/dp/B0BKQZMGMX",
"https://www.amazon.com/dp/B0B15N7K6B",
"https://www.amazon.com/dp/B0BKQZ5JHT",
"https://www.amazon.com/dp/B0BKR1ZVYT",
"https://www.amazon.com/dp/B0BKR21Y2X",
"https://www.amazon.com/dp/B0843D647H",
"https://www.amazon.com/dp/B0BWLP51PK",
"https://www.amazon.com/dp/B0BWM3THT8",
"https://www.amazon.com/dp/B099FKVR2R",
"https://www.amazon.com/dp/B0BTTYWMHF",
"https://www.amazon.com/dp/B0BKQXFBQH",
"https://www.amazon.com/dp/B0BWLZZL3L",
"https://www.amazon.com/dp/B0BTTXRL65",
"https://www.amazon.com/dp/B0BKR2HSBS",
"https://www.amazon.com/dp/B0BWLNZ397",
"https://www.amazon.com/dp/B0BTTZ9K46",
"https://www.amazon.com/dp/B0BTTZQ5KF",
"https://www.amazon.com/dp/B099DGGGZH",
"https://www.amazon.com/dp/B0BWLTNSR6",
"https://www.amazon.com/dp/B0BKQYXNBJ",
"https://www.amazon.com/dp/B0B15LXMGN",
"https://www.amazon.com/dp/B0BKQYCD67",
"https://www.amazon.com/dp/B0843CTC39",
"https://www.amazon.com/dp/B0BWLXP8V6",
"https://www.amazon.com/dp/B0BTTWNXDR",
"https://www.amazon.com/dp/B0BWM1DK1H",
"https://www.amazon.com/dp/B0BWLV9MR4",
"https://www.amazon.com/dp/B0B15N3KWG",
"https://www.amazon.com/dp/B0B15L6TMF",
"https://www.amazon.com/dp/B0BTTZNKF2",
"https://www.amazon.com/dp/B0BTTYC1F7",
"https://www.amazon.com/dp/B0BTTWM5SF",
"https://www.amazon.com/dp/B0BTTXMYXT",
"https://www.amazon.com/dp/B0BTTZSHZZ",
"https://www.amazon.com/dp/B099DGLSW1",
"https://www.amazon.com/dp/B0B15MLDLL",
"https://www.amazon.com/dp/B0B15MS6BB",
"https://www.amazon.com/dp/B0BKQVYHCM",
"https://www.amazon.com/dp/B0B15N5W7K",
"https://www.amazon.com/dp/B0BWLKL692",
"https://www.amazon.com/dp/B09HSS1VSK",
"https://www.amazon.com/dp/B0BWM3MLNP",
"https://www.amazon.com/dp/B0BWLW95FD",
"https://www.amazon.com/dp/B0BWLQ5FT5",
"https://www.amazon.com/dp/B0B15LP5BR",
"https://www.amazon.com/dp/B0BWLX78VX",
"https://www.amazon.com/dp/B0BTTZFLPQ",
"https://www.amazon.com/dp/B0BWLVSYMX",
"https://www.amazon.com/dp/B0B15LYGWM",
"https://www.amazon.com/dp/B0BTTYFGCM",
"https://www.amazon.com/dp/B0BKQX2XVF",
"https://www.amazon.com/dp/B0BKR1KPML",
"https://www.amazon.com/dp/B0BTTYQ51S",
"https://www.amazon.com/dp/B0BKQWGKRM",
"https://www.amazon.com/dp/B0BKR375GR",
"https://www.amazon.com/dp/B0BWLPQGWX",
"https://www.amazon.com/dp/B0B1W1YT8X",
"https://www.amazon.com/dp/B0BWLYH1X5",
"https://www.amazon.com/dp/B0B15MSBKP",
"https://www.amazon.com/dp/B0BWLRZQSS",
"https://www.amazon.com/dp/B0BKR28QQ5",
"https://www.amazon.com/dp/B0B15LYVCV",
"https://www.amazon.com/dp/B0BTTY9DN1",
"https://www.amazon.com/dp/B099DMSZQP",
"https://www.amazon.com/dp/B0BTTZK8M1",
"https://www.amazon.com/dp/B0BTTZ5B5R",
"https://www.amazon.com/dp/B0B15LSHGF",
"https://www.amazon.com/dp/B0BWLMQXVJ",
"https://www.amazon.com/dp/B0BWM7MDTB",
"https://www.amazon.com/dp/B0B15LYZDS",
"https://www.amazon.com/dp/B0BKR22233",
"https://www.amazon.com/dp/B0009IK5QC",
"https://www.amazon.com/dp/B0BWLM23S9",
"https://www.amazon.com/dp/B0BKQZDPYT",
"https://www.amazon.com/dp/B0BWLMQ7MQ",
"https://www.amazon.com/dp/B0BKQZKD6F",
"https://www.amazon.com/dp/B099DRL7HH",
"https://www.amazon.com/dp/B0BTTYFHFL",
"https://www.amazon.com/dp/B0B15KV32J",
"https://www.amazon.com/dp/B0BWLPGCXD",
"https://www.amazon.com/dp/B0BTTZF18Y",
"https://www.amazon.com/dp/B0CN3PPDN7",
"https://www.amazon.com/dp/B0B15KVJR7",
"https://www.amazon.com/dp/B0B1W25T3F",
"https://www.amazon.com/dp/B0B15MGQ9C",
"https://www.amazon.com/dp/B0BTTXW26V",
"https://www.amazon.com/dp/B0BWLP4FCD",
"https://www.amazon.com/dp/B0BTTZXQS4",
"https://www.amazon.com/dp/B0BKQYSR59",
"https://www.amazon.com/dp/B0BKR3M7S6",
"https://www.amazon.com/dp/B0B15M4NP1",
"https://www.amazon.com/dp/B0BTTZ34SD",
"https://www.amazon.com/dp/B0BKR1VP3V",
"https://www.amazon.com/dp/B0BTTWR7PN",
"https://www.amazon.com/dp/B0BKR1PCTM",
"https://www.amazon.com/dp/B099DDH57B",
"https://www.amazon.com/dp/B0BTTYZC7Z",
"https://www.amazon.com/dp/B0B15QJYXD",
"https://www.amazon.com/dp/B0BWLKHSBR",
"https://www.amazon.com/dp/B0BTTXFB8Y",
"https://www.amazon.com/dp/B0B15MS75L",
"https://www.amazon.com/dp/B0BWLT6SMK",
"https://www.amazon.com/dp/B0BWLSGYNT",
"https://www.amazon.com/dp/B0BWLPJPQX",
"https://www.amazon.com/dp/B0BTTZ44GG",
"https://www.amazon.com/dp/B099DWGVCL",
"https://www.amazon.com/dp/B0B168VFZQ",
"https://www.amazon.com/dp/B0BTTYBD3F",
"https://www.amazon.com/dp/B0B15N61M5",
"https://www.amazon.com/dp/B0BWLV6LLP",
"https://www.amazon.com/dp/B0BWLHN1VG",
"https://www.amazon.com/dp/B0B15N6481",
"https://www.amazon.com/dp/B0BKR2NGBC",
"https://www.amazon.com/dp/B0BWLY1N6Y",
"https://www.amazon.com/dp/B099DFFHPY",
"https://www.amazon.com/dp/B0B1W2QVMN"]

In [10]:
df1=pd.DataFrame(Linklist,columns=['Links'])

In [32]:
df1.loc[1,"Name"]

nan

In [16]:
length=len(df1)
print(length)

216

# 3. Setting Webdriver and Website Specific Information

In [11]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://www.amazon.com/')

In [12]:
location = driver.find_element(By.ID, 'nav-global-location-popover-link')

location.click()
sleep(3)
pin = driver.find_element(By.ID, 'GLUXZipUpdateInput')
pinnumber='94203'
pin.send_keys(pinnumber)

apply=driver.find_element(By.CSS_SELECTOR, 'span.a-button-inner[data-action="GLUXPostalUpdateAction"]')
apply.click()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [13]:
cols =['Sl.No','Attributes','Short_Details','Variants'] #,'Review_Mentions','Standards'
df = pd.DataFrame(columns=cols)
df
count=0

In [14]:
driver.get(df1["Links"][0])

In [17]:
for i in tqdm(range(length)):
    driver.get(df1["Links"][i])
    print(i)
    df.loc[count,'Sl.No']=int(i)
    sleep(3)
    try:
        df.loc[count,'Name']=driver.find_element(By.XPATH, "//span[@class='a-size-large product-title-word-break']").text
        df.loc[count,'Links']=df1["Links"][i]
        try:
            pricetopay=float(driver.find_element(By.CLASS_NAME, "priceToPay").text.replace('''\n''','.').replace('$','').replace(',',''))
            df.loc[count,'Current Price']=pricetopay
        except:
            pass
        try:
            listprice=float(driver.find_element(By.CLASS_NAME, "a-text-price").text.replace('''\n''','.').replace('$','').replace(',',''))
            df.loc[count,'List Price']=listprice
        except:
            try:
                df.loc[count,'List Price']=pricetopay
            except:
                pass
        try:
            df.loc[count,'Rating']=float(driver.find_element(By.ID, "averageCustomerReviews").text.split("\n")[0])
        except:
            df.loc[count,'Rating']=0               
        try:
            df.loc[count,'No of Ratings']=int(driver.find_element(By.ID, "acrCustomerReviewText").text.split(' ')[0].replace(",",""))
        except:
            df.loc[count,'No of Ratings']=0
        try:
            df.loc[count,"Product Description"]=(driver.find_element(By.XPATH, "(//div[@id='productDescription'])").text)
        except:
            df.loc[count,"Product Description"]=0

        Alist=[]
        try:
            table=driver.find_element(By.CSS_SELECTOR,'[id="productDetails_techSpec_section_1"]')
            Values=table.find_elements(By.TAG_NAME, "tr")
            for row in Values:
                # Extract data from columns (td/th elements)
                l=row.find_element(By.TAG_NAME, "th").text
                v=row.find_element(By.TAG_NAME, "td").text
                Alist.append(l+":"+v)
        except:
            pass
        try:
            table=driver.find_element(By.CSS_SELECTOR,'[id="productDetails_detailBullets_sections1"]')
            Values=table.find_elements(By.TAG_NAME, "tr")
            for row in Values:
                # Extract data from columns (td/th elements)
                l=row.find_element(By.TAG_NAME, "th").text
                v=row.find_element(By.TAG_NAME, "td").text
                Alist.append(l+":"+v)
        except:
            attrs=driver.find_element(By.CSS_SELECTOR,'[id="detailBulletsWrapper_feature_div"]').find_elements(By.CSS_SELECTOR,'[class="a-list-item"]')
            for att in attrs:
                Alist.append(att.text)
        df.at[count,'Attributes']=Alist
        variants=[]
        try:
            vs=len(driver.find_elements(By.CSS_SELECTOR,'[class="twisterSlotDiv "]'))
            for n in range(vs):

                variant=driver.find_elements(By.CSS_SELECTOR,'[class="twisterTextDiv text"]')[n].text
                cost=(driver.find_elements(By.CSS_SELECTOR,'[class="twisterSlotDiv "]')[n].text)
                ASIN=(driver.find_element(By.CSS_SELECTOR,f'[id="size_name_{n}"]').get_attribute('data-defaultasin'))
                v=variant+" :|: "+cost+" :|: "+ASIN
                variants.append(v)
            print(variants)
            sleep(1)
            df.at[count,'Variants']=variants
        except:
            df.at[count,'Variants']=""

        try:
            df.loc[count,'Sales_LastMonth']=int(driver.find_element(By.ID, "social-proofing-faceout-title-tk_bought").text.split("+")[0].replace('K','000'))
        except:
            df.loc[count,'Sales_LastMonth']=0
        try:
            df.loc[count,'Details']=driver.find_element(By.XPATH, "(//div[@class='a-section a-spacing-medium a-spacing-top-small'])").text
        except:
            pass
        D_s=[]
        try:
            ls=driver.find_elements(By.CSS_SELECTOR,'[class="a-span3"]')
            vs=driver.find_elements(By.CSS_SELECTOR,'[class="a-span9"]')
            for l,v in zip(ls,vs):
                D_s.append(l.text+":"+v.text)
        except:
            pass
        try:
            es=driver.find_elements(By.CLASS_NAME,"a-normal")
            os= es[2].find_elements(By.CLASS_NAME,"a-text-bold")
            vs=es[2].find_elements(By.CSS_SELECTOR,'[class="a-size-base handle-overflow"]')
            for o, v  in zip( os, vs):
                D_s.append(o.text+":"+v.text)
        except:
            pass
        try:
            Atts=driver.find_elements(By.CSS_SELECTOR,'[class="a-span6"]')
            for att in Atts:
                vals=att.text.replace("\n",':')
                D_s.append(vals)
        except:
            pass

        df.at[count,"Short_Details"]=D_s
        try:
            df.loc[count,'Product_Category']=driver.find_element(By.CSS_SELECTOR,'[class="a-unordered-list a-horizontal a-size-small"]').text.rsplit('\n')[-1]
        except:
            pass
        try:
            df.loc[count,'ReviewSummary']=driver.find_element(By.CSS_SELECTOR,'[id="product-summary"]').text
        except:
            pass
        try:
            df.loc[count,'FirstAvailableDate']=driver.find_element(By.XPATH, "//th[contains(text(), 'Date First Available')]").find_element(By.XPATH, "./following-sibling::td").text
        except:
            pass
        try:
            elements=driver.find_elements(By.CSS_SELECTOR, '[data-csa-c-action="infoPopOver"]')
            len(elements)
            slist=[]
            for element in elements:
                s=element.get_attribute('data-csa-c-item-id')
                slist.append(s)
            #print(slist)
            df.at[count,"Sentiment"]=slist
        except:
            df.loc[count,'Sentiment']=""
        try: 
            filename=df1["Links"][i].split("/")[-1]+".jpg" # Extract filename from URL (modify if needed)
            t=driver.find_element(By.CSS_SELECTOR,'[id="landingImage"]')
            s=t.get_attribute('src')
            import requests

            # Download the image using requests
            response = requests.get(s, stream=True)

            if response.status_code == 200:            
                savepath=imagepath+"\\"+str(i)+"_"+filename
                df.loc[count,'ImageName']=str(i)+"_"+filename
            # Get filename from URL or generate a unique one
                with open(savepath, 'wb') as f:
                    for chunk in response.iter_content(1024):
                        f.write(chunk)
                print(f"Image downloaded: {filename}")
            else:
                print(f"Failed to download image: {s}")
        except:
            print(f"part number not available for {filename}")
        count=count+1
        balanceitem=length-i
        #print(balanceitem)
        #timeremaining(balanceitem,i)
        clear_output(wait=True)
    except:
        continue

100%|██████████| 216/216 [30:27<00:00,  8.46s/it]

In [18]:
print(df.shape)
df.tail()

(215, 17)

,Sl.No,Attributes,Short_Details,Variants,Name,Links,Current Price,List Price,Rating,No of Ratings,Product Description,Sales_LastMonth,Details,Product_Category,ReviewSummary,FirstAvailableDate,Sentiment
210,211,"[Brand:Trico, Vehicle Service Type:Car, Item L...","[Brand:Trico, Vehicle Service Type:Car, Item L...",[],TRICO Gold 3-Piece Driver/Passenger/Rear All-W...,https://www.amazon.com/dp/B0B15N6481,39.99,23.99,4.3,20727.0,Complete all your windshield wiper replacement...,0.0,About this item\n3-PIECE DRIVER/PASSENGER/REAR...,Blades,Customers say\nCustomers find the wiper blades...,"May 12, 2022","[Ease of installation_POSITIVE, Works well_POS..."
211,212,"[Brand:Trico, Vehicle Service Type:Truck, Item...","[Brand:Trico, Vehicle Service Type:Truck, Item...",[],TRICO Truck™ (58-22225) 22 Inch Pack of 2 Auto...,https://www.amazon.com/dp/B0BKR2NGBC,46.41,49.99,3.9,106.0,TRICO Truck is bigger and badder than your ave...,0.0,About this item\nOPTIMAL PERFORMANCE: 20% heav...,Blades,Customers say\nCustomers find the wiper blades...,"October 28, 2022","[Functionality_POSITIVE, Wiper quality_POSITIV..."
212,213,"[Brand:Trico, Vehicle Service Type:Car, Item L...","[Brand:Trico, Vehicle Service Type:Car, Item L...",[],"TRICO Silicone Ceramic Coated 28"" + 28"" Super ...",https://www.amazon.com/dp/B0BWLY1N6Y,56.09,65.99,4.1,1124.0,"Come rain or shine, ensure a clear view on the...",0.0,"About this item\n28"" + 28"" DRIVER & PASSENGER ...",Blades,Customers say\nCustomers are satisfied with th...,"February 23, 2023","[Works well_POSITIVE, Wipe quality_POSITIVE, B..."
213,214,"[Brand:Trico, Vehicle Service Type:Car, Mounti...","[Brand:Trico, Vehicle Service Type:Car, Mounti...",[],"TRICO Gold 21"" + 19"" Premium Automotive Replac...",https://www.amazon.com/dp/B099DFFHPY,32.69,32.69,4.3,20727.0,"Come rain or shine, ensure a clear view on the...",0.0,"About this item\n21"" + 19"" DRIVER & PASSENGER ...",Blades,Customers say\nCustomers find the wiper blades...,"January 21, 2020","[Ease of installation_POSITIVE, Works well_POS..."
214,215,"[Brand:Trico, Vehicle Service Type:Car, Mounti...","[Brand:Trico, Vehicle Service Type:Car, Mounti...",[],"TRICO Gold 21"" + 19"" Premium Automotive Replac...",https://www.amazon.com/dp/B0B1W2QVMN,32.69,32.69,4.3,20727.0,"Come rain or shine, ensure a clear view on the...",0.0,"About this item\n21"" + 19"" DRIVER & PASSENGER ...",Blades,Customers say\nCustomers find the wiper blades...,"January 21, 2020","[Ease of installation_POSITIVE, Works well_POS..."

# 5. Post Processing Data and Exporting

In [40]:
namesplit=search_text.split(" ")
print(namesplit)

['Oxygen', 'Sensor']

In [41]:
df['Name_Clean']=df['Name'].str.lower().str.replace("compatible with","").str.replace('w/',"with ")
for i in range(len(df)):
    if namesplit[0] in df['Name_Clean'][i] and namesplit[1] in df['Name_Clean'][i]and namesplit[2] in df['Name_Clean'][i]and namesplit[3] in df['Name_Clean'][i]and namesplit[1] in df['Name_Clean'][4]:
        df.loc[i,'Product']=search_text
    else:
        df.loc[i,"Product"]="Other Product"
del df['Name_Clean']

In [18]:
#df = df[(df['Current Price'] > 0)]

In [42]:
df['Short_Details'][1]

['Brand:Bosch',
 'Item dimensions L x W x H:5.9 x 2.3 x 2.2 inches',
 'Material:Stainless Steel',
 'Style:Oxygen Sensor',
 'Mounting Type:Flange Mount']

In [43]:
df['Material']=df['Short_Details'].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Material:',expand=True)[1].str.split(''',''',expand=True)[0]
df['ASIN']=df['Links'].str.split('dp/',expand=True)[1]
df=df.drop_duplicates(subset=['Links'])

In [44]:
df['Part Number']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('ManufacturerPartNumber:',expand=True)[1].str.split(',',expand=True)[0]
df['Brand']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Brand:',expand=True)[1].str.split(',',expand=True)[0]
df['Manufacturer']=df["Attributes"].apply(lambda x: str(x).replace('[','').replace(']','').replace('\'', '').replace(' ','')).str.split('Manufacturer:',expand=True)[1].str.split(',',expand=True)[0]
df['Source']="Amazon"
df[['Rating',"No of Ratings","Sales_LastMonth",'Manufacturer','Material','Part Number', "Brand","Source"]].head()

,Rating,No of Ratings,Sales_LastMonth,Manufacturer,Material,Part Number,Brand,Source
0,4.6,2154.0,300.0,Lisle,None,12230,Lisle,Amazon
1,4.5,2431.0,0.0,Bosch,StainlessSteel,None,None,Amazon
2,4.5,2431.0,0.0,No,StainlessSteel,None,None,Amazon
3,4.5,2431.0,100.0,Bosch,StainlessSteel,None,None,Amazon
4,4.5,2431.0,0.0,No,StainlessSteel,None,None,Amazon

In [45]:
cols=["Sl.No",
"Name",
"Product",
'Product_Category',
"Current Price",
"List Price",
"Rating",
"No of Ratings",
"Short_Details",
"Details",
"Product Description",
"Sales_LastMonth",
"Attributes",
"Brand",
"Part Number",
'Variants',
"Manufacturer",
"ReviewSummary",
"FirstAvailableDate",
"Sentiment",
"Material",
"ASIN",
"Links",
"Source",
"ImageName"
] #'Standards',
df=df[cols]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sl.No                500 non-null    object
 1   Name                 500 non-null    object
 2   Product              500 non-null    object
 3   Product_Category     500 non-null    object
 4   Current Price        498 non-null    float64
 5   List Price           500 non-null    float64
 6   Rating               500 non-null    float64
 7   No of Ratings        500 non-null    float64
 8   Short_Details        500 non-null    object
 9   Details              500 non-null    object
 10  Product Description  500 non-null    object
 11  Sales_LastMonth      500 non-null    float64
 12  Attributes           500 non-null    object
 13  Brand                253 non-null    object
 14  Part Number          251 non-null    object
 15  Variants             500 non-null    object
 16  Manufacturer         500 non-null    object
 17  ReviewSummary        276 non-null    object
 18  FirstAvailableDate   253 non-null    object
 19  Sentiment            500 non-null    object
 20  Material             364 non-null    object
 21  ASIN                 500 non-null    object
 22  Links                500 non-null    object
 23  Source               500 non-null    object
 24  ImageName            500 non-null    object
dtypes: float64(5), object(20)
memory usage: 101.6+ KB

In [47]:
print(df.shape)
df.head()

(500, 25)

,Sl.No,Name,Product,Product_Category,Current Price,List Price,Rating,No of Ratings,Short_Details,Details,...,Variants,Manufacturer,ReviewSummary,FirstAvailableDate,Sentiment,Material,ASIN,Links,Source,ImageName
0,0,"Lisle 12230 Oxygen Sensor Thread Chaser , Black",Other Product,Oxygen,8.04,11.99,4.6,2154.0,"[Brand:Lisle, Item dimensions L x W x H:4.25 x...",About this item\nCleans Threads in Oxygen Sens...,...,[],Lisle,Customers say\nCustomers like the functionalit...,"May 10, 2006",,None,B000XETMW0,https://www.amazon.com/dp/B000XETMW0,Amazon,0_B000XETMW0.jpg
1,1,Bosch 18121 OE Fitment Wideband Oxygen Sensor ...,Other Product,Oxygen,136.50,136.50,4.5,2431.0,"[Brand:Bosch, Item dimensions L x W x H:5.9 x ...",About this item\n[INNOVATIVE TECHNOLOGY] - Eve...,...,[],Bosch,Customers say\nCustomers like the functionalit...,NaN,"[Functionality_POSITIVE, Fit_POSITIVE, Value f...",StainlessSteel,B00GYG3R2W,https://www.amazon.com/dp/B00GYG3R2W,Amazon,1_B00GYG3R2W.jpg
2,2,BOSCH 15680 Premium Original Equipment Oxygen ...,Other Product,Oxygen,66.50,126.21,4.5,2431.0,"[Brand:Bosch, Item dimensions L x W x H:2.2 x ...",About this item\n[INNOVATIVE TECHNOLOGY] - Eve...,...,[],No,Customers say\nCustomers like the functionalit...,NaN,"[Functionality_POSITIVE, Fit_POSITIVE, Value f...",StainlessSteel,B000CF3W9O,https://www.amazon.com/dp/B000CF3W9O,Amazon,2_B000CF3W9O.jpg
3,3,BOSCH 17323 Premium Original Equipment Oxygen ...,Other Product,Oxygen,72.99,92.99,4.5,2431.0,"[Brand:Bosch, Item dimensions L x W x H:2.2 x ...",About this item\n[INNOVATIVE TECHNOLOGY] - Eve...,...,[],Bosch,Customers say\nCustomers like the functionalit...,NaN,"[Functionality_POSITIVE, Fit_POSITIVE, Value f...",StainlessSteel,B00EZQK9RY,https://www.amazon.com/dp/B00EZQK9RY,Amazon,3_B00EZQK9RY.jpg
4,4,BOSCH 17215 Premium Original Equipment Oxygen ...,Other Product,Oxygen,117.25,206.99,4.5,2431.0,"[Brand:Bosch, Item dimensions L x W x H:5.83 x...",About this item\n[INNOVATIVE TECHNOLOGY] - Eve...,...,[],No,Customers say\nCustomers like the functionalit...,NaN,"[Functionality_POSITIVE, Fit_POSITIVE, Value f...",StainlessSteel,B000CF3WOY,https://www.amazon.com/dp/B000CF3WOY,Amazon,4_B000CF3WOY.jpg

In [48]:
dfAtt=df[['ASIN','Attributes']]
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)

In [49]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No Products contains this Attribute'})
summary_df

,Attributes,No Products contains this Attribute
64,Best Sellers Rank,500
71,Customer Reviews,498
86,Item Weight,300
91,Manufacturer,254
58,ASIN,254
...,...,...
36,#45 in Automotive Replacement Oxygen Sensors,0
35,#44 in Automotive Replacement Oxygen Sensors,0
34,#426 in Automotive Replacement Oxygen Sensors,0
33,#425 in Automotive Replacement Oxygen Sensors,0
0,"#1,173 in Automotive Replacement Oxygen Sensors",0

In [26]:
# !pip install -U pip setuptools wheel
# !pip install -U spacy
# !python -m spacy download en_core_web_sm
# import spacy

# nlp = spacy.load("en_core_web_sm")  
# for i in range(length):
#     try:
#         texts=df["Name"][i]
#         doc=nlp(texts)
#         standard_Lists=[]
#         for entity in doc.ents:        
#             if entity.label_=="ORG":
#                 standard_Lists.append(entity.text)
#         df.at[i, 'Standards']=standard_Lists
#     except:
#         pass

In [50]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')
    dfAtt.to_excel(writer,index=False, sheet_name='Attribute_Values')

In [51]:
with pd.ExcelWriter(imagepath+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')
    dfAtt.to_excel(writer,index=False, sheet_name='Attribute_Values')

# 99. Archived Codes

In [ ]:
#Downloading images from amazon.
from selenium import webdriver
from selenium.webdriver.common.by import By
import openpyxl
import requests
from io import BytesIO
from openpyxl import Workbook
from openpyxl.drawing.image import Image

#--------------------------------------------------------------------------------------------------------------------------
il=[]
for i in range(length):
    driver.get(links[i])
    imagelink=driver.find_element(By.ID,"landingImage").get_attribute('src')
    il.append(imagelink)
    response = requests.get(imagelink)
    img_data = BytesIO(response.content)
    ASIN=links[i].split('dp/')[1]
    img_filename = f"{ASIN}.jpg"
    with open(img_filename, "wb") as img_file:
        img_file.write(img_data.getvalue())
    # # Create a DataFrame
    # df = pd.DataFrame({'Product Image URL': [imagelink]})
    # df.loc[count,'ASIN']=ASIN
    # # Save the DataFrame to an Excel file
    # excel_filename = "product_data.xlsx"
    # df.to_excel(excel_filename, index=False,)
    # wb = Workbook()
    # ws = wb.active
    # img = Image(img_filename)
    # ws.add_image(img, f'C{count+2}')
    # wb.save(excel_filename)
    balanceitem=length-i
    timeremaining(balanceitem,i)

NameError: name 'length' is not defined