# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

# 2. Defining the Product Information and Location

In [2]:
Links=["https://www.amazon.com/dp/B0BTTW77JH",
"https://www.amazon.com/dp/B0BTTWBZ4K",
"https://www.amazon.com/dp/B0BTTWM5SF",
"https://www.amazon.com/dp/B0BTTWNXDR",
"https://www.amazon.com/dp/B0BTTWR7PN",
"https://www.amazon.com/dp/B0BTTWV22P",
"https://www.amazon.com/dp/B0BTTX6KYL",
"https://www.amazon.com/dp/B0BTTX6VC7",
"https://www.amazon.com/dp/B0BTTX7VGC",
"https://www.amazon.com/dp/B0BTTXFB8Y",
"https://www.amazon.com/dp/B0BTTXHFMC",
"https://www.amazon.com/dp/B0BTTXN8PP",
"https://www.amazon.com/dp/B0BTTXP5VW",
"https://www.amazon.com/dp/B0BTTXPNT8",
"https://www.amazon.com/dp/B0BTTXQTWC",
"https://www.amazon.com/dp/B0BTTXRGMH",
"https://www.amazon.com/dp/B0BTTXRL65",
"https://www.amazon.com/dp/B0BTTXSQVF",
"https://www.amazon.com/dp/B0BTTXTBMG",
"https://www.amazon.com/dp/B0BTTXV6ZM",
"https://www.amazon.com/dp/B0BTTXVH1V",
"https://www.amazon.com/dp/B0BTTXW26V",
"https://www.amazon.com/dp/B0BTTXW86Q",
"https://www.amazon.com/dp/B0BTTXXTTW",
"https://www.amazon.com/dp/B0BTTY13YR",
"https://www.amazon.com/dp/B0BTTY29KZ",
"https://www.amazon.com/dp/B0BTTY2CPV",
"https://www.amazon.com/dp/B0BTTY3RJX",
"https://www.amazon.com/dp/B0BTTY3WZP",
"https://www.amazon.com/dp/B0BTTY43TP",
"https://www.amazon.com/dp/B0BTTY4N81",
"https://www.amazon.com/dp/B0BTTY585Y",
"https://www.amazon.com/dp/B0BTTY5SNR",
"https://www.amazon.com/dp/B0BTTY7ZD2",
"https://www.amazon.com/dp/B0BTTY844R",
"https://www.amazon.com/dp/B0BTTY85HB",
"https://www.amazon.com/dp/B0BTTY8KD2",
"https://www.amazon.com/dp/B0BTTY9DN1",
"https://www.amazon.com/dp/B0BTTY9R2F",
"https://www.amazon.com/dp/B0BTTYBD3F",
"https://www.amazon.com/dp/B0BTTYBFFF",
"https://www.amazon.com/dp/B0BTTYBFNQ",
"https://www.amazon.com/dp/B0BTTYC1F7",
"https://www.amazon.com/dp/B0BTTYC4YG",
"https://www.amazon.com/dp/B0BTTYDP3K",
"https://www.amazon.com/dp/B0BTTYDZCP",
"https://www.amazon.com/dp/B0BTTYF22S",
"https://www.amazon.com/dp/B0BTTYFGCM",
"https://www.amazon.com/dp/B0BTTYFHFL",
"https://www.amazon.com/dp/B0BTTYGFT5",
"https://www.amazon.com/dp/B0BTTYH6HF",
"https://www.amazon.com/dp/B0BTTYHHXY",
"https://www.amazon.com/dp/B0BTTYL6RT",
"https://www.amazon.com/dp/B0BTTYM3QM",
"https://www.amazon.com/dp/B0BTTYN6WN",
"https://www.amazon.com/dp/B0BTTYPC61",
"https://www.amazon.com/dp/B0BTTYPGCB",
"https://www.amazon.com/dp/B0BTTYPVVX",
"https://www.amazon.com/dp/B0BTTYQ51S",
"https://www.amazon.com/dp/B0BTTYR3H8",
"https://www.amazon.com/dp/B0BTTYSTN9",
"https://www.amazon.com/dp/B0BTTYTFL3",
"https://www.amazon.com/dp/B0BTTYTJL7",
"https://www.amazon.com/dp/B0BTTYWFGN",
"https://www.amazon.com/dp/B0BTTYWMHF",
"https://www.amazon.com/dp/B0BTTYZC7Z",
"https://www.amazon.com/dp/B0BTTZ34SD",
"https://www.amazon.com/dp/B0BTTZ44GG",
"https://www.amazon.com/dp/B0BTTZ5B5R",
"https://www.amazon.com/dp/B0BTTZ77K3",
"https://www.amazon.com/dp/B0BTTZ7CS6",
"https://www.amazon.com/dp/B0BTTZ9K46",
"https://www.amazon.com/dp/B0BTTZ9XZ7",
"https://www.amazon.com/dp/B0BTTZ9YWK",
"https://www.amazon.com/dp/B0BTTZF18Y",
"https://www.amazon.com/dp/B0BTTZFLPQ",
"https://www.amazon.com/dp/B0BTTZK1PJ",
"https://www.amazon.com/dp/B0BTTZK3PL",
"https://www.amazon.com/dp/B0BTTZK8M1",
"https://www.amazon.com/dp/B0BTTZKFFY",
"https://www.amazon.com/dp/B0BTTZLDS1",
"https://www.amazon.com/dp/B0BTTZMWB7",
"https://www.amazon.com/dp/B0BTTZNKF2",
"https://www.amazon.com/dp/B0BTTZPKNS",
"https://www.amazon.com/dp/B0BTTZQ5KF",
"https://www.amazon.com/dp/B0BTTZRFCR",
"https://www.amazon.com/dp/B0BTTZS6SW",
"https://www.amazon.com/dp/B0BTTZSCP8",
"https://www.amazon.com/dp/B0BTTZSHZZ",
"https://www.amazon.com/dp/B0BTTZSLL6",
"https://www.amazon.com/dp/B0BTTZT6DS",
"https://www.amazon.com/dp/B0BTTZXQS4",
"https://www.amazon.com/dp/B0BTTZYQCH",
"https://www.amazon.com/dp/B0BTV12K23",
"https://www.amazon.com/dp/B0BTV12Y9T",
"https://www.amazon.com/dp/B0BTV1HL55",
"https://www.amazon.com/dp/B0BTV1ZZYV",
"https://www.amazon.com/dp/B0BTTXMYXT"
]

In [3]:
length=len(Links)
print(length)

98

# 3. Setting Webdriver and Website Specific Information

In [4]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://www.amazon.com/')

In [5]:
location = driver.find_element(By.ID, 'nav-global-location-popover-link')

location.click()
sleep(3)
pin = driver.find_element(By.ID, 'GLUXZipUpdateInput')
pinnumber='94203'
pin.send_keys(pinnumber)

apply=driver.find_element(By.CSS_SELECTOR, 'span.a-button-inner[data-action="GLUXPostalUpdateAction"]')
apply.click()

In [7]:
driver.find_element(By.CSS_SELECTOR,'[data-csa-c-type="link"]').click()

In [9]:
eid=driver.find_element(By.CSS_SELECTOR,'[id="ap_email"]')
eid.click()
emailid="Vikram.Vadhirajan@firstbrandsgroup.com"
eid.send_keys(emailid)
eid.send_keys(Keys.ENTER)
sleep(2)

passw=driver.find_element(By.CSS_SELECTOR,'[id="ap_password"]')
passw.click()
password="FBG@Nov-2024"
passw.send_keys(password)
passw.send_keys(Keys.ENTER)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ap_email"]"}
  (Session info: chrome=144.0.7559.110); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff64ec5f3d5
	0x7ff64ec5f430
	0x7ff64ea010bd
	0x7ff64ea5c2fe
	0x7ff64ea5c60c
	0x7ff64eaad187
	0x7ff64eaa9d08
	0x7ff64ea4cb0c
	0x7ff64ea4da53
	0x7ff64ef3b470
	0x7ff64ef3586d
	0x7ff64ef5621a
	0x7ff64ec7b235
	0x7ff64ec83a5c
	0x7ff64ec68844
	0x7ff64ec689f6
	0x7ff64ec4eb87
	0x7ff86a5d7374
	0x7ff86b6dcc91

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [10]:
cols =['ASIN'] #,'Review_Mentions','Standards'
df = pd.DataFrame(columns=cols)
df
count=0

In [12]:
driver.get(Links[2])

In [13]:
len(Links)

98

In [15]:
driver.find_element(By.CSS_SELECTOR,'[data-hook="see-all-reviews-link-foot"]').click()

In [14]:
for i in tqdm(range (len(Links))):
    print(f"Number of Items scanned:{i}")
    driver.get(Links[i])
    sleep(2)
    try:
        Name=driver.find_element(By.ID,"title").text
        try:
            driver.find_element(By.CSS_SELECTOR,'[id="acrCustomerReviewText"]').click()
            sleep(3)
            driver.find_element(By.CSS_SELECTOR,'[data-hook="see-all-reviews-link-foot"]').click()
            sleep(1)
            var=0
            driver.find_element(By.CLASS_NAME,'cr-sort-dropdown').click()
            driver.find_element(By.CSS_SELECTOR,'[aria-labelledby="sort-order-dropdown_1"]').click()
            sleep(1)
            for s in range(5):
                driver.find_element(By.CLASS_NAME,'star-rating-select').click()
                driver.find_elements(By.ID,f"star-count-dropdown_0")[s+1].click()
                sleep(1)
                for m in range(100):
                    sleep(2)
                    #print("1")
                    rbs=driver.find_elements(By.CSS_SELECTOR,'[data-hook="review-body"]')
                    titles=driver.find_element(By.CSS_SELECTOR,'[id="cm_cr-review_list"]').find_elements(By.CSS_SELECTOR,'[data-hook="review-title"]')
                    starnum=driver.find_element(By.CSS_SELECTOR,'[id="reviews-filter-info-segment"]').text
                    revdates=driver.find_elements(By.CSS_SELECTOR,'[data-hook="review-date"]')
                    variants=driver.find_elements(By.CSS_SELECTOR,'[data-hook="format-strip"]')
                    print(len(variants))
                    if len(variants)==0:                    
                        for rb, title,revdate in zip(rbs,titles,revdates):
                            df.loc[count,"#Comments"]=var+1
                            df.loc[count,"ASIN"]=Links[i].split("/dp/")[1]
                            df.loc[count, "Title"]=title.text
                            df.loc[count, "Comments"]=rb.text
                            df.loc[count,'Review Date']=revdate.text.split(" on ")[-1]
                            df.loc[count,'Star']=starnum
                            df.loc[count,"Name"]=Name
                            try:
                                df.loc[count,"Variant"]=variant.text
                            except:
                                df.loc[count,"Variant"]=""
                            count=count+1
                            var=var+1
                            clear_output(wait=True)
                        try:
                            driver.find_element(By.CSS_SELECTOR,'[class="a-last"]').click()
                        except:
                            break
                    else:
                        for rb, title,revdate,variant in zip(rbs,titles,revdates,variants):
                            df.loc[count,"#Comments"]=var+1
                            df.loc[count,"ASIN"]=Links[i].split("/dp/")[1]
                            df.loc[count, "Title"]=title.text
                            df.loc[count, "Comments"]=rb.text
                            df.loc[count,'Review Date']=revdate.text.split(" on ")[-1]
                            df.loc[count,'Star']=starnum
                            df.loc[count,"Name"]=Name
                            try:
                                df.loc[count,"Variant"]=variant.text
                            except:
                                df.loc[count,"Variant"]=""
                            count=count+1
                            var=var+1
                            clear_output(wait=True)
                        try:
                            driver.find_element(By.CSS_SELECTOR,'[class="a-last"]').click()
                        except:
                            break
            print(f"Number of comments:{var}")   
        except:
            pass
    except:
        pass

  0%|          | 0/98 [00:00<?, ?it/s]

Number of Items scanned:0

  1%|          | 1/98 [00:11<18:06, 11.20s/it]

Number of Items scanned:1

  2%|▏         | 2/98 [00:21<17:20, 10.84s/it]

Number of Items scanned:2

  3%|▎         | 3/98 [00:31<16:32, 10.45s/it]

Number of Items scanned:3

  3%|▎         | 3/98 [00:36<19:23, 12.25s/it]

KeyboardInterrupt:

In [32]:
df

,ASIN,#Comments,Title,Comments,Review Date,Star,Name,Variant
0,B000CI6EG4,1.0,The place to go for a remanufactured part,The protective coating is a plus. Reasonably p...,"April 7, 2021",5 star,Cardone 18-B4688 Remanufactured Unloaded Disc ...,
1,B000CIABPE,1.0,Description very wrong,Product description is still wrong. This does ...,"April 16, 2021",1 star,Cardone 18-B4728 Remanufactured Unloaded Disc ...,
2,B0010DQM58,1.0,Calipers,I used these calipers to upgrade my 2006 Tahoe...,"August 23, 2013",3 star,A1 Cardone 18-B4919 Remanufactured Unloaded Di...,
3,B0019WHKSS,1.0,Four Stars,Easily install and comparable to the factory O...,"September 27, 2017",4 star,Cardone 18-B5030 Remanufactured Unloaded Disc ...,
4,B0019WHKSS,2.0,more Cardone junk,"the bracket doesn't seem to be OEM, looks like...","November 24, 2019",1 star,Cardone 18-B5030 Remanufactured Unloaded Disc ...,
...,...,...,...,...,...,...,...,...
1002,B000C02DVW,58.0,May not be a carter pump in the carter box.,Pretty sure this was not a carter pump. Would ...,"March 21, 2022",1 star,Carter Mechanical Fuel Pump System Automotive ...,
1003,B000C02DVW,59.0,Buy OEM,"Lasted about 20,000 miles and is now leaking.","September 9, 2019",1 star,Carter Mechanical Fuel Pump System Automotive ...,
1004,B000C02DVW,60.0,not working,"first one never arrived, installed the 2nd one...","February 11, 2024",1 star,Carter Mechanical Fuel Pump System Automotive ...,
1005,B000C02DVW,61.0,"Terrible part, left me stranded twice.",I had one of these fail within a week on a 7.3...,"January 26, 2024",1 star,Carter Mechanical Fuel Pump System Automotive ...,
1006,B000C1F8XG,1.0,"Perfect fit, made in Italy","Perfect fit, made in Italy. What more could u ...","June 21, 2015",5 star,Airtex AW9128 Engine Water Pump,

In [33]:
OFolder=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Data Scraping - Amazon data\Amazon"
from datetime import date
Date=str(date.today()).replace("-","")
Source="Amazon_"
search_text="Brakes"
with pd.ExcelWriter(OFolder+'\\'+f'{Date}_{Source}ProductReviews_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Reviews')

In [79]:
%pip install nltk

Requirement already satisfied: nltk in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: joblib in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: tqdm in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: colorama in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [114]:
%pip install nltk textblob

Requirement already satisfied: nltk in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: textblob in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (0.18.0.post0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: joblib in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: tqdm in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: click in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: colorama in c:\users\vikram.vadhirajan\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [116]:
import nltk
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Vikram.Vadhirajan\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vikram.Vadhirajan\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Vikram.Vadhirajan\AppData\Roaming\nltk_data..
[nltk_data]     .
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from textblob import TextBlob
nltk.download('vader_lexicon')

In [82]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Initialize VADER sentiment analyzer
sid = SentimentIntensityAnalyzer()

In [107]:
cols =["Positive Words","Negative Words"] #,'Review_Mentions','Standards'
dfs = pd.DataFrame(columns=cols)
dfs
count=0

In [117]:
for i in tqdm(range(len(df))):
    # Sample text
    text =df["Comments"][i]
    # Tokenize the text into words (or word chunks)
    words = word_tokenize(text)

    # Load stop words
    stop_words = set(stopwords.words('english'))

    # Remove stop words
    filtered_words = [word for word in words if word.lower() not in stop_words]

    # Analyze the sentiment for each word
    word_sentiments = {}
    for word in filtered_words:
        word_sentiment = sid.polarity_scores(word)
        word_sentiments[word] = word_sentiment['compound']

    # # Display each word with its sentiment score
    # for word, score in word_sentiments.items():
    #     print(f"Word: '{word}', Sentiment Score: {score}")

    # Interpretation based on each word's compound score
    PW=[word for word, score in word_sentiments.items() if score >= 0.05]
    NW=[word for word, score in word_sentiments.items() if score <= -0.05]
    dfs.at[i,"Comments"] = text
    dfs.at[i,"ASIN"] = df["ASIN"][i]
    dfs.at[i,"Positive Words"] = PW
    dfs.at[i,"Negative Words"] = NW

    # print("\nPositive words:", positive_words)
    # print("Negative words:", negative_words)

100%|██████████| 786/786 [00:01<00:00, 592.84it/s]

In [118]:
dfs

,Positive Words,Negative Words,Comments,ASIN
0,"[perfect, easy, well, prevents]",[],perfect for my needs.\neasy to use.\nthe tight...,B0B2T3F3HM
1,[good],[],Very heavy duty everything about it is good,B0B2T3F3HM
2,"[enjoyed, secure, solid]",[],Really enjoyed using this with a cargo carrier...,B0B2T3F3HM
3,"[perfect, solution, secure, want]","[worried, exhaust, damage]",I wanted to add a small cargo carrier to our c...,B0B2T3F3HM
4,"[great, good, like, want, dedicated]",[bad],Using with a Curt spare tire carrier. Works gr...,B0B2T3F3HM
...,...,...,...,...
781,"[easily, best, easy]",[sucker],I have owned several hitch racks and this is e...,B09VCNQS75
782,"[like, happier, play, nice, peace, definitely]",[worry],This thing is a tank. More than what I reallly...,B09VCNQS75
783,"[Play, impression, help, natural, pretty, conf...","[mess, problem, shake, disappointment]",Play Video\nDon't let the shiny blue anodized ...,B09VCNQS75
784,"[like, good, well]","[sucks, bad, low]",i like the welds also good heavy stock it went...,B07QMP6W8B
785,[Well],[bad],Where are the directions for install? Only bad...,B07QMP6W8B

# 5. Post Processing Data and Exporting

In [120]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductSentiment_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Comments')
    dfs.to_excel(writer,index=False, sheet_name='Sentiment')

# 99. Archived Codes