In [122]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

In [123]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://carlsoncatalog.com/')
driver.maximize_window()

Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)

In [97]:
cols =['PartNumber'] #,'Review_Mentions','Standards'
df1 = pd.DataFrame(columns=cols)
df2 = pd.DataFrame(columns=cols)
count1=0
count2=0

In [37]:
df = pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\92_Our Products\Buyers guide ACES File preparation missing.xlsx" , sheet_name='Buyers guide')

In [39]:
df

,Part_Number,Brand_Name,Part_type_Name,VIO US,VIO CA,VIO Total,Vehicle_summary,min_year,max_year,Position
0,H9407-2,Carlson,Brake Bleeder Screw,143719589,16911202,160630791,2023 Acura Integra | 2001 - 2002 Acura MDX | 2...,1969,2024,NaN
1,H1457,Carlson,Brake Hydraulic Hose Lock Clip,104590683,7525761,112116444,1999 - 2008 Acura TL | 2004 - 2008 Acura TSX |...,1976,2020,NaN
2,H1457-2,Carlson,Brake Hydraulic Hose Lock Clip,104520130,7518144,112038274,1999 - 2008 Acura TL | 2004 - 2008 Acura TSX |...,1976,2020,NaN
3,H9411-2,Carlson,Brake Bleeder Screw,79465212,7476457,86941669,1996 - 1999 Acura SLX | 1980 - 1986 Audi 4000 ...,1965,2023,NaN
4,H9409-2,Carlson,Brake Bleeder Screw,58282310,5809907,64092217,1997 - 1999 Acura CL | 2013 - 2018 Acura ILX |...,1970,2024,NaN
...,...,...,...,...,...,...,...,...,...,...
4139,H5904,Carlson,Disc Brake Hardware Kit,0,0,0,1994 - 2000 Chevrolet Chevy | 2003 - 2012 Chev...,1994,2012,NaN
4140,H5905,Carlson,Disc Brake Hardware Kit,0,0,0,2011 - 2015 Chevrolet Matiz | 2004 - 2010 Pont...,2004,2015,NaN
4141,H5906,Carlson,Disc Brake Hardware Kit,0,0,0,2018 - 2019 Chevrolet Beat | 2011 - 2015 Chevr...,2011,2019,NaN
4142,H5955,Carlson,Disc Brake Hardware Kit,0,0,0,2001 - 2012 Dodge Atos,2001,2012,NaN
4143,H5998,Carlson,Disc Brake Hardware Kit,0,0,0,2002 - 2004 Ford Fiesta Ikon | 2006 - 2007 For...,2002,2007,NaN

In [165]:
for p in tqdm(range(3858,len(df))):
    # try:
    #     wait.until(EC.presence_of_element_located(( By.XPATH, "//span[contains(@class, 'x-btn-inner') and text()='Close']").click()
    # except:
    #     pass
    searchbox=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '[role="textbox"]')))
    searchbox.click()
    searchbox.clear()
    searchbox.send_keys(df["Part_Number"][p])
    print(p,":",df["Part_Number"][p]," | Rows:",count1)
    searchbox.send_keys(Keys.ENTER)
    sleep(3)
    errormessage=wait.until(EC.presence_of_element_located((By.CLASS_NAME, "x-window-text"))).text
    if "No part(s) found matching" not in errormessage:
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "a.PartNumberLink"))).click()
        sleep(4)
        wait.until(EC.presence_of_element_located((By.XPATH,"//span[contains(@class, 'x-tab-inner') and text()='Buyers Guide']/ancestor::span[contains(@class, 'x-tab-button')]"))).click()
        sleep(2)
        Pages = int(wait.until(EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'x-toolbar-text') and contains(text(), 'of')]"))).text.split(" ")[-1])
        for page in range(Pages):
            sleep(3)
            rows = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "tr.x-grid-row")))
            for row in rows:
                # Find all the <div> elements inside this row
                cells = row.find_elements(By.CSS_SELECTOR, "div.x-grid-cell-inner")
                if len(cells) >= 5:  # We expect 5 columns based on your HTML

                    df1.loc[count1,'PartNumber']=df["Part_Number"][p]
                    df1.loc[count1,'Make']=cells[0].text
                    df1.loc[count1,"Model"]=cells[1].text
                    df1.loc[count1,"Year"]=cells[2].text
                    df1.loc[count1,"Position"]=cells[3].text
                    df1.loc[count1,"Description"]=cells[4].text
                    count1+=1
            try:
                wait.until(EC.presence_of_element_located((By.XPATH,"//span[contains(@class, 'x-tbar-page-next')]/ancestor::span[contains(@class, 'x-btn-button')]"))).click()
            except:
                pass
        wait.until(EC.presence_of_element_located(( By.XPATH, "//span[contains(@class, 'x-btn-inner') and text()='Close']"))).click()
        clear_output(wait=True)
    else:
        wait.until(EC.element_to_be_clickable((By.XPATH, "//span[text()='OK']/ancestor::a"))).click()

100%|██████████| 286/286 [1:07:29<00:00, 14.16s/it]

In [166]:
df1

,PartNumber,Make,Model,Year,Position,Description
0,H9407-2,ACURA,MDX,02-01,All,Brake Bleeder Screw - FRONT
1,H9407-2,ACURA,RLX,15-14,All,Brake Bleeder Screw - REAR
2,H9407-2,AUDI,A3,05-04,All,Brake Bleeder Screw - REAR
3,H9407-2,AUDI,A3 QUATTRO,13-12,All,Brake Bleeder Screw - REAR
4,H9407-2,AUDI,A4,14-09,All,Brake Bleeder Screw - REAR
...,...,...,...,...,...,...
67224,H5906,CHEVROLET,SPARK,15-11,All,Disc Brake Hardware Kit - FRONT
67225,H5906,CHEVROLET,SPARK CLASSIC,17-16,All,Disc Brake Hardware Kit - FRONT
67226,H5955,DODGE,ATOS,12-01,All,Disc Brake Hardware Kit - FRONT
67227,H5998,FORD,FIESTA IKON,04-02,All,Disc Brake Hardware Kit - FRONT
67228,H5998,FORD,IKON,07-06,All,Disc Brake Hardware Kit - FRONT

In [167]:
df1["PartNumber"].value_counts()

PartNumber
H1191      1180
H1191-2     756
H9410-2     580
H9407-2     572
H9409-2     492
           ...
41131         1
19090         1
13137         1
7200          1
41333         1
Name: count, Length: 4125, dtype: int64

In [168]:
df1.to_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\92_Our Products\Carlson_Parts_OutputFull.xlsx", index=False)