# Library calling

In [127]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from urllib.parse import unquote
import pandas as pd
import datetime 
from IPython.display import clear_output

# Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)
Source="CarParts"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

# Setting Webdriver and Website Specific Information

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.carparts.com/')
driver.maximize_window()
wait=WebDriverWait(driver, 5)

In [3]:
driver.find_element(By.CSS_SELECTOR,'[data-testid="desktop-geo-locator"]').click()
sleep(1)
pin = driver.find_element(By.CSS_SELECTOR, '[class="StyledTextInput-sc-1x30a0s-0 cZzNgu"]')
pin.click()
pin.clear()
pinnumber='94203'
pin.send_keys(pinnumber)

wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '[class="StyledButton-sc-323bzc-0 ignnRb"]'))).click()

In [5]:
# Find the search bar by its ID
try:
    search_bar = driver.find_element(By.ID, 'searchBox')
except:
    search_bar=driver.find_element(By.ID, "twotabsearchtextbox")

# Enter the search text

search_bar.send_keys(search_text)

# Submit the form to perform the search
search_bar.send_keys(Keys.ENTER)

In [12]:
#select 45 grid
page=driver.find_element(By.ID,"showItemsBox-2")
page.click()

# Defining the Dataframe and Extracting the data into the Dataframe

In [163]:
df2 = pd.DataFrame(columns=Cols)
count1=0
Itemlist=[]

In [164]:
df2

Empty DataFrame
Columns: [Sl.No]
Index: []

In [141]:
Cols=["Sl.No"]
df = pd.DataFrame(columns=Cols)
count=0
Cols=["Sl.No"]
df1 = pd.DataFrame(columns=Cols)
count1=0
Itemlist=[]

In [ ]:
#Manually need to search for the item in the website.

In [157]:
### caution: Works only on full screen
maxpage=int(driver.find_element(By.CLASS_NAME,"facMnh").text.split("of ")[1].split(" ")[0])
for i in range(maxpage):
    currentpage=int(driver.find_element(By.CLASS_NAME,"facMnh").text.split("Page ")[1].split(" ")[0])
    maxpage=int(driver.find_element(By.CLASS_NAME,"facMnh").text.split("of ")[1].split(" ")[0])
    sleep(2)
    print(f"current page:{currentpage}")
    trial=driver.find_elements(By.CLASS_NAME,"table-body")[1].text.split("\n")
    for i in range(len(trial)):
        df.loc[count,"Sl.No"]=count+1
        df.loc[count,"Item"]=trial[i]
        df.loc[count,"PartNumber"]=driver.find_element(By.CLASS_NAME,'darNcx').text.split(" ")[0]
        count=count+1
    driver.find_element(By.ID,"pagination-next").click()
    clear_output(wait=True)

current page:8

ElementClickInterceptedException: Message: element click intercepted: Element <div id="pagination-next" data-testid="desktop-vehicle-fitment-information-pagination-next" class="StyledBox-sc-13pk1d4-0 ebYpcg sc-1mu8khs-0" style="user-select: none;" disabled="">...</div> is not clickable at point (929, 70). Other element would receive the click: <div class="StyledBox-sc-13pk1d4-0 iMixDJ sc-18eg4mt-6 eSewOZ item">...</div>
  (Session info: chrome=124.0.6367.208)
Stacktrace:
	GetHandleVerifier [0x00007FF6BDEF1522+60802]
	(No symbol) [0x00007FF6BDE6AC22]
	(No symbol) [0x00007FF6BDD27CE4]
	(No symbol) [0x00007FF6BDD7E877]
	(No symbol) [0x00007FF6BDD7C344]
	(No symbol) [0x00007FF6BDD7980A]
	(No symbol) [0x00007FF6BDD789E2]
	(No symbol) [0x00007FF6BDD6AE8B]
	(No symbol) [0x00007FF6BDD9AB7A]
	(No symbol) [0x00007FF6BDD6A7C6]
	(No symbol) [0x00007FF6BDD9AD90]
	(No symbol) [0x00007FF6BDDBA224]
	(No symbol) [0x00007FF6BDD9A923]
	(No symbol) [0x00007FF6BDD68FEC]
	(No symbol) [0x00007FF6BDD69C21]
	GetHandleVerifier [0x00007FF6BE1F41BD+3217949]
	GetHandleVerifier [0x00007FF6BE236157+3488183]
	GetHandleVerifier [0x00007FF6BE22F0DF+3459391]
	GetHandleVerifier [0x00007FF6BDFAB8E6+823622]
	(No symbol) [0x00007FF6BDE75FBF]
	(No symbol) [0x00007FF6BDE70EE4]
	(No symbol) [0x00007FF6BDE71072]
	(No symbol) [0x00007FF6BDE618C4]
	BaseThreadInitThunk [0x00007FFBB8997344+20]
	RtlUserThreadStart [0x00007FFBBA7826B1+33]

In [158]:
df

     Sl.No                  Item PartNumber
0        1  2008-2009 Pontiac G8      51440
1        2                    GT      51440
2        3            8 Cyl 6.0L      51440
3        4                     -      51440
4        5     2009 Buick Allure      51440
...    ...                   ...        ...
1583  1584                     -      53027
1584  1585   2003 Dodge Ram 1500      53027
1585  1586               Laramie      53027
1586  1587            8 Cyl 5.9L      53027
1587  1588                     -      53027

[1588 rows x 3 columns]

In [159]:
for i in range(len(df)):
    df1.loc[count1,"Part Number"]=df["PartNumber"][i]
    r=df["Sl.No"][i]%4
    q=df["Sl.No"][i]//4
    df1.loc[count1,"Sl.No"]=q
    if r==1:
        df1.loc[count1,"Vehicle Name"]=df["Item"][i]
    if r==2:
        df1.loc[count1,"Submodel"]=df["Item"][i]
    if r==3:
        df1.loc[count1,"Engine"]=df["Item"][i]
    if r==0:
        df1.loc[count1,"Fitment Information"]=df["Item"][i]
    count1=q

In [160]:
df1

,Sl.No,Part Number,Vehicle Name,Submodel,Engine,Fitment Information
0,1,51440,2008-2009 Pontiac G8,GT,8 Cyl 6.0L,-
1,2,51440,2009 Buick Allure,Super,8 Cyl 5.3L,-
2,3,51440,2009 Buick LaCrosse,Super,8 Cyl 5.3L,-
3,4,51440,2009 Chevrolet Avalanche,LT,8 Cyl 6.0L,-
4,5,51440,2009 Chevrolet Avalanche,LTZ,8 Cyl 6.0L,-
...,...,...,...,...,...,...
392,393,53027,2002 Dodge Dakota,SXT,8 Cyl 5.9L,-
393,394,53027,2002-2003 Dodge Durango,SLT Plus,8 Cyl 5.9L,-
394,395,53027,2002-2003 Dodge Durango,Sport,8 Cyl 5.9L,-
395,396,53027,2003 Dodge Durango,SXT,8 Cyl 5.9L,-
396,397,53027,2003 Dodge Ram 1500,Laramie,8 Cyl 5.9L,-

In [162]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\CarParts\Outputs'

with pd.ExcelWriter(OFolder+f'\Carparts_Application_Detail_NGK_SparkPlug_Wireset.xlsx') as writer:  
    df1.to_excel(writer,index=False, sheet_name='Raw')

In [22]:
while Results < 240:#TotalResults:
    sleep (2)
    pageNumbers=wait.until(EC.presence_of_element_located((By.ID,"topBarinformation"))).text
    Results= int(pageNumbers.split(" ")[3])
    TotalResults= pageNumbers.split(" ")[5]
    #print (Results, TotalResults)
    TP=int(TotalResults)
    PPP=int(Results)
    NoP=round(TP-PPP,0)
    print(PPP)
    for i in range(10):
        try:
            wait.until(EC.presence_of_element_located((By.TAG_NAME,'body'))).send_keys(Keys.END)
            sleep(1)
        except:
            break
    #Extracting hrefs
    element = driver.find_element(By.ID,"MainSection")
    anchor_elements = element.find_elements(By.TAG_NAME,'a')
    sleep(1)
    for anchor in anchor_elements:
        href = anchor.get_attribute('href')
        df.loc[count,'Links']=href
        count=count+1
    sleep(1)
    Nextpage=driver.find_element(By.ID,"pagination-next")
    Nextpage.click()

45
90
135
180
225
270

In [24]:
print(len(df))
df=df.drop_duplicates(["Links"])

270

# Post Processing Data and Exporting

In [25]:
df.to_excel(IFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx', index=False)

# Archived Codes