In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

In [2]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)
driver.get('https://carterengineered.com/find-parts')

In [9]:
List=["W1000M",
"W1088M",
"W1090M",
"W1091M",
"W1103M",
"W1106M",
"W1107M",
"W129M",
"W144M",
"W1878M",
"W1901M",
"W1902M",
"W1928M",
"W1941M",
"W1943M",
"W1968M",
"W1969M",
"W1974M",
"W1981M",
"W1982M",
"W1983M",
"W1985M",
"W1986M",
"W1988M",
"W2058M",
"W2059M",
"W2061M",
"W2064M",
"W2065M",
"W2066M",
"W2067M",
"W2083M",
"W2084M",
"W2090M",
"W2091M",
"W2092M",
"W2093M",
"W2094M",
"W2097M",
"W2099M",
"W2100M",
"W2114M",
"W2115M",
"W2117M",
"W2118M",
"W2119M",
"W2121M",
"W2122M",
"W2124M",
"W2136M",
"W2137M",
"W2138M",
"W2139M",
"W2140M",
"W2141M",
"W2142M",
"W2143M",
"W2144M",
"W2149M",
"W2150M",
"W2151M",
"W2156M",
"W2157M",
"W2159M",
"W2190M",
"W2195M",
"W2196M",
"W2200M",
"W2218M",
"W2221M",
"W2222M",
"W2223M",
"W2224M",
"W2227M",
"W2233M",
"W2234M",
"W2235M",
"W2236M",
"W2237M",
"W2238M",
"W2248M",
"W2249M",
"W2250M",
"W2251M",
"W2253M",
"W2254M",
"W2258M",
"W2271M",
"W2274M",
"W2276M",
"W2279M",
"W2280M",
"W2281M",
"W2330M",
"W2332M",
"W2338M",
"W2339M",
"W2340M",
"W2353M",
"W2358M",
"W2367M",
"W2373M",
"W2375M",
"W2376M",
"W2377M",
"W2378M",
"W2396E",
"W2397E",
"W2398E",
"W2402M",
"W2407M",
"W2408M",
"W2409M",
"W2411M",
"W2415M",
"W2417M",
"W2419M",
"W2425M",
"W2427M",
"W2436M",
"W2437M",
"W2438M",
"W2439M",
"W2440M",
"W2445E",
"W2449M",
"W2450M",
"W2451M",
"W2453M",
"W2454M",
"W2458M",
"W2459M",
"W245M",
"W2460M",
"W2461M",
"W2462M",
"W2463M",
"W2464M",
"W2465M",
"W2466M",
"W2467M",
"W2468M",
"W2469M",
"W2470M",
"W2471M",
"W2472M",
"W2473M",
"W2475M",
"W2480M",
"W2487M",
"W2488M",
"W2493M",
"W2590M",
"W2599M",
"W2614M",
"W2615M",
"W2625M",
"W2639M",
"W2649WJM",
"W2650M",
"W2674M",
"W2684M",
"W2685M",
"W2691M",
"W2694M",
"W2702M",
"W2703M",
"W2704M",
"W2706M",
"W2707M",
"W2711M",
"W2723M",
"W2743M",
"W2744M",
"W2751M",
"W2769M",
"W2770M",
"W2771M",
"W2772M",
"W2773M",
"W2774M",
"W2775M",
"W2775WJM",
"W2777M",
"W2780M",
"W2781M",
"W2782M",
"W2784M",
"W2785M",
"W278M",
"W2791M",
"W2804M",
"W295M",
"W343M",
"W345M",
"W352M",
"W366HDAM",
"W366M",
"W373HDAM",
"W373HDM",
"W373M",
"W375M",
"W381M",
"W382M",
"W384M",
"W386HDAM",
"W386M",
"W397M",
"W399M",
"W401M",
"W4027M",
"W404M",
"W411M",
"W413HDAM",
"W413M",
"W424M",
"W431M",
"W442HDM",
"W442M",
"W450HDM",
"W450M",
"W451M",
"W455HDM",
"W455M",
"W457M",
"W458HDAM",
"W458M",
"W459M",
"W460M",
"W461HDAM",
"W461HDM",
"W461M",
"W466M",
"W473M",
"W478M",
"W479M",
"W482M",
"W483M",
"W484M",
"W485HDM",
"W485M",
"W486M",
"W487M",
"W490HDM",
"W490M",
"W493M",
"W494M",
"W500M",
"W505M",
"W508M",
"W510HDM",
"W510M",
"W520HDAM",
"W520HDM",
"W520M",
"W525M",
"W528M",
"W529M",
"W530M",
"W535M",
"W536M",
"W538HDAM",
"W538M",
"W540M",
"W544M",
"W545M",
"W546M",
"W547HDAM",
"W547M",
"W553M",
"W560M",
"W561M",
"W562M",
"W564M",
"W565M",
"W566M",
"W568M",
"W571HDM",
"W571M",
"W572HDAM",
"W572M",
"W573M",
"W574M",
"W576M",
"W577M",
"W578M",
"W583M",
"W584M",
"W587M",
"W588M",
"W592M",
"W594M",
"W595HDAM",
"W595M",
"W596M",
"W598M",
"W599HDM",
"W599M",
"W600M",
"W601M",
"W602M",
"W603M",
"W604M",
"W605M",
"W606M",
"W608M",
"W609M",
"W610M",
"W613M",
"W614M",
"W616M",
"W617M",
"W618M",
"W619M",
"W620M",
"W621M",
"W622M",
"W623M",
"W624M",
"W625M",
"W627M",
"W630M",
"W631M",
"W632M",
"W634M",
"W635M",
"W636M",
"W637M",
"W638M",
"W639M",
"W641HDAM",
"W641M",
"W642M",
"W644M",
"W645HDAM",
"W645M",
"W646M",
"W647M",
"W649M",
"W651M",
"W652M",
"W653M",
"W654M",
"W656M",
"W657HDAM",
"W657M",
"W659M",
"W660M",
"W661M",
"W662M",
"W662WJM",
"W663M",
"W664M",
"W665M",
"W666M",
"W667M",
"W668M",
"W669M",
"W671M",
"W672M",
"W676M",
"W677M",
"W678M",
"W681M",
"W682M",
"W683M",
"W685M",
"W686M",
"W687M",
"W690M",
"W692M",
"W693M",
"W694M",
"W695M",
"W698M",
"W700M",
"W702M",
"W705M",
"W707M",
"W708M",
"W710M",
"W711HDM",
"W711M",
"W715HDM",
"W715M",
"W717M",
"W718M",
"W719M",
"W721M",
"W722M",
"W723M",
"W724M",
"W726M",
"W728M",
"W732M",
"W736M",
"W743M",
"W745M",
"W746M",
"W747M",
"W749M",
"W750M",
"W751M",
"W754M",
"W755M",
"W756M",
"W757M",
"W758M",
"W759M",
"W763M",
"W764M",
"W765M",
"W766M",
"W767M",
"W768M",
"W769M",
"W770M",
"W772M",
"W773M",
"W774M",
"W775M",
"W776M",
"W777M",
"W779M",
"W780M",
"W781M",
"W782M",
"W783M",
"W784M",
"W785M",
"W786M",
"W787M",
"W789M",
"W792M",
"W795M",
"W798M",
"W800M",
"W801M",
"W802M",
"W803M",
"W806M",
"W807M",
"W809M",
"W810M",
"W811M",
"W812M",
"W813M",
"W815M",
"W816M",
"W819M",
"W821M",
"W825M",
"W833M",
"W834M",
"W835M",
"W836M",
"W837M",
"W838M",
"W839M",
"W840M",
"W841M",
"W842M",
"W843M",
"W844M",
"W846M",
"W848M",
"W849M",
"W853M",
"W856M",
"W858M",
"W859M",
"W860M",
"W861M",
"W862M",
"W863M",
"W864M",
"W865M",
"W866M",
"W867M",
"W868M",
"W869M",
"W870M",
"W871M",
"W873M",
"W875M",
"W876M",
"W877M",
"W878M",
"W880M",
"W881M",
"W882M",
"W883M",
"W884M",
"W885M",
"W887M",
"W888M",
"W890M",
"W891M",
"W893M",
"W894M",
"W895M",
"W896M",
"W897M",
"W898M",
"W899M",
"W9000M",
"W9001M",
"W9002M",
"W9003M",
"W9004M",
"W9005M",
"W9006M",
"W9008M",
"W9010M",
"W9013M",
"W9014M",
"W9015M",
"W9016M",
"W9017M",
"W9018M",
"W9019M",
"W9020M",
"W9021M",
"W9022M",
"W9023M",
"W9024M",
"W9025M",
"W9026M",
"W9028M",
"W9029M",
"W9030M",
"W9031M",
"W9032M",
"W9033M",
"W9035M",
"W9035WJM",
"W9036M",
"W9037M",
"W9038M",
"W9039M",
"W9043M",
"W9044M",
"W9045M",
"W9046M",
"W9047M",
"W9048M",
"W9049M",
"W9051M",
"W9053M",
"W9054M",
"W9055M",
"W9057M",
"W9059M",
"W9060M",
"W9061M",
"W9062M",
"W9067M",
"W9068M",
"W9072M",
"W9073M",
"W9074M",
"W9078M",
"W9080M",
"W9081M",
"W9084M",
"W9086M",
"W9087M",
"W9089M",
"W9090M",
"W9091M",
"W9095M",
"W9096M",
"W9097M",
"W9098M",
"W9099M",
"W9100M",
"W9101M",
"W9102M",
"W9103M",
"W9105M",
"W9107M",
"W9108M",
"W9110M",
"W9113M",
"W9114M",
"W9115M",
"W9119M",
"W9120M",
"W9121M",
"W9122M",
"W9124M",
"W9125M",
"W9126M",
"W9127M",
"W9128M",
"W9129M",
"W9130M",
"W9131M",
"W9132M",
"W9133M",
"W9134M",
"W9135M",
"W9136M",
"W9137M",
"W9138M",
"W9139M",
"W9140M",
"W9141M",
"W9142M",
"W9143M",
"W9144M",
"W9145M",
"W9147M",
"W9148M",
"W9149M",
"W9150M",
"W9151M",
"W9152M",
"W9153M",
"W9154M",
"W9156M",
"W9157M",
"W9158M",
"W9160M",
"W9163M",
"W9164M",
"W9165M",
"W9166M",
"W9167M",
"W9170M",
"W9171M",
"W9173M",
"W9174M",
"W9175M",
"W9176M",
"W9177M",
"W9182M",
"W9187M",
"W9189M",
"W9200M",
"W9201M",
"W9202M",
"W9203M",
"W9204M",
"W9207M",
"W9210M",
"W9216M",
"W9219M",
"W9225M",
"W9228M",
"W9231M",
"W9234M",
"W9237M",
"W9240M",
"W9243M",
"W9246M",
"W9249M",
"W9251M",
"W9254M",
"W9256M",
"W9257M",
"W9260M",
"W9270M",
"W9271M",
"W9272M",
"W9273M",
"W9275M",
"W9276M",
"W9277M",
"W9301M",
"W9303M",
"W9304M",
"W9305M",
"W9309M",
"W9313M",
"W9314M",
"W9316M",
"W9320M",
"W9322M",
"W9325M",
"W9330M",
"W9333M",
"W9334M",
"W9335M",
"W9336M",
"W9337M",
"W9338M",
"W9339M",
"W9340M",
"W9341M",
"W9342M",
"W9343M",
"W9344M",
"W9345M",
"W9346M",
"W9347M",
"W9348M",
"W9349M",
"W9350M",
"W9351M",
"W9352M",
"W9354M",
"W9356M",
"W9358M",
"W9360M",
"W9361M",
"W9363M",
"W9366M",
"W9367M",
"W9368M",
"W9369M",
"W9371M",
"W9372M",
"W9374M",
"W9375M",
"W9376M",
"W9377M",
"W9378M",
"W9379M",
"W9380M",
"W9408M",
"W9409M",
"W9411M",
"W9412M",
"W9413M",
"W9414M",
"W9415M",
"W9418M",
"W9500M",
"W9502M",
"W9508M",
"W9524M",
"W9525M",
"W9526M",
"W9528M",
"W9532M",
"W9537M",
"W9542M",
"W9544M",
"W9551M",
"W9552M",
"W9555M",
"W9556M",
"W9558M",
"W9559M",
"W9700M",
"W9701M",
"WHD3000M",
"WHD6000M",
"WHD6001M",
"WHD6002M",
"WHD6006M",
"WHD6012M",
"WHD6051M",
"WHD6052M",
"WHD6053M",
"WHD6057M",
"WHD6061M",
"WHD6062M",
"WHD6063M",
"WHD6064M",
"WHD6068M",
"WHD6069M",
"WHD6073M",
"WHD6076M",
"WHD6090M",
"WHD6113M",
"WHD6119M",
"WHD6205M",
"WHD6208M",
"WHD6301M",
"WHD6303M",
"WHD6307M",
"WHD6308M",
"WHD6309M",
"WHD6315M",
"WHD6325M",
"WHD6500M",
"WHD6501M",
"WHD6502M",
"WHD6520M",
"WHD6542M",
"WHD6543M",
"WHD6545M",
"WHD6550M",
"WHD6601M",
"WHD6602M",
"WHD6603M",
"WHD6700M",
"WHD7315M",
"W9146M",
"W9331M",
"W2477M",
"W2608M",
"W2616M",
"W2690M",
"W2699M",
"W2700M",
"W2754M",
"W2790M",
"W2826M",
"W2827M",
"W2828M",
"W2829M",
"W2830M",
"W2851M",
"W2853M",
"W2854M",
"W2855M",
"W2858M",
"W2859M",
"W2860M",
"W2861M",
"W2862M",
"W2863M",
"W2864M",
"W2865M",
"W2866M",
"W2867M",
"W9423M",
"W2649M",
"W2500M",
"W5050M",
"W5051M",
"W5060M",
"W5062M",
"W5071M",
"W6102M",
"W6103M",
"W6105M",
"W6121M",
"W2331M",
"W2889E",
"W9409RFPK",
"W9409RFPK-2",
"W9240RFPK",
"W9240RFPK-2",
"W9101RFPK",
"W2901M",
"W2904M",
"W2841M",
"W2817M",
"W2906M",
"W2912M",
"W2913M",
"W2956E",
"W2902M",
"W2922E",
"W2783M",
"W2900M",
"W2903M",
"W2905M",
"W2911M",
"W2923E",
"W2927E",
"W2928E",
"W2930E",
"W2933M",
"W2934E",
"W2936M",
"W9128RF",
"W9303RF",
"W2938M",
"W2380E",
"W2381E",
"W2383E",
"W2384E",
"W2385E",
"W2387E",
"W2389E",
"W2390E",
"W2391E",
"W2522E",
"W2523E",
"W2524E",
"W2525E",
"W2526E",
"W2527E",
"W2529E",
"W2530E",
"W2531E",
"W2582E",
"W2583E",
"W2584E",
"W2585E",
"W2586E",
"W2631E",
"W2632E",
"W2633E",
"W2634E",
"W2635E",
"W2636E",
"W2637E",
"W2638E",
"W2714E",
"W2715E",
"W2716E",
"W2721E",
"W2725E",
"W2726E",
"W2727E",
"W2728E",
"W2730E",
"W2731E",
"W2733E",
"W2776E",
"W2807E",
"W2808E",
"W2809E",
"W2810E",
"W2811E",
"W2812E",
"W2813E",
"W2814E",
"W9278E",
"W2806E",
"W2844E",
"W2884E",
"W2885E",
"W2886E",
"W2887E",
"W2888E",
"W2908E",
"W2883E",
"W2925E",
"W2926E",
"W2929E",
"W2495E",
"W2914E",
"W2915E",
"W2953E",
"W2954E",
"W2955E",
"W2746E",
"W2957E",
"W2958E",
"W2959E",
"W2932E",
"W2824E",
"W2879E",
"W2935E",
"W2944E",
"W2945E",
]

In [78]:
cols =['PartNumber'] #,'Review_Mentions','Standards'
df1 = pd.DataFrame(columns=cols)
df2 = pd.DataFrame(columns=cols)
count1=0
count2=0

In [34]:
driver.find_elements(By.CLASS_NAME,"product-item-link")[0].click()

In [66]:
searchbox=driver.find_element(By.ID,"search")
searchbox.clear()

In [99]:
for l in tqdm(range(818,len(List))):
    print(l,List[l])
    searchbox=driver.find_element(By.ID,"search")
    searchbox.click()
    searchbox.send_keys(List[l])
    searchbox.send_keys(Keys.ENTER)
    sleep(1)
    try:
        try:
            driver.find_elements(By.CLASS_NAME,"product-item-link")[0].click()
        except:
            pass
        left=driver.find_elements(By.CLASS_NAME,'product-basic-details__text--left')
        right=driver.find_elements(By.CLASS_NAME,'product-basic-details__text--right')
        try:
            PartName=driver.find_element(By.CLASS_NAME,'product-basic-details__text--title').text
            for i, j in zip( left, right):
                df1.loc[count1,'PartNumber']=List[l]
                df1.loc[count1,'PartName']=PartName 
                df1.loc[count1,"Attribute"]=i.text
                df1.loc[count1,"Value"]=j.text
                count1=count1+1
            try:        
                df2.loc[count2,'PartNumber']=List[l]
                df2.loc[count2,'PartName']=PartName   
                df2.loc[count2,"Application"]=driver.find_element(By.CLASS_NAME,"app-summary--text").text
                count2=count2+1
                clear_output(wait=True)   
            except:
                pass
            driver.find_element(By.CLASS_NAME,'div-return-plp').click()
        except:
            searchbox=driver.find_element(By.ID,"search")
            searchbox.clear()
    except:
        searchbox=driver.find_element(By.ID,"search")
        searchbox.clear()
        pass
    sleep(1)

 94%|█████████▎| 117/125 [30:15<00:54,  6.80s/it]

935 W2958E

 94%|█████████▍| 118/125 [30:21<00:44,  6.29s/it]

936 W2959E

 95%|█████████▌| 119/125 [30:25<00:34,  5.81s/it]

937 W2932E

 96%|█████████▌| 120/125 [30:31<00:29,  5.81s/it]

938 W2824E

 97%|█████████▋| 121/125 [30:36<00:22,  5.55s/it]

939 W2879E

 98%|█████████▊| 122/125 [30:41<00:16,  5.44s/it]

940 W2935E

 98%|█████████▊| 123/125 [30:47<00:10,  5.42s/it]

941 W2944E

 99%|█████████▉| 124/125 [30:52<00:05,  5.34s/it]

942 W2945E

100%|██████████| 125/125 [30:56<00:00, 14.86s/it]

In [100]:
df1

,PartNumber,PartName,Attribute,Value
0,W1000M,ENGINE WATER PUMP,Mounting Hardware Included:,No
1,W1000M,ENGINE WATER PUMP,Mounting Hole Quantity:,4
2,W1000M,ENGINE WATER PUMP,Housing Material:,Cast Iron
3,W1000M,ENGINE WATER PUMP,Pulley Included:,Yes
4,W1000M,ENGINE WATER PUMP,Fan Clutch Included:,No
...,...,...,...,...
13277,W2957E,ENGINE AUXILIARY WATER PUMP,Mounting Hole Diameter:,N/A
13278,W2957E,ENGINE AUXILIARY WATER PUMP,Backing Type:,N/A
13279,W2957E,ENGINE AUXILIARY WATER PUMP,Pulley Flange Mount Hole Quantity:,N/A
13280,W2957E,ENGINE AUXILIARY WATER PUMP,Pulley Flange Thickness:,N/A
13281,W2957E,ENGINE AUXILIARY WATER PUMP,Pulley Flange Diameter:,N/A

In [101]:
df2

,PartNumber,PartName,Application
0,0,ENGINE WATER PUMP,Henry J Corsair (1952-1954)\nJeep CJ6A (1966-1...
1,1,ENGINE WATER PUMP,Austin Marina (1973-1975)\nMG MGB (1972-1980)
2,2,ENGINE WATER PUMP,Austin A40 (1961)\nMG Midget (1962-1974)\nMorr...
3,3,ENGINE WATER PUMP,Fiat 124 (1974-1983)\nFiat 131 (1975-1978)\nFi...
4,4,ENGINE WATER PUMP,Audi A3 (2006-2008)\nVolkswagen Golf R (2012-2...
...,...,...,...
902,929,ENGINE AUXILIARY WATER PUMP,2014-2019 BMW X5 (Liter: 3.0); 2014-2018 BMW 6...
903,930,ENGINE AUXILIARY WATER PUMP,"Audi RS4 2008-07, S4 2009-04"
904,931,ENGINE AUXILIARY WATER PUMP,"Audi A8 Quattro 2009-05, Allroad Quattro 2005-04"
905,932,ENGINE AUXILIARY WATER PUMP,Audi A5 2.0L 2009-2012
906,934,ENGINE AUXILIARY WATER PUMP,"BMW 525i 2004-01, 528i 2000-96, 530i 2001, X5 ..."

In [102]:
OFolder=r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\92_Our Products"

In [103]:
with pd.ExcelWriter(OFolder+'\\'+'Carter_Extract.xlsx') as writer:  # doctest: +SKIP
    df1.to_excel(writer,index=False, sheet_name='Attributes')
    df2.to_excel(writer,index=False, sheet_name='Application')