In [1]:
# pip install selenium

# 1. Library calling

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
import pandas as pd
import datetime

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

# 2. Defining the Product Information and Location

In [3]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][70]
print(search_text)
From="Google"
Folder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{From}\Outputs'
Selection='Buy '

                           Product Name
0                         Ignition Coil
1               Windshield Washer Pumps
2                 coupler trailer locks
3   Adjustable Trailer Hitch Ball Mount
4                        Vacuum Cleaner
..                                  ...
66                                DOT 5
67             Brake Spreading Tool kit
68                  Drum Brake Tool Kit
69                  Brake Spring Pliers
70               swing away hitch mount

[71 rows x 1 columns]
swing away hitch mount

# 3. Setting Webdriver and Website Specific Information

In [4]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.google.com')
driver.maximize_window()
wait=WebDriverWait(driver, 10)

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

In [5]:
driver.find_element(By.CSS_SELECTOR,'[class="ayzqOc pHiOh"]').click()
element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '[class="YpcDnf OSrXXb HG1dvd"]')))
element.click()
element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '[class="nAmqJe EpPYLd Zt0a5e"]')))
element.click()

element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '[class="z1asCe GNeCNe"]')))
element.click()

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
confirm_button = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '[data-pid="gl"]')))
confirm_button.click()

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
option_text = 'United States'

# Find the option using XPath and text
option_xpath = f'//div[text()="{option_text}"]/parent::g-menu-item'
option_element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, option_xpath)))

# Click the option
option_element.click()

In [6]:
driver.get('https://www.google.com')

In [7]:
search=driver.find_element(By.CSS_SELECTOR,'[class="a4bIc"]')
search.click()


input=driver.find_element(By.CSS_SELECTOR,'[id="APjFqb"]')
input.send_keys(Selection+search_text)

input.submit()
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
driver.find_element(By.CSS_SELECTOR,'[jsname="bVqjv"]').click()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [70]:
cols =['Sl.No'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)

count=0
df

Empty DataFrame
Columns: [Sl.No]
Index: []

In [16]:
driver.find_elements(By.CLASS_NAME,"gG84n")[1].text

'$1,099.95'

In [17]:
driver.find_elements(By.CLASS_NAME,"lmQWe")[1].text

'$1,099.95'

In [25]:
print(driver.find_elements(By.CLASS_NAME,"MUWJ8c")[1].text)

RockyMounts AfterParty Swing Away Platform Hitch Rack
$1,099.95
rockymounts.com
, 10+
 Free by 9/10
4.4
(16)

In [49]:
details=driver.find_elements(By.CLASS_NAME,"MUWJ8c")

In [71]:
for det in details:
    df.loc[count,'Sl.No']=count
    df.loc[count,'Name']=det.text.split("\n")[0]
    df.loc[count,'Current Price']=det.find_element(By.CLASS_NAME,"lmQWe").text.replace("$","").replace(",","")
    try:
        df.loc[count,'Rating']=det.find_element(By.CSS_SELECTOR,'[class="yi40Hd YrbPuc"]').text
    except:
        df.loc[count,'Rating']=""
    try:
        df.loc[count,'No of Ratings']=det.find_element(By.CSS_SELECTOR,'[class="RDApEe YrbPuc"]').text.replace("(","").replace(")","")
    except:
        df.loc[count,'No of Ratings']=""
    df.loc[count,'Source']=det.find_element(By.CSS_SELECTOR,'[class="WJMUdc cyspcb"]').text
    count=count+1

In [72]:
df=df.dropna(subset=["Sl.No"])

In [73]:
df=df[df["Name"]!=""]

In [74]:
df

,Sl.No,Name,Current Price,Rating,No of Ratings,Source
0,0,KAC Swing Away Hitch Adapter,379.99,,,Amazon.com - Seller
1,1,RockyMounts AfterParty Swing Away Platform Hit...,1099.95,4.4,16,rockymounts.com
2,2,Rage Powersport Swing Away Option for Hitch Mo...,159.99,3.6,98,Walmart - Discount Ramps
3,3,Saris Swing Away Accessory Hitch,349.99,4.4,18,Home Depot
4,4,Stowaway SwingAway Hitch Cargo Rack,749.00,,,Amazon.com - Seller
...,...,...,...,...,...,...
250,250,3 Bike Rack Bicycle Carrier Racks Hitch Mount ...,87.99,,,Amazon.com - Seller
252,252,KYX Bike Rack,299.99,,,Amazon.com
254,254,"RockyMounts MonoRail 2"" Bike Hitch Rack",499.95,4.7,118,rockymounts.com
256,256,"WILDROAD E-Bike Hitch Rack for Car, Quick Rele...",170.97,,,Amazon.com - Seller
258,258,Saris Freedom 4 Bike Hitch Rack,649.99,4.4,111,Saris Equipment

In [ ]:
        try: 
            filename=df1["Links"][i].split("/")[-1]+".jpg" # Extract filename from URL (modify if needed)
            t=driver.find_element(By.CSS_SELECTOR,'[id="landingImage"]')
            s=t.get_attribute('src')
            import requests

            # Download the image using requests
            response = requests.get(s, stream=True)

            if response.status_code == 200:            
                savepath=imagepath+"\\"+str(i)+"_"+filename
                df.loc[count,'ImageName']=str(i)+"_"+filename
            # Get filename from URL or generate a unique one
                with open(savepath, 'wb') as f:
                    for chunk in response.iter_content(1024):
                        f.write(chunk)
                print(f"Image downloaded: {filename}")
            else:
                print(f"Failed to download image: {s}")
        except:
            print(f"part number not available for {filename}")

In [42]:
driver.find_elements(By.CLASS_NAME,"XNo5Ab")[1].get_attribute('src')

'https://encrypted-tbn0.gstatic.com/favicon-tbn?q=tbn%3AANd9GcSOhNSCWTZdY8XUZUA9e9uYTo08qpl28BcrKQfyJF3oRiPhzybMTRIhlkKVC_-ozYprIYOazfJoo0JGV054UAuw4P5iYNXd4HY'

In [11]:
for i in range(5):
    try:
        viewmore=driver.find_element(By.CLASS_NAME,'avgUYd').click()
    except:
        print("No More")
    elements = WebDriverWait(driver, 10).until(EC.presence_of_all_elements_located((By.CLASS_NAME, 'sh-dgr__grid-result')))
    # Iterate through each element and extract the information
    for element in elements:
        title = element.find_element(By.CLASS_NAME, 'tAxDx').text
        price = element.find_element(By.CLASS_NAME, 'a8Pemb').text
        href = element.find_element(By.CSS_SELECTOR, 'a.shntl').get_attribute('href').split('url=')[1]
        Source=element.find_element(By.CLASS_NAME,'aULzUe').text
        Rating=element.find_element(By.CLASS_NAME,'QIrs8').text
        #print(Rating)
        if 'star' in Rating:
            df.loc[count,'Rating']=Rating.split(' out of')[0]
            df.loc[count,'No of Ratings']=Rating.split(' product')[0].split('s.')[1]
        else:
            df.loc[count,'Rating']=0
            df.loc[count,'No of Ratings']=0
        if 'Was' in Rating:
            df.loc[count,'List Price']=Rating.split("Was ")[1].rsplit('.')[1]
        else:
            df.loc[count,'List Price']= price 
        df.loc[count,'Sl.No']=count+1
        df.loc[count,'Name']=title
        df.loc[count,'Current Price']=price
        df.loc[count,'Links']=href.split('%3F')[0]
        df.loc[count,'Source']=From
        count=count+1

    driver.find_element(By.CSS_SELECTOR,'[id="pnnext"]').click()
    i=i+1
df

No More

TimeoutException: Message:

In [12]:
df

Empty DataFrame
Columns: [Sl.No]
Index: []

# 5. Post Processing Data and Exporting

In [10]:
df["Rating"]=df["Rating"].astype(float)
df["No of Ratings"]=df["No of Ratings"].str.replace(",","").astype(float)
df['List Price']=df['List Price'].str.replace("$","").str.replace(''',''',"").astype(float)
df["Current Price"]=df['Current Price'].str.replace("$","").str.replace(",","").astype(float)
df['Sl.No']=df['Sl.No'].astype(int)
df[['Rating',"No of Ratings","Source"]]

     Rating  No of Ratings  Source
0       4.7         1281.0  Google
1       0.0            NaN  Google
2       0.0            NaN  Google
3       4.7         1286.0  Google
4       0.0            NaN  Google
..      ...            ...     ...
315     0.0            NaN  Google
316     0.0            NaN  Google
317     0.0            NaN  Google
318     0.0            NaN  Google
319     0.0            NaN  Google

[320 rows x 3 columns]

In [11]:
cols=["Sl.No",
"Name",
"Current Price",
"List Price",
"Rating",
"No of Ratings",
"Links",
"Source"
]
df=df[cols]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 320 entries, 0 to 319
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.No          320 non-null    int32
 1   Name           320 non-null    object
 2   Current Price  320 non-null    float64
 3   List Price     320 non-null    float64
 4   Rating         320 non-null    float64
 5   No of Ratings  67 non-null     float64
 6   Links          320 non-null    object
 7   Source         320 non-null    object
dtypes: float64(4), int32(1), object(3)
memory usage: 29.4+ KB

In [13]:
df.to_excel(Folder+'\\'+f'{From}_SearchProductDetails_'+search_text+'.xlsx', index=False,sheet_name='Raw')

# 99. Archived Codes