# 1. Library calling

In [1]:
#pip install selenium
#pip install webdriver_manager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [2]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)
Source="HomeDepo"
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

# 3. Setting Webdriver and Website Specific Information

In [3]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://www.homedepot.com/')
driver.maximize_window()
### Please update capatche.

In [4]:
location = driver.find_element(By.CSS_SELECTOR, '[data-testid="delivery-zip-button"]')
location.click()
sleep(1)

pin = driver.find_element(By.CSS_SELECTOR, '[placeholder="Enter ZIP Code"]')
pinnumber='94203'
pin.send_keys(pinnumber)
pin.submit()

In [5]:
# Find the search bar by its ID
try:
    search_bar = driver.find_element(By.CSS_SELECTOR, '[data-testid="typeahead-search-field-input"]')    
except:
    search_bar=driver.find_element(By.ID, "twotabsearchtextbox")

# Enter the search text

search_bar.send_keys(search_text)

# Submit the form to perform the search
search_bar.submit()

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [6]:
Cols=["Links","Name"]
df = pd.DataFrame(columns=Cols)
df
count=0

In [7]:

for i in range(10):
    driver.execute_script("window.scrollTo(0, 4600);")
    sleep(1)
    product_pods = driver.find_elements(By.CSS_SELECTOR, '[data-testid="product-header"][data-component="ProductHeader"]')
    print(len(product_pods))
    # Create a list to store product information
    product_info_list = []
    row=0
    # Iterate through each product pod
    for product_pod in product_pods:
        if row<24:
            # Extract product title
            product_title = product_pod.find_element(By.CLASS_NAME, 'product-header__title-product--ey0fs').text.strip()

            # Extract href value
            product_href = product_pod.find_element(By.CSS_SELECTOR, 'a').get_attribute('href').strip()

            # Append the product information to the list
            df.loc[count,'Links']=product_href
            df.loc[count,'Name']=product_title
            row=row+1
            count=count+1
        else:
            break

    elemento = driver.find_element(By.CLASS_NAME,"results-pagination__counts")
    print(elemento.text)
    # Print the text content of the element
    #print("Element Text:", element.text)
    max=elemento.text.split('of')[0].split('-')[1]
    TotalPage=elemento.text.split('of')[1].split('results')[0]
    print(max,TotalPage)

    if max!= TotalPage:
        next_button = driver.find_element(By.CSS_SELECTOR, '[aria-label="Next"]')
        #driver.execute_script("window.scrollTo(0, 3000);")
        #driver.execute_script("arguments[0].scrollIntoView();", next_button)
        next_button.click()
        sleep(1)
        #driver.refresh()
        i=i+1
        sleep(2)
        print("---------------------------------")
    else:
        break

41
Showing 1-24 of 105 results.
24   105
---------------------------------
51
Showing 25-48 of 112 results.
48   112
---------------------------------
51
Showing 49-72 of 112 results.
72   112
---------------------------------
36
Showing 73-96 of 112 results.
96   112
---------------------------------
19
Showing 97-105 of 105 results.
105   105

ElementClickInterceptedException: Message: element click intercepted: Element <a class="hd-pagination__link " href="/s/?keyword=Washer+Fluid+Reservoir&amp;" aria-label="Next"></a> is not clickable at point (1179, 21). Other element would receive the click: <div class="sui-flex sui-font-regular sui-items-center sui-bg-primary sui-text-primary sui-px-4 sui-pt-4 sui-pb-12 sui-gap-2 sui-bg-primary lg:sui-pb-4 lg:sui-gap-6">...</div>
  (Session info: chrome=121.0.6167.161)
Stacktrace:
	GetHandleVerifier [0x00007FF7AEEB5E42+3538674]
	(No symbol) [0x00007FF7AEAD4C02]
	(No symbol) [0x00007FF7AE985AEB]
	(No symbol) [0x00007FF7AE9D33E4]
	(No symbol) [0x00007FF7AE9D1122]
	(No symbol) [0x00007FF7AE9CE884]
	(No symbol) [0x00007FF7AE9CD5A9]
	(No symbol) [0x00007FF7AE9C1950]
	(No symbol) [0x00007FF7AE9EF0AA]
	(No symbol) [0x00007FF7AE9C124A]
	(No symbol) [0x00007FF7AE9EF2C0]
	(No symbol) [0x00007FF7AEA0BDE3]
	(No symbol) [0x00007FF7AE9EEE53]
	(No symbol) [0x00007FF7AE9BF514]
	(No symbol) [0x00007FF7AE9C0631]
	GetHandleVerifier [0x00007FF7AEEE6CAD+3738973]
	GetHandleVerifier [0x00007FF7AEF3C506+4089270]
	GetHandleVerifier [0x00007FF7AEF34823+4057299]
	GetHandleVerifier [0x00007FF7AEC05C49+720121]
	(No symbol) [0x00007FF7AEAE126F]
	(No symbol) [0x00007FF7AEADC304]
	(No symbol) [0x00007FF7AEADC432]
	(No symbol) [0x00007FF7AEACBD04]
	BaseThreadInitThunk [0x00007FFED19A7344+20]
	RtlUserThreadStart [0x00007FFED1AE26B1+33]

In [8]:
df

,Links,Name
0,https://www.homedepot.com/p/OE-Solutions-Winds...,OE Solutions\nWindshield Washer Fluid Reservoir
1,https://www.homedepot.com/p/Washer-Fluid-Reser...,Washer Fluid Reservoir Cap 2012-2017 Ford Focu...
2,https://www.homedepot.com/p/OE-Solutions-Winds...,OE Solutions\nWindshield Washer Fluid Reservoir
3,https://www.homedepot.com/p/Rain-X-128-fl-oz-3...,Rain-X\n128 fl. oz. +32°F Degree Bug Remover W...
4,https://www.homedepot.com/p/Washer-Fluid-Reser...,Washer Fluid Reservoir Cap
...,...,...
110,https://www.homedepot.com/p/Thinkcar-8-in-OBD2...,Thinkcar\n8 in. OBD2 Scanner Tablet Profession...
111,https://www.homedepot.com/p/Thinkcar-OBD2-Scan...,Thinkcar\nOBD2 Scanner Car Code Reader Check E...
112,https://www.homedepot.com/p/Thinkcar-Professio...,Thinkcar\nProfessional Mechanic OBD2 Scanner C...
113,https://www.homedepot.com/p/VEVOR-Refrigerant-...,
114,https://www.homedepot.com/p/VEVOR-Drive-Shaft-...,

# 5. Post Processing Data and Exporting

In [10]:
df=df.drop_duplicates(subset=["Links"])
df

,Links,Name
0,https://www.homedepot.com/p/OE-Solutions-Winds...,OE Solutions\nWindshield Washer Fluid Reservoir
1,https://www.homedepot.com/p/Washer-Fluid-Reser...,Washer Fluid Reservoir Cap 2012-2017 Ford Focu...
2,https://www.homedepot.com/p/OE-Solutions-Winds...,OE Solutions\nWindshield Washer Fluid Reservoir
3,https://www.homedepot.com/p/Rain-X-128-fl-oz-3...,Rain-X\n128 fl. oz. +32°F Degree Bug Remover W...
4,https://www.homedepot.com/p/Washer-Fluid-Reser...,Washer Fluid Reservoir Cap
...,...,...
110,https://www.homedepot.com/p/Thinkcar-8-in-OBD2...,Thinkcar\n8 in. OBD2 Scanner Tablet Profession...
111,https://www.homedepot.com/p/Thinkcar-OBD2-Scan...,Thinkcar\nOBD2 Scanner Car Code Reader Check E...
112,https://www.homedepot.com/p/Thinkcar-Professio...,Thinkcar\nProfessional Mechanic OBD2 Scanner C...
113,https://www.homedepot.com/p/VEVOR-Refrigerant-...,
114,https://www.homedepot.com/p/VEVOR-Drive-Shaft-...,

In [11]:
df.to_excel(IFolder+'\\'+f'{Source}ProductLinks_'+search_text+'.xlsx', index=False)

# 99. Archived Codes