# Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import unquote
from selenium.webdriver.support.ui import Select
import pandas as pd
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import datetime 

import warnings

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from IPython.display import clear_output

# Defining the Product Information and Location

In [2]:
Product="Cable Set"

In [3]:
df1=pd.read_excel(input ("Please paste the File path").replace('"',""),sheet_name="Table1")
df1

,Make,Model,Year,Keys,Unnamed: 4,Unnamed: 5
0,Ford,Fairlane,1962.0,1962 Ford Fairlane,NaN,NaN
1,Mercury,Meteor,1962.0,1962 Mercury Meteor,NaN,NaN
2,Ford,300,1963.0,1963 Ford 300,NaN,NaN
3,Ford,Country Sedan,1963.0,1963 Ford Country Sedan,NaN,NaN
4,Ford,Country Squire,1963.0,1963 Ford Country Squire,NaN,NaN
...,...,...,...,...,...,...
2768,Nissan,NP300,2010.0,2010 Nissan NP300,NaN,NaN
2769,Nissan,Pickup,2010.0,2010 Nissan Pickup,NaN,NaN
2770,Nissan,NP300,2011.0,2011 Nissan NP300,NaN,NaN
2771,Nissan,NP300,2012.0,2012 Nissan NP300,NaN,NaN
2772,Oldsmobile,Delta,NaN,Oldsmobile Delta,NaN,NaN

In [4]:
Keys=df1["Keys"]
Keys=list(set(Keys))
print(Keys[1], len(Keys) )

1979 GMC P1500 2773

In [40]:
dfc=pd.read_excel(input ("Please paste the File path").replace('"',""))

CompletedKeys=dfc["Keys"]
print(len(CompletedKeys))

def remove_items_using_set(long_list, items_to_remove):
  """
  Removes items from a long list based on a list of items to remove.

  Args:
      long_list (list): The longer list from which items will be removed.
      items_to_remove (list): The list of items to remove.

  Returns:
      list: A new list with the items removed.
  """
  return list(set(long_list) - set(items_to_remove))

#  Setting Webdriver and Website Specific Information

In [5]:
path= 'C://chromedriver.exe'
browser=webdriver.Chrome()
browser.maximize_window()

In [6]:
browser.get('https://dh.identifix.com/id/login')
sleep(1)

In [7]:
username_field = browser.find_element(By.ID,'UserName')  
username_field.send_keys('constantina')
sleep(1)

password_field = browser.find_element(By.ID,'Password')  
password_field.send_keys('constantina01')
sleep(1)

Login = browser.find_element(By.ID,'Login')  
Login.click()
sleep(1)

home=browser.current_url
browser.get(home)

# Defining the Dataframe and Extracting the data into the Dataframe

## 1. Extracting All Variants

In [15]:
Cols=["Models"]
df1 = pd.DataFrame(columns=Cols)
count=0

In [22]:
from tqdm import tqdm
for x in tqdm(range(787,len(Keys))):
    typebox=WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.ID,"CreateVehicle_suggest_box")))
    #typebox.click()
    boxed=Keys[x]    
    #print(boxed)
    typebox.send_keys(boxed)
    sleep(2)
    o2=browser.find_elements(By.CLASS_NAME,"ui-menu-item")
    for i in range(len(o2)):
        df1.loc[count,'Sl.No']=x
        df1.loc[count,'Models']=Keys[x]
        df1.loc[count,'Variants']=o2[i].text        
        count=count+1
    typebox.clear()

 98%|█████████▊| 1943/1986 [1:10:59<01:34,  2.19s/it]

StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=122.0.6261.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF66D724C82+3505170]
	(No symbol) [0x00007FF66D350852]
	(No symbol) [0x00007FF66D204145]
	(No symbol) [0x00007FF66D213D11]
	(No symbol) [0x00007FF66D209E14]
	(No symbol) [0x00007FF66D2080DA]
	(No symbol) [0x00007FF66D20B54B]
	(No symbol) [0x00007FF66D20B610]
	(No symbol) [0x00007FF66D24B8F5]
	(No symbol) [0x00007FF66D24117F]
	(No symbol) [0x00007FF66D26BE8A]
	(No symbol) [0x00007FF66D23F27A]
	(No symbol) [0x00007FF66D26C0A0]
	(No symbol) [0x00007FF66D2883B2]
	(No symbol) [0x00007FF66D26BC33]
	(No symbol) [0x00007FF66D23D618]
	(No symbol) [0x00007FF66D23E6B1]
	GetHandleVerifier [0x00007FF66D7567DD+3708781]
	GetHandleVerifier [0x00007FF66D7AFC5D+4074477]
	GetHandleVerifier [0x00007FF66D7A7DDF+4042095]
	GetHandleVerifier [0x00007FF66D47A136+708806]
	(No symbol) [0x00007FF66D35CB0F]
	(No symbol) [0x00007FF66D357D14]
	(No symbol) [0x00007FF66D357E6C]
	(No symbol) [0x00007FF66D3479A4]
	BaseThreadInitThunk [0x00007FF9BF427344+20]
	RtlUserThreadStart [0x00007FF9BF7626B1+33]

In [ ]:
n = 3
groups = text.split(',')
','.join(groups[:n]), ','.join(groups[n:])

In [20]:
df1

,Models,Variants,Sl.No
0,1998 Acura CL,"1998 Acura CL 2.3L, L4, Des F23A1, 16V, USA/Ca...",0.0
1,1998 Acura CL,"1998 Acura CL 3.0L, V6, Des J30A1, 24V, USA/Ca...",0.0
2,1998 Acura CL,"1998 Acura CL Premium 2.3L, L4, Des F23A1, 16V...",0.0
3,1998 Acura CL,"1998 Acura CL Premium 3.0L, V6, Des J30A1, 24V...",0.0
4,1979 GMC P1500,"1979 GMC P1500 4.8L, L6, VIN T, 12V, USA/Canada",1.0
...,...,...,...
7580,1988 Ford F-Super Duty,"1988 Ford F Super Duty 7.5L, V8, Gas, VIN G, U...",787.0
7581,1965 Ford Ranchero,"1965 Ford Ranchero 2.8L, L6, VIN U, 12V, USA",788.0
7582,1965 Ford Ranchero,"1965 Ford Ranchero 3.3L, L6, VIN T, 12V, USA",788.0
7583,1965 Ford Ranchero,"1965 Ford Ranchero 4.7L, V8, VIN A, 16V, USA",788.0
7584,1965 Ford Ranchero,"1965 Ford Ranchero 4.7L, V8, VIN C, 16V, USA",788.0

In [ ]:
with pd.ExcelWriter(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df1.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')
    dfAtt.to_excel(writer,index=False, sheet_name='Attribute_Values')

# Post Processing Data

In [34]:
df.to_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\10_Spark Plug Wire Set"+'\\'+'IdentifixLinks'+Product+'_indexed_726+.xlsx', index=False)

# Archived Codes

In [ ]:
for i in range(283,len(Keys)):
    typebox=browser.find_element(By.ID,"CreateVehicle_suggest_box")
    #typebox.click()
    boxed=Keys[i]
    #print(boxed)
    sleep(2)
    typebox.send_keys(boxed)
    sleep(1)
    o2=browser.find_elements(By.CLASS_NAME,"ui-menu-item")
    print("number of vehicle: ", len(o2))
    if(len(o2))<=1:
        o=browser.find_element(By.CLASS_NAME,"ui-menu-item")
        o.click()
    else:
        o2[1].click()
    sleep(3)
    selected_text = WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.CLASS_NAME,"vehicle-info"))).text
    try:        
        OEMRepair = WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.XPATH,"//li/a[text()='OEM Repair/Replace']")))
        # WebDriverWait(browser, max_wait_time).until(OEMRepair)
        sleep(1)
        OEMRepair.click()
        sleep(1)
        #IGCoil = browser.find_element(By.ID,"tb-search-box")
        IGCoil = WebDriverWait(browser, 40).until(EC.element_to_be_clickable(( By.ID,"tb-search-box")))
        element_to_click = WebDriverWait(browser, 40).until(EC.element_to_be_clickable(( By.ID,"bt-search")))
        #WebDriverWait(browser, max_wait_time).until(IGCoil)
        # Click the element
        sleep(5)
        IGCoil.send_keys("Ignition Coil(s)")
        sleep(1)
        #search = WebDriverWait(browser, 40).until(EC.presence_of_element_located((By.ID,"bt-search")))
        element_to_click.click()
        sleep(2)
        #WebDriverWait(browser, max_wait_time).until(search)       
        # expand=browser.find_element(By.CLASS_NAME,"expand-collapse-icon")
        # WebDriverWait(browser, max_wait_time).until(expand)
        # expand.click()
        # link2=browser.find_element(By.CLASS_NAME,'document-link')
        # Page2=link2.get_attribute('href')
        # actions=ActionChains(browser).send_keys(Keys.ARROW_DOWN).send_keys(Keys.ENTER)
        # actions.perform()
        NewV = WebDriverWait(browser, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']=browser.current_url
        print(i+1)
        NewV.click()
    except:
        NewV = WebDriverWait(browser, 40).until(EC.presence_of_element_located((By.XPATH, "//div[@class='sub-menu-item right-sub-menu-item']/a[@title='New Vehicle']")))
        df.loc[i,'Selected Model']=selected_text
        df.loc[i,'Link']="No OEM Repair"
        NewV.click()
    # df.loc[row,"Link2"]=Page2
    #print("Number of items: ",i+1)