# 1. Library calling

In [107]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings


# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [108]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = "MasterCylinder"
print(search_text)
Source="NAPA"
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
filename='_Link.txt'
f=open(IFolder+'\\'+search_text+filename,'r')
Linebraker='geo-pod-lists-innerwrapper'
prefix='https://www.napaonline.com'

                           Product Name
0                         Ignition Coil
1               Windshield Washer Pumps
2                 coupler trailer locks
3   Adjustable Trailer Hitch Ball Mount
4                        Vacuum Cleaner
..                                  ...
70               swing away hitch mount
71                      Garage Products
72                        Oxygen Sensor
73             Brand Specific O2 Sensor
74                                  FOB

[75 rows x 1 columns]
MasterCylinder

# 3. Setting Webdriver and Website Specific Information

In [109]:
content=f.read()
List=content.split(Linebraker)
print(len(List))

1597

In [110]:
content=f.read()
print(content)

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [111]:
cols =['Sl.No'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)

In [112]:
List[12]

'"><div class="geo-pod-offers geo-productpod-top"></div><div class="geo-product-pod"><div class="geo-productpod-middle"><div class="geo-pod-img"><div class="geo-pod-promos"><geo-promotions class="hydrated"></geo-promotions></div><a href="/en/p/UP_M39447"><geo-scene7-img class="hydrated"><geo-img class="hydrated"><host><picture><source srcset="https://media.napaonline.com/is/image/GenuinePartsCompany/291880302?fmt=webp&amp;qlt=70&amp;wid=100&amp;hei=100" media="(max-width:639px)"><source media="(min-width: 640px) and (max-width:1023px)" srcset="https://media.napaonline.com/is/image/GenuinePartsCompany/291880302?fmt=webp&amp;qlt=70&amp;wid=150&amp;hei=150"><source media="(min-width:1024px)" srcset="https://media.napaonline.com/is/image/GenuinePartsCompany/291880302?fmt=webp&amp;qlt=70&amp;wid=200&amp;hei=200"><img src="https://media.napaonline.com/is/image/GenuinePartsCompany/291880302?fmt=jpg&amp;qlt=70" alt="Brake Master Cylinder" width="200" height="200" loading="lazy"></picture></host></geo-img></geo-scene7-img></a></div><div class="geo-pod-container mobile-phablet"><div class="geo-pod-title geo-productpod-top mobile-phablet" title="Brake Master Cylinder"><a href="/en/p/UP_M39447" class="geo-prod_pod_title">Brake Master Cylinder</a><div class="geo-pod-normal-text product-review" data-bv-show="inline_rating" data-bv-product-id="UP_M39447" data-bv-redirect-url="/en/p/UP_M39447#reviews" data-bv-ready="true"><div><a id="b15afc7a-dd17-4edc-8ac1-24f79ead2264" href="/en/p/UP_M39447#reviews" class="bv_main_container bv_hover" aria-label="0.0 out of 5 stars.  "><div class="bv_stars_component_container" aria-hidden="true"><div class="bv_stars_button_container"><span class="bv_stars_svg_no_wrap" aria-hidden="true"><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_0_0.00_wkv7NMRenF&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_0_0.00_wkv7NMRenF&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_0_0.00_wkv7NMRenF" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_1_0.00_ZPQ0yIo8ur&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_1_0.00_ZPQ0yIo8ur&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_1_0.00_ZPQ0yIo8ur" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_2_0.00_AJ63bDZW45&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_2_0.00_AJ63bDZW45&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_2_0.00_AJ63bDZW45" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_3_0.00_5bzt6GncyB&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_3_0.00_5bzt6GncyB&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_3_0.00_5bzt6GncyB" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_4_0.00_VnJWENldcp&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_4_0.00_VnJWENldcp&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_4_0.00_VnJWENldcp" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg></span></div></div><div class="bv_averageRating_component_container" aria-hidden="true"><div class="bv_text">0.0</div></div><div class="bv_numReviews_component_container" aria-hidden="true"><div class="bv_text">(0)</div></div></a></div></div><div class="geo-pod-detail mobile-phablet"><div class="geo-pod-part"><div class="geo-pod-normal-text"><span class="geo-pod-normal-text">Part #: </span>UP M39447</div></div><div class="geo-fitment-type-msg tablet-desktop">Add a vehicle to guarantee fit</div></div></div><div class="geo-fitment-type-msg mobile-phablet">Add a vehicle to guarantee fit</div></div><div class="geo-pod-detail tablet-desktop"><div class="geo-pod-title geo-productpod-top" title="Brake Master Cylinder"><a href="/en/p/UP_M39447" class="geo-prod_pod_title">Brake Master Cylinder</a></div><div class="milwaukee-spacer"></div><div class="geo-pod-normal-text product-review" data-bv-show="inline_rating" data-bv-product-id="UP_M39447" data-bv-redirect-url="/en/p/UP_M39447#reviews" data-bv-ready="true"><div><a id="b5e585a3-f403-4597-b03b-915e93c4839d" href="/en/p/UP_M39447#reviews" class="bv_main_container bv_hover" aria-label="0.0 out of 5 stars.  "><div class="bv_stars_component_container" aria-hidden="true"><div class="bv_stars_button_container"><span class="bv_stars_svg_no_wrap" aria-hidden="true"><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_0_0.00_tAOevkXELD&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_0_0.00_tAOevkXELD&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_0_0.00_tAOevkXELD" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_1_0.00_zrGaEF55Lt&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_1_0.00_zrGaEF55Lt&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_1_0.00_zrGaEF55Lt" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_2_0.00_gGjsHFf71s&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_2_0.00_gGjsHFf71s&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_2_0.00_gGjsHFf71s" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_3_0.00_4eZdgEba9b&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_ratings_star_filled_3_0.00_4eZdgEba9b&quot;) !important;"></path><defs><linearGradient id="bv_inline_ratings_star_filled_3_0.00_4eZdgEba9b" x1="0.00%" y1="0%" x2="100%" y2="0%"><stop offset="0%" style="stop-color: rgb(255, 199, 44); stop-opacity: 1;"></stop><stop offset="1%" style="stop-color: rgb(153, 153, 153); stop-opacity: 1;"></stop></linearGradient></defs></svg><svg focusable="false" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 25 25" style="width: 18px !important; height: 18px !important;"><polygon points="" style="fill: url(&quot;#bv_inline_ratings_star_filled_4_0.00_3fJ1DXsbxN&quot;) !important;"></polygon><path d="M24.8676481,9.0008973 C24.7082329,8.54565507 24.2825324,8.23189792 23.7931772,8.20897226 L16.1009423,8.20897226 L13.658963,0.793674161 C13.4850788,0.296529881 12.9965414,-0.0267985214 12.4623931,0.00174912135 L12.4623931,0.00174912135 C11.9394964,-0.00194214302 11.4747239,0.328465149 11.3146628,0.81767189 L8.87268352,8.23296999 L1.20486846,8.23296999 C0.689809989,8.22949161 0.230279943,8.55030885 0.0640800798,9.0294023 C-0.102119784,9.50849575 0.0623083246,10.0383495 0.472274662,10.3447701 L6.69932193,14.9763317 L4.25734261,22.4396253 C4.08483744,22.9295881 4.25922828,23.4727606 4.68662933,23.7767181 C5.11403038,24.0806756 5.69357086,24.0736812 6.11324689,23.7595003 L12.6333317,18.9599546 L19.1778362,23.7595003 C19.381674,23.9119158 19.6299003,23.9960316 19.8860103,23.9994776 C20.2758842,24.0048539 20.6439728,23.8232161 20.8724402,23.5127115 C21.1009077,23.202207 21.1610972,22.8017824 21.0337405,22.4396253 L18.5917612,14.9763317 L24.6967095,10.3207724 C25.0258477,9.95783882 25.0937839,9.43328063 24.8676481,9.0008973 Z" style="fill: url(&quot;#bv_inline_rat

In [113]:
List[13].split('data-geo-brand="')[1].split('"')[0]

'Dorman'

In [114]:
count=0

for i in range(1,len(List)):
    df.loc[count,'Sl.No']=int(i)
    try:
        df.loc[count,'Current Price']=float(List[i].split('data-price="')[1].split('"><div>')[0])
    except:
        pass
    df.loc[count,'Name']=List[i].split('"geo-prod_pod_title">')[1].split('</a><div')[0]
    df.loc[count,'Links']=prefix+List[i].split('href="')[1].split('"')[0]
    df.loc[count,'Source']=Source
    try:
        df.loc[count,'Brand']=List[i].split('data-geo-brand="')[1].split('"')[0]
    except:
        df.loc[count,'Brand']=""
    df.loc[count,'Part Number']=List[i].split('part-number="')[1].split('" class="')[0]
    count=count+1

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1596 entries, 0 to 1595
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.No          1596 non-null   object
 1   Current Price  1224 non-null   float64
 2   Name           1596 non-null   object
 3   Links          1596 non-null   object
 4   Source         1596 non-null   object
 5   Brand          1596 non-null   object
 6   Part Number    1596 non-null   object
dtypes: float64(1), object(6)
memory usage: 164.3+ KB

In [116]:
df.nunique()

Sl.No            1596
Current Price      96
Name                1
Links             306
Source              1
Brand               2
Part Number       306
dtype: int64

In [117]:
df

,Sl.No,Current Price,Name,Links,Source,Brand,Part Number
0,1,174.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M39999,NAPA,Dorman,M39999
1,2,139.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M631007,NAPA,Dorman,M631007
2,3,66.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M83579,NAPA,Dorman,M83579
3,4,69.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M71248,NAPA,Dorman,M71248
4,5,72.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M39052,NAPA,Dorman,M39052
...,...,...,...,...,...,...,...
1591,1592,129.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M36127,NAPA,Dorman,M36127
1592,1593,190.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M630588,NAPA,Dorman,M630588
1593,1594,185.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M630802,NAPA,Dorman,M630802
1594,1595,114.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M630034,NAPA,Dorman,M630034
1595,1596,134.99,Brake Master Cylinder,https://www.napaonline.com/en/p/UP_M630031,NAPA,Dorman,M630031

# 5. Post Processing Data and Exporting

In [118]:
df['Sl.No']=df['Sl.No'].astype(int)

In [119]:
cols=["Sl.No",
"Name",
"Current Price",
"Brand",
"Part Number",
"Links",
"Source"
]
df = df[cols]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1596 entries, 0 to 1595
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.No          1596 non-null   int64
 1   Name           1596 non-null   object
 2   Current Price  1224 non-null   float64
 3   Brand          1596 non-null   object
 4   Part Number    1596 non-null   object
 5   Links          1596 non-null   object
 6   Source         1596 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 164.3+ KB

In [120]:
df.tail()

,Sl.No,Name,Current Price,Brand,Part Number,Links,Source
1591,1592,Brake Master Cylinder,129.99,Dorman,M36127,https://www.napaonline.com/en/p/UP_M36127,NAPA
1592,1593,Brake Master Cylinder,190.99,Dorman,M630588,https://www.napaonline.com/en/p/UP_M630588,NAPA
1593,1594,Brake Master Cylinder,185.99,Dorman,M630802,https://www.napaonline.com/en/p/UP_M630802,NAPA
1594,1595,Brake Master Cylinder,114.99,Dorman,M630034,https://www.napaonline.com/en/p/UP_M630034,NAPA
1595,1596,Brake Master Cylinder,134.99,Dorman,M630031,https://www.napaonline.com/en/p/UP_M630031,NAPA

In [121]:
df.to_excel(OFolder+'\\'+f'{Source}ProductDetails_'+search_text+'.xlsx', index=False)

# 99. Archived Codes