# 1. Library calling

In [15]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import warnings
from IPython.display import clear_output
import numpy as np
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [16]:
Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\Holes_Engine Water Pump'
#Brand_Name='SCHRADER TPMS SOLUTIONS'
#Type_Name='TPMS Sensor'

# 3. Setting Webdriver and Website Specific Information

In [27]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://web.tecalliance.net/opticat/qa/login')
driver.maximize_window()
wait=WebDriverWait(driver, 10)
button =wait.until(EC.presence_of_element_located((By.ID,"ppms_cm_save-choices")))
button.click()

In [28]:
username_field = driver.find_element(By.ID,'userName')  
username_field.send_keys('vikram.vadhirajan@firstbrandsgroup.com')
password_field = driver.find_element(By.ID,'password')  
password_field.send_keys('FBG@Jun-2024')
button = driver.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()

In [19]:
List=["4792195",
"59121008",
"11511407113",
"11512379782",
"11517555214",
"11517596763",
"11517597715",
"11517604027",
"11517643930",
"11517838135",
"11517838201",
"11517846361",
"11518074234",
"11518482250",
"11518482251",
"11518524797",
"11518582740",
"11518617545",
"11518623574",
"11518632585",
"11518635089",
"11518635090",
"11518638026",
"11518638494",
"11518642290",
"11518650987",
"11518657274",
"11537843738",
"92810601520",
"94410600300",
"94610603300",
"94810601103",
"94810603300",
"95510603300",
"95810603312",
"95810603313",
"95810603340",
"95810603341",
"95812101200",
"95812101210",
"98010601104",
"99710601170",
"038121011A",
"03H121008K|06K121011D|06L121012M",
"03H121008M|06K121011D|06L121012M",
"04E121600AL",
"04L121011E",
"04L121011E|04L121011",
"05E121111AB",
"06060-5K0-000|19200-5K0-A01",
"06191-58G-A00",
"061J0-5WJ-A00|19200-5K0-A01",
"06A121012G",
"06E121016C",
"06E121016N",
"06E121018A",
"06E121018H|06M121013D",
"06K121011B",
"06K121011C",
"06K121011C|06L121012L",
"06K121011C|06L121012L|06L121012M",
"06K121011D",
"06L121012A|06L121012K",
"06L121012A|06L121012L|06L121012M",
"06L121012A|06L121012L|06L121012M|06L121111N",
"06L121012H|06L121012L",
"06L121012H|06L121012L|06L121111N",
"06L121012K",
"06L121012L",
"06L121012L|06L121111N",
"06L121012M",
"06M121013D",
"079121012F",
"079121012F|079121012S",
"079121012S",
"079121012T|079121013M",
"079121013M",
"079121013R",
"079121014M",
"07D121005R",
"07D121008A",
"07K121011J",
"07K121011J|07K121011N",
"07L121014D",
"07P121004",
"07P121005",
"07Z121011",
"0P2121014E",
"0P2121014F",
"0P2121014F|0P2121014H",
"0P2121014H",
"0PB121005A|0PB121010A",
"0PB121005C|0PB121010D",
"0PB121005D|0PB121010E",
"0PB121005D|0PB121010E|0PC121005A|0PC121010A|9A210604004",
"0PB121005D|0PB121010E|0PC121005A|0PC121010A|9A210604004|9A210605001",
"0PB121005D|0PB121010E|0PC121005A|0PC121010A|9A210604004|9A210605002",
"0PB121010A|9A210603972",
"0PB121010C",
"0PB121010C|0PB121035A",
"0PB121010E",
"0PB121010E|0PB121035A",
"0PB121035A",
"0PC121005|0PC121010|9A210604003|9A210605001",
"0PC121005|0PC121010|9A210604003|9A210605002",
"0PC121005A|0PC121005A|0PC121010A|9A210604004|9A210605002",
"0PC121005A|0PC121010A|9A210604004|9A210605001",
"0PC121005A|0PC121010A|9A210604004|9A210605002",
"104123462|JDE40023",
"104123463",
"104123463|LR116115|LR121418|LR146321",
"104123463|LR121418",
"104123463|T4A41037",
"104123502|LR180396",
"104123521",
"11515A444F4|11515A55395|11517952783|11518482251|11518650986|11519453667",
"11515A444F4|11517952783",
"11515A444F4|11517952783|11518482251|11518650986",
"11515A55395|11519453667",
"11517596763|11518635090",
"11517597715|11517604027",
"11517604027|11518516204",
"11517643067|11517643067|11518632585|11518632585",
"11517643067|11518632585",
"11517643930|11518623582",
"11517644809|11518638026",
"11517644810|11518638494",
"11518054857|11518094658",
"11518482250|11518638026",
"11518482250|11518650987",
"11518482250|11518650988",
"11518482251|11518650986",
"11518482251|11518742075|11519489805",
"11518516205|11518635090",
"11518524797|11518543828",
"11518631940|11518678905",
"11518632585|11518632585",
"11518632585|11518638026",
"11518742075|11519489805",
"122123458|JDE41184",
"122123458|LR092953|LR154597",
"122123458|LR154597",
"12622036",
"12638455",
"12645126",
"12657499|12672035",
"12667383",
"12667385",
"12667387",
"12672035",
"12677029",
"12677352|12680257",
"12679360",
"12680257",
"12681169",
"12681169|25205816",
"12681171",
"12683011",
"12685259",
"12686208",
"12687631",
"12687631|12687631",
"12687632",
"12692045",
"12694089",
"12694321",
"12698367|12702611",
"12699889",
"12702611|12714605",
"12706665",
"12707180",
"12707676",
"12707680",
"12707765",
"12708893",
"12708893|12712953",
"12708893|12712953|12724894|12724894|12724894",
"12709178",
"12712271",
"12712953|12712953|12724894|12724894",
"12712953|12712953|12724894|12724894|12724894",
"12712953|12712953|12724894|12724894|12724894|12724894",
"12712953|12724894",
"12712953|12724894|12724894",
"12712953|12724894|12724894|12724894|12724894",
"12712956",
"12713806",
"12714605",
"12717097",
"12718538",
"12720527",
"12724330",
"12724522",
"12724522|12727108",
"12724523",
"12725187|12725191",
"12725728",
"1300A055",
"1300A083",
"1300A107",
"1300A110",
"1300A182",
"1300A196",
"133-200-04-00-80|270-200-06-00-80",
"16020-45050",
"16032-18010|16100-19385",
"16032-24010",
"16032-24010|16032-24010|16032-24020|16032-F2010",
"16032-24010|16032-24010|16032-F2010",
"16032-24020",
"16032-25010",
"16032-25010|16032-25010|16032-F0010",
"16032-25010|16032-25010|16032-F0010|16032-F0011",
"16032-25010|16032-25010|16032-F0011",
"16032-25010|16032-F0010",
"16032-25010|16032-F0010|16032-F0011",
"16032-25010|16032-F0011",
"16032-25030",
"16032-F0010",
"16032-F0010|16032-F0011",
"16032-F0011",
"16032-WAA01|16100-WAA04",
"16032-WAA02|16100-WAA03",
"16100-09491|16100-39496",
"16100-09690",
"16100-09690|16100-39616",
"16100-09720",
"16100-25030",
"16100-25030|16100-F0010",
"16100-25040",
"16100-29157",
"16100-39506",
"16100-39545",
"16100-39555",
"16100-39565",
"16100-39595",
"16100-39616",
"16100-79445",
"16100-79505",
"16100-79525",
"16100-80008",
"16100-80011",
"16100-F9010",
"16100-WAA03",
"16100-WAA04",
"16100-WB001",
"161A0-29015",
"161A0-39035",
"161A0-39045",
"17400-84Z10",
"19200-5J0-A01",
"19200-5K0-A01",
"19200-5K0-A01|19200-6C1-305",
"19200-66V-A01",
"19200-69F-A01",
"19200-6A0-A01",
"19200-6B2-A01",
"19200-6C1-305",
"19200-6FB-A01",
"19200-6S9-A01",
"19200-RDF-A01",
"19200-RDV-J01",
"19200-RPY-G01",
"19200-RW0-003",
"19303456",
"19417097",
"21010-3RC2A",
"21010-4HK0A",
"21010-4HK0E",
"21010-4HK1B",
"21010-5NA0A",
"21010-5RB0A",
"21010-6KA1A",
"21010-6RC0A",
"21010-7S000",
"21010-93C3N",
"21010-9BT0A",
"21010-AL528|B1010-JK20A",
"21010-EZ40A",
"21010-HG00G",
"21010-HG00H",
"21010-HG00H|21010-HG00K",
"21010-HG00K",
"21010-JA11A",
"21010W020P",
"21110AA710",
"21110AA740",
"21110AA770",
"21110AA810",
"21111AA240",
"2510003800",
"2510003HB0",
"2510003HB0|2510003HB0",
"2510008HA0",
"251002B700",
"251002B700|251002B700|251002M800",
"251002B710",
"251002B710|251002B710",
"251002E020",
"251002E050",
"251002E050|251002E050",
"251002E271|251002E272",
"251002E272",
"251002E272|251002E272",
"251002G800|251102G800",
"251002GTA0",
"251002GTA0|251002GTB0",
"251002GTA0|251002GTB0|251002GTB0",
"251002GTB0",
"251002GTB0|251002GTB0",
"251002GTC0",
"251002J000",
"251002J000|251002J000",
"251002J600",
"251002M011",
"251002M011|251002M012",
"251002M012",
"251002M020",
"251002M800",
"251002MHA0",
"251002MHA0|251002MHA0",
"251002MHA0|251002MHA0|251002MHA0",
"251002S000",
"251002S000|251102S000",
"251002S500",
"251002S500|251102S000",
"251002T000|251102S000",
"251002T010|251102S000",
"251003CAC0",
"251003F000",
"251003F000|251003F000",
"251003F000|251003F300",
"251003F300",
"251003F310",
"251003L100",
"251003L100|251003L100",
"251003N100",
"251003N400",
"251102CTA0|251102CTA0|251202CTA0|251202CTA0",
"251102CTA0|251202CTA0",
"251102G000",
"251102G510",
"251102G800",
"25191164",
"25201450",
"25201452",
"25204277|55505442",
"25204309",
"2542003000|264200030180",
"260200110080",
"264200030180",
"274200040780",
"274200090080",
"276-200-08-01-80",
"30751700",
"31368419",
"31368715",
"31368715|31439790",
"31368715|31657417",
"31368715|31686005",
"31369715",
"40009321",
"40009483",
"4694307AC",
"4763776AB",
"4893133AF",
"4893618AC",
"4893618AE",
"4893618AF",
"4893618AG",
"4893941AB",
"4893941AB|4893941AC",
"4893941AC",
"4893942AB",
"4893942AB|4893942AC",
"4893942AC",
"5010898AA",
"5037164AB",
"5037164AC",
"5037730AA",
"5047389AC",
"5048124AC",
"5048124AG|68632888AA",
"5048283AC",
"5048283AD",
"5048283AE",
"5048283AF",
"5048550AB",
"5048550AC",
"5048616AD",
"5048709AC",
"5048709AF",
"5048710AF",
"5086959AA",
"5142985AA",
"5184498AN",
"55501354",
"55502845",
"55505441|55505442",
"55505442",
"55506790",
"55506791",
"55508938",
"55508938|55515871",
"55508939",
"55515497",
"55515497|55515497",
"55515497|55515497|55515497",
"55582273",
"651200160280",
"68013932AA",
"68095483AA",
"68111624AF",
"68165882AC",
"68165882AD",
"68211202AB",
"68211202AB|68211202AB",
"68259379AA",
"68261224AD",
"68261224AE",
"68261224AF",
"68311108AE",
"68311109AA",
"68311109AB",
"68311109AC",
"68346911AA",
"68346911AA|68346912AA",
"68346911AB",
"68346911AB|68346912AB",
"68346915AA",
"68346915AA|68346916AA",
"68346916AA",
"68349798AA",
"68385387AA",
"68439898AA",
"68445352AA",
"68445352AA|68445352AA|68445352AA|68445352AA",
"68460638AA",
"68490109AA",
"68490215AA",
"68493460AC",
"68524862AA",
"68548612AB",
"68569196AA",
"68600987AA",
"68632888AA",
"89060527",
"95810603300|95810603302",
"95810603300|95810603303",
"95810603300|95810603304",
"9A110603971|9A110604872",
"9A110603972|9A110604872",
"9A110604800",
"9A110604800|9A110604801",
"9A110604801",
"9A110604870",
"9A110604872",
"9A210603972",
"9A210603972|9A210604902",
"9A210604003",
"9A210604003|9A210605001",
"9A712101303",
"9A712101304",
"9A712101304|9A712101304",
"9A712101402",
"9A712101402|9A712101403",
"A1122001301",
"A1132000101",
"A1132000301",
"A1332000400",
"A1332000400|A1332000601",
"A1332000601",
"A1392000000",
"A1522000301",
"A1552000101",
"A1562000201",
"A1562000601",
"A1572000001|A2782000601",
"A1572000001|A2782001301",
"A1572000107",
"A1572000201",
"A1572000201|A1572000201",
"A1772000001",
"A1772000001|A1772000400",
"A1772000207|A1772000400",
"A1772000400",
"A2002000001",
"A2562000500",
"A2562001400",
"A2602001200",
"A2642000100|A2642000401",
"A2662000720",
"A2702000000",
"A2702000600",
"A2702000601",
"A2702000801",
"A2722000901",
"A2722001401",
"A2722001401|A2722001801",
"A2722001801",
"A2732000201",
"A2742000107|A2742000307|A2742000407|A2742000801|A2742001507",
"A2742000107|A2742000307|A2742000701|A2742000801|A2742001507",
"A2742000107|A2742000307|A2742000801",
"A2742000107|A2742000307|A2742000801|A2742001507",
"A2742000107|A2742000907",
"A2742000207",
"A2742000207|A2742000800|A2742000900|A2742001000",
"A2742000207|A2742000900",
"A2742000307",
"A2742000307|A2742000407|A2742001507",
"A2742000900",
"A2742000907",
"A2742001000",
"A2762001301",
"A2782000007",
"A2782000007|A2782000501",
"A2782000007|A2782001201",
"A2782000501",
"A2782000601",
"A2782000601|A2782000801",
"A2782000601|A2782001301",
"A2782001201",
"A6422001701",
"A6422002201",
"A6512000200",
"A6512000300|A6512006501",
"A6512000301",
"A6512000301|A6512002101|A6512002301|A6512003701",
"A6512002100|A6512006201",
"AJ812119",
"AJ812119|C2D20660",
"AJ813909",
"AJ813909|AJ814042",
"AJ813909|AJ814042|JDE40573",
"AJ813909|JDE40573",
"AJ814042",
"B1010-JK20A",
"BC3Z-8501-A",
"BK3Z-8501-B",
"BK3Z-8501-B|BK3Z-8501-G",
"BR3Z-8501-D",
"BR3Z-8501-D|L1MZ8501D",
"BR3Z-8501-D|LK4Z-8501-B",
"BR3Z-8501-S|ML3Z-8501-C",
"C2D20660|C2Z21781",
"C2Z21781",
"C2Z21781|C2Z28248|C2Z29189",
"C2Z21781|C2Z29189",
"C2Z21781|C2Z31146",
"C2Z21781|C2Z31587",
"C2Z29189",
"C2Z31146",
"C2Z31587",
"CK4Z-8501-A",
"DR3Z-8501-A|KR3Z-8501-A",
"DS7Z-8501-C",
"EJ7Z-8501-A",
"EJ7Z-8501-C",
"EJ7Z-8501-F",
"EJ7Z-8501-G",
"FT4Z-8501-D|K2GZ-8501-A",
"HC3Z-8501-A",
"HG7Z-8501-A",
"HL3Z-8501-B",
"HL3Z-8501-B|JL3Z-8501-B",
"HX7Z-8501-A",
"HX7Z8501B",
"JDE36106|JDE38893|JDE40573|JDE41184",
"JDE38247",
"JDE38596|JDE40455|JDE40573|JDE41184",
"JDE38879",
"JDE38879|JDE40318|JDE40454",
"JDE38879|JDE40454",
"JDE38893",
"JDE38893|JDE40573",
"JDE38893|JDE40573|JDE41184",
"JDE40023",
"JDE40023|JDE40573",
"JDE40318|JDE40454",
"JDE40573",
"JDE41184",
"JDE41437",
"JDE41439|JDE41680",
"JL3Z-8501-A",
"JL3Z-8501-B",
"JLM10648",
"JLM10819",
"JT4Z-8501-A",
"K2GZ-8501-A",
"KR3Z-8501-A",
"L1MZ-8501-A",
"L1MZ-8501-B",
"L1MZ8501C",
"LB5Z-8501-A",
"LC3Z-8501-A",
"LC3Z-8501-B",
"LF94-15-100A",
"LK4Z-8501-A",
"LK4Z-8501-B",
"LR006861",
"LR013164|LR089625|LR116115|LR125488",
"LR013164|LR089625|LR125488",
"LR025302",
"LR033993",
"LR040990",
"LR053310",
"LR055239|LR116115",
"LR080736",
"LR081578",
"LR081578|LR123392|LR154597",
"LR089625",
"LR092953",
"LR092953|LR115260|LR115260|LR123392|LR123906|LR140742|LR154597",
"LR092953|LR115260|LR140742|LR154597",
"LR092953|LR123392|LR154597",
"LR092953|LR154597",
"LR092953|LR180393|LR189053",
"LR095332",
"LR097165",
"LR097165|LR116115",
"LR115260|LR140742",
"LR116115",
"LR116115|LR121418",
"LR116115|LR146321|LR180396",
"LR116736|LR123384",
"LR121418",
"LR123392",
"LR123392|LR154597",
"LR123392|LR154597|LR161571",
"LR154597",
"LR158234",
"LR180393|LR189053",
"LR180396",
"LR186436",
"LX6Z-8501-D",
"ML3Z-8501-A",
"ML3Z-8501-A|ML3Z-8501-B",
"ML3Z-8501-E",
"ML3Z-8K153-E",
"MQ718214",
"N/A",
"N3R1-15-100",
"OPB121005B|OPB121010A",
"P2GZ8501A",
"P51B15010D|PE31-15-010C",
"P5PW-15-010B",
"P5PW-15-010B|PY8W15010B|PYFA-15-010D",
"P5PW-15-010B|PYFA-15-010D",
"PAB121014C",
"PAC121012B|PAC121012",
"PC3Z8501A",
"PEB000030",
"PY8W15010B",
"PYFA-15-010D",
"Q0004681V002000000",
"SU003-09040",
"T4A41037",
"XR858491",
"12657499",
"12677352",
"12698367",
"12702611",
"12712953",
"12724894",
"12725187",
"12725191",
"12727108",
"25204277",
"25205816",
"31439790",
"31657417",
"31686005",
"55505441",
"55515871",
"104123462",
"104123502",
"122123458",
"2542003000",
"11517643067",
"11517644809",
"11517644810",
"11517952783",
"11518054857",
"11518094658",
"11518516204",
"11518516205",
"11518543828",
"11518623582",
"11518631940",
"11518650986",
"11518650988",
"11518678905",
"11518742075",
"11519453667",
"11519489805",
"95810603300",
"95810603302",
"95810603303",
"95810603304",
"2.51002E+276",
"03H121008K",
"03H121008M",
"04L121011",
"06060-5K0-000",
"061J0-5WJ-A00",
"06E121018H",
"06L121012A",
"06L121012H",
"06L121111N",
"079121012T",
"07K121011N",
"0PB121005A",
"0PB121005C",
"0PB121005D",
"0PB121010A",
"0PB121010D",
"0PC121005",
"0PC121005A",
"0PC121010",
"0PC121010A",
"11515A444F4",
"11515A55395",
"133-200-04-00-80",
"16032-18010",
"16032-F2010",
"16032-WAA01",
"16032-WAA02",
"16100-09491",
"16100-19385",
"16100-39496",
"16100-F0010",
"21010-AL528",
"251002G800",
"251002T000",
"251002T010",
"251102CTA0",
"251102S000",
"251202CTA0",
"270-200-06-00-80",
"5048124AG",
"68346912AA",
"68346912AB",
"9A110603971",
"9A110603972",
"9A210604004",
"9A210604902",
"9A210605001",
"9A210605002",
"9A712101403",
"A1572000001",
"A1772000207",
"A2642000100",
"A2642000401",
"A2742000107",
"A2742000407",
"A2742000701",
"A2742000800",
"A2742000801",
"A2742001507",
"A2782000801",
"A2782001301",
"A6512000300",
"A6512002100",
"A6512002101",
"A6512002301",
"A6512003701",
"A6512006201",
"A6512006501",
"BK3Z-8501-G",
"BR3Z-8501-S",
"C2D20660",
"C2Z28248",
"DR3Z-8501-A",
"FT4Z-8501-D",
"JDE36106",
"JDE38596",
"JDE40318",
"JDE40454",
"JDE40455",
"JDE41439",
"JDE41680",
"L1MZ8501D",
"LR013164",
"LR055239",
"LR115260",
"LR116736",
"LR123384",
"LR125488",
"LR140742",
"LR146321",
"LR161571",
"LR180393",
"LR189053",
"ML3Z-8501-B",
"ML3Z-8501-C",
"OPB121005B",
"OPB121010A",
"P51B15010D",
"PAC121012",
"PAC121012B",
"PE31-15-010C"
]

In [29]:
searchbutton=driver.find_element(By.ID,"part-search-input")
searchbutton.click()
searchbutton.send_keys(List[0])
driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
sleep(1)

In [30]:
select_1=driver.find_element(By.XPATH,"(//div[@class='d-flex align-self-stretch align-items-center flex-row-reverse flex-shrink-0'])")
select_1.click()
select_2=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[1]")
select_2.click()
select_3=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[10]")
select_3.click()
select_1.click()
sleep(2)

In [32]:
Totalpage=int(driver.find_element(By.XPATH,'//span[@ref="lbTotal" and @class="ag-paging-number"]').text)
Currentpage=int(driver.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
Totalpage

1

In [46]:
driver.find_elements(By.CSS_SELECTOR,'div[role="row"]')[1].get_attribute("row-id").replace("]-[","/").replace("[","").replace("]","")

'BBKR/04792195'

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [54]:
cols=['Part No.']
df = pd.DataFrame(columns=cols)
df
count=0

linkprefix="https://web.tecalliance.net/opticat/qa/parts/"
linksuffix="/ap-detail"

In [55]:
from tqdm import tqdm
for i in tqdm(range(len(List))):#len(List))):
    if "|" not in List[i]:
        searchbutton=driver.find_element(By.ID,"part-search-input")
        searchbutton.click()
        searchbutton.send_keys(List[i])
        driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
        sleep(2)
        try:
            Nodata=driver.find_element(By.CSS_SELECTOR, '[class="text-nowrap ng-star-inserted"]').text 
            df.loc[count,"SearchText"]=List[i]
            df.loc[count,"Competitor"]=Nodata
            df.loc[count,"Link"]=driver.current_url
            count=count+1
        except:
            statuses=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "article-status-cell")))
            Contents=driver.find_elements(By.CLASS_NAME, "generic-article") 
            PNS=driver.find_elements(By.CLASS_NAME, "text-primary")
            CNS=driver.find_elements(By.CLASS_NAME, "font-weight-bold")
            searchtext=driver.find_element(By.CLASS_NAME, "ng-star-inserted") 
            Productcodes=driver.find_elements(By.CSS_SELECTOR,'div[role="row"]')
            for status, content, pn,cn, productcode in zip(statuses,Contents,PNS,CNS,Productcodes[1:]):
                df.loc[count,"SearchText"]=List[i]
                df.loc[count,"Competitor"]=cn.text
                df.loc[count,"Part No."]=pn.text
                #df.loc[count,"Status"]=status.text
                df.loc[count,"Name"]=content.text
                pc=productcode.get_attribute("row-id").replace("]-[","/").replace("[","").replace("]","")
                link=linkprefix+pc+linksuffix
                df.loc[count,"Link"]=driver.current_url
                df.loc[count,"ProductLink"]=link
                count=count+1
    else:
            df.loc[count,"SearchText"]=List[i]
            df.loc[count,"Competitor"]="To be Dealt separately"
            count=count+1
        
    clear_output(wait=True)

100%|██████████| 802/802 [22:13<00:00,  1.66s/it]

In [56]:
df

,Part No.,SearchText,Competitor,Name,Link,ProductLink
0,04792195,4792195,Mopar,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
1,04792195AB,4792195,Mopar,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
2,WP-9132,4792195,ASC,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
3,41079,4792195,Gates,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
4,120-1350,4792195,GMB,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
...,...,...,...,...,...,...
1801,180-3050,PAC121012,GMB,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
1802,180-3050,PAC121012B,GMB,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
1803,7.07152.29.0,PAC121012B,Pierburg distributed by Hella,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/B...
1804,7.07152.29.0,PAC121012B,Pierburg,Engine Water Pump,https://web.tecalliance.net/opticat/qa/parts/s...,https://web.tecalliance.net/opticat/qa/parts/J...
1805,NaN,PE31-15-010C,No data to display,NaN,https://web.tecalliance.net/opticat/qa/parts/s...,NaN

In [57]:
df["SearchText"].value_counts().sort_values(ascending=False)

2.51002E+276                           30
N/A                                    30
5086959AA                              18
038121011A                             15
06A121012G                             14
                                       ..
0PC121005A                              1
JDE36106|JDE38893|JDE40573|JDE41184     1
JDE38247                                1
JDE38596|JDE40455|JDE40573|JDE41184     1
PE31-15-010C                            1
Name: SearchText, Length: 801, dtype: int64

# 5. Post Processing Data and Exporting

In [12]:
df['Count']=1

In [13]:
#https://web.tecalliance.net/opticat/qa/parts/CMTQ/V51-08-0001/ap-detail
prefix='https://web.tecalliance.net/opticat/qa/parts/'
mid='''/'''
suffix='/ap-detail'

df['Link']=prefix+df['Sup_Code'].str.split(']-',expand=True)[0].str.replace('[','')+mid+df['Sup_Code'].str.split(']-',expand=True)[1].str.replace('[','').str.replace(']','')+suffix
df['Link']

0       https://web.tecalliance.net/opticat/qa/parts/B...
1       https://web.tecalliance.net/opticat/qa/parts/B...
2       https://web.tecalliance.net/opticat/qa/parts/B...
3       https://web.tecalliance.net/opticat/qa/parts/B...
4       https://web.tecalliance.net/opticat/qa/parts/B...
                              ...
1685    https://web.tecalliance.net/opticat/qa/parts/B...
1686    https://web.tecalliance.net/opticat/qa/parts/B...
1687    https://web.tecalliance.net/opticat/qa/parts/B...
1688    https://web.tecalliance.net/opticat/qa/parts/B...
1689    https://web.tecalliance.net/opticat/qa/parts/B...
Name: Link, Length: 1690, dtype: object

In [14]:
cols=df.columns.to_list()
remove=["Supplier Name",'Part Name','Part No.','Link']
cols=[ele for ele in cols if ele not in remove]
colsort=sorted(cols)
cols=remove+colsort
df = df[cols]
# df=df[df['Part Name']==Type_Name]
df

,Supplier Name,Part Name,Part No.,Link,AAP_UDA_119,AAP_UDA_12,AAP_UDA_120,AAP_UDA_121,AAP_UDA_122,AAP_UDA_123,...,Mounting Hole Quantity,Mounting Type,Outer Cylinder Color,Outer Cylinder Material,SHAFT CONNECTION,Shaft,Stroke Length,Sup_Code,Universal Or Specific Fit,Washer Included
0,Strong Arm,Multi-Purpose Lift Support,A4281,https://web.tecalliance.net/opticat/qa/parts/B...,N,EA,N,N,N,N,...,NaN,NaN,Black,Steel,NaN,NaN,15.4 in,[BBZN]-[A4281],Universal,NaN
1,Strong Arm,Liftgate Lift Support,A4808,https://web.tecalliance.net/opticat/qa/parts/B...,Y,EA,Y,N,N,N,...,NaN,NaN,Black,Steel,NaN,NaN,12.31 in,[BBZN]-[A4808],Specific,NaN
2,Strong Arm,Hood Lift Support,A4850,https://web.tecalliance.net/opticat/qa/parts/B...,Y,EA,Y,N,N,N,...,NaN,NaN,Black,Steel,NaN,NaN,12.12 in,[BBZN]-[A4850],Specific,NaN
3,Strong Arm,Liftgate Lift Support,A4851,https://web.tecalliance.net/opticat/qa/parts/B...,Y,EA,Y,N,N,N,...,NaN,NaN,Black,Steel,NaN,NaN,12.47 in,[BBZN]-[A4851],Specific,NaN
4,Strong Arm,Tailgate Lift Support,A4852,https://web.tecalliance.net/opticat/qa/parts/B...,Y,EA,Y,N,N,N,...,NaN,NaN,Black,Steel,NaN,NaN,12.71 in,[BBZN]-[A4852],Specific,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1685,Strong Arm,Multi-Purpose Lift Support Stud,SA3001,https://web.tecalliance.net/opticat/qa/parts/B...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Stud,Black,NaN,NaN,NaN,NaN,[BBZN]-[SA3001],Universal,NaN
1686,Strong Arm,Multi-Purpose Lift Support Stud,SA3002,https://web.tecalliance.net/opticat/qa/parts/B...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Stud,NaN,NaN,NaN,NaN,NaN,[BBZN]-[SA3002],Universal,No
1687,Strong Arm,Multi-Purpose Lift Support Bracket,SA3100,https://web.tecalliance.net/opticat/qa/parts/B...,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,[BBZN]-[SA3100],Universal,NaN
1688,Strong Arm,Multi-Purpose Lift Support Bracket,SA3101,https://web.tecalliance.net/opticat/qa/parts/B...,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,[BBZN]-[SA3101],Universal,NaN
1689,Strong Arm,Multi-Purpose Lift Support Bracket,SA3102,https://web.tecalliance.net/opticat/qa/parts/B...,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,[BBZN]-[SA3102],Universal,NaN

In [15]:
df_unpivoted=pd.melt(df, id_vars=remove, value_vars=colsort, ignore_index=True,var_name="Attribute").dropna()
df_unpivoted

,Supplier Name,Part Name,Part No.,Link,Attribute,value
0,Strong Arm,Multi-Purpose Lift Support,A4281,https://web.tecalliance.net/opticat/qa/parts/B...,AAP_UDA_119,N
1,Strong Arm,Liftgate Lift Support,A4808,https://web.tecalliance.net/opticat/qa/parts/B...,AAP_UDA_119,Y
2,Strong Arm,Hood Lift Support,A4850,https://web.tecalliance.net/opticat/qa/parts/B...,AAP_UDA_119,Y
3,Strong Arm,Liftgate Lift Support,A4851,https://web.tecalliance.net/opticat/qa/parts/B...,AAP_UDA_119,Y
4,Strong Arm,Tailgate Lift Support,A4852,https://web.tecalliance.net/opticat/qa/parts/B...,AAP_UDA_119,Y
...,...,...,...,...,...,...
84496,Strong Arm,Multi-Purpose Lift Support Stud,SA3002,https://web.tecalliance.net/opticat/qa/parts/B...,Universal Or Specific Fit,Universal
84497,Strong Arm,Multi-Purpose Lift Support Bracket,SA3100,https://web.tecalliance.net/opticat/qa/parts/B...,Universal Or Specific Fit,Universal
84498,Strong Arm,Multi-Purpose Lift Support Bracket,SA3101,https://web.tecalliance.net/opticat/qa/parts/B...,Universal Or Specific Fit,Universal
84499,Strong Arm,Multi-Purpose Lift Support Bracket,SA3102,https://web.tecalliance.net/opticat/qa/parts/B...,Universal Or Specific Fit,Universal
86186,Strong Arm,Multi-Purpose Lift Support Stud,SA3002,https://web.tecalliance.net/opticat/qa/parts/B...,Washer Included,No

In [58]:
with pd.ExcelWriter(Folder+'\\'+'Opticat_Export_Holes_Identification2.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    #df_unpivoted.to_excel(writer,index=False, sheet_name='Attributes')

# 99. Archived Codes

In [ ]:
# To extract the Supplier part number from the list


from tqdm import tqdm
for a in tqdm(range(51,len(List))):
    print(a)    
    search_content=driver.find_element(By.ID,"part-search-input")
    search_content.click()
    search_content.send_keys(List[a])
    driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
    sleep(2)
    PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")
    Suppliers =driver.find_elements(By.CSS_SELECTOR, 'p > span.font-weight-bold')       
    for p, s in zip(PN,Suppliers):
        text_content = p.find_element(By.CSS_SELECTOR,'.text-truncate a').text
        print(List[a],":",s.text.strip(),"-",text_content)
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    driver.find_element(By.CSS_SELECTOR,'[id="part-search-input"]').clear()

In [ ]:
        # Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
        # #counter=0
        # for index, element2 in enumerate(Param):
        #     # Access specific attributes or text content of the element
        #     criteria_name = element2.find_element(By.CSS_SELECTOR,'.font-weight-bold:first-child').text
        #     value=element2.find_element(By.CSS_SELECTOR,'span:not(.font-weight-bold)').text
        #     # print(criteria_name,'     :      ',value)
        #     if str(df.loc[counter,criteria_name])!='nan':
        #         counter=counter+1
        #         df.loc[counter,criteria_name]=value
        #     else:
        #         df.loc[counter,criteria_name]=value

In [ ]:
#Reference only

from selenium import webdriver
from bs4 import BeautifulSoup

# Wait for the page to load (you might need to adjust the wait time)
browser.implicitly_wait(10)

# Get the page source and create a BeautifulSoup object
page_source = browser.page_source
soup = BeautifulSoup(page_source, 'html.parser')

# Find all elements with the specified class
elements = soup.find_all('div', class_='ag-row')

# Enumerate the elements based on row index and article-criteria
for index, element in enumerate(elements, start=1):
    # Extract row index
    row_index = element['row-index']


    # Extract article-criteria
    article_criterias = element.select('.article-criteria')
    article_criteria_texts = [criteria.get_text(strip=True) for criteria in article_criterias]

    # Print the results (you can modify this based on your needs)

    for criteria_text in article_criteria_texts:
        CN=criteria_text.split(":")[0]
        CV=criteria_text.split(":")[1]        
        

    print("\n")

In [ ]:
Param_Name=[]

for i in range(Totalpage):
    Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
    for index, element in enumerate(Param):
        # Access specific attributes or text content of the element
        criteria_name = WebDriverWait(element, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR,".font-weight-bold:first-child"))).text
        Param_Name.append(criteria_name)
    Currentpage=int(browser.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
    print("Page#",Currentpage,"Completed",datetime.datetime.now())
    if Currentpage < Totalpage:
        NextPage=browser.find_element(By.CLASS_NAME, 'ag-icon-next')
        NextPage.click()
        sleep(3)
        i=i+1

if Totalpage>1:
    First_Page=browser.find_element(By.XPATH,'//div[@ref="btFirst"]')
    First_Page.click()

In [ ]:
Param_Name=set(Param_Name)
cols=Param_Name
cols
df = pd.DataFrame(columns=cols)
print(len(cols))
df