# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
import pandas as pd

# 2. Defining the Product Information and Location

In [2]:
Item_Code=["Direct Ignition Coil 178-8154",
"Direct Ignition Coil 178-8225",
"Direct Ignition Coil 178-8235",
"Direct Ignition Coil 178-8250",
"Direct Ignition Coil 178-8253",
"Direct Ignition Coil 178-8255",
"Direct Ignition Coil 178-8258",
"Direct Ignition Coil 178-8261",
"Direct Ignition Coil 178-8272",
"Direct Ignition Coil 178-8273",
"Direct Ignition Coil 178-8274",
"Direct Ignition Coil 178-8276",
"Direct Ignition Coil 178-8285",
"Direct Ignition Coil 178-8286",
"Direct Ignition Coil 178-8287",
"Direct Ignition Coil 178-8288",
"Direct Ignition Coil 178-8290",
"Direct Ignition Coil 178-8292",
"Direct Ignition Coil 178-8293",
"Direct Ignition Coil 178-8294",
"Direct Ignition Coil 178-8296",
"Direct Ignition Coil 178-8297",
"Direct Ignition Coil 178-8298",
"Direct Ignition Coil 178-8300",
"Direct Ignition Coil 178-8301",
"Direct Ignition Coil 178-8302",
"Direct Ignition Coil 178-8303",
"Direct Ignition Coil 178-8304",
"Direct Ignition Coil 178-8305",
"Direct Ignition Coil 178-8306",
"Direct Ignition Coil 178-8307",
"Direct Ignition Coil 178-8309",
"Direct Ignition Coil 178-8310",
"Direct Ignition Coil 178-8313",
"Direct Ignition Coil 178-8314",
"Direct Ignition Coil 178-8315",
"Direct Ignition Coil 178-8316",
"Direct Ignition Coil 178-8317",
"Direct Ignition Coil 178-8318",
"Direct Ignition Coil 178-8319",
"Direct Ignition Coil 178-8320",
"Direct Ignition Coil 178-8328",
"Direct Ignition Coil 178-8329",
"Direct Ignition Coil 178-8332",
"Direct Ignition Coil 178-8333",
"Direct Ignition Coil 178-8335",
"Direct Ignition Coil 178-8337",
"Direct Ignition Coil 178-8338",
"Direct Ignition Coil 178-8339",
"Direct Ignition Coil 178-8344",
"Direct Ignition Coil 178-8345",
"Direct Ignition Coil 178-8347",
"Direct Ignition Coil 178-8348",
"Direct Ignition Coil 178-8349",
"Direct Ignition Coil 178-8350",
"Direct Ignition Coil 178-8353",
"Direct Ignition Coil 178-8354",
"Direct Ignition Coil 178-8355",
"Direct Ignition Coil 178-8356",
"Direct Ignition Coil 178-8358",
"Direct Ignition Coil 178-8359",
"Direct Ignition Coil 178-8360",
"Direct Ignition Coil 178-8362",
"Direct Ignition Coil 178-8363",
"Direct Ignition Coil 178-8364",
"Direct Ignition Coil 178-8365",
"Direct Ignition Coil 178-8367",
"Direct Ignition Coil 178-8368",
"Direct Ignition Coil 178-8370",
"Direct Ignition Coil 178-8372",
"Direct Ignition Coil 178-8373",
"Direct Ignition Coil 178-8374",
"Direct Ignition Coil 178-8376",
"Direct Ignition Coil 178-8379",
"Direct Ignition Coil 178-8380",
"Direct Ignition Coil 178-8381",
"Direct Ignition Coil 178-8383",
"Direct Ignition Coil 178-8384",
"Direct Ignition Coil 178-8386",
"Direct Ignition Coil 178-8387",
"Direct Ignition Coil 178-8388",
"Direct Ignition Coil 178-8389",
"Direct Ignition Coil 178-8390",
"Direct Ignition Coil 178-8392",
"Direct Ignition Coil 178-8393",
"Direct Ignition Coil 178-8394",
"Direct Ignition Coil 178-8395",
"Direct Ignition Coil 178-8397",
"Direct Ignition Coil 178-8398",
"Direct Ignition Coil 178-8399",
"Direct Ignition Coil 178-8407",
"Direct Ignition Coil 178-8408",
"Direct Ignition Coil 178-8409",
"Direct Ignition Coil 178-8411",
"Direct Ignition Coil 178-8412",
"Direct Ignition Coil 178-8413",
"Direct Ignition Coil 178-8414",
"Direct Ignition Coil 178-8415",
"Direct Ignition Coil 178-8416",
"Direct Ignition Coil 178-8417",
"Direct Ignition Coil 178-8419",
"Direct Ignition Coil 178-8423",
"Direct Ignition Coil 178-8424",
"Direct Ignition Coil 178-8425",
"Direct Ignition Coil 178-8427",
"Direct Ignition Coil 178-8429",
"Direct Ignition Coil 178-8431",
"Direct Ignition Coil 178-8434",
"Direct Ignition Coil 178-8435",
"Direct Ignition Coil 178-8436",
"Direct Ignition Coil 178-8437",
"Direct Ignition Coil 178-8438",
"Direct Ignition Coil 178-8440",
"Direct Ignition Coil 178-8443",
"Direct Ignition Coil 178-8445",
"Direct Ignition Coil 178-8446",
"Direct Ignition Coil 178-8447",
"Direct Ignition Coil 178-8453",
"Direct Ignition Coil 178-8462",
"Direct Ignition Coil 178-8463",
"Direct Ignition Coil 178-8471",
"Direct Ignition Coil 178-8472",
"Direct Ignition Coil 178-8474",
"Direct Ignition Coil 178-8476",
"Direct Ignition Coil 178-8478",
"Direct Ignition Coil 178-8479",
"Direct Ignition Coil 178-8480",
"Direct Ignition Coil 178-8481",
"Direct Ignition Coil 178-8482",
"Direct Ignition Coil 178-8483",
"Direct Ignition Coil 178-8484",
"Direct Ignition Coil 178-8486",
"Direct Ignition Coil 178-8487",
"Direct Ignition Coil 178-8488",
"Direct Ignition Coil 178-8489",
"Direct Ignition Coil 178-8491",
"Direct Ignition Coil 178-8494",
"Direct Ignition Coil 178-8496",
"Direct Ignition Coil 178-8498",
"Direct Ignition Coil 178-8501",
"Direct Ignition Coil 178-8503",
"Direct Ignition Coil 178-8504",
"Direct Ignition Coil 178-8508",
"Direct Ignition Coil 178-8509",
"Direct Ignition Coil 178-8510",
"Direct Ignition Coil 178-8511",
"Direct Ignition Coil 178-8512",
"Direct Ignition Coil 178-8514",
"Direct Ignition Coil 178-8516",
"Direct Ignition Coil 178-8517",
"Direct Ignition Coil 178-8521",
"Direct Ignition Coil 178-8523",
"Direct Ignition Coil 178-8524",
"Direct Ignition Coil 178-8525",
"Direct Ignition Coil 178-8526",
"Direct Ignition Coil 178-8527",
"Direct Ignition Coil 178-8528",
"Direct Ignition Coil 178-8529",
"Direct Ignition Coil 178-8530",
"Direct Ignition Coil 178-8531",
"Direct Ignition Coil 178-8532",
"Direct Ignition Coil 178-8533",
"Direct Ignition Coil 178-8534",
"Direct Ignition Coil 178-8535",
"Direct Ignition Coil 178-8536",
"Direct Ignition Coil 178-8537",
"Direct Ignition Coil 178-8538",
"Direct Ignition Coil 178-8539",
"Direct Ignition Coil 178-8540",
"Direct Ignition Coil 178-8541",
"Direct Ignition Coil 178-8542",
"Direct Ignition Coil 178-8543",
"Direct Ignition Coil 178-8544",
"Direct Ignition Coil 178-8545",
"Direct Ignition Coil 178-8546",
"Direct Ignition Coil 178-8547",
"Direct Ignition Coil 178-8548",
"Direct Ignition Coil 178-8549",
"Direct Ignition Coil 178-8550",
"Direct Ignition Coil 178-8551",
"Direct Ignition Coil 178-8552",
"Direct Ignition Coil 178-8553",
"Direct Ignition Coil 178-8554",
"Direct Ignition Coil 178-8555",
"Direct Ignition Coil 178-8556",
"Direct Ignition Coil 178-8557",
"Direct Ignition Coil 178-8558",
"Direct Ignition Coil 178-8559",
"Direct Ignition Coil 178-8560",
"Direct Ignition Coil 178-8561",
"Direct Ignition Coil 178-8562",
"Direct Ignition Coil 178-8563",
"Direct Ignition Coil 178-8564",
"Direct Ignition Coil 178-8565",
"Direct Ignition Coil 178-8566",
"Direct Ignition Coil 178-8567",
"Direct Ignition Coil 178-8568",
"Direct Ignition Coil 178-8569",
"Direct Ignition Coil 178-8570",
"Direct Ignition Coil 178-8571",
"Direct Ignition Coil 178-8572",
"Direct Ignition Coil 178-8573",
"Direct Ignition Coil 178-8574",
"Direct Ignition Coil 178-8575",
"Direct Ignition Coil 178-8576",
"Direct Ignition Coil 178-8577",
"Direct Ignition Coil 178-8578",
"Direct Ignition Coil 178-8579",
"Direct Ignition Coil 178-8580",
"Direct Ignition Coil 178-8581",
"Direct Ignition Coil 178-8582",
"Direct Ignition Coil 178-8583",
"Direct Ignition Coil 178-8584",
"Direct Ignition Coil 178-8585",
"Direct Ignition Coil 178-8586",
"Direct Ignition Coil 178-8587",
"Direct Ignition Coil 178-8588",
"Direct Ignition Coil 178-8589",
"Direct Ignition Coil 178-8590",
"Direct Ignition Coil 178-8591",
"Direct Ignition Coil 178-8592",
"Direct Ignition Coil 178-8593",
"Direct Ignition Coil 178-8594",
"Direct Ignition Coil 178-8595",
"Direct Ignition Coil 178-8596",
"Direct Ignition Coil 178-8597",
"Direct Ignition Coil 178-8598",
"Direct Ignition Coil 178-8599",
"Direct Ignition Coil 178-8600",
"Direct Ignition Coil 178-8601",
"Direct Ignition Coil 178-8602",
"Direct Ignition Coil 178-8603",
"Direct Ignition Coil 178-8604",
"Direct Ignition Coil 68385535AC",
"Direct Ignition Coil 673-0201",
"Direct Ignition Coil 673-1100",
"Direct Ignition Coil 673-1101",
"Direct Ignition Coil 673-1102",
"Direct Ignition Coil 673-1103",
"Direct Ignition Coil 673-1200",
"Direct Ignition Coil 673-1201",
"Direct Ignition Coil 673-1202",
"Direct Ignition Coil 673-1203",
"Direct Ignition Coil 673-1204",
"Direct Ignition Coil 673-1205",
"Direct Ignition Coil 673-1206",
"Direct Ignition Coil 673-1207",
"Direct Ignition Coil 673-1300",
"Direct Ignition Coil 673-1301",
"Direct Ignition Coil 673-1303",
"Direct Ignition Coil 673-1304",
"Direct Ignition Coil 673-1305",
"Direct Ignition Coil 673-1306",
"Direct Ignition Coil 673-1307",
"Direct Ignition Coil 673-1308",
"Direct Ignition Coil 673-1309",
"Direct Ignition Coil 673-1310",
"Direct Ignition Coil 673-1311",
"Direct Ignition Coil 673-1312",
"Direct Ignition Coil 673-2201",
"Direct Ignition Coil 673-2202",
"Direct Ignition Coil 673-2300",
"Direct Ignition Coil 673-2301",
"Direct Ignition Coil 673-2302",
"Direct Ignition Coil 673-2304",
"Direct Ignition Coil 673-2305",
"Direct Ignition Coil 673-2306",
"Direct Ignition Coil 673-2307",
"Direct Ignition Coil 673-2308",
"Direct Ignition Coil 673-2309",
"Direct Ignition Coil 673-2310",
"Direct Ignition Coil 673-2311",
"Direct Ignition Coil 673-2312",
"Direct Ignition Coil 673-2313",
"Direct Ignition Coil 673-2314",
"Direct Ignition Coil 673-2315",
"Direct Ignition Coil 673-2316",
"Direct Ignition Coil 673-2317",
"Direct Ignition Coil 673-2318",
"Direct Ignition Coil 673-3203",
"Direct Ignition Coil 673-3204",
"Direct Ignition Coil 673-3205",
"Direct Ignition Coil 673-4001",
"Direct Ignition Coil 673-4002",
"Direct Ignition Coil 673-4003",
"Direct Ignition Coil 673-4004",
"Direct Ignition Coil 673-4005",
"Direct Ignition Coil 673-4006",
"Direct Ignition Coil 673-4010",
"Direct Ignition Coil 673-4011",
"Direct Ignition Coil 673-4012",
"Direct Ignition Coil 673-4013",
"Direct Ignition Coil 673-4014",
"Direct Ignition Coil 673-4015",
"Direct Ignition Coil 673-4016",
"Direct Ignition Coil 673-4017",
"Direct Ignition Coil 673-4018",
"Direct Ignition Coil 673-4019",
"Direct Ignition Coil 673-4020",
"Direct Ignition Coil 673-4021",
"Direct Ignition Coil 673-4022",
"Direct Ignition Coil 673-4023",
"Direct Ignition Coil 673-4024",
"Direct Ignition Coil 673-4025",
"Direct Ignition Coil 673-4026",
"Direct Ignition Coil 673-4027",
"Direct Ignition Coil 673-4028",
"Direct Ignition Coil 673-4029",
"Direct Ignition Coil 673-4030",
"Direct Ignition Coil 673-4231",
"Direct Ignition Coil 673-4232",
"Direct Ignition Coil 673-4233",
"Direct Ignition Coil 673-4234",
"Direct Ignition Coil 673-5200",
"Direct Ignition Coil 673-5201",
"Direct Ignition Coil 673-5202",
"Direct Ignition Coil 673-5203",
"Direct Ignition Coil 673-5204",
"Direct Ignition Coil 673-5205",
"Direct Ignition Coil 673-5300",
"Direct Ignition Coil 673-5301",
"Direct Ignition Coil 673-5302",
"Direct Ignition Coil 673-6000",
"Direct Ignition Coil 673-6001",
"Direct Ignition Coil 673-6003",
"Direct Ignition Coil 673-6004",
"Direct Ignition Coil 673-6005",
"Direct Ignition Coil 673-6006",
"Direct Ignition Coil 673-6008",
"Direct Ignition Coil 673-6009",
"Direct Ignition Coil 673-6010",
"Direct Ignition Coil 673-6011",
"Direct Ignition Coil 673-6012",
"Direct Ignition Coil 673-6013",
"Direct Ignition Coil 673-6014",
"Direct Ignition Coil 673-6016",
"Direct Ignition Coil 673-6100",
"Direct Ignition Coil 673-6101",
"Direct Ignition Coil 673-6102",
"Direct Ignition Coil 673-6200",
"Direct Ignition Coil 673-6201",
"Direct Ignition Coil 673-6202",
"Direct Ignition Coil 673-6203",
"Direct Ignition Coil 673-6204",
"Direct Ignition Coil 673-6205",
"Direct Ignition Coil 673-6300",
"Direct Ignition Coil 673-6301",
"Direct Ignition Coil 673-6302",
"Direct Ignition Coil 673-6303",
"Direct Ignition Coil 673-6304",
"Direct Ignition Coil 673-7000",
"Direct Ignition Coil 673-7001",
"Direct Ignition Coil 673-7002",
"Direct Ignition Coil 673-7003",
"Direct Ignition Coil 673-7100",
"Direct Ignition Coil 673-7101",
"Direct Ignition Coil 673-7102",
"Direct Ignition Coil 673-7104",
"Direct Ignition Coil 673-7105",
"Direct Ignition Coil 673-7106",
"Direct Ignition Coil 673-7107",
"Direct Ignition Coil 673-7108",
"Direct Ignition Coil 673-7109",
"Direct Ignition Coil 673-7110",
"Direct Ignition Coil 673-7111",
"Direct Ignition Coil 673-7112",
"Direct Ignition Coil 673-7201",
"Direct Ignition Coil 673-7202",
"Direct Ignition Coil 673-7203",
"Direct Ignition Coil 673-7204",
"Direct Ignition Coil 673-7205",
"Direct Ignition Coil 673-7206",
"Direct Ignition Coil 673-7300",
"Direct Ignition Coil 673-7301",
"Direct Ignition Coil 673-7302",
"Direct Ignition Coil 673-7303",
"Direct Ignition Coil 673-7304",
"Direct Ignition Coil 673-8200",
"Direct Ignition Coil 673-8201",
"Direct Ignition Coil 673-8202",
"Direct Ignition Coil 673-8203",
"Direct Ignition Coil 673-8204",
"Direct Ignition Coil 673-8205",
"Direct Ignition Coil 673-8206",
"Direct Ignition Coil 673-8207",
"Direct Ignition Coil 673-8208",
"Direct Ignition Coil 673-8209",
"Direct Ignition Coil 673-8300",
"Direct Ignition Coil 673-8301",
"Direct Ignition Coil 673-8302",
"Direct Ignition Coil 673-8303",
"Direct Ignition Coil 673-8304",
"Direct Ignition Coil 673-8305",
"Direct Ignition Coil 673-8308",
"Direct Ignition Coil 673-8309",
"Direct Ignition Coil 673-8310",
"Direct Ignition Coil 673-8311",
"Direct Ignition Coil 673-8312",
"Direct Ignition Coil 673-8313",
"Direct Ignition Coil 673-8314",
"Direct Ignition Coil 673-9100",
"Direct Ignition Coil 673-9101",
"Direct Ignition Coil 673-9102",
"Direct Ignition Coil 673-9200",
"Direct Ignition Coil 673-9201",
"Direct Ignition Coil 673-9202",
"Direct Ignition Coil 673-9203",
"Direct Ignition Coil 673-9204",
"Direct Ignition Coil 673-9300",
"Direct Ignition Coil 673-9301",
"Direct Ignition Coil 673-9302",
"Direct Ignition Coil 673-9303",
"Direct Ignition Coil 673-9304",
"Direct Ignition Coil 673-9305",
"Direct Ignition Coil 673-9306",
"Direct Ignition Coil 673-9330",
"Direct Ignition Coil 673-9331",
"Direct Ignition Coil 673-9332",
"Direct Ignition Coil 673-9333",
"Direct Ignition Coil 193175331",
"Direct Ignition Coil 193175361",
"Direct Ignition Coil 193175381",
"Direct Ignition Coil 193175481",
"Direct Ignition Coil 193175491",
"Direct Ignition Coil 193175531",
"Direct Ignition Coil 193175541",
"Direct Ignition Coil 193175551",
"Direct Ignition Coil 193175591",
"Direct Ignition Coil 193175671",
"Direct Ignition Coil 193175681",
"Direct Ignition Coil 193175701",
"Direct Ignition Coil 193175781",
"Direct Ignition Coil 193175801",
"Direct Ignition Coil 193175841",
"Direct Ignition Coil 193175851",
"Direct Ignition Coil 193175911",
"Direct Ignition Coil 193175921",
"Direct Ignition Coil 193175931",
"Direct Ignition Coil 193175941",
"Direct Ignition Coil 193175951",
"Direct Ignition Coil 193175981",
"Direct Ignition Coil 230035221",
"Direct Ignition Coil 230035231",
"Direct Ignition Coil 230035251",
"Direct Ignition Coil 230035301",
"Direct Ignition Coil 230035311",
"Direct Ignition Coil 230035321",
"Direct Ignition Coil 230035331",
"Direct Ignition Coil 230035361",
"Direct Ignition Coil 230035391",
"Direct Ignition Coil 230035401",
"Direct Ignition Coil 230035431",
"Direct Ignition Coil 230035441",
"Direct Ignition Coil 230035451",
"Direct Ignition Coil 230035471",
"Direct Ignition Coil 230035491",
"Direct Ignition Coil 230035501",
"Direct Ignition Coil 230035531",
"Direct Ignition Coil 230035541",
"Direct Ignition Coil 230035551",
"Direct Ignition Coil 230035571",
"Direct Ignition Coil 230035611",
"Direct Ignition Coil 230035621",
"Direct Ignition Coil 230035631",
"Direct Ignition Coil 230035641",
"Direct Ignition Coil 230035651",
"Direct Ignition Coil 230035701",
"Direct Ignition Coil 230035721",
"Direct Ignition Coil 230035751",
"Direct Ignition Coil 230035761",
"Direct Ignition Coil 230035791",
"Direct Ignition Coil 230035801",
"Direct Ignition Coil 230035821",
"Direct Ignition Coil 230035841",
"Direct Ignition Coil 230035851",
"Direct Ignition Coil 230035871",
"Direct Ignition Coil 230035911",
"Direct Ignition Coil 230035941",
"Direct Ignition Coil 230035951",
"Direct Ignition Coil 230035981",
"Direct Ignition Coil 230036061",
"Direct Ignition Coil 230036071",
"Direct Ignition Coil 230036081",
"Direct Ignition Coil 230036091",
"Direct Ignition Coil 230036111",
"Direct Ignition Coil 230036121",
"Direct Ignition Coil 230036161",
"Direct Ignition Coil 230036171",
"Direct Ignition Coil 230036181",
"Direct Ignition Coil 230036231",
"Direct Ignition Coil 230036241",
"Direct Ignition Coil 230036251",
"Direct Ignition Coil 230036271",
"Direct Ignition Coil 230036321",
"Direct Ignition Coil 230036351",
"Direct Ignition Coil 230036361",
"Direct Ignition Coil 230036381",
"Direct Ignition Coil 230036411",
"Direct Ignition Coil 230036441",
"Direct Ignition Coil 230036451",
"Direct Ignition Coil 230036471",
"Direct Ignition Coil 230036481",
"Direct Ignition Coil 230036491",
"Direct Ignition Coil 230036551",
"Direct Ignition Coil 230036591",
"Direct Ignition Coil 230036621",
"Direct Ignition Coil 230036651",
"Direct Ignition Coil 230036661",
"Direct Ignition Coil 230036671",
"Direct Ignition Coil 230036681",
"Direct Ignition Coil 358000001",
"Direct Ignition Coil 358000051",
"Direct Ignition Coil 358000071",
"Direct Ignition Coil 358000091",
"Direct Ignition Coil 358000131",
"Direct Ignition Coil 358000231",
"Direct Ignition Coil 358000281",
"Direct Ignition Coil 358000341",
"Direct Ignition Coil 358000381",
"Direct Ignition Coil 358000391",
"Direct Ignition Coil 358000421",
"Direct Ignition Coil 358000451",
"Direct Ignition Coil 358000461",
"Direct Ignition Coil 358000631",
"Direct Ignition Coil 358000651",
"Direct Ignition Coil 358000661",
"Direct Ignition Coil 358000671",
"Direct Ignition Coil 358000821",
"Direct Ignition Coil 358000931",
"Direct Ignition Coil 358000991",
"Direct Ignition Coil 358057081",
"Direct Ignition Coil 358057111",
"Direct Ignition Coil 358057121",
"Direct Ignition Coil 358057171",
"Direct Ignition Coil 358057201",
"Direct Ignition Coil 358057211",
"Direct Ignition Coil 358057231",
"Direct Ignition Coil 358057241",
"Direct Ignition Coil 358057371",
"Direct Ignition Coil 358057401",
"Direct Ignition Coil 358057411",
"Direct Ignition Coil 358057461",
"Direct Ignition Coil 358057511",
"Direct Ignition Coil 358057531",
"Direct Ignition Coil 358057561",
"Direct Ignition Coil 358057571",
"Direct Ignition Coil 358057591",
"Direct Ignition Coil 358057601",
"Direct Ignition Coil 358057611",
"Direct Ignition Coil 358057621",
"Direct Ignition Coil 358057631",
"Direct Ignition Coil 358057651",
"Direct Ignition Coil 358057661",
"Direct Ignition Coil 358057671",
"Direct Ignition Coil 358057681",
"Direct Ignition Coil 358057691",
"Direct Ignition Coil 358057711",
"Direct Ignition Coil 358057721",
"Direct Ignition Coil 358057741",
"Direct Ignition Coil 358057761",
"Direct Ignition Coil 358057771",
"Direct Ignition Coil 358057781",
"Direct Ignition Coil 358057911",
"Direct Ignition Coil 358057921",
"Direct Ignition Coil 358057971",
"Direct Ignition Coil 358168021",
"Direct Ignition Coil 358168041",
"Direct Ignition Coil 358168061",
"Direct Ignition Coil 358168071",
"Direct Ignition Coil 358168081",
"Direct Ignition Coil 358168091",
"Direct Ignition Coil 358168101",
"Direct Ignition Coil 358168121",
"Direct Ignition Coil 358168141",
"Direct Ignition Coil 358168161",
"Direct Ignition Coil 358168191",
"Direct Ignition Coil 358168211",
"Direct Ignition Coil 358168231",
"Direct Ignition Coil 358168311",
"Direct Ignition Coil 358168321",
"Direct Ignition Coil 358168371",
"Direct Ignition Coil 358168391",
"Direct Ignition Coil 358168471",
"Direct Ignition Coil 358168531",
"Direct Ignition Coil 358168561",
"Direct Ignition Coil 358168571",
"Direct Ignition Coil 358168681",
"Direct Ignition Coil 358168751",
"Direct Ignition Coil 358168761",
"Direct Ignition Coil 358168771",
"Direct Ignition Coil 358168781",
"Direct Ignition Coil V10-70-0012",
"Direct Ignition Coil V10-70-0013",
"Direct Ignition Coil V10-70-0043-1",
"Direct Ignition Coil V10-70-0045",
"Direct Ignition Coil V10-70-0058",
"Direct Ignition Coil V10-70-0060",
"Direct Ignition Coil V10-70-0061",
"Direct Ignition Coil V10-70-0062",
"Direct Ignition Coil V10-70-0063",
"Direct Ignition Coil V10-70-0064",
"Direct Ignition Coil V10-70-0067",
"Direct Ignition Coil V10-70-0068",
"Direct Ignition Coil V10-70-0098",
"Direct Ignition Coil V20-70-0011",
"Direct Ignition Coil V20-70-0012",
"Direct Ignition Coil V20-70-0020",
"Direct Ignition Coil V20-70-0021",
"Direct Ignition Coil V20-70-0022",
"Direct Ignition Coil V30-70-0012",
"Direct Ignition Coil V30-70-0016",
"Direct Ignition Coil V30-70-0017",
"Direct Ignition Coil V30-70-0025",
"Direct Ignition Coil V30-70-0027",
"Direct Ignition Coil V30-70-0028",
"Direct Ignition Coil V45-70-0001",
"Direct Ignition Coil V49-70-0004",
"Ignition Coil 245203"]
Product='Direct Ignition Coil'

In [3]:
Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Opticat_Scrapping\Outputs'

# 3. Setting Webdriver and Website Specific Information

In [4]:
path= 'C://chromedriver.exe'
browser=webdriver.Chrome()
browser.get('https://web.tecalliance.net/opticat/qa/login')
browser.maximize_window()
sleep(5)

In [5]:
button = browser.find_element(By.ID,'ppms_cm_save-choices')
button.click()

In [6]:
username_field = browser.find_element(By.ID,'userName')  
username_field.send_keys('yuvaraj.g@firstbrandsgroup.com')
password_field = browser.find_element(By.ID,'password')  
password_field.send_keys('Opticat@29')
button = browser.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()
sleep(2)

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [7]:
count=0
cols=['PartNumber','Product_Name','Make','Models','Model_Years','Start_Year','End_Year','Source_Link']
df = pd.DataFrame(columns=cols)
df

Empty DataFrame
Columns: [PartNumber, Product_Name, Make, Models, Model_Years, Start_Year, End_Year, Source_Link]
Index: []

In [9]:
for ic in range(len(Item_Code)):
    search_content=browser.find_element(By.ID,"part-search-input")
    search_content.click()
    search_content.send_keys(Item_Code[ic])
    Search_Button=browser.find_element(By.CLASS_NAME, "btn-search").click()
    sleep(2)

    #-----------------------------------------------------------------------------------------------------------------
    click_Firstelement=browser.find_element(By.CSS_SELECTOR,'div[role="row"][aria-rowindex="2"]')
    click_Firstelement.click()
    #-----------------------------------------------------------------------------------------------------------------
    Product_Locator= (By.CSS_SELECTOR, '.title.text-uppercase span')
    Product_Name_element = WebDriverWait(browser, 10).until(EC.presence_of_element_located(Product_Locator))
    sleep(3)
    # Get the text content of the element
    Product_Name = Product_Name_element.text
    print(Product_Name,ic)
    #-----------------------------------------------------------------------------------------------------------------
    Vehicle_Selection_ICON=browser.find_element(By.CSS_SELECTOR,'li.ng-star-inserted a[role="tab"] i.ta-icon-car-front')
    Vehicle_Selection_ICON.click()
    #-----------------------------------------------------------------------------------------------------------------
    # Wait for the button to be clickable
    button_locator = (By.CLASS_NAME, 'p-autocomplete-dropdown')
    button = WebDriverWait(browser, 10).until(EC.element_to_be_clickable(button_locator))

    # Click the button
    button.click()
    

    panel_locator = (By.CLASS_NAME, 'p-autocomplete-panel')
    panel = WebDriverWait(browser, 10).until(EC.presence_of_element_located(panel_locator))

    # Find all the items in the list
    items_locator = (By.CSS_SELECTOR, '.p-autocomplete-items .ng-star-inserted')
    items = panel.find_elements(*items_locator)
    item_texts=[]
    for i in items:
         item_texts.append(i.text)
    # Extract text from each item
    # item_texts = [item.text for item in items]
    #print(item_texts)
    item_texts=set(item_texts)
    item_texts=list(item_texts)
    item_texts.sort()
    # Print or use the item texts as needed
    print(item_texts)
    #-----------------------------------------------------------------------------------------------------------------


    #-----------------------------------------------------------------------------------------------------------------
    
    for j in range(len(item_texts)):
        inputkeys=item_texts[j]
        #print(inputkeys)
        input_element = browser.find_element(By.CLASS_NAME,'p-autocomplete-input')
        input_element.click()
        # Clear any existing text in the input field (optional, if needed)
        input_element.clear()
        # Type the target value into the input field
        input_element.send_keys(inputkeys)
        sleep(1)
        input_element.send_keys(Keys.ENTER)
        #print('entered')
        table_element = browser.find_element(By.XPATH, "//tbody[@_ngcontent-ng-c3462382488='']")
        # Find all rows in the table
        Model = table_element.find_elements(By.TAG_NAME, "th")
        Model_Year = table_element.find_elements(By.TAG_NAME, "td")
        current_URL=browser.current_url
        for i in range(1,len(Model)):
                # This has to be defined. 
                df.loc[count,'Make']=item_texts[j]
                df.loc[count,'Product_Name']=Product_Name
                df.loc[count,'PartNumber']=Item_Code[ic]
                df.loc[count,'Models']=Model[i].text
                df.loc[count,'Model_Years']= Model_Year[i].text
                df.loc[count,'Source_Link']=current_URL
                count=count+1
                #print(count)            
        sleep(1)
        #print('Manufacturers-',j+1, 'Models-',count)    
        input_element.clear()
    print("Number of Part Number Scrapped: ", ic+1)
    clear_output(wait=True)

BECK/ARNLEY 178-8154 DIRECT IGNITION COIL 0
['BMW']
Number of Part Number Scrapped:  1

NameError: name 'clear_output' is not defined

# 5. Post Processing Data and Exporting

In [31]:
#-----------------------------------------------------------------------------------------------------------------
df['Model_Years']=df['Model_Years'].str.split(',')
df=df.explode('Model_Years')
df = df.drop_duplicates()
df = df.reset_index(drop=True)


#-----------------------------------------------------------------------------------------------------------------
for i in range(len(df)):
    if "-" in df['Model_Years'][i]:
        #print(i)
        year=df['Model_Years'].str.split('-')[i]
        startyear=year[0]
        endyear=year[1]
        df.loc[i,'Start_Year']=startyear
        df.loc[i,'End_Year']=endyear
    if "-" not in df['Model_Years'][i]:
        #print (i)
        df.loc[i,'Start_Year']=df['Model_Years'][i]
        df.loc[i,'End_Year']=df['Model_Years'][i]
#-----------------------------------------------------------------------------------------------------------------
df['Start_Year']=df['Start_Year'].str.replace(" ","").astype(int)
df['End_Year']=df['End_Year'].str.replace(" ","").astype(int)

#-----------------------------------------------------------------------------------------------------------------
del df['Model_Years']
#-----------------------------------------------------------------------------------------------------------------

In [35]:
print(df.shape)
df

(891, 7)

,PartNumber,Product_Name,Make,Models,Start_Year,End_Year,Source_Link
0,U5146,NGK U5146 IGNITION COIL,Lexus,ES330,2004,2006,https://web.tecalliance.net/opticat/qa/parts/B...
1,U5146,NGK U5146 IGNITION COIL,Lexus,RX330,2004,2006,https://web.tecalliance.net/opticat/qa/parts/B...
2,U5146,NGK U5146 IGNITION COIL,Lexus,RX400h,2006,2008,https://web.tecalliance.net/opticat/qa/parts/B...
3,U5146,NGK U5146 IGNITION COIL,Toyota,Camry,2004,2006,https://web.tecalliance.net/opticat/qa/parts/B...
4,U5146,NGK U5146 IGNITION COIL,Toyota,Highlander,2004,2010,https://web.tecalliance.net/opticat/qa/parts/B...
...,...,...,...,...,...,...,...
886,U5145,NGK U5145 IGNITION COIL,Toyota,Corolla iM,2017,2018,https://web.tecalliance.net/opticat/qa/parts/B...
887,U5145,NGK U5145 IGNITION COIL,Toyota,Matrix,2009,2014,https://web.tecalliance.net/opticat/qa/parts/B...
888,U5145,NGK U5145 IGNITION COIL,Toyota,Prius,2010,2015,https://web.tecalliance.net/opticat/qa/parts/B...
889,U5145,NGK U5145 IGNITION COIL,Toyota,Prius Plug-In,2012,2015,https://web.tecalliance.net/opticat/qa/parts/B...
890,U5145,NGK U5145 IGNITION COIL,Toyota,Prius V,2012,2017,https://web.tecalliance.net/opticat/qa/parts/B...

In [36]:
df.to_excel(Folder+'\\'+'Opticat_Where_Used_List_'+ Product +'.xlsx', index=False)

# 99. Archived Codes