# 1. Library calling

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from datetime import datetime
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import warnings
from IPython.display import clear_output
import numpy as np
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import datetime
from tqdm import tqdm

# 2. Defining the Product Information and Location

In [2]:
Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\Holes_Fuel Pump\Output'
#Brand_Name='SCHRADER TPMS SOLUTIONS'
#Type_Name='TPMS Sensor'

# 3. Setting Webdriver and Website Specific Information

In [114]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://web.tecalliance.net/opticat/qa/login')
driver.maximize_window()
wait=WebDriverWait(driver, 10)
button =wait.until(EC.presence_of_element_located((By.ID,"ppms_cm_save-choices")))
button.click()

In [115]:
username_field = driver.find_element(By.ID,'userName')  
username_field.send_keys('vikram.vadhirajan@firstbrandsgroup.com')
password_field = driver.find_element(By.ID,'password')  
password_field.send_keys('FBG@Jun-2024')
button = driver.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()

In [5]:
dfi=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Vikram Data research\Holes_Fuel Pump\Holes_Data_Fuel_Pump.xlsx",sheet_name="Sheet1")

In [6]:
# dfi=dfi[dfi['Inclusion']==1].reset_index()

In [7]:
dfi

,Potential,VehicleTypeName,BaseVehicleID,MakeName,ModelName,YearID,Liter,CC,CID,Cylinders,...,FuelTypeName,PartType,Position,Total VIO,PartListCarter,Notes-Internal,VIO-Internal,PartListOE,Notes-OE,VIO-OE
0,NaN,Car,5885,Acura,CL,1997,2.2,2156,-,4,...,GAS,Fuel Pump Module Assembly,NaN,2078,NaN,NaN,0,17040-SV1-A32,NaN,2078
1,NaN,Car,5885,Acura,CL,1997,3.0,2997,-,6,...,GAS,Fuel Pump Module Assembly,NaN,1855,NaN,NaN,0,17040-SS8-A02,NaN,1855
2,NaN,Car,5886,Acura,CL,1998,2.3,2254,-,4,...,GAS,Fuel Pump Module Assembly,NaN,1263,NaN,NaN,0,17040-SY8-A01,NaN,1263
3,NaN,Car,5886,Acura,CL,1998,3.0,2997,-,6,...,GAS,Fuel Pump Module Assembly,NaN,1867,NaN,NaN,0,17040-SS8-A02,NaN,1867
4,NaN,Car,5887,Acura,CL,1999,2.3,2254,-,4,...,GAS,Fuel Pump Module Assembly,NaN,1314,NaN,NaN,0,17040-SY8-A01,NaN,1314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10957,NaN,Truck,163540,Volvo,XC90,2023,2.0,1969,-,4,...,MILD HYBRID EV-GAS (MHEV),Fuel Pump Module Assembly,NaN,11333,NaN,NaN,0,31478637|31478637|31478638|31478638|32203572,Variant code: G601 and G302|Variant code: G601...,11333
10958,NaN,Truck,163540,Volvo,XC90,2023,2.0,1969,-,4,...,MILD HYBRID EV-GAS (MHEV),Fuel Pump Module Assembly,NaN,23579,NaN,NaN,0,31478637|31478637|31478638|31478638|32203572,Variant code: G601 and G302|Variant code: G601...,23579
10959,NaN,Truck,174704,Volvo,XC90,2024,2.0,1969,-,4,...,PLUG-IN HYBRID EV-GAS (PHEV),Fuel Pump Module Assembly,NaN,6302,NaN,NaN,0,31478637|31478637|31478638|31478638|32203572,Variant code: G601 and G302|Variant code: G601...,6302
10960,NaN,Truck,174704,Volvo,XC90,2024,2.0,1969,-,4,...,MILD HYBRID EV-GAS (MHEV),Fuel Pump Module Assembly,NaN,13069,NaN,NaN,0,31478637|31478637|31478638|31478638|32203572,Variant code: G601 and G302|Variant code: G601...,13069
10961,NaN,Truck,174704,Volvo,XC90,2024,2.0,1969,-,4,...,MILD HYBRID EV-GAS (MHEV),Fuel Pump Module Assembly,NaN,2200,NaN,NaN,0,31478637|31478637|31478638|31478638|32203572,Variant code: G601 and G302|Variant code: G601...,2200

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [113]:
cols=['Part No.']
df = pd.DataFrame(columns=cols)
df
count=0

linkprefix="https://web.tecalliance.net/opticat/qa/parts/"
linksuffix="/ap-detail"

In [9]:
l=len(dfi)
print(l)

10962

In [14]:
# find=driver.find_element(By.CSS_SELECTOR,'[placeholder="Filter"]')
# find.click()
# find.send_keys("Spark Plug Wire Set")

In [10]:
# wait.until(EC.presence_of_element_located((By.XPATH, "//a[contains(text(), 'Spark Plug Wire Set')]"))).click()

In [146]:
for i in tqdm(range (10324,l)): #len(dfi):
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    print(i)
    print(dfi.YearID[i]," ",dfi.MakeName[i]," ",dfi.ModelName[i])
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[class="ta-icon-cancel"]'))).click()    
    Type=driver.find_element(By.CSS_SELECTOR,'[placeholder="Type"]')
    Type.click()
    Type.send_keys("Car/Truck/Van")
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Year=driver.find_element(By.CSS_SELECTOR,'[placeholder="Model year "]')
    Year.click()
    Year.send_keys(str(dfi.YearID[i]))
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Manufacture=driver.find_element(By.CSS_SELECTOR,'[placeholder="Manufacturer "]')
    Manufacture.click()
    Manufacture.send_keys(dfi.MakeName[i])
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Model=driver.find_element(By.CSS_SELECTOR,'[placeholder="Models "]')
    Model.click()
    try:
        Model.send_keys(dfi.ModelName[i])
        sleep(.5)
        driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    except:
        continue
    try:
        wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.EngineDetail[i]}')]"))).click()
    except:
        pass
    try:
        wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.FuelTypeName[i]}')]"))).click()
    except:
        pass
    try:
        driver.find_element(By.XPATH,f"//label[contains(text(), '{dfi.AspirationName[i]}')]").click()
    except:
        pass
    try:
        brands=driver.find_elements(By.CLASS_NAME,'p-placeholder')[0]
        brands.click()
    except: 
        pass
    try:
        driver.find_element(By.CSS_SELECTOR,'[role="textbox"]').send_keys("Fuel Pump")
        sleep(.5)
        driver.find_element(By.CSS_SELECTOR,'[role="checkbox"]').click()
        brands.click()
        sleep(3)
        # if i==0:
        #     driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
        #     select_2=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[1]")
        #     select_2.click()
        #     select_3=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[10]")
        #     select_3.click()
        #     sleep(2)
        #     driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
        statuses=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "article-status-cell")))
        Contents=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "generic-article"))) 
        PNS=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, '[class="text-wrap text-primary"]')))
        CNS=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "font-weight-bold")))
        searchtext=driver.find_element(By.CLASS_NAME, "ng-star-inserted") 
        Productcodes=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'div[role="row"]')))
        Applns=driver.find_elements(By.CSS_SELECTOR,'[col-id="application"]')
        c=1
        for status, content, pn,cn, productcode,appln in zip(statuses,Contents,PNS,CNS,Productcodes[1:],Applns[1:]):
            df.loc[count,"Sl.No"]=i
            df.loc[count,'#Items Display']=c
            df.loc[count,"CARTER PNo-FromHoles"]=dfi.PartListCarter[i]
            df.loc[count,"Year"]=str(dfi.YearID[i])
            df.loc[count,"Make"]=dfi.MakeName[i]
            df.loc[count,"Model"]=dfi.ModelName[i]
            df.loc[count,"Engine_details"]=dfi.EngineDetail[i]
            df.loc[count,"Fuel"]=dfi.FuelTypeName[i]
            df.loc[count,"Aspiration"]=dfi.AspirationName[i]        
            df.loc[count,"OE Part Number"]=dfi.PartListOE[i]
            df.loc[count,"SelectedVehicle"]=driver.find_element(By.CSS_SELECTOR,'[class="p-menuitem-text ng-star-inserted"]').text
            #df.loc[count,"SearchText"]=List[i]
            df.loc[count,"Competitor"]=cn.text
            df.loc[count,"Part No."]=pn.text
            df.loc[count,"Application"]=(appln.text)
            #df.loc[count,"Status"]=status.text
            df.loc[count,"Name"]=content.text
            pc=productcode.get_attribute("row-id").replace("]-[","/").replace("[","").replace("]","")
            link=linkprefix+pc+linksuffix
            df.loc[count,"Link"]=driver.current_url
            df.loc[count,"ProductLink"]=link
            count=count+1
            c=c+1    
    except:
            df.loc[count,"Sl.No"]=i
            df.loc[count,'#Items Display']=c
            df.loc[count,"CARTER PNo-FromHoles"]=dfi.PartListCarter[i]
            df.loc[count,"Year"]=str(dfi.YearID[i])
            df.loc[count,"Make"]=dfi.MakeName[i]
            df.loc[count,"Model"]=dfi.ModelName[i]
            df.loc[count,"Engine_details"]=dfi.EngineDetail[i]
            df.loc[count,"Fuel"]=dfi.FuelTypeName[i]
            df.loc[count,"Aspiration"]=dfi.AspirationName[i]        
            df.loc[count,"OE Part Number"]=dfi.PartListOE[i]
            df.loc[count,"Link"]=driver.current_url
            count=count+1
            c=c+1  
    clear_output(wait=True)

100%|██████████| 638/638 [1:46:44<00:00, 10.04s/it]

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27665 entries, 0 to 27664
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Part No.              27450 non-null  object
 1   Sl.No                 27665 non-null  float64
 2   #Items Display        27665 non-null  float64
 3   CARTER PNo-FromHoles  0 non-null      float64
 4   Year                  27665 non-null  object
 5   Make                  27665 non-null  object
 6   Model                 27665 non-null  object
 7   Engine_details        27665 non-null  object
 8   Fuel                  27665 non-null  object
 9   Aspiration            27665 non-null  object
 10  OE Part Number        15057 non-null  object
 11  SelectedVehicle       27450 non-null  object
 12  Competitor            27450 non-null  object
 13  Application           27450 non-null  object
 14  Name                  27450 non-null  object
 15  Link                  27665 non-null  object
 16  ProductLink           27450 non-null  object
dtypes: float64(3), object(14)
memory usage: 4.8+ MB

In [148]:
print(df.shape)
df.tail()

(27665, 17)

,Part No.,Sl.No,#Items Display,CARTER PNo-FromHoles,Year,Make,Model,Engine_details,Fuel,Aspiration,OE Part Number,SelectedVehicle,Competitor,Application,Name,Link,ProductLink
27660,V95-71-0010,10957.0,1.0,NaN,2023,Volvo,XC90,L4 2.0L,MILD HYBRID EV-GAS (MHEV),Turbo/Supercharged,31478637|31478637|31478638|31478638|32203572,2023 Volvo XC90,VEMO,L4 2.0L 1969cc,Fuel Pump Driver Module,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...
27661,V95-71-0010,10958.0,1.0,NaN,2023,Volvo,XC90,L4 2.0L,MILD HYBRID EV-GAS (MHEV),Turbocharged,31478637|31478637|31478638|31478638|32203572,2023 Volvo XC90,VEMO,L4 2.0L 1969cc,Fuel Pump Driver Module,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...
27662,V95-71-0010,10959.0,1.0,NaN,2024,Volvo,XC90,L4 2.0L,PLUG-IN HYBRID EV-GAS (PHEV),Turbo/Supercharged,31478637|31478637|31478638|31478638|32203572,2024 Volvo XC90,VEMO,L4 2.0L 1969cc,Fuel Pump Driver Module,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...
27663,V95-71-0010,10960.0,1.0,NaN,2024,Volvo,XC90,L4 2.0L,MILD HYBRID EV-GAS (MHEV),Turbo/Supercharged,31478637|31478637|31478638|31478638|32203572,2024 Volvo XC90,VEMO,L4 2.0L 1969cc,Fuel Pump Driver Module,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...
27664,V95-71-0010,10961.0,1.0,NaN,2024,Volvo,XC90,L4 2.0L,MILD HYBRID EV-GAS (MHEV),Turbocharged,31478637|31478637|31478638|31478638|32203572,2024 Volvo XC90,VEMO,L4 2.0L 1969cc,Fuel Pump Driver Module,https://web.tecalliance.net/opticat/qa/parts/a...,https://web.tecalliance.net/opticat/qa/parts/C...

# 5. Post Processing Data and Exporting

In [149]:
df['MMY']=df['Year']+" "+df['Make']+" "+df['Model'].astype('str')
df['check']=np.where(df['MMY']==df['SelectedVehicle'],True,False)

In [150]:
dfi['Key']=dfi['YearID'].astype('str')+"_"+dfi['MakeName']+"_"+dfi['ModelName'].astype('str')+"_"+dfi['EngineDetail']+"_"+dfi['FuelTypeName']+"_"+dfi['AspirationName']

In [151]:
df['Key']=df['Year']+"_"+df['Make']+"_"+df['Model'].astype('str')+"_"+df['Engine_details']+"_"+df['Fuel']+"_"+df['Aspiration']

In [152]:
mini=int(df['Sl.No'].min())
maxy=int(df['Sl.No'].max())

In [153]:
df_sorted=df[["Sl.No","#Items Display","CARTER PNo-FromHoles","OE Part Number",'SelectedVehicle', 'Year', 'Make', 'Model','Engine_details', 'Fuel', 'Aspiration','Part No.', 'Competitor','Name',"Application", 'Link','ProductLink',"Key",'check']]

In [154]:
df_delphi = df_sorted[(df_sorted['Competitor'] == 'Delphi') | (df_sorted['Competitor'] == 'Carter')]

In [155]:
df_delphi.columns.difference(['Sl.No', '#Items Display'])

Index(['Application', 'Aspiration', 'CARTER PNo-FromHoles', 'Competitor',
       'Engine_details', 'Fuel', 'Key', 'Link', 'Make', 'Model', 'Name',
       'OE Part Number', 'Part No.', 'ProductLink', 'SelectedVehicle', 'Year'],
      dtype='object')

In [156]:
df_delphi_cleaned=df_delphi.drop_duplicates(subset=df_delphi.columns.difference(['Sl.No', '#Items Display']))

In [157]:
with pd.ExcelWriter(Folder+'\\'+f'Opticat_Export_FuelPump_MMYCombination_{mini}-{maxy}.xlsx') as writer:  # doctest: +SKIP
    dfi.to_excel(writer,index=True, sheet_name='Original List')
    df.to_excel(writer,index=True, sheet_name='Raw')
    df_delphi.to_excel(writer,index=True, sheet_name='Delphi')
    df_sorted.to_excel(writer,index=False, sheet_name='Sorted')
    df_delphi_cleaned.to_excel(writer,index=False, sheet_name='Cleaned_Delphi')

# 99. Archived Codes

In [ ]:
# To extract the Supplier part number from the list


from tqdm import tqdm
for a in tqdm(range(51,len(List))):
    print(a)    
    search_content=driver.find_element(By.ID,"part-search-input")
    search_content.click()
    search_content.send_keys(List[a])
    driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
    sleep(2)
    PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")
    Suppliers =driver.find_elements(By.CSS_SELECTOR, 'p > span.font-weight-bold')       
    for p, s in zip(PN,Suppliers):
        text_content = p.find_element(By.CSS_SELECTOR,'.text-truncate a').text
        print(List[a],":",s.text.strip(),"-",text_content)
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    driver.find_element(By.CSS_SELECTOR,'[id="part-search-input"]').clear()

In [ ]:
        # Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
        # #counter=0
        # for index, element2 in enumerate(Param):
        #     # Access specific attributes or text content of the element
        #     criteria_name = element2.find_element(By.CSS_SELECTOR,'.font-weight-bold:first-child').text
        #     value=element2.find_element(By.CSS_SELECTOR,'span:not(.font-weight-bold)').text
        #     # print(criteria_name,'     :      ',value)
        #     if str(df.loc[counter,criteria_name])!='nan':
        #         counter=counter+1
        #         df.loc[counter,criteria_name]=value
        #     else:
        #         df.loc[counter,criteria_name]=value

In [ ]:
#Reference only

from selenium import webdriver
from bs4 import BeautifulSoup

# Wait for the page to load (you might need to adjust the wait time)
browser.implicitly_wait(10)

# Get the page source and create a BeautifulSoup object
page_source = browser.page_source
soup = BeautifulSoup(page_source, 'html.parser')

# Find all elements with the specified class
elements = soup.find_all('div', class_='ag-row')

# Enumerate the elements based on row index and article-criteria
for index, element in enumerate(elements, start=1):
    # Extract row index
    row_index = element['row-index']


    # Extract article-criteria
    article_criterias = element.select('.article-criteria')
    article_criteria_texts = [criteria.get_text(strip=True) for criteria in article_criterias]

    # Print the results (you can modify this based on your needs)

    for criteria_text in article_criteria_texts:
        CN=criteria_text.split(":")[0]
        CV=criteria_text.split(":")[1]        
        

    print("\n")

In [ ]:
Param_Name=[]

for i in range(Totalpage):
    Param =browser.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
    for index, element in enumerate(Param):
        # Access specific attributes or text content of the element
        criteria_name = WebDriverWait(element, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR,".font-weight-bold:first-child"))).text
        Param_Name.append(criteria_name)
    Currentpage=int(browser.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
    print("Page#",Currentpage,"Completed",datetime.datetime.now())
    if Currentpage < Totalpage:
        NextPage=browser.find_element(By.CLASS_NAME, 'ag-icon-next')
        NextPage.click()
        sleep(3)
        i=i+1

if Totalpage>1:
    First_Page=browser.find_element(By.XPATH,'//div[@ref="btFirst"]')
    First_Page.click()

In [ ]:
Param_Name=set(Param_Name)
cols=Param_Name
cols
df = pd.DataFrame(columns=cols)
print(len(cols))
df

In [ ]:
##Modified to be deleted
for i in tqdm(range (30,l)): #len(dfi)):
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    print(i)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'[class="ta-icon-cancel"]'))).click()    
    Type=driver.find_element(By.CSS_SELECTOR,'[placeholder="Type"]')
    Type.click()
    Type.send_keys("Car/Truck/Van")
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Year=driver.find_element(By.CSS_SELECTOR,'[placeholder="Model year "]')
    Year.click()
    Year.send_keys(str(dfi.YearID[i]))
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Manufacture=driver.find_element(By.CSS_SELECTOR,'[placeholder="Manufacturer "]')
    Manufacture.click()
    Manufacture.send_keys(dfi.MakeName[i])
    sleep(.5)
    driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    Model=driver.find_element(By.CSS_SELECTOR,'[placeholder="Models "]')
    Model.click()
    try:
        Model.send_keys(dfi.ModelName[i])
        sleep(.5)
        driver.find_element(By.CSS_SELECTOR,'[role="option"]').click()
    except:
        continue
    try:
        sleep(2)
        find=driver.find_element(By.CSS_SELECTOR,'[placeholder="Filter"]')
        find.click()
        find.send_keys("Spark Plug Wire Set")
        # brands.click()
        wait.until(EC.presence_of_element_located((By.XPATH, "//a[contains(text(), 'Spark Plug Wire Set')]"))).click()

        sleep(3)

    except:
        continue
    try:
        wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.EngineDetail[i]}')]"))).click()
        print(dfi.EngineDetail[i])
    except:
        continue
    # try:
    #     wait.until(EC.presence_of_element_located((By.XPATH,f"//label[contains(text(), '{dfi.FuelTypeName[i]}')]"))).click()
    # except:
    #     pass
    # try:
    #     driver.find_element(By.XPATH,f"//label[contains(text(), '{dfi.AspirationName[i]}')]").click()
    # except:
    #     pass
    # try:
    #     brands=driver.find_elements(By.CLASS_NAME,'p-placeholder')[0]
    #     brands.click()
    # except: 
    #     pass
    try:

        # if i==0:
        #     driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
        #     select_2=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[1]")
        #     select_2.click()
        #     select_3=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[10]")
        #     select_3.click()
        #     sleep(2)
        #     driver.find_element(By.CSS_SELECTOR,'[class="p-multiselect-label"]').click()
        statuses=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "article-status-cell")))
        Contents=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "generic-article"))) 
        PNS=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, '[class="text-truncate text-primary"]')))
        CNS=wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "font-weight-bold")))
        searchtext=driver.find_element(By.CLASS_NAME, "ng-star-inserted") 
        Productcodes=wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR,'div[role="row"]')))
        Applns=driver.find_elements(By.CSS_SELECTOR,'[col-id="application"]')
        for status, content, pn,cn, productcode,appln in zip(statuses,Contents,PNS,CNS,Productcodes[1:],Applns[1:]):
            df.loc[count,"Sl.No"]=i
            # df.loc[count,"CARTER PNo-FromHoles"]=dfi.PartListCarter[i]
            df.loc[count,"Year"]=str(dfi.YearID[i])
            df.loc[count,"Make"]=dfi.MakeName[i]
            df.loc[count,"Model"]=dfi.ModelName[i]
            df.loc[count,"Engine_details"]=dfi.EngineDetail[i]
            # df.loc[count,"Fuel"]=dfi.FuelTypeName[i]
            # df.loc[count,"Aspiration"]=dfi.AspirationName[i]        
            # df.loc[count,"OE Part Number"]=dfi.PartListOE[i]
            df.loc[count,"SelectedVehicle"]=driver.find_element(By.CSS_SELECTOR,'[class="p-menuitem-text ng-star-inserted"]').text
            #df.loc[count,"SearchText"]=List[i]
            df.loc[count,"Competitor"]=cn.text
            df.loc[count,"Part No."]=pn.text
            df.loc[count,"Application"]=(appln.text)
            #df.loc[count,"Status"]=status.text
            df.loc[count,"Name"]=content.text
            pc=productcode.get_attribute("row-id").replace("]-[","/").replace("[","").replace("]","")
            link=linkprefix+pc+linksuffix
            df.loc[count,"Link"]=driver.current_url
            df.loc[count,"ProductLink"]=link
            count=count+1    
    except:
            df.loc[count,"Sl.No"]=i
            # df.loc[count,"CARTER PNo-FromHoles"]=dfi.PartListCarter[i]
            df.loc[count,"Year"]=str(dfi.YearID[i])
            df.loc[count,"Make"]=dfi.MakeName[i]
            df.loc[count,"Model"]=dfi.ModelName[i]
            df.loc[count,"Engine_details"]=dfi.EngineDetail[i]
            # df.loc[count,"Fuel"]=dfi.FuelTypeName[i]
            # df.loc[count,"Aspiration"]=dfi.AspirationName[i]        
            # df.loc[count,"OE Part Number"]=dfi.PartListOE[i]
            df.loc[count,"Link"]=driver.current_url
            count=count+1
    clear_output(wait=True)