# 1. Library calling

In [1]:
import datetime
import warnings
from datetime import datetime
from time import sleep

import numpy as np
import pandas as pd
from IPython.display import clear_output
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select, WebDriverWait

# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
from tqdm import tqdm

# 2. Defining the Product Information and Location

In [2]:
Folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Catalog\Catalog System Consolidation\Cardone Calipers\Potential Matching Files\OE Based'
Brand_Name='Cardone'
Type_Name='Caliper'

# 3. Setting Webdriver and Website Specific Information

In [76]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
driver.get('https://web.tecalliance.net/opticat/qa/login')
driver.maximize_window()
button =WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.ID,"ppms_cm_save-choices")))
button.click()
wait=WebDriverWait(driver, 5)

TimeoutException: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF67FEFFB05+28789]
	(No symbol) [0x00007FF67FE686E0]
	(No symbol) [0x00007FF67FD0592A]
	(No symbol) [0x00007FF67FD5930E]
	(No symbol) [0x00007FF67FD595FC]
	(No symbol) [0x00007FF67FDA28A7]
	(No symbol) [0x00007FF67FD7F47F]
	(No symbol) [0x00007FF67FD9F654]
	(No symbol) [0x00007FF67FD7F1E3]
	(No symbol) [0x00007FF67FD4A938]
	(No symbol) [0x00007FF67FD4BAA1]
	GetHandleVerifier [0x00007FF68023933D+3410093]
	GetHandleVerifier [0x00007FF68024E7DD+3497293]
	GetHandleVerifier [0x00007FF680242A73+3448803]
	GetHandleVerifier [0x00007FF67FFC7BBB+848171]
	(No symbol) [0x00007FF67FE73C3F]
	(No symbol) [0x00007FF67FE6F6E4]
	(No symbol) [0x00007FF67FE6F87D]
	(No symbol) [0x00007FF67FE5ED49]
	(No symbol) [0x00007FFEEECF7374]
	RtlUserThreadStart [0x00007FFEEFB1CC91+33]

In [77]:
username_field = driver.find_element(By.ID,'userName')  
username_field.send_keys('vikram.vadhirajan@firstbrandsgroup.com')
password_field = driver.find_element(By.ID,'password')  
password_field.send_keys('FBG@Jun-2024')
button = driver.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()

In [12]:
username_field = driver.find_element(By.ID,'userName')  
username_field.send_keys('yuvaraj.g@firstbrandsgroup.com')
password_field = driver.find_element(By.ID,'password')  
password_field.send_keys('Opticat@29')
button = driver.find_element(By.XPATH, "(//div[@class='col-sm-12'])")
button.click()

In [5]:
Brand_field_DD = driver.find_element(By.XPATH, "(//div[@class='p-dropdown-trigger'])[1]")  
Brand_field_DD.click()
Brand_field = driver.find_element(By.XPATH, "(//input[@class='p-dropdown-filter p-inputtext p-component'])[1]")  
Brand_field.send_keys(Brand_Name)
select_1=driver.find_element(By.XPATH,"(//li[@class='p-ripple p-element p-dropdown-item'])")
select_1.click()
Type_field_DD = driver.find_element(By.XPATH, "(//div[@class='p-dropdown-trigger'])[2]")
Type_field_DD.click()
sleep(1)

Type_field = driver.find_element(By.XPATH, "(//input[@class='p-dropdown-filter p-inputtext p-component'])[1]")  
Type_field.send_keys(Type_Name)

# select_1=driver.find_element(By.XPATH,"(//li[@class='p-ripple p-element p-dropdown-item'])")
# select_1.click()
Type_field.send_keys(Keys.ENTER)
sleep(1)

searchButton=driver.find_element(By.ID,'brand-productgroup-search-button')
searchButton.click()

ElementClickInterceptedException: Message: element click intercepted: Element <div role="button" aria-label="dropdown trigger" aria-haspopup="listbox" class="p-dropdown-trigger">...</div> is not clickable at point (541, 272). Other element would receive the click: <div class="loading ng-tns-c325580674-7 fixed ng-trigger ng-trigger-flyInOut ng-star-inserted">...</div>
  (Session info: chrome=126.0.6478.56)
Stacktrace:
	GetHandleVerifier [0x00007FF77E133E62+31618]
	(No symbol) [0x00007FF77E0AB0C9]
	(No symbol) [0x00007FF77DF6888A]
	(No symbol) [0x00007FF77DFC022E]
	(No symbol) [0x00007FF77DFBDBE2]
	(No symbol) [0x00007FF77DFBB07B]
	(No symbol) [0x00007FF77DFBA246]
	(No symbol) [0x00007FF77DFAC281]
	(No symbol) [0x00007FF77DFDD10A]
	(No symbol) [0x00007FF77DFABBA6]
	(No symbol) [0x00007FF77DFDD320]
	(No symbol) [0x00007FF77DFFCA80]
	(No symbol) [0x00007FF77DFDCEB3]
	(No symbol) [0x00007FF77DFAA46B]
	(No symbol) [0x00007FF77DFAB001]
	GetHandleVerifier [0x00007FF77E43A03D+3202397]
	GetHandleVerifier [0x00007FF77E486A5D+3516285]
	GetHandleVerifier [0x00007FF77E47C4D0+3473904]
	GetHandleVerifier [0x00007FF77E1E5D66+760454]
	(No symbol) [0x00007FF77E0B6B6F]
	(No symbol) [0x00007FF77E0B1D04]
	(No symbol) [0x00007FF77E0B1E92]
	(No symbol) [0x00007FF77E0A123F]
	BaseThreadInitThunk [0x00007FFCADF07344+20]
	RtlUserThreadStart [0x00007FFCAE0426B1+33]

In [5]:
select_1=driver.find_element(By.XPATH,"(//div[@class='d-flex align-self-stretch align-items-center flex-row-reverse flex-shrink-0'])")
select_1.click()
select_2=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[3]")
select_2.click()
select_3=driver.find_element(By.XPATH,"(//p-multiselectitem[@class='p-element ng-star-inserted'])[10]")
select_3.click()
select_1.click()
sleep(2)

In [4]:
Totalpage=int(driver.find_element(By.XPATH,'//span[@ref="lbTotal" and @class="ag-paging-number"]').text)
Currentpage=int(driver.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
Totalpage

11

# 4. Defining the Dataframe and Extracting the data into the Dataframe

## Part Details

In [30]:
cols=['Sup_Code']
df = pd.DataFrame(columns=cols)
df

Empty DataFrame
Columns: [Sup_Code]
Index: []

In [49]:
import datetime
from datetime import timedelta

import numpy as np
from IPython.display import clear_output

timestamp=[]
timediff=[]
def timeremaining(balanceitem,i):
    timestamp.insert(i,datetime.datetime.now())
    if i>=1:
        diff=timestamp[i]-timestamp[i-1]
        timediff.insert(i,diff.total_seconds())		
        remainingtime=np.median(timediff)*balanceitem
        millis=int(remainingtime)		
        #print(millis)
        seconds=(millis)%60
        seconds = int(seconds)
        minutes=(millis/(60))%60
        minutes = int((minutes)) #math.floor
        hours=(millis/(60*60))%24
        hours=int(hours)
        print(f'Item looped: {i+1} \nItems Remining: {balanceitem-1} and \nTime Remaining: {hours}:{minutes}:{seconds}')
        etc=datetime.datetime.now()+timedelta(hours=hours,minutes=minutes,seconds=seconds)
        print(f'Estimated time of completion:{etc}')        
        clear_output(wait=True)

In [31]:
lineNo1=0
lineNo2=0
lineNo3=0
lineNo4=0
counter=0
for i in range(Totalpage):
    if i <= Totalpage:
        fe=int(driver.find_element(By.CSS_SELECTOR,'[class="flex-shrink-0 ng-star-inserted"]').text.split(" - ")[0].split(" ")[-1])
        le=int(driver.find_element(By.CSS_SELECTOR,'[class="flex-shrink-0 ng-star-inserted"]').text.split(" - ")[1].split(" ")[0])
        te=le-fe
        Currentpage=int(driver.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
        #print("Page#",Currentpage,"inprogress",datetime.datetime.now())
#-----------------------------------------------------------------------------------------------------------------------------------------  
        all_links = driver.find_elements(By.CSS_SELECTOR,'div[role="row"]')
        for link in all_links[1:]:
            df.loc[lineNo4,'Sup_Code']=link.get_attribute('row-id')
            lineNo4=lineNo4+1
#-----------------------------------------------------------------------------------------------------------------------------------------  
        PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")
        # if i==1:
        #     print(PN[0].text)
        PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")       
        for index1,element1 in enumerate(PN):
            # Access specific attributes or text content of the element
            text_content = PN[index1].find_element(By.CSS_SELECTOR,'.text-truncate a').text
            df.loc[lineNo1,'Part No.']=text_content
            lineNo1=lineNo1+1
#-----------------------------------------------------------------------------------------------------------------------------------------   
        PartNames =driver.find_elements(By.CSS_SELECTOR, 'span.generic-article')  
        for index2, PartName in enumerate(PartNames):
            # Access specific attributes or text content of the element
            df.loc[lineNo2,'Part Name']=PartName.text.strip()
            lineNo2=lineNo2+1
#-----------------------------------------------------------------------------------------------------------------------------------------   
        Suppliers =driver.find_elements(By.CSS_SELECTOR, '[tooltipstyleclass="long-tooltip"]')
        for index3, supplier in enumerate(Suppliers[:-1]):
            # Access specific attributes or text content of the element
            df.loc[lineNo3,'Supplier Name']=supplier.text.strip() 
            lineNo3=lineNo3+1 
#-----------------------------------------------------------------------------------------------------------------------------------------  
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'html.parser')
        # Find all elements with the specified class
        elements = soup.find_all('div', class_='ag-row')
        # Enumerate the elements based on row index and article-criteria
        for index, element in enumerate(elements, start=1):
            # Extract row index
            row_index = int(element['row-index'])
            #print(row_index)
            
            # Extract article-criteria
            article_criterias = element.select('.article-criteria')
            article_criteria_texts = [criteria.get_text(strip=True) for criteria in article_criterias]

            # Print the results (you can modify this based on your needs)

            for criteria_text in article_criteria_texts:
                CN=criteria_text.split(":")[0]
                CV=criteria_text.split(":")[1]       
                df.loc[row_index,CN]=CV
            # df.loc[row_index,"Part Number"]=df_1.loc[row_index,"Part Number"]
            # df.loc[row_index,"Part Name"]=df_1.loc[row_index,"Part Name"]
            # df.loc[row_index,"Supplier Name"]=df_1.loc[row_index,"Supplier Name"]    
#-----------------------------------------------------------------------------------------------------------------------------------------    
        Currentpage=int(driver.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
        balanceitem=Totalpage-i
        timeremaining(balanceitem,i)
        if Currentpage < Totalpage:
            NextPage=driver.find_element(By.CLASS_NAME, 'ag-icon-next')
            NextPage.click()
            sleep(5)
    i=i+1
if Totalpage>1:
    First_Page=driver.find_element(By.XPATH,'//div[@ref="btFirst"]')
    First_Page.click()

NameError: name 'Totalpage' is not defined

In [81]:
df

,Sup_Code,Part Name,Supplier Name,Stock Number,Part Number,Voltage,Ignition Type,Coil Type,Oil Filled,Terminal Type,Terminal Quantity,Connector Gender,Terminal Gender,Mounting Bracket Included
0,[BCDP]-[48568],Ignition Coil,Discontinued,48568,U1122,12.0 2h,Electronic,HEI,No,Blade,4,Female,Male,No
1,[BCDP]-[48569],Ignition Coil,Announced,48569,U5070,12.0 2h,Distributorless,COP (Coil on Plug),No,Blade,3,Female,Male,No
2,[BCDP]-[48570],Ignition Coil,Announced,48570,U5071,12.0 2h,Distributorless,COP (Coil on Plug),No,Blade,3,Female,Male,No
3,[BCDP]-[48571],Ignition Coil,Discontinued,48571,U3036,12.0 2h,Distributorless,DIS,No,Blade,2,Female,Male,No
4,[BCDP]-[48575],Ignition Coil,Discontinued,48575,U5193,12.0 2h,Distributorless,COP (Coil on Plug),No,Blade,3,Female,Male,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,[BCDP]-[U6045],Ignition Coil,Discontinued,48712,U6045,12.0 2h,Distributorless,COP (Rail System),No,Blade,7,Female,Male,Yes
1038,[BCDP]-[U6046],Ignition Coil,Discontinued,48836,U6046,12.0 2h,Distributorless,COP (Rail System),No,Blade,10,Female,Male,No
1039,[BCDP]-[U6047],Ignition Coil,Discontinued,48908,U6047,12.0 2h,Distributorless,COP (Rail System),No,Blade,7,Female,Male,No
1040,[BCDP]-[U6048],Ignition Coil,Discontinued,48965,U6048,12.0 2h,Distributorless,COP (Rail System),No,Blade,7,Female,Male,No
1041,[BCDP]-[U6051],Ignition Coil,Announced,49026,U6051,12.0 2h,Distributorless,COP (Rail System),No,Blade,10,Female,Male,No

In [26]:
count=0

In [39]:
statuses=driver.find_elements(By.CLASS_NAME, "article-status-cell")
Contents=driver.find_elements(By.CLASS_NAME, "generic-article") 
PNS=driver.find_elements(By.CLASS_NAME, "text-primary")
CNS=driver.find_elements(By.CLASS_NAME, "font-weight-bold")
searchtext=driver.find_element(By.CLASS_NAME, "ng-star-inserted")    

for status, content, pn,cn in zip(statuses,Contents,PNS,CNS):

    df.loc[count,"SearchText"]=searchtext.text.split("Search")[1].split('\n')[0]
    df.loc[count,"Competitor"]=cn.text
    df.loc[count,"PartNumber"]=pn.text
    #df.loc[count,"Status"]=status.text
    df.loc[count,"Name"]=content.text
    count=count+1

In [13]:
df

,Part No.,Sup_Code,Part Name,Supplier Name,Length,Width,Height,Weight,Part Description,Boiling Point,...,Flammable,Capacity [litre],Assy./disassy. by qualified personnel required!,Product Group,Prop 65 - Short Label,Prop 65 Warning Label,Prop 65 Yes/No,Specifications/Approvals,Recommendations,ISO
0,ESI6-32N,[BBHK]-[ESI6-32N],Brake Fluid,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L04005,[BBHN]-[L04005],Brake Fluid,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,L04010,[BBHN]-[L04010],Brake Fluid,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,L04050,[BBHN]-[L04050],Brake Fluid,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,L04210,[BBHN]-[L04210],Brake Fluid,Search by brands and part types,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,NaN,NaN,NaN,Available to Order,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,NaN,NaN,NaN,Available to Order,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NaN,NaN,NaN,Available to Order,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,Available to Order,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,NaN,NaN,IAM criteria\nDamaging To Painted Surfaces\nAl...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df

    Part No.           Sup_Code                                      Part Name
0      20028     [DXMM]-[20028]  Tire Pressure Monitoring System (TPMS) Sensor
1      20034     [DXMM]-[20034]  Tire Pressure Monitoring System (TPMS) Sensor
2      20064     [DXMM]-[20064]  Tire Pressure Monitoring System (TPMS) Sensor
3      20069     [DXMM]-[20069]  Tire Pressure Monitoring System (TPMS) Sensor
4      20076     [DXMM]-[20076]  Tire Pressure Monitoring System (TPMS) Sensor
..       ...                ...                                            ...
85  ST4138DL  [DXMM]-[ST4138DL]  Tire Pressure Monitoring System (TPMS) Sensor
86  ST4139DL  [DXMM]-[ST4139DL]  Tire Pressure Monitoring System (TPMS) Sensor
87  ST4141DL  [DXMM]-[ST4141DL]  Tire Pressure Monitoring System (TPMS) Sensor
88  ST4142DL  [DXMM]-[ST4142DL]  Tire Pressure Monitoring System (TPMS) Sensor
89  ST4143DL  [DXMM]-[ST4143DL]  Tire Pressure Monitoring System (TPMS) Sensor

[90 rows x 3 columns]

In [14]:
df=df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123 entries, 0 to 134
Data columns (total 53 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Part No.                                         121 non-null    object
 1   Sup_Code                                         121 non-null    object
 2   Part Name                                        121 non-null    object
 3   Supplier Name                                    123 non-null    object
 4   Length                                           14 non-null     object
 5   Width                                            14 non-null     object
 6   Height                                           14 non-null     object
 7   Weight                                           14 non-null     object
 8   Part Description                                 14 non-null     object
 9   Boiling Point                                    2 non-null      object
 10  Color                                            2 non-null      object
 11  Composition                                      3 non-null      object
 12  Container Type                                   5 non-null      object
 13  Flash Point                                      13 non-null     object
 14  Fluid Composition                                6 non-null      object
 15  Minimum Dry Boiling Point                        12 non-null     object
 16  Minimum Wet Boiling Point                        12 non-null     object
 17  Polyglycol Ether Based                           11 non-null     object
 18  Type                                             6 non-null      object
 19  Volume                                           6 non-null      object
 20  Damaging To Painted Surfaces                     6 non-null      object
 21  DOT Rating                                       2 non-null      object
 22  Length [mm]                                      5 non-null      object
 23  Recommended replace interval [years]             1 non-null      object
 24  Recommended replace interval [km]                1 non-null      object
 25  Specifications                                   1 non-null      object
 26  Specification                                    1 non-null      object
 27  Quality                                          1 non-null      object
 28  Width [mm]                                       5 non-null      object
 29  Height [mm]                                      5 non-null      object
 30  Packaging height [cm]                            1 non-null      object
 31  DOT specification                                2 non-null      object
 32  Dry Boiling Point [°C]                           1 non-null      object
 33  Packaging Depth [cm]                             1 non-null      object
 34  Packing Type                                     1 non-null      object
 35  California Proposition 65 Required               21 non-null     object
 36  Chemical Properties                              1 non-null      object
 37  Packaging width [cm]                             1 non-null      object
 38  Capacity [Litre]                                 1 non-null      object
 39  Capacity                                         1 non-null      object
 40  California Proposition 65 Text                   20 non-null     object
 41  Wet Boiling Point [°C]                           1 non-null      object
 42  Weight [kg]                                      5 non-null      object
 43  Flammable                                        2 non-null      object
 44  Capacity [litre]                                 1 non-null      object
 45  Assy./disassy. by qualified personnel required!  1 non-null      object
 46  Product Group                                    10 non-null     object
 47  Prop 65 - Short Label                            7 non-null      object
 48  Prop 65 Warning Label                            8 non-null      object
 49  Prop 65 Yes/No                                   7 non-null      object
 50  Specifications/Approvals                         6 non-null      object
 51  Recommendations                                  2 non-null      object
 52  ISO                                              6 non-null      object
dtypes: object(53)
memory usage: 51.9+ KB

## Search Part and extract Data (Name Number and Availability)

In [64]:
cols=['index']
df_s = pd.DataFrame(columns=cols)
df_s
count=0
prefix="https://web.tecalliance.net/opticat/qa/parts/"
suffix="/ap-detail"

In [65]:
df_in=pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Catalog\Catalog System Consolidation\Cardone Calipers\Potential Matching Files\OE Based\Match_Consolidation_Cardone_Reybestos.xlsx",sheet_name='Base',skiprows=1)

In [66]:
df_in

,Unnamed: 0,Cardone Part,Caliper Name,Raybestos Base Part Number,Relationship,Found in Cardone PIES Data,Bracket,Type,WithBracket,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,1,18-4007,CARDONE_NO_LEFT,CAL4220,1:1,Yes,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,18-4072,CARDONE_NO_LEFT,CAL4126,1:1,Yes,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,18-4076,CARDONE_NO_LEFT,CAL4120,1:1,Yes,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,18-4113,CARDONE_NO_LEFT,CAL10403,1:1,Yes,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,18-4123,CARDONE_NO_LEFT,CAL4156,1:1,Yes,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1228,0,19-B901,CARDONE_W_BRACKET_NO_LEFT,CAL3828,1:1,Yes,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1229,0,19-B985,CARDONE_W_BRACKET_NO_LEFT,CAL3889,1:1,Yes,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1230,0,19-B985B,CARDONE_W_BRACKET_NO_LEFT,CAL3889,1:1,Yes,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231,0,19-B985C,CARDONE_W_BRACKET_NO_LEFT,CAL3889,1:1,Yes,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1232,0,19-B989,CARDONE_W_BRACKET_NO_LEFT,CAL10140,1:1,Yes,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df_in=df_in[df_in['Found in Cardone PIES Data']=="Yes"].reset_index()

In [68]:
df_in['Cardone Part'][1]

'18-4072'

In [78]:
for l in tqdm(range(605+505,len(df_in))):
    searchbox=driver.find_element(By.ID,"part-search-input")
    searchbox.click()
    searchbox.send_keys(df_in['Cardone Part'][l])
    sleep(.5)
    searchbox.send_keys(Keys.ENTER)
    sleep(3)
    try:
        partcount=len(wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"ag-row-position-absolute"))))
        print(partcount, df_in['Cardone Part'][l])
        j=1
        sleep(3)       
        itemlist=driver.find_elements(By.CLASS_NAME,"ag-row-position-absolute")[0]
        items=itemlist.find_elements(By.CLASS_NAME,"article-criteria")
        for item in items:     
            df_s.loc[count,'AttributeName']=item.text.split(":")[0]
            df_s.loc[count,'AttributeValue']=item.text.split(":")[1]
            #df_s.loc[count,'#Items']=j
            df_s.loc[count,'index']=l
            df_s.loc[count,'PartNumber']=df_in['Cardone Part'][l]
            df_s.loc[count,'SupplierPartNumber']=itemlist.find_element(By.CSS_SELECTOR,'[col-id="articleNo"]').text
            df_s.loc[count,'Supplier']=itemlist.find_element(By.CSS_SELECTOR,'[col-id="description"]').find_elements(By.CLASS_NAME,"font-weight-bold")[0].text
            df_s.loc[count,'ProductName']=itemlist.find_element(By.CSS_SELECTOR,'[col-id="description"]').find_elements(By.CLASS_NAME,"generic-article")[0].text
            df_s.loc[count,'Status']=itemlist.find_element(By.CSS_SELECTOR,'[col-id="stateText"]').text
            df_s.loc[count,'Links']=prefix+(driver.find_elements(By.CLASS_NAME,"ag-row-position-absolute")[0].get_attribute('row-id').replace("[","").replace("]",""))+suffix            
            count=count+1
    except:
        df_s.loc[count,'index']=l
        df_s.loc[count,'#Items']=0
        df_s.loc[count,'PartNumber']=df_in['Cardone Part'][l]
        df_s.loc[count,'Supplier']="No Supplier information"
        count=count+1
    clear_output(wait=True)

100%|██████████| 30/30 [01:55<00:00,  3.83s/it]

In [79]:
df_s # printing the

,index,AttributeName,AttributeValue,PartNumber,SupplierPartNumber,Supplier,ProductName,Status,Links,#Items
0,0,Inlet Port Size,0.44,18-4007,18-4007,CARDONE Reman,Disc Brake Caliper,Available to Order,https://web.tecalliance.net/opticat/qa/parts/C...,NaN
1,0,Piston Quantity,1,18-4007,18-4007,CARDONE Reman,Disc Brake Caliper,Available to Order,https://web.tecalliance.net/opticat/qa/parts/C...,NaN
2,0,Piston Material,Steel,18-4007,18-4007,CARDONE Reman,Disc Brake Caliper,Available to Order,https://web.tecalliance.net/opticat/qa/parts/C...,NaN
3,0,Package Contents,Caliper; Instruction Sheet; Hardware Kit,18-4007,18-4007,CARDONE Reman,Disc Brake Caliper,Available to Order,https://web.tecalliance.net/opticat/qa/parts/C...,NaN
4,0,Bleeder Port Size,3/8x24,18-4007,18-4007,CARDONE Reman,Disc Brake Caliper,Available to Order,https://web.tecalliance.net/opticat/qa/parts/C...,NaN
...,...,...,...,...,...,...,...,...,...,...
28802,1135,NaN,NaN,19-B901,NaN,No Supplier information,NaN,NaN,NaN,0.0
28803,1136,NaN,NaN,19-B985,NaN,No Supplier information,NaN,NaN,NaN,0.0
28804,1137,NaN,NaN,19-B985B,NaN,No Supplier information,NaN,NaN,NaN,0.0
28805,1138,NaN,NaN,19-B985C,NaN,No Supplier information,NaN,NaN,NaN,0.0
28806,1139,NaN,NaN,19-B989,NaN,No Supplier information,NaN,NaN,NaN,0.0

In [80]:
with pd.ExcelWriter(Folder+'\\'+'Opticat_Export_Cardone'+'PartNumbers'+'.xlsx') as writer:  # doctest: +SKIP
    df_s.to_excel(writer,index=False, sheet_name='Raw')

## Search Part and extract Data (Name Number and Availability along with Attribute)

In [36]:
cols=['index','Attributes']
df_pa = pd.DataFrame(columns=cols)
df_pa
count=0

In [34]:
totpage=int(driver.find_element(By.CSS_SELECTOR,'[ref="lbTotal"]').text)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[ref="lbTotal"]"}
  (Session info: chrome=131.0.6778.140); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6F9C16CC5+28821]
	(No symbol) [0x00007FF6F9B83850]
	(No symbol) [0x00007FF6F9A2578A]
	(No symbol) [0x00007FF6F9A791BE]
	(No symbol) [0x00007FF6F9A794AC]
	(No symbol) [0x00007FF6F9AC2647]
	(No symbol) [0x00007FF6F9A9F33F]
	(No symbol) [0x00007FF6F9ABF412]
	(No symbol) [0x00007FF6F9A9F0A3]
	(No symbol) [0x00007FF6F9A6A778]
	(No symbol) [0x00007FF6F9A6B8E1]
	GetHandleVerifier [0x00007FF6F9F4FCCD+3408029]
	GetHandleVerifier [0x00007FF6F9F6743F+3504143]
	GetHandleVerifier [0x00007FF6F9F5B61D+3455469]
	GetHandleVerifier [0x00007FF6F9CDBDCB+835995]
	(No symbol) [0x00007FF6F9B8EB6F]
	(No symbol) [0x00007FF6F9B8A824]
	(No symbol) [0x00007FF6F9B8A9BD]
	(No symbol) [0x00007FF6F9B7A1A9]
	(No symbol) [0x00007FFC75727374]
	RtlUserThreadStart [0x00007FFC76E7CC91+33]

In [37]:
prefix="https://web.tecalliance.net/opticat/qa/parts/"
suffix="/ap-detail"

In [38]:
for s in tqdm(range(8,totpage)):
    print(s, count)
    partcount=len(wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME,"ag-row-position-absolute"))))
    for i in range(partcount):
        df_pa.loc[count,'SupplierPartNumber']=(driver
                                               .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
                                               .find_element(By.CSS_SELECTOR,'[col-id="articleNo"]')
                                               .text
                                               )
        df_pa.loc[count,'Supplier']=(driver
                                     .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
                                     .find_element(By.CSS_SELECTOR,'[col-id="description"]')
                                     .find_elements(By.CLASS_NAME,"font-weight-bold")[0]
                                     .text
                                    )
        df_pa.loc[count,'ProductName']=(driver
                                        .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
                                        .find_element(By.CSS_SELECTOR,'[col-id="description"]')
                                        .find_elements(By.CLASS_NAME,"font-weight-bold")[1]
                                        .text
                                        )
        Atts=(driver
              .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
              .find_element(By.CSS_SELECTOR,'[col-id="description"]')
              .find_elements(By.CLASS_NAME,'article-criteria')
              )
        Attributes=[]
        for attri in Atts:
            CN=attri.text.split(":")[0]
            CV=attri.text.split(":")[1]       
            df_pa.loc[count,CN]=CV
        df_pa.at[count,'Attributes']=Attributes
        df_pa.loc[count,'Status']=(driver
                                   .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
                                   .find_element(By.CSS_SELECTOR,'[col-id="stateText"]')
                                   .text
                                   )
        df_pa.loc[count,'Link']=prefix+(driver
                                        .find_elements(By.CLASS_NAME,"ag-row-position-absolute")[i]
                                        .get_attribute('row-id')
                                        .replace(']-[','/')
                                        .replace("[","")
                                        .replace("]","")
                                        )+suffix
        count=count+1
    clear_output(wait=True)
    driver.find_element(By.CSS_SELECTOR,'[aria-label="Next Page"]').click()
    sleep(10)

NameError: name 'totpage' is not defined

In [139]:
df_pa

,index,Attributes,SupplierPartNumber,Supplier,ProductName,Terminal Type,Terminal Quantity,Connector Gender,Terminal Gender,Mounting Type,...,Length - mm,Number Of Wires,Output Signal Range (V),Technology,Hex Size,Attachment Method,Overall Length (in),Hex Size (in),Hex Size (mm),Overall Length (mm)
0,NaN,[],11022,Bosch,Oxygen Sensor,Pin,4,Female,Female,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,[],11023,Bosch,Oxygen Sensor,Pin,4,Female,Female,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,[],11024,Bosch,Oxygen Sensor,Pin,4,Female,Female,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,[],11027,Bosch,Oxygen Sensor,Threaded,1,Male,Female,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,[],11032,Bosch,Oxygen Sensor,Pin,1,Female,Female,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10118,NaN,[],O21084,Wagner Sensors,Oxygen Sensor,Spade,1,Female,Male,Flange Mount,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10119,NaN,[],O21085,Wagner Sensors,Oxygen Sensor,Spade,2,Male,Male,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10120,NaN,[],O21086,Wagner Sensors,Oxygen Sensor,NaN,NaN,Female,NaN,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10121,NaN,[],O21087,Wagner Sensors,Oxygen Sensor,Spade,4,Male,Male,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10122,NaN,[],O21088,Wagner Sensors,Oxygen Sensor,NaN,NaN,Female,NaN,Threaded,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
with pd.ExcelWriter(Folder+'\\'+'Opticat_Export_'+Type_Name+'.xlsx') as writer:  # doctest: +SKIP
    df_pa.to_excel(writer,index=False, sheet_name='Raw')

# 5. Post Processing Data and Exporting

In [71]:
df['Count']=1

In [72]:
#https://web.tecalliance.net/opticat/qa/parts/CMTQ/V51-08-0001/ap-detail
prefix='https://web.tecalliance.net/opticat/qa/parts/'
mid='''/'''
suffix='/ap-detail'

df['Link']=prefix+df['Sup_Code'].str.split(']-',expand=True)[0].str.replace('[','')+mid+df['Sup_Code'].str.split(']-',expand=True)[1].str.replace('[','').str.replace(']','')+suffix
df['Link']

0       https://web.tecalliance.net/opticat/qa/parts/B...
1       https://web.tecalliance.net/opticat/qa/parts/B...
2       https://web.tecalliance.net/opticat/qa/parts/B...
3       https://web.tecalliance.net/opticat/qa/parts/B...
4       https://web.tecalliance.net/opticat/qa/parts/B...
                              ...
1037                                                  NaN
1038                                                  NaN
1039                                                  NaN
1040                                                  NaN
1041                                                  NaN
Name: Link, Length: 1042, dtype: object

In [73]:
cols=df.columns.to_list()
remove=["Supplier Name",'Part Name','Part No.','Link']
cols=[ele for ele in cols if ele not in remove]
colsort=sorted(cols)
cols=remove+colsort
df = df[cols]
# df=df[df['Part Name']==Type_Name]
df

KeyError: "['Part No.'] not in index"

In [74]:
df_unpivoted=pd.melt(df, id_vars=remove, value_vars=colsort, ignore_index=True,var_name="Attribute").dropna()
df_unpivoted

KeyError: "The following 'id_vars' are not present in the DataFrame: ['Part No.']"

In [82]:
with pd.ExcelWriter(Folder+'\\'+'Opticat_Export_'+Type_Name+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    #df_unpivoted.to_excel(writer,index=False, sheet_name='Attributes')

# 99. Archived Codes

In [ ]:
# To extract the Supplier part number from the list


from tqdm import tqdm

for a in tqdm(range(51,len(List))):
    print(a)    
    search_content=driver.find_element(By.ID,"part-search-input")
    search_content.click()
    search_content.send_keys(List[a])
    driver.find_element(By.CSS_SELECTOR,'[ta-name="search-button"]').click()
    sleep(2)
    PN =driver.find_elements(By.XPATH, "(//div[@class='text-truncate text-primary'])")
    Suppliers =driver.find_elements(By.CSS_SELECTOR, 'p > span.font-weight-bold')       
    for p, s in zip(PN,Suppliers):
        text_content = p.find_element(By.CSS_SELECTOR,'.text-truncate a').text
        print(List[a],":",s.text.strip(),"-",text_content)
    sleep(1)
    driver.find_element(By.CSS_SELECTOR,'[id="menu-home"]').click()
    driver.find_element(By.CSS_SELECTOR,'[id="part-search-input"]').clear()

In [ ]:
        # Param =driver.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
        # #counter=0
        # for index, element2 in enumerate(Param):
        #     # Access specific attributes or text content of the element
        #     criteria_name = element2.find_element(By.CSS_SELECTOR,'.font-weight-bold:first-child').text
        #     value=element2.find_element(By.CSS_SELECTOR,'span:not(.font-weight-bold)').text
        #     # print(criteria_name,'     :      ',value)
        #     if str(df.loc[counter,criteria_name])!='nan':
        #         counter=counter+1
        #         df.loc[counter,criteria_name]=value
        #     else:
        #         df.loc[counter,criteria_name]=value

In [ ]:
#Reference only

from bs4 import BeautifulSoup
from selenium import webdriver

# Wait for the page to load (you might need to adjust the wait time)
driver.implicitly_wait(10)

# Get the page source and create a BeautifulSoup object
page_source = driver.page_source
soup = BeautifulSoup(page_source, 'html.parser')

# Find all elements with the specified class
elements = soup.find_all('div', class_='ag-row')

# Enumerate the elements based on row index and article-criteria
for index, element in enumerate(elements, start=1):
    # Extract row index
    row_index = element['row-index']


    # Extract article-criteria
    article_criterias = element.select('.article-criteria')
    article_criteria_texts = [criteria.get_text(strip=True) for criteria in article_criterias]

    # Print the results (you can modify this based on your needs)

    for criteria_text in article_criteria_texts:
        CN=criteria_text.split(":")[0]
        CV=criteria_text.split(":")[1]        
        

    print("\n")

In [ ]:
Param_Name=[]

for i in range(Totalpage):
    Param =driver.find_elements(By.XPATH, "(//span[@class='article-criteria'])")
    for index, element in enumerate(Param):
        # Access specific attributes or text content of the element
        criteria_name = WebDriverWait(element, 5).until(EC.presence_of_element_located((By.CSS_SELECTOR,".font-weight-bold:first-child"))).text
        Param_Name.append(criteria_name)
    Currentpage=int(driver.find_element(By.XPATH, '//span[@ref="lbCurrent" and @class="ag-paging-number"]').text) 
    print("Page#",Currentpage,"Completed",datetime.datetime.now())
    if Currentpage < Totalpage:
        NextPage=driver.find_element(By.CLASS_NAME, 'ag-icon-next')
        NextPage.click()
        sleep(3)
        i=i+1

if Totalpage>1:
    First_Page=driver.find_element(By.XPATH,'//div[@ref="btFirst"]')
    First_Page.click()

In [ ]:
Param_Name=set(Param_Name)
cols=Param_Name
cols
df = pd.DataFrame(columns=cols)
print(len(cols))
df