# 1. Library calling

In [3]:
import pandas as pd
import warnings
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

# 2. Defining the Product Information and Location

In [6]:
SummaryFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(SummaryFolder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][60]
print(search_text)
Source="Walmart"
IFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Inputs'
OFolder=fr'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\{Source}\Outputs'
filename='_Link.txt'
f=open(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\New folder\Category_List.txt")
Linebraker='int-prod-card'
prefix='https://www.walmart.com//ip/'

                           Product Name
0                         Ignition Coil
1               Windshield Washer Pumps
2                 coupler trailer locks
3   Adjustable Trailer Hitch Ball Mount
4                        Vacuum Cleaner
..                                  ...
56                  Windshield Sunshade
57                     Motor Cycle Bags
58                         Brake Fluids
59                   CAR Vacuum Cleaner
60                 Power Steering Fluid

[61 rows x 1 columns]
Power Steering Fluid

# 3. Setting Webdriver and Website Specific Information

In [7]:
content=f.read()

In [8]:
List=content.split(Linebraker)

In [9]:
print(len(List))

11

# 4. Defining the Dataframe and Extracting the data into the Dataframe

In [26]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
import warnings
from tqdm import tqdm
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")
import os

In [41]:
path= 'C://chromedriver.exe'
driver=webdriver.Chrome()
wait=WebDriverWait(driver, 5)

In [42]:
driver.get('https://uniquefasteners.com/our-catalog/')

In [55]:
cols =['Sl.No'] #,'Review_Mentions'
df = pd.DataFrame(columns=cols)
count=0

In [ ]:
cols =['Sl.No'] #,'Review_Mentions'
df1 = pd.DataFrame(columns=cols)
count1=0

In [56]:
prod_cat1=driver.find_elements(By.CLASS_NAME, "int-card-body")
links=driver.find_elements(By.CSS_SELECTOR, 'div.int-card-body a.int-button')
for i, j in zip(prod_cat1,links):
    df.loc[count,'Product']=i.text.split("\n")[0]
    df.loc[count,'Link']=j.get_attribute('href')
    count= count+1

In [59]:
df

,Sl.No,Product,Link
0,NaN,Aluminum Extrusions,https://uniquefasteners.com/product-category/e...
1,NaN,Cargo Safety Products,https://uniquefasteners.com/product-category/c...
2,NaN,Concrete,https://uniquefasteners.com/product-category/c...
3,NaN,Electricals,https://uniquefasteners.com/product-category/e...
4,NaN,Hose Clamps,https://uniquefasteners.com/product-category/h...
5,NaN,OEM,https://uniquefasteners.com/product-category/oem/
6,NaN,Post Tension,https://uniquefasteners.com/product-category/p...
7,NaN,Shoring,https://uniquefasteners.com/product-category/s...
8,NaN,Trailer Parts,https://uniquefasteners.com/product-category/t...
9,NaN,Wire Mesh,https://uniquefasteners.com/product-category/w...

In [60]:
driver.find_element(By.CLASS_NAME,"elementor-size-sm").get_attribute('href')

'https://uniquefasteners.com/request-a-quote/'

In [64]:
for i in range(len(df['Link'])):
    driver.get(df['Link'][i])
    sleep(3)
    Products=driver.find_elements(By.CLASS_NAME,"elementor-size-default")
    Links=driver.find_elements(By.CLASS_NAME,"elementor-size-sm")
    for p,q in zip(Products,Links):
        df1.loc[count1,"Product_Category"]=df['Product'][i]
        df1.loc[count1,'Product']=p.text
        df1.loc[count1,'Link']=q.get_attribute('href')
        count1=count1+1

In [65]:
df1

,Sl.No,Product_Category,Product,Link
0,NaN,Aluminum Extrusions,ALUMINUM EXTRUSION TRAY PROFILE 1,https://uniquefasteners.com/request-a-quote/
1,NaN,Aluminum Extrusions,ALUMINUM EXTRUSION TRAY PROFILE 2,https://uniquefasteners.com/wp-content/uploads...
2,NaN,Aluminum Extrusions,ALUMINUM EXTRUSION TRIM PROFILE 1,https://uniquefasteners.com/product/aluminum-e...
3,NaN,Aluminum Extrusions,ALUMINUM EXTRUSION TRIM PROFILE 2,https://uniquefasteners.com/product/aluminum-e...
4,NaN,Aluminum Extrusions,ALUMINUM EXTRUSION TRIM PROFILE 3,https://uniquefasteners.com/product/aluminum-e...
...,...,...,...,...
98,NaN,Trailer Parts,Work with Us,https://uniquefasteners.com/product/equalizer-...
99,NaN,Trailer Parts,Contact Us,https://uniquefasteners.com/product/flange-nut/
100,NaN,Wire Mesh,WIRE MESH,https://uniquefasteners.com/request-a-quote/
101,NaN,Wire Mesh,Work with Us,https://uniquefasteners.com/products/
102,NaN,Wire Mesh,Contact Us,https://uniquefasteners.com/about-us/

# 5. Post Processing Data and Exporting

In [39]:
df['Sl.No']=df['Sl.No'].astype(int)
df['List Price']=(df['List Price']).astype(float)
df['Current Price']=(df['Current Price']).astype(float)
df['Rating']=(df['Rating']).astype(float)
df['No of Ratings']=(df['No of Ratings']).astype(float)

In [40]:
cols=["Sl.No",
"Name",
"Product",
"Current Price",
"List Price",
"Rating",
"No of Ratings",
"Links",
"Source"
]
df = df[cols]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 0 to 516
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.No          517 non-null    int32
 1   Name           517 non-null    object
 2   Product        517 non-null    object
 3   Current Price  501 non-null    float64
 4   List Price     501 non-null    float64
 5   Rating         517 non-null    float64
 6   No of Ratings  517 non-null    float64
 7   Links          517 non-null    object
 8   Source         517 non-null    object
dtypes: float64(4), int32(1), object(4)
memory usage: 54.5+ KB

In [25]:
df.to_excel(r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Others\New folder\ProductLinks.xlsx', index=False)

# 99. Archived Codes