In [221]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

In [222]:
folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects'
summaryFile='Scraping_List.txt'
st=pd.read_csv(folder+'\\'+summaryFile)
print(st)
#Define Product to extract
search_text = st['Product Name'][9]
print(search_text)

                                  Product Name
0                                Ignition Coil
1                      Windshield Washer Pumps
2                        coupler trailer locks
3          Adjustable Trailer Hitch Ball Mount
4                               Vacuum Cleaner
5                                   Spark Plug
6              bluetooth Enabled Trailer locks
7                          Power Steering Hose
8   Power Steering Pressure Line Hose Assembly
9                       Washer Fluid Reservoir
10          Hitch Ball Mount with Weight Scale
11                               LED Headlamps
12                             LED flashlights
13                   Fiberglass Tonneau Covers
14                    Aluminium Tonneau Covers
15                     Hardfold Tonneau Covers
16                            Spark Plug Wires
17                 washer fluid reservoir tank
18                   Non Automotive Gas Struts
Washer Fluid Reservoir

In [223]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f:
            if 'Details' in f:
                if search_text in f:
                    file_list.append(f)
file_list

['AmazonProductDetails_Washer Fluid Reservoir.xlsx',
 'AutoZoneProductDetails_Washer Fluid Reservoir.xlsx',
 'CarPartsProductDetails_Washer Fluid Reservoir.xlsx',
 'e-bayProductDetails_Washer Fluid Reservoir.xlsx',
 'Go-PartsProductDetails_Washer Fluid Reservoir.xlsx',
 'Google_SearchProductDetails_Washer Fluid Reservoir.xlsx',
 'HomeDepoProductDetails_Washer Fluid Reservoir.xlsx',
 'NAPAProductDetails_Washer Fluid Reservoir.xlsx',
 'OReilyAutoProductDetails_Washer Fluid Reservoir.xlsx',
 'SummitProductDetails_Washer Fluid Reservoir.xlsx',
 'WalmartProductDetails_Washer Fluid Reservoir.xlsx']

In [224]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [225]:
file_link

['C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\Amazon\\Outputs\\AmazonProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\AutoZone\\Outputs\\AutoZoneProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\CarParts\\Outputs\\CarPartsProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\e-bay\\Outputs\\e-bayProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\Go-Parts\\Outputs\\Go-PartsProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\Google\\Outputs\\Google_SearchProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\HomeDepo\\Outputs\\HomeDepoProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\NAPA\\Outputs\\NAPAProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\OReilyAuto\\Outputs\\OReilyAutoProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\Summit\\Outputs\\SummitProductDetails_Washer Fluid Reservoir.xlsx',
 'C:\\Users\\Vikram.Vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\99_Automation_Projects\\Walmart\\Outputs\\WalmartProductDetails_Washer Fluid Reservoir.xlsx']

In [226]:
df=pd.DataFrame()
for file in file_link:
    df1=pd.read_excel(file)
    df1["SourceName"]=file
    #df['SourceName'] = df['SourceName'].str.replace('C://Users//Vikramv//OneDrive - ZF Friedrichshafen AG//DvS//Dump_Files//Demand_Database_Downloads//', '')
    df1['SourceName'] = df1['SourceName'].str.rsplit('''\\''',1,expand=True)[1]
    df=df.append(df1)

In [227]:
df=df.reset_index()
del df['Sl.No']
del df['index']

In [228]:
cols=df.columns.to_list()
remove=['Source',"SourceName"]
colsr=[ele for ele in cols if ele not in remove]
cols=remove+colsr
print(cols)
df = df[cols]

['Source', 'SourceName', 'Name', 'Product', 'Current Price', 'List Price', 'Rating', 'No of Ratings', 'Short_Details', 'Details', 'Sales_LastMonth', 'Attributes', 'Brand', 'Manufacturer', 'FirstAvailableDate', 'ReviewSummary', 'Sentiment', 'Material', 'ASIN', 'Links', 'Part Number', 'UPC Code']

In [229]:
df["SourceName"].value_counts()

AmazonProductDetails_Washer Fluid Reservoir.xlsx           895
Google_SearchProductDetails_Washer Fluid Reservoir.xlsx    320
SummitProductDetails_Washer Fluid Reservoir.xlsx           293
CarPartsProductDetails_Washer Fluid Reservoir.xlsx         270
Go-PartsProductDetails_Washer Fluid Reservoir.xlsx         253
e-bayProductDetails_Washer Fluid Reservoir.xlsx            239
WalmartProductDetails_Washer Fluid Reservoir.xlsx          195
AutoZoneProductDetails_Washer Fluid Reservoir.xlsx         154
NAPAProductDetails_Washer Fluid Reservoir.xlsx             146
OReilyAutoProductDetails_Washer Fluid Reservoir.xlsx       126
HomeDepoProductDetails_Washer Fluid Reservoir.xlsx         114
Name: SourceName, dtype: int64

In [230]:
dfAtt=df[['Links',"Name",'Attributes','Source']]
dfAtt=dfAtt.dropna()
dfAtt=dfAtt.reset_index()

In [231]:
from ast import literal_eval
for i in range(len(dfAtt)):
    dfAtt.at[i,'Attributes']=literal_eval(dfAtt['Attributes'][i])

In [232]:
dfAtt=dfAtt.explode('Attributes')
dfAtt[['Attributes', 'Value']] = dfAtt['Attributes'].str.split(':',1, expand=True)
dfAtt

,index,Links,Name,Attributes,Source,Value
0,0,https://www.amazon.com/dp/B00HI02OKO,ACDelco GM Original Equipment 25979368 Windshi...,Manufacturer,Amazon,ACDelco
0,0,https://www.amazon.com/dp/B00HI02OKO,ACDelco GM Original Equipment 25979368 Windshi...,Brand,Amazon,ACDelco
0,0,https://www.amazon.com/dp/B00HI02OKO,ACDelco GM Original Equipment 25979368 Windshi...,Model,Amazon,Windshield Washer Pump
0,0,https://www.amazon.com/dp/B00HI02OKO,ACDelco GM Original Equipment 25979368 Windshi...,Item Weight,Amazon,4.3 ounces
0,0,https://www.amazon.com/dp/B00HI02OKO,ACDelco GM Original Equipment 25979368 Windshi...,Product Dimensions,Amazon,6.09 x 3.06 x 3.06 inches
...,...,...,...,...,...,...
2189,2809,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,Summit Racing Part Number,Summit,ADO-19256391
2189,2809,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,UPC,Summit,00195491142855
2189,2809,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,Reservoir Material,Summit,Plastic
2189,2809,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,Reservoir Color,Summit,Natural
2189,2809,https://www.summitracing.com/parts/ado-19256391,ACDelco GM Genuine Parts Windshield Washer Res...,Quantity,Summit,Sold individually.

In [233]:
cols=["Source",
"Name",
"Attributes",
"Value",
"Links"
]
dfAtt = dfAtt[cols]
dfAtt=dfAtt.drop_duplicates()
dfAtt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20670 entries, 0 to 2189
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Source      20670 non-null  object
 1   Name        20670 non-null  object
 2   Attributes  20666 non-null  object
 3   Value       20666 non-null  object
 4   Links       20670 non-null  object
dtypes: object(5)
memory usage: 968.9+ KB

In [234]:
dfAtt

,Source,Name,Attributes,Value,Links
0,Amazon,ACDelco GM Original Equipment 25979368 Windshi...,Manufacturer,ACDelco,https://www.amazon.com/dp/B00HI02OKO
0,Amazon,ACDelco GM Original Equipment 25979368 Windshi...,Brand,ACDelco,https://www.amazon.com/dp/B00HI02OKO
0,Amazon,ACDelco GM Original Equipment 25979368 Windshi...,Model,Windshield Washer Pump,https://www.amazon.com/dp/B00HI02OKO
0,Amazon,ACDelco GM Original Equipment 25979368 Windshi...,Item Weight,4.3 ounces,https://www.amazon.com/dp/B00HI02OKO
0,Amazon,ACDelco GM Original Equipment 25979368 Windshi...,Product Dimensions,6.09 x 3.06 x 3.06 inches,https://www.amazon.com/dp/B00HI02OKO
...,...,...,...,...,...
2189,Summit,ACDelco GM Genuine Parts Windshield Washer Res...,Summit Racing Part Number,ADO-19256391,https://www.summitracing.com/parts/ado-19256391
2189,Summit,ACDelco GM Genuine Parts Windshield Washer Res...,UPC,00195491142855,https://www.summitracing.com/parts/ado-19256391
2189,Summit,ACDelco GM Genuine Parts Windshield Washer Res...,Reservoir Material,Plastic,https://www.summitracing.com/parts/ado-19256391
2189,Summit,ACDelco GM Genuine Parts Windshield Washer Res...,Reservoir Color,Natural,https://www.summitracing.com/parts/ado-19256391
2189,Summit,ACDelco GM Genuine Parts Windshield Washer Res...,Quantity,Sold individually.,https://www.summitracing.com/parts/ado-19256391

In [235]:
summary_df = pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count',columns="Source").reset_index()
totalsummarydf=pd.pivot_table(dfAtt, values='Value', index='Attributes',aggfunc='count').reset_index()
totalsummarydf
summary_df=pd.merge(summary_df,totalsummarydf,on='Attributes')
summary_df
summary_df =summary_df.sort_values(by='Value',ascending=False)
summary_df=summary_df.rename(columns ={'Value':'No. of Products contains this Attribute'})
summary_df

,Attributes,Amazon,CarParts,Go-Parts,HomeDepot,OReilyAuto,Summit,e-bay,No. of Products contains this Attribute
16,Brand,885.0,270.0,253.0,NaN,NaN,293.0,239.0,1940
129,Manufacturer Part Number,882.0,NaN,NaN,NaN,NaN,NaN,228.0,1110
2,ASIN,891.0,NaN,NaN,NaN,NaN,NaN,4.0,895
128,Manufacturer,869.0,NaN,NaN,NaN,NaN,NaN,3.0,872
113,Item Weight,686.0,NaN,NaN,NaN,NaN,NaN,19.0,705
...,...,...,...,...,...,...,...,...,...
162,Note-1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
163,Note-2,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
164,Note-3,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
167,Number Of Items,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
318,texture of material,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1

In [236]:
df['Name_Clean']=df['Name'].str.lower().str.replace("compatible with","").str.replace('w/',"with ")
for i in range(len(df)):
    if "washer " in df['Name_Clean'][i] and "reservoir" in df['Name_Clean'][i]:

        if 'cap'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
                df.loc[i,'Product']="Washer Fluid Reservoir With Cap"
        elif 'grommet'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
            df.loc[i,'Product']="Washer Fluid Reservoir With Grommet"
        elif 'hose'in df['Name_Clean'][i] and 'with' in df['Name_Clean'][i]:
            df.loc[i,'Product']="Washer Fluid Reservoir With Hose"
        elif 'cap 'in df['Name_Clean'][i] and not 'with' in df['Name_Clean'][i]:
            df.loc[i,'Product']="Cap"
        elif 'grommet' in df['Name_Clean'][i]:
            df.loc[i,"Product"]='Grommet'
        elif 'hose'in df['Name_Clean'][i] and not 'with' in df['Name_Clean'][i]:
            df.loc[i,'Product']="Hose"
        elif "washer " in df['Name_Clean'][i] and "reservoir" in df['Name_Clean'][i]:
            df.loc[i,'Product']="Washer Fluid Reservoir"
    elif'pump'in df['Name_Clean'][i]:
        df.loc[i,"Product"]="Washer Pump"
    else:
        df.loc[i,"Product"]="Other Product"

del df['Name_Clean']

In [237]:
df['Product'].value_counts()

Washer Fluid Reservoir             2260
Other Product                       303
Cap                                 206
Washer Fluid Reservoir With Cap     147
Washer Pump                          81
Grommet                               6
Hose                                  2
Name: Product, dtype: int64

In [238]:
OFolder=r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\General - PE Product Innovation\Scraped_Files"

In [239]:
with pd.ExcelWriter(OFolder+'\\'+f'Consol_Scrapped_Data_'+search_text+'.xlsx') as writer:  # doctest: +SKIP
    df.to_excel(writer,index=False, sheet_name='Raw')
    summary_df.to_excel(writer,index=False, sheet_name='Attribute_Summary')
    dfAtt.to_excel(writer,index=False, sheet_name='Attribute_Value')

In [241]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3005 entries, 0 to 3004
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Source              3005 non-null   object
 1   SourceName          3005 non-null   object
 2   Name                3005 non-null   object
 3   Product             3005 non-null   object
 4   Current Price       2919 non-null   float64
 5   List Price          1591 non-null   float64
 6   Rating              2307 non-null   float64
 7   No of Ratings       2078 non-null   float64
 8   Short_Details       451 non-null    object
 9   Details             1819 non-null   object
 10  Sales_LastMonth     1000 non-null   float64
 11  Attributes          2190 non-null   object
 12  Brand               1833 non-null   object
 13  Manufacturer        871 non-null    object
 14  FirstAvailableDate  891 non-null    object
 15  ReviewSummary       150 non-null    object
 16  Sentiment           894 non-null    object
 17  Material            129 non-null    object
 18  ASIN                1049 non-null   object
 19  Links               3005 non-null   object
 20  Part Number         2466 non-null   object
 21  UPC Code            587 non-null    object
dtypes: float64(5), object(17)
memory usage: 516.6+ KB

In [240]:
print(OFolder+'\\'+f'Consol_Scrapped_Data_'+search_text+'.xlsx')

C:\Users\Vikram.Vadhirajan\OneDrive - Trico\General - PE Product Innovation\Scraped_Files\Consol_Scrapped_Data_Washer Fluid Reservoir.xlsx