In [1]:
import pandas as pd

In [8]:
df_BOM=pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\WIP\FeedbackFiles\Hardware_Share_Folder\BOM_Summarized.xlsx",sheet_name="Sheet1")
df_BOM

,Finished Good P/N,Finished Good Description,Raw Material Part Number,Raw Material Description,Type,Qty Per Kit
0,30020623,WASHER,20623,Washers-Flat Copper,PART,10.0
1,30020623,WASHER,A5,Bags-Poly,PACKAGING,1.0
2,30020623,WASHER,MR602-3,.,.,1.0
3,3003246X10,HOLD DOWN PART,3246,"Washer-""C""",PART,10.0
4,3003246X10,HOLD DOWN PART,A5,Bags-Poly,PACKAGING,1.0
...,...,...,...,...,...,...
119543,554Z1098S,Z1098S KIT SET,AZN21,Bags-Poly,PACKAGING,1.0
119544,554Z1099S,Z1099S KIT SET,24354,Clip-Locating,PART,4.0
119545,554Z1099S,Z1099S KIT SET,AZN21,Bags-Poly,PACKAGING,1.0
119546,554Z1913S,Z1913S KIT SET,25333,Clip-Locating,PART,4.0
119547,554Z1913S,Z1913S KIT SET,AZN21,Bags-Poly,PACKAGING,1.0

In [9]:
df_BOM['PartNumber']=df_BOM['Finished Good Description'].astype(str).str.split(' ').str[0]
df_BOM = df_BOM[(df_BOM['PartNumber'] != "nan") & (df_BOM['PartNumber'] != "")].reset_index(drop=True)
df_BOM["Qty Per Kit"]=df_BOM["Qty Per Kit"].astype(int).astype(str)
df_BOM = df_BOM[df_BOM['Raw Material Description'] != "."]
df_BOM

,Finished Good P/N,Finished Good Description,Raw Material Part Number,Raw Material Description,Type,Qty Per Kit,PartNumber
0,57510026,01TK10026 KIT SET,24787G,Clip-Locating,PART,2,01TK10026
1,57510026,01TK10026 KIT SET,24788G,Clip-Locating,PART,2,01TK10026
2,55310026,01TK10026 KIT SET,24787G,Clip-Locating,PART,2,01TK10026
3,55310026,01TK10026 KIT SET,24788G,Clip-Locating,PART,2,01TK10026
4,55310026G2,01TK10026G2 KIT SET,24787H,Clip-Locating,PART,2,01TK10026G2
...,...,...,...,...,...,...,...
115004,554Z1098S,Z1098S KIT SET,AZN21,Bags-Poly,PACKAGING,1,Z1098S
115005,554Z1099S,Z1099S KIT SET,24354,Clip-Locating,PART,4,Z1099S
115006,554Z1099S,Z1099S KIT SET,AZN21,Bags-Poly,PACKAGING,1,Z1099S
115007,554Z1913S,Z1913S KIT SET,25333,Clip-Locating,PART,4,Z1913S
115008,554Z1913S,Z1913S KIT SET,AZN21,Bags-Poly,PACKAGING,1,Z1913S

In [10]:
df_Items=pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\WIP\FeedbackFiles\Hardware_Share_Folder\BOM_Summarized.xlsx",sheet_name="Sheet2")
df_Items = df_Items[df_Items['IBI Numbers'].notna()]
df_Items

     PartNumber IBI Numbers                Part Type
3254     BC500A       H1300      Parking Brake Cable
3266     81668A       H5900  Disc Brake Hardware Kit
3267     81670A       13698  Disc Brake Hardware Kit
3268     81671A       H5899  Disc Brake Hardware Kit
3269     81672A      13694Q  Disc Brake Hardware Kit
...         ...         ...                      ...
7201      82402       16236         Caliper Seal Kit
7204       3620       H2337               Brake Drum
7205       3630       H2348               Brake Drum
7206       3631       H2349               Brake Drum
7207       3638       12577               Brake Drum

[3301 rows x 3 columns]

In [11]:
df_merged = pd.merge(df_BOM, df_Items['IBI Numbers'], left_on='PartNumber', right_on='IBI Numbers', how='inner')
df_merged

,Finished Good P/N,Finished Good Description,Raw Material Part Number,Raw Material Description,Type,Qty Per Kit,PartNumber,IBI Numbers
0,5548175L,12502 SELF-ADJ REPAIR KIT,20942,Levers,PART,1,12502,12502
1,5548175L,12502 SELF-ADJ REPAIR KIT,20946,Tip-Adjusting Screw,PART,1,12502,12502
2,5548175L,12502 SELF-ADJ REPAIR KIT,21713U,Screw-Adjusting Assembly,PART,1,12502,12502
3,5548175L,12502 SELF-ADJ REPAIR KIT,4654,"Washer-""C""",PART,2,12502,12502
4,5548175L,12502 SELF-ADJ REPAIR KIT,5649,"Spring-Return, Single Hook End",PART,1,12502,12502
...,...,...,...,...,...,...,...,...
38761,3009507,H9507-2 (16) BANJO BOLT KIT,TQ5,Miscellaneous,PACKAGING,1,H9507-2,H9507-2
38762,5029507,H9507-2 BANJO BOLT KIT,24467,Washers-Flat Copper,PART,2,H9507-2,H9507-2
38763,5029507,H9507-2 BANJO BOLT KIT,5155,Bolt-Inlet,PART,1,H9507-2,H9507-2
38764,5029507,H9507-2 BANJO BOLT KIT,A33,Bags-Poly,PACKAGING,1,H9507-2,H9507-2
38765,5029507,H9507-2 BANJO BOLT KIT,MS10,Miscellaneous,PACKAGING,1,H9507-2,H9507-2

In [12]:
df_merged["PartQty"]=df_merged['Raw Material Description']+" (" + df_merged["Qty Per Kit"]+ ")"
df_merged=df_merged[df_merged['Type']=="PART"]

In [13]:
df_Cropped=df_merged[['IBI Numbers','PartQty']].drop_duplicates().reset_index(drop=True)
df_final=df_Cropped.groupby('IBI Numbers')['PartQty'].apply(lambda x: '; '.join(x)).reset_index()
df_final

     IBI Numbers                                            PartQty
0          12502  Levers (1); Tip-Adjusting Screw (1); Screw-Adj...
1          12503  Levers (1); Tip-Adjusting Screw (1); Screw-Adj...
2          12504  Levers (1); Tip-Adjusting Screw (1); Washers-F...
3          12505  Levers (1); Tip-Adjusting Screw (1); Washers-F...
4          12517  Tip-Adjusting Screw (1); Levers (1); Cover-Dus...
...          ...                                                ...
2812     H9502-2  Bolt-Inlet (1); Washers-Flat Copper (2); 8708....
2813     H9503-2  Bolt-Inlet (1); Washers-Flat Copper (2); 8708....
2814     H9505-2            Washers-Flat Copper (2); Bolt-Inlet (1)
2815     H9506-2  Bolt-Inlet (1); Washers-Flat Copper (2); 8708....
2816     H9507-2            Washers-Flat Copper (2); Bolt-Inlet (1)

[2817 rows x 2 columns]

In [14]:
output_file = r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\WIP\FeedbackFiles\Hardware_Share_Folder\cleaned_file.xlsx"
with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    df_final.to_excel(writer, sheet_name="Final", index=False)
    df_merged.to_excel(writer, sheet_name="All", index=False)