In [45]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [46]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\28_NAPA_Scorecard'
# OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'

In [47]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f and ('20250722_Core'  in f):

                    file_list.append(f)
file_list

['20250722_Core_Autolite.xlsx',
 '20250722_Core_BPI.xlsx',
 '20250722_Core_Trico.xlsx']

In [48]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))



file_link

['C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\28_NAPA_Scorecard\\20250722_Core_Autolite.xlsx',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\28_NAPA_Scorecard\\20250722_Core_BPI.xlsx',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\28_NAPA_Scorecard\\20250722_Core_Trico.xlsx']

In [72]:
cols=['BrandName', 'Supplier Item Number', 'Attribute', 'Value','Process Step']
df_base=pd.DataFrame(columns=cols)
df_base

Empty DataFrame
Columns: [BrandName, Supplier Item Number, Attribute, Value, Process Step]
Index: []

In [73]:
for i in range(len(file_link)):
       df_1=pd.read_excel(file_link[i])
       df_1=df_1[['BrandName', 
              'Supplier Item Number',
              'Country of Origin', "Interchange Required (Empty='Yes')",
              "OE Interchange Required (Empty ='Yes')", 'Shipping Exclusions?',
              'Salability Restrictions', 'Shipping Exclusions info', 'Harmonize Code',
              'Proper Shipping Name', 'Hazardous Class or Division', 'UN ID Number',
              'Package Group', 'Label Codes', 'Application Item?', 'UNSPSC Code',
              'HQ Line Abbrev', 'Group Code', 'Jobber F.O.Q.', 'Jobber Std Pkg',
              'Product Classification', 'DC Cost (USD)', 'Goldenrod', 'Blue',
              'Master Installer', 'Green', 'Red/Retail (USD)', 'List (USD)',
              'Core Pricing?', 'Per Car Qty', 'Supplier UOM', 'Disposition Code',
              'Date Product Available', 'ORM-D', 'Regulated?', 'Standard Package',
              'Unit Desg', 'ws_UPS', 'Is Sold To Consumer-US',
              'Quantity of Eaches in Package', 'DC Core (USD)', 'List Core (USD)',
              'Jobber Core', 'Core Code', 'Primary Image', 'Prop65 Statement',
              'Prop 65 PDF Coverage', 'SDS PDF Coverage', 'Warranty PDF Coverage',
              'Product Features', 'Features and Benefits', 'Features and Benefits.1',
              'Features and Benefits.2', 'Brand', 'Prop 65?', 'IsUPCRequired?',
              'Single UPC Coverage', 'ReasonForNoUPC?', 'Height (mm)', 'Height (in)',
              'Width (mm)', 'Width (in)', 'Length/Depth (mm)', 'Length/Depth (in)',
              'Weight (kg)', 'Weight (lb)']]
       df_1=df_1.iloc[1:]
       df_1.fillna("FBGsss",inplace=True)
       df_2=pd.melt(df_1,id_vars=['BrandName', 
              'Supplier Item Number'],var_name='Attribute',value_name='Value')
       df_2
       df_2['Process Step']="Smart Sheet,Catalog,Data Distribution"
       df_2['Process Step']=df_2['Process Step'].str.split(',')
       df_2=df_2.explode('Process Step')
       df_base=pd.concat([df_base,df_2],axis=0)

In [74]:
df_base["Value"]=np.where(df_base['Value']=="FBGsss",np.nan,df_base['Value'])

In [75]:
df_base

,BrandName,Supplier Item Number,Attribute,Value,Process Step
0,Autolite,ANPSE1,Country of Origin,NaN,Smart Sheet
0,Autolite,ANPSE1,Country of Origin,NaN,Catalog
0,Autolite,ANPSE1,Country of Origin,NaN,Data Distribution
1,Autolite,NPC6,Country of Origin,NaN,Smart Sheet
1,Autolite,NPC6,Country of Origin,NaN,Catalog
...,...,...,...,...,...
22334,TRICO,SAFECOMBO,Weight (lb),NaN,Catalog
22334,TRICO,SAFECOMBO,Weight (lb),NaN,Data Distribution
22335,TRICO,3CASEREBATE,Weight (lb),NaN,Smart Sheet
22335,TRICO,3CASEREBATE,Weight (lb),NaN,Catalog
22335,TRICO,3CASEREBATE,Weight (lb),NaN,Data Distribution