In [10]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [11]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\PDM\excel Files'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'

In [12]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f:

                    file_list.append(f)
file_list

['EXCEL_SEGMENTS_FULL_BBDW_ASC_20250804_101939.xlsx',
 'EXCEL_SEGMENTS_FULL_BBFX_Balkamp_20250804_102252.xlsx',
 'EXCEL_SEGMENTS_FULL_BBRH_Motorcraft_20250804_105146.xlsx',
 'EXCEL_SEGMENTS_FULL_BBRQ_Autolite_20250804_103511.xlsx',
 'EXCEL_SEGMENTS_FULL_BBZN_Strong Arm_20250804_110057.xlsx',
 'EXCEL_SEGMENTS_FULL_BCQS_Carter_20250804_122952.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250804_101448.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250804_101527.xlsx',
 'EXCEL_SEGMENTS_FULL_BCVC_ACDelco_20250804_101627.xlsx',
 'EXCEL_SEGMENTS_FULL_CFHH_Duralast_20250804_102421.xlsx',
 'EXCEL_SEGMENTS_FULL_CFHH_Duralast_20250804_104421.xlsx',
 'EXCEL_SEGMENTS_FULL_CNHS_Magneti Marelli_20250804_104654.xlsx',
 'EXCEL_SEGMENTS_FULL_CNRD_CARDONE New_20250804_104048.xlsx',
 'EXCEL_SEGMENTS_FULL_CPCX_CARDONE Reman_20250804_112751.xlsx',
 'EXCEL_SEGMENTS_FULL_FBBF_LubFix_20250804_122305.xlsx',
 'EXCEL_SEGMENTS_FULL_FLJL_Champ filters_20250804_104243.xlsx',
 'EXCEL_SEGMENTS_FULL_FNTH_Mighty Lift_20250804_105051.xlsx',
 'EXCEL_SEGMENTS_FULL_FXLT_Carquest Premium Water Pumps_20250804_103623.xlsx',
 'EXCEL_SEGMENTS_FULL_FXNK_Carquest Premium Fuel Pumps_20250804_104744.xlsx',
 'EXCEL_SEGMENTS_FULL_FXPS_CARDONE Ultra_20250804_103610.xlsx',
 'EXCEL_SEGMENTS_FULL_GFDR_NAPA Fuel Pumps_20250804_110150.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWK_Import Direct Fuel Pumps_20250804_104554.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWM_Import Direct Timing Kits and Water Pumps_20250804_104611.xlsx',
 'EXCEL_SEGMENTS_FULL_GQWN_Import Direct Water Pumps_20250804_104649.xlsx',
 'EXCEL_SEGMENTS_FULL_GQXB_MasterPro Fuel Pumps_20250804_104656.xlsx',
 'EXCEL_SEGMENTS_FULL_HFVZ_Autolite Iridium XP - Archived_20250804_101846.xlsx',
 'EXCEL_SEGMENTS_FULL_HNTB_Driveworks Water Pumps_20250804_104247.xlsx',
 'EXCEL_SEGMENTS_FULL_HTTT_TruGrade_20250804_111051.xlsx',
 'EXCEL_SEGMENTS_FULL_HWMS_AVM Industries_20250804_102326.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLR_Autolite Ignition - Archived_20250804_102537.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLS_Autolite Copper_20250804_101657.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLT_Autolite Double Platinum_20250804_101716.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLV_Autolite Glow Plugs_20250804_101734.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLW_Autolite Platinum_20250804_101932.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLX_Autolite Racing_20250804_102015.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLY_Autolite Xtreme Sport_20250804_102041.xlsx',
 'EXCEL_SEGMENTS_FULL_HXLZ_Autolite Xtreme Start_20250804_102100.xlsx',
 'EXCEL_SEGMENTS_FULL_HXMB_Autolite Iridium Ultra_20250804_101819.xlsx',
 'EXCEL_SEGMENTS_FULL_HXTZ_Michelin Engine Parts_20250804_104954.xlsx',
 'EXCEL_SEGMENTS_FULL_HYJT_Carter Water Pumps_20250804_114057.xlsx',
 'EXCEL_SEGMENTS_FULL_HYTZ_Carter Premium Water Pumps_20250804_104101.xlsx',
 'EXCEL_SEGMENTS_FULL_HYVJ_Airtex Fuel Pumps_20250804_101918.xlsx',
 'EXCEL_SEGMENTS_FULL_OE05_Motor OE (OLD)_20250804_113125.xlsx',
 'EXCEL_SEGMENTS_FULL_T00718_Mex Mighty Lift_20250804_104832.xlsx',
 'EXCEL_SEGMENTS_FULL_T02616_Base Spark Plugs_20250804_102404.xlsx',
 'EXCEL_SEGMENTS_FULL_T02624_Cardone OReilly_20250804_112306.xlsx',
 'EXCEL_SEGMENTS_FULL_T02667_Cardone Advance_20250804_105751.xlsx',
 'EXCEL_SEGMENTS_FULL_T02668_Cardone AutoZone_20250804_105928.xlsx',
 'EXCEL_SEGMENTS_FULL_T02669_Cardone GM_AC Delco_20250804_103219.xlsx',
 'EXCEL_SEGMENTS_FULL_T02670_Cardone Goodyear_20250804_102545.xlsx',
 'EXCEL_SEGMENTS_FULL_T02723_Cardone Carquest_20250804_102410.xlsx',
 'EXCEL_SEGMENTS_FULL_T02812_Cardone NAPA US_20250804_105820.xlsx',
 'EXCEL_SEGMENTS_FULL_T02813_Cardone NAPA Canada_20250804_105956.xlsx',
 'EXCEL_SEGMENTS_FULL_T02960_Autolite Othermotive_20250804_101942.xlsx',
 'EXCEL_SEGMENTS_FULL_T083_MEX Autolite_20250804_104920.xlsx']

In [13]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [14]:
len(file_link)

55

In [15]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\Standard\\Import files\\PDM\\excel Files\\EXCEL_SEGMENTS_FULL_BBFX_Balkamp_20250804_102252.xlsx'

In [16]:
cols=['Brand', 'PartNumber', 'PartTerminologyName',  'PAName', 'Value']
df_Match = pd.DataFrame(columns=cols)
df_Match

Empty DataFrame
Columns: [Brand, PartNumber, PartTerminologyName, PAName, Value]
Index: []

In [17]:
file_link[1].split("FULL_")[1].split("_20")[0]

'BBFX_Balkamp'

In [18]:
for i in range(len(file_link)):
    # workbook=openpyxl.load_workbook(file_link[i])
    BrandName= file_link[i].split("FULL_")[1].split("_20")[0]
    print(i,BrandName)
    df_item=pd.read_excel(file_link[i],sheet_name="Items")
    df_Attr=pd.read_excel(file_link[i],sheet_name="PartAttributes", keep_default_na=False, na_values=[''])
    df_item=df_item.astype(str)
    df_Attr=df_Attr.astype(str)
    df=df_Attr.merge(df_item,how="inner")
    df.rename(columns={'Attribute': "PAName",'PartType':'PartTerminologyName','AttributeValue':'Value'}, inplace=True)
    ListColumns=['Brand', 'PartNumber', 'PartTerminologyName',  'PAName', 'Value']
    df=df[ListColumns]
    df=df.drop_duplicates().reset_index(drop=True)
    df['Brand']=BrandName
    df_Match=pd.concat([df_Match,df])

0 BBDW_ASC
1 BBFX_Balkamp
2 BBRH_Motorcraft
3 BBRQ_Autolite
4 BBZN_Strong Arm
5 BCQS_Carter
6 BCVC_ACDelco
7 BCVC_ACDelco
8 BCVC_ACDelco
9 CFHH_Duralast
10 CFHH_Duralast
11 CNHS_Magneti Marelli
12 CNRD_CARDONE New
13 CPCX_CARDONE Reman
14 FBBF_LubFix
15 FLJL_Champ filters
16 FNTH_Mighty Lift
17 FXLT_Carquest Premium Water Pumps
18 FXNK_Carquest Premium Fuel Pumps
19 FXPS_CARDONE Ultra
20 GFDR_NAPA Fuel Pumps
21 GQWK_Import Direct Fuel Pumps
22 GQWM_Import Direct Timing Kits and Water Pumps
23 GQWN_Import Direct Water Pumps
24 GQXB_MasterPro Fuel Pumps
25 HFVZ_Autolite Iridium XP - Archived
26 HNTB_Driveworks Water Pumps
27 HTTT_TruGrade
28 HWMS_AVM Industries
29 HXLR_Autolite Ignition - Archived
30 HXLS_Autolite Copper
31 HXLT_Autolite Double Platinum
32 HXLV_Autolite Glow Plugs
33 HXLW_Autolite Platinum
34 HXLX_Autolite Racing
35 HXLY_Autolite Xtreme Sport
36 HXLZ_Autolite Xtreme Start
37 HXMB_Autolite Iridium Ultra
38 HXTZ_Michelin Engine Parts
39 HYJT_Carter Water Pumps
40 HYTZ_Carter Premium Water Pumps
41 HYVJ_Airtex Fuel Pumps
42 OE05_Motor OE (OLD)
43 T00718_Mex Mighty Lift
44 T02616_Base Spark Plugs
45 T02624_Cardone OReilly
46 T02667_Cardone Advance
47 T02668_Cardone AutoZone
48 T02669_Cardone GM_AC Delco
49 T02670_Cardone Goodyear
50 T02723_Cardone Carquest
51 T02812_Cardone NAPA US
52 T02813_Cardone NAPA Canada
53 T02960_Autolite Othermotive
54 T083_MEX Autolite

In [19]:
df_Match['Brand'].unique()

array(['BBDW_ASC', 'BBFX_Balkamp', 'BBRQ_Autolite', 'BBZN_Strong Arm',
       'BCQS_Carter', 'BCVC_ACDelco', 'CFHH_Duralast',
       'CNHS_Magneti Marelli', 'CNRD_CARDONE New', 'CPCX_CARDONE Reman',
       'FNTH_Mighty Lift', 'FXLT_Carquest Premium Water Pumps',
       'FXNK_Carquest Premium Fuel Pumps', 'FXPS_CARDONE Ultra',
       'GFDR_NAPA Fuel Pumps', 'GQWK_Import Direct Fuel Pumps',
       'GQWN_Import Direct Water Pumps', 'GQXB_MasterPro Fuel Pumps',
       'HFVZ_Autolite Iridium XP - Archived',
       'HNTB_Driveworks Water Pumps', 'HTTT_TruGrade',
       'HWMS_AVM Industries', 'HXLR_Autolite Ignition - Archived',
       'HXLS_Autolite Copper', 'HXLT_Autolite Double Platinum',
       'HXLV_Autolite Glow Plugs', 'HXLW_Autolite Platinum',
       'HXLX_Autolite Racing', 'HXLY_Autolite Xtreme Sport',
       'HXLZ_Autolite Xtreme Start', 'HXMB_Autolite Iridium Ultra',
       'HYJT_Carter Water Pumps', 'HYTZ_Carter Premium Water Pumps',
       'HYVJ_Airtex Fuel Pumps', 'OE05_Motor OE (OLD)',
       'T00718_Mex Mighty Lift', 'T02624_Cardone OReilly',
       'T02667_Cardone Advance', 'T02668_Cardone AutoZone',
       'T02669_Cardone GM_AC Delco', 'T02670_Cardone Goodyear',
       'T02723_Cardone Carquest', 'T02812_Cardone NAPA US',
       'T02813_Cardone NAPA Canada', 'T083_MEX Autolite'], dtype=object)

In [20]:
df_Match

,Brand,PartNumber,PartTerminologyName,PAName,Value
0,BBDW_ASC,WP-1000,Engine Water Pump,Fan Clutch Included,No
1,BBDW_ASC,WP-1000,Engine Water Pump,Housing Material,Cast Iron
2,BBDW_ASC,WP-1000,Engine Water Pump,Hub Height,113.03
3,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Quantity,4
4,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Thread Size,M6X1.00
...,...,...,...,...,...
6901,T083_MEX Autolite,UR-8,Wiper Blade,SMALL ENGINE,N
6902,T083_MEX Autolite,UR-8,Wiper Blade,SNOWMOBILE,N
6903,T083_MEX Autolite,UR-8,Wiper Blade,TRANSMISSION SPECIFIC,N
6904,T083_MEX Autolite,UR-8,Wiper Blade,Design,For heavy rains
6905,T083_MEX Autolite,UR-8,Wiper Blade,Frame Type,Beam

In [21]:
df_Filter=pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\Active_Part_List_BrandMap.xlsx",sheet_name="BrandMap")
df_Filter = df_Filter[df_Filter['Status'] != "Inactive"]

In [22]:
merge_DF=pd.merge(df_Match,df_Filter,how="inner",  right_on=["BrandName"], left_on=["Brand"],suffixes=('_match', '_filter'))
merge_DF

,Brand_match,PartNumber,PartTerminologyName,PAName,Value,BrandName,Brand_filter,Product Group,Source,Status,Parent-Child- Customer Brand
0,BBDW_ASC,WP-1000,Engine Water Pump,Fan Clutch Included,No,BBDW_ASC,ASC,Repair,PDM,Active,Parent
1,BBDW_ASC,WP-1000,Engine Water Pump,Housing Material,Cast Iron,BBDW_ASC,ASC,Repair,PDM,Active,Parent
2,BBDW_ASC,WP-1000,Engine Water Pump,Hub Height,113.03,BBDW_ASC,ASC,Repair,PDM,Active,Parent
3,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Quantity,4,BBDW_ASC,ASC,Repair,PDM,Active,Parent
4,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Thread Size,M6X1.00,BBDW_ASC,ASC,Repair,PDM,Active,Parent
...,...,...,...,...,...,...,...,...,...,...,...
1939106,T00718_Mex Mighty Lift,PG5021R,Liftgate Lift Support,Universal Or Specific Fit,Specific,T00718_Mex Mighty Lift,Mighty Lift,Repair,PDM,Active,Child
1939107,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Internal Rebound Spring,No,T00718_Mex Mighty Lift,Mighty Lift,Repair,PDM,Active,Child
1939108,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Outer Cylinder Color,Black,T00718_Mex Mighty Lift,Mighty Lift,Repair,PDM,Active,Child
1939109,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Outer Cylinder Material,Steel,T00718_Mex Mighty Lift,Mighty Lift,Repair,PDM,Active,Child
1939110,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Universal Or Specific Fit,Specific,T00718_Mex Mighty Lift,Mighty Lift,Repair,PDM,Active,Child

In [23]:
merge_DF=merge_DF[['BrandName', 'PartNumber', 'PartTerminologyName',  'PAName', 'Value']]
merge_DF.rename(columns={'BrandName': 'Brand'}, inplace=True)
merge_DF = merge_DF.dropna(subset=['PartTerminologyName'])
merge_DF

,Brand,PartNumber,PartTerminologyName,PAName,Value
0,BBDW_ASC,WP-1000,Engine Water Pump,Fan Clutch Included,No
1,BBDW_ASC,WP-1000,Engine Water Pump,Housing Material,Cast Iron
2,BBDW_ASC,WP-1000,Engine Water Pump,Hub Height,113.03
3,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Quantity,4
4,BBDW_ASC,WP-1000,Engine Water Pump,Hub Hole Thread Size,M6X1.00
...,...,...,...,...,...
1939106,T00718_Mex Mighty Lift,PG5021R,Liftgate Lift Support,Universal Or Specific Fit,Specific
1939107,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Internal Rebound Spring,No
1939108,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Outer Cylinder Color,Black
1939109,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Outer Cylinder Material,Steel
1939110,T00718_Mex Mighty Lift,PG5022,Liftgate Lift Support,Universal Or Specific Fit,Specific

In [24]:
df_Attributes=merge_DF[['Brand', 'PartTerminologyName',  'PAName']].drop_duplicates().reset_index(drop=True)

In [25]:
chunk_size=1000000
# Create a list of DataFrames by splitting the original DataFrame
df_chunks = [merge_DF.iloc[i:i + chunk_size] for i in range(0, len(merge_DF), chunk_size)]

In [26]:
with pd.ExcelWriter(OFolder+'\\'+'PDM_Attribute_List.xlsx') as writer:  # doctest: +SKIP
    for i, chunk in enumerate(df_chunks):
        sheet_name = f"Chunk_{i+1}"  # Naming each sheet dynamically
        chunk.to_excel(writer, sheet_name=sheet_name, index=False)
    df_Attributes.to_excel(writer,index=False, sheet_name='FBG_Attributes')