## File Import

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from IPython.display import clear_output

In [2]:
file=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\FBG_SKU_Attributes.csv"

In [3]:
df=pd.read_csv(file, encoding='utf-8', low_memory=False, keep_default_na=False, na_values=[''])
# df=df.drop_duplicates()
# df = df[df['PartTerminologyName'].notna()]
# df

In [4]:
df

,Product Group,Source,BrandName,Brand,PartNumber,PartTerminologyName,Status,PAName,Attribute_Type,Value,AC_AttributeCount,Attribute_Value,Key,Parent-Child- Customer Brand
0,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Casting Number,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpCasting Number,Parent
1,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Fan Clutch Included,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpFan Clutch Included,Parent
2,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Grade Type,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpGrade Type,Parent
3,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Housing Material,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpHousing Material,Parent
4,Repair,PDM,BBDW_ASC,ASC,EWP1220,Engine Water Pump,Active,Hub Height,Autocare_Attribute,NaN,1.0,0.0,EWP1220Engine Water PumpHub Height,Parent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428054,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Lens Width,FBG_Attribute,5.5,0.0,0.0,8261605Agriculture LightLens Width,Child
11428055,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65,FBG_Attribute,Yes,0.0,0.0,8261605Agriculture LightProp 65,Child
11428056,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65 Chemical,FBG_Attribute,DEHP,0.0,0.0,8261605Agriculture LightProp 65 Chemical,Child
11428057,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,Prop 65 Warning,FBG_Attribute,WARNING: Cancer and Reproductive Harm – www.p6...,0.0,0.0,8261605Agriculture LightProp 65 Warning,Child
11428058,Towing,Hitch Pro,Wesbar,Wesbar,8261605,Agriculture Light,Active,NaN,FBG_Attribute,NaN,0.0,0.0,8261605Agriculture Lightnan,Child

In [5]:
df['FileName']=df.Brand+"_"+df.PartTerminologyName

In [6]:
df['Product Group'].unique()

array(['Repair', 'Brakes', 'Towing', 'Steering/ Electronics', 'Filter',
       'Lighting', 'Wipers'], dtype=object)

In [7]:
df = df[df['Parent-Child- Customer Brand'] == "Parent"]

In [8]:
output_location=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\FBG_Data\Phase-2\FBG_Circulation"

In [10]:
df['Product Group'].unique()

array(['Repair', 'Brakes', 'Steering/ Electronics', 'Filter', 'Towing',
       'Wipers'], dtype=object)

In [13]:
import re
#filtering only Required Product Group
Type="Brakes"
df_IN=df[df['Product Group']==Type]
Filenames=df_IN.FileName.unique()
length=len(Filenames)
for i in tqdm(range (length)):
    BrandName=df[(df.FileName==Filenames[i])]['BrandName'].mode()[0]
    print(i, Filenames[i])
    # and separating Autocare Attributes and FBG Attributes
    df1=df_IN[(df_IN.FileName==Filenames[i]) & (df_IN['Attribute_Type']=="Autocare_Attribute")]
    df1=df1.drop(columns=['FileName'])    
    df1=df1[['PartNumber','PartTerminologyName', 'PAName', 'Value']]
    grouped=df1.groupby(['PartNumber','PartTerminologyName', 'PAName'])['Value'].agg(lambda x: list(x) if len(x) > 1 else x.iloc[0])
    # Unstack to get pivot-style format
    pivot_df_AC = grouped.unstack(fill_value=None)
    df2=df_IN[(df_IN.FileName==Filenames[i]) & (df_IN['Attribute_Type']!="Autocare_Attribute")]
    df2=df2.drop(columns=['FileName'])
    df2=df2[['PartNumber','PartTerminologyName', 'PAName', 'Value']]
    grouped=df2.groupby(['PartNumber','PartTerminologyName', 'PAName'])['Value'].agg(lambda x: list(x) if len(x) > 1 else x.iloc[0])
    # Unstack to get pivot-style format
    pivot_df_FBG= grouped.unstack(fill_value=None)
    Filename=re.sub(r"[^a-zA-Z0-9\s_]", "", Filenames[i].split("_")[1])
    with pd.ExcelWriter(rf"{output_location}\{Type}\\"+BrandName+"_"+Filename.replace(" ","")+".xlsx") as writer:
        pivot_df_AC.to_excel(writer, sheet_name="Autocare", index=True, engine='openpyxl')
        pivot_df_FBG.to_excel(writer, sheet_name="FBG", index=True, engine='openpyxl')
    #print("File FBG_SKU_Attributes_"+Filenames[i]+".xlsx created successfully")
    clear_output(wait=True)

100%|██████████| 121/121 [05:10<00:00,  2.57s/it]

In [ ]:
df1

Empty DataFrame
Columns: [Product Group, Source, BrandName, Brand, PartNumber, PartTerminologyName, Status, PAName, Attribute_Type, Value, AC_AttributeCount, Attribute_Value, Key, Parent-Child- Customer Brand]
Index: []

In [40]:
df_IN=df[df['Product Group']==Type]
len(df_IN.PartTerminologyName.unique())

73

In [ ]:
Brand_Filenames=df.Brand.unique()
print(len(Brand_Filenames))
for i in range (len(Brand_Filenames)):
    print(i)
    df1=df[df.Brand==Brand_Filenames[i]]
    df1=df1.drop(columns=['Brand'])
    ProductNames=df1.PartTerminologyName.unique()
    FileName=rf"{output_location}\FBG_SKU_Attributes_"+Brand_Filenames[i]+".xlsx"
    # df1=df1[['PartNumber', 'PAName', 'Value']]
        # Create Excel writer per region
    with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
        for j in range(len(ProductNames)):
            df2=df1[df1.PartTerminologyName==ProductNames[j]]
            # df2=df2[['PartNumber', 'PAName', 'Value']]
            grouped=df2.groupby(['PartTerminologyName','PartNumber', 'PAName'])['Value'].agg(lambda x: list(x) if len(x) > 1 else x.iloc[0])
            # Unstack to get pivot-style format
            pivot_df = grouped.unstack(fill_value=None)
            print("Processing Product:", ProductNames[j])
            ProductNames[j]=ProductNames[j].replace('/', '_').replace(' ', "")
            if len(ProductNames[j]) > 31:
                ProductNames[j] = ProductNames[j][:31]
            pivot_df.to_excel(writer, sheet_name=str(ProductNames[j]), index=True)
    print("File FBG_SKU_Attributes_"+Brand_Filenames[i]+".xlsx created successfully")
    clear_output(wait=True)

Processing Product: Engine Water Pump
Processing Product: Engine Auxiliary Water Pump
Processing Product: Drive Motor Inverter Cooler Water Pump
Processing Product: Electric Engine Water Pump
Processing Product: Engine Water Pump Pulley Bolt Cover
Processing Product: Engine Water Pump Adapter
Processing Product: Accessory Drive Belt Idler Assembly
Processing Product: Engine Timing Belt Kit with Water Pump
File FBG_SKU_Attributes_ASC.xlsx created successfully
Processing Product: Trunk Lid Lift Support
Processing Product: Hood Lift Support
Processing Product: Liftgate Lift Support
Processing Product: Multi-Purpose Lift Support
Processing Product: Convertible Top Cover Lift Support
Processing Product: Seat Adjustment Strut
Processing Product: Door Lift Support
Processing Product: Back Glass Lift Support
Processing Product: Tailgate Lift Support
Processing Product: Cargo Van Access Panel Lift Support
Processing Product: Truck Bed Storage Box Lid Lift Support
Processing Product: Top Stowage Compartment Lift Support
Processing Product: Hatch Lift Support Set
Processing Product: Multi-Purpose Lift Support Stud
Processing Product: Multi-Purpose Lift Support Bracket
File FBG_SKU_Attributes_AVM Industries.xlsx created successfully
Processing Product: Mechanical Fuel Pump
Processing Product: Fuel Pump Bowl
Processing Product: Fuel Sender and Hanger Assembly
Processing Product: Fuel Pump Hanger
Processing Product: Fuel Pump Check Valve
Processing Product: Direct Injection High Pressure Fuel Pump
Processing Product: Electric Fuel Pump
Processing Product: Fuel Pump and Strainer Set
Processing Product: Fuel Pump Hanger Assembly
Processing Product: Fuel Pump Module Assembly
Processing Product: Fuel Tank Sender Assembly
Processing Product: Fuel Pump Reservoir
Processing Product: Fuel Tank and Pump Assembly Combination
Processing Product: Fuel Filter Housing
Processing Product: Fuel Pump Bowl Gasket
Processing Product: Fuel Pump Mounting Gasket
Processing Product: Fuel Pump Spacer
Processing Product: Fuel Pump Pulsator
Processing Product: Fuel Pump Strainer
Processing Product: Fuel Tank Pressure Sensor
Processing Product: Fuel Filter
Processing Product: Fuel Line Seal Ring
Processing Product: Fuel Tank Lock Ring
Processing Product: Fuel Level Sensor
Processing Product: Engine Oil Pressure Sensor
Processing Product: Fuel Pump Push Rod
Processing Product: Fuel Pump Tank Seal
Processing Product: Fuel Pump Wiring Harness
File FBG_SKU_Attributes_Airtex.xlsx created successfully
Processing Product: Spark Plug
Processing Product: Diesel Glow Plug
Processing Product: Ignition Coil
File FBG_SKU_Attributes_Autolite.xlsx created successfully
Processing Product: Brake Master Cylinder Repair Kit
Processing Product: Drum Brake Wheel Cylinder Kit
Processing Product: Disc Brake Caliper Seal Kit
Processing Product: Banjo Washer
Processing Product: Parking Brake Hardware Kit
Processing Product: Disc Brake Caliper Bushing
Processing Product: Brake Hydraulic Hose
Processing Product: Brake Bleeder Screw
Processing Product: Drum Brake Shoe Hold Down Spring
Processing Product: Disc Brake Caliper Support Spring
Processing Product: Disc Brake Guide Pin Retaining Clip
Processing Product: Disc Brake Hardware Kit
Processing Product: Parking Brake Cable
Processing Product: Brake Hydraulic Banjo Bolt
Processing Product: Brake and Clutch Master Cylinder Assembly
Processing Product: Clutch Hydraulic Hose
Processing Product: Drum Brake Shoe Return Spring Kit
Processing Product: Drum Brake Shoe Spring Hold Down Pin
Processing Product: Parking Brake Strut Spring
Processing Product: Drum Brake Adjusting Screw Spring
Processing Product: Drum Brake Adjusting Screw Assembly
Processing Product: Drum Brake Adjusting Lever Return Spring
Processing Product: Drum Brake Adjusting Override Spring
Processing Product: Parking Brake Lever Pivot Pin
Processing Product: Drum Brake Adjusting Cam Stud
Processing Product: Drum Brake Shoe Anchor Spring Lock
Processing Product: Drum Brake Shoe Anchor Pin
Processing Product: Disc Brake Caliper Bolt Kit
Processing Product: Disc Brake Anti-Rattle Clip
Processing Product: Disc Brake Caliper Bracket Mounting Bolt
Processing Product: Disc Brake Caliper Bolt
Processing Product: Disc Brake Caliper Support Key Retaining Bolt
Processing Product: Disc Brake Caliper Support Key
Processing Product: Disc Brake Caliper Pin Boot Kit
Processing Product: Disc Brake Pad Drag Reduction Clip
Processing Product: Disc Brake Low Frequency Noise Damper
Processing Product: Disc Brake Caliper Piston
Processing Product: Disc Brake Caliper Pin Kit
Processing Product: Wheel Lug Stud
Processing Product: Drum Brake Wheel Cylinder
Processing Product: Brake Master Cylinder
Processing Product: Drum Brake Shoe Hold Down Kit
Processing Product: Disc Brake Kit
Processing Product: Disc Brake Caliper
Processing Product: Disc Brake Caliper Pin
Processing Product: Promotional Item
Processing Product: Drum Brake Hardware Kit
Processing Product: Wheel Bearing and Hub Assembly
Processing Product: Axle Bearing and Hub Assembly Repair Kit
Processing Product: Trailer Brake Shoe Set
Processing Product: Trailer Brake Magnet
Processing Product: Brake Backing Plate
Processing Product: Disc Brake Rotor
Processing Product: Disc Brake Caliper Guide Bushing Kit
Processing Product: Disc Brake Rotor and Hub Assembly
Processing Product: Axle Hub
Processing Product: Brake Drum
Processing Product: Wheel Hub Washer
Processing Product: Disc Brake Rotor Shim
Processing Product: Disc Brake Pad Set
Processing Product: Disc Brake Caliper Set
Processing Product: Parking Brake Disc Brake Pad Set
Processing Product: Disc Brake Pad Wear Sensor
Processing Product: Drum Brake Shoe
Processing Product: Parking Brake Shoe
File FBG_SKU_Attributes_BPI.xlsx created successfully
Processing Product: Trailer Jack Mount
Processing Product: Trailer Jack Crank
Processing Product: Trailer Jack
Processing Product: Trailer Jack Foot
Processing Product: Trailer Jack Gearbox
Processing Product: Coupler Adj. Tube
Processing Product: Coupler Outer Tube
Processing Product: Trailer Coupler
Processing Product: Gooseneck Coupler
Processing Product: Lunette Ring
Processing Product: Trailer Jack Bolt
Processing Product: Trailer Jack Wheel
Processing Product: Coupler Plate
Processing Product: Trailer Jack Pin
Processing Product: Trailer Jack Gear
Processing Product: Fifth Wheel Jack
Processing Product: Trailer Powered Jack
Processing Product: Trailer Jack Cover
Processing Product: Trailer Jack Level
Processing Product: Trailer Jack Light
Processing Product: Trailer Jack Screw
Processing Product: Trailer Jack Bearing
Processing Product: Swivel Trailer Mount
Processing Product: Jack Stowage Mount
Processing Product: Trailer Jack Retaini
Processing Product: Trailer Jack Bracket
Processing Product: Trailer Jack Caster
Processing Product: Trailer Jack Knob
Processing Product: Trailer Jack Leg
Processing Product: Pull Pin Assembly
Processing Product: Trailer Jack Clip
Processing Product: Trailer Jack End Cap
Processing Product: Coupler Cap Spring
Processing Product: Coupler Locking Pin
Processing Product: Trailer Jack Remote
Processing Product: Jack Contactor Kit
Processing Product: 3 Pin Connector
Processing Product: Channel Adapter Kit
Processing Product: Trailer Jack Adapter
Processing Product: DC Electric Winch
Processing Product: Hawse Fairlead
Processing Product: Electric Winch
Processing Product: Wireless Remote
Processing Product: Tie Rod Kit
Processing Product: Roller Fairlead
Processing Product: Winch Connector
Processing Product: Trailer Hitch Lock
Processing Product: Trailer Coupler Lock
Processing Product: Ratchet Jack
Processing Product: Farm Jack
Processing Product: Farm Jack Foot Plate
Processing Product: Jack Handle Holder
Processing Product: Farm Jack Repair Kit
Processing Product: Farm Jack Handle
Processing Product: Trailer Jack Handle
Processing Product: Coupler Channel
Processing Product: Trailer Jack Shaft
Processing Product: Safety Chain Clip
Processing Product: Trailer Jack Ring
Processing Product: Coupler Pin/Lanyard
Processing Product: Trailer Jack Plate
File FBG_SKU_Attributes_BULLDOG.xlsx created successfully
Processing Product: Hood Lift Support
Processing Product: Liftgate Lift Support
Processing Product: Trunk Lid Lift Support
Processing Product: Back Glass Lift Support
Processing Product: Tailgate Lift Support
Processing Product: Door Lift Support
Processing Product: Multi-Purpose Lift Support
Processing Product: Seat Adjustment Strut
Processing Product: Cargo Van Access Panel Lift Support
Processing Product: Truck Bed Storage Box Lid Lift Support
Processing Product: Convertible Top Cover Lift Support
Processing Product: Top Stowage Compartment Lift Support
Processing Product: Multi-Purpose Lift Support Stud
Processing Product: Multi-Purpose Lift Support Bracket
File FBG_SKU_Attributes_Balkamp.xlsx created successfully
Processing Product: Side Marker Light
Processing Product: Trailer Light Lens
Processing Product: Trailer Light Gasket
Processing Product: License Plate Light
Processing Product: License Bracket
Processing Product: Interior Light
Processing Product: Trailer Porch Light
Processing Product: Trailer Taillight
Processing Product: Taillight Bezel
Processing Product: Taillight Lens
Processing Product: Battery Post Adaptor
Processing Product: Trailer Light Module
Processing Product: Trailer ID Light Bar
Processing Product: Waterproof Lights
Processing Product: Trailer End Wiring
Processing Product: Vehicle End Connecto
Processing Product: Trailer End Connecto
Processing Product: Mounting Bracket
Processing Product: Breakaway Switch
Processing Product: Breakaway Charger
Processing Product: Breakaway Kit
Processing Product: Vehicle End Wiring
Processing Product: Fifth Wheel Harness
Processing Product: Wire Holder
Processing Product: Adapter 4 to 5-Flat
Processing Product: Trailer Connector
Processing Product: Breakaway Cable
Processing Product: Battery Isolator
Processing Product: Trailer Fender Light
Processing Product: Trailer Reflector
Processing Product: Junction Box
Processing Product: Taillight Snap Ring
File FBG_SKU_Attributes_Bargman.xlsx created successfully
Processing Product: Disc Brake Caliper
Processing Product: Steering Column Intermediate Shaft
Processing Product: Steering Column Universal Joint Assembly
Processing Product: Power Steering Filter
Processing Product: Rack and Pinion Bushing Kit
Processing Product: Steering Tie Rod End Bushing Kit
Processing Product: Steering Pitman Arm
Processing Product: Disc Brake Caliper Set
Processing Product: Fuel Injection Pump Installation Kit
Processing Product: Diesel Fuel Injector Installation Kit
Processing Product: High Pressure Oil Rail Repair Kit
Processing Product: High Pressure Oil Rail Tool
Processing Product: Turbocharger Mounting Gasket Set
Processing Product: Exhaust Gas Recirculation (EGR) Cooler Gasket Kit
Processing Product: Parking Brake Actuator
Processing Product: Turbocharger Cartridge
Processing Product: Turbocharger
Processing Product: Turbocharger Mount
Processing Product: Turbocharger Service Kit
Processing Product: Turbocharger Actuator
Processing Product: Turbocharger Compressor Wheel
Processing Product: Turbocharger Exhaust Adapter
Processing Product: Turbocharger Vane Position Solenoid
Processing Product: Turbocharger Oil Line
Processing Product: Turbocharger Coolant Supply Line
Processing Product: Turbocharger Coolant Return Line
Processing Product: Turbocharger Coolant and Oil Supply / Return Line Kit
Processing Product: Leaf Spring Axle U-Bolt Kit
Processing Product: Rack and Pinion Hydraulic Transfer Tubing Assembly
Processing Product: Power Steering Pump Pulley
Processing Product: Power Steering Reservoir
Processing Product: Brake Dust Shield
Processing Product: Nitrogen Oxide (NOx) Sensor
Processing Product: Power Brake Booster
Processing Product: Engine Auxiliary Water Pump
Processing Product: CV Axle Assembly
Processing Product: CV Intermediate Shaft
Processing Product: Diesel Particulate Filter (DPF) Gasket
Processing Product: Fuel Injection Throttle Body
Processing Product: Wiper Motor Pulse Board
Processing Product: Window Motor
Processing Product: Window Regulator
Processing Product: Window Motor and Regulator Assembly
Processing Product: Window Motor Gear Kit
Processing Product: Headlight Motor
Processing Product: Transfer Case Motor
Processing Product: 4WD Actuator
Processing Product: Distributor
Processing Product: Engine Camshaft Position Sensor
Processing Product: Camshaft Synchronizer Alignment Tool Kit
Processing Product: Engine Camshaft Synchronizer
Processing Product: Engine Crankshaft Position Sensor
Processing Product: Windshield Wiper Motor
Processing Product: Windshield Wiper Linkage
Processing Product: Windshield Wiper Motor Crank Arm Kit
Processing Product: Mass Air Flow Sensor
Processing Product: Power Brake Booster Vacuum Pump
Processing Product: Vacuum Pump
Processing Product: Power Steering Pump
Processing Product: Rack and Pinion Assembly
Processing Product: Steering Gear
File FBG_SKU_Attributes_Cardone New.xlsx created successfully
Processing Product: ABS Control Module
Processing Product: ABS Hydraulic Assembly
Processing Product: ABS Pump and Motor Assembly
Processing Product: Disc Brake Caliper Bracket
Processing Product: Disc Brake Caliper
Processing Product: Rack and Pinion Assembly
Processing Product: Air Brake Disc Brake Caliper
Processing Product: Steering Column
Processing Product: Power Steering Assist Motor
Processing Product: Steering Column Intermediate Shaft
Processing Product: Power Steering Pump
Processing Product: Electronic Brake Assembly
Processing Product: Electronic Brake Pump and Motor
Processing Product: Electronic Brake Pedal Simulator
Processing Product: Steering Gear
Processing Product: Power Steering Control Valve
Processing Product: Power Steering Power Cylinder
Processing Product: Fuel Injection Pump
Processing Product: Diesel Fuel Injector Driver Module Resistor
Processing Product: Fuel Injector
Processing Product: Instrument Cluster
Processing Product: Supercharger
Processing Product: Turbocharger
Processing Product: Fuel Injection Pressure Regulator
Processing Product: Distributor
Processing Product: Engine Camshaft Synchronizer
Processing Product: Engine Oil Pump Drive Shaft
Processing Product: Engine Camshaft Position Sensor
Processing Product: Engine Crankshaft Position Sensor
Processing Product: Secondary Air Injection Pump
Processing Product: Drive Axle Assembly
Processing Product: Windshield Wiper Motor
Processing Product: Wiper Motor Pulse Board
Processing Product: Windshield Washer Pump
Processing Product: Window Motor
Processing Product: Window Motor and Regulator Assembly
Processing Product: Sunroof Motor
Processing Product: Window Motor Gear Kit
Processing Product: Power Sliding Door Motor
Processing Product: Window Regulator
Processing Product: Transfer Case Motor
Processing Product: Headlight Motor
Processing Product: HVAC Control Module
Processing Product: Exhaust Gas Recirculation (EGR) Cooler
Processing Product: Liftgate Actuator
Processing Product: Power Brake Booster
Processing Product: Power Brake Booster Hydraulic Motor Pump
Processing Product: Diesel Exhaust Fluid (DEF) Pump
Processing Product: Diesel Exhaust Fluid (DEF) Heater
Processing Product: CV Axle Assembly
Processing Product: Vacuum Pump
Processing Product: Vacuum Pump Pulley
Processing Product: Drive Shaft
Processing Product: Fuel Injection Throttle Body
Processing Product: Accelerator Pedal Sensor
Processing Product: Diesel Particulate Filter (DPF)
Processing Product: Engine Control Module (ECM)
Processing Product: Transmission Control Module
Processing Product: Body Control Module
Processing Product: Integrated Control Module
Processing Product: Active Suspension Control Module
Processing Product: Transfer Case Control Module
Processing Product: Relay Control Module
Processing Product: Lighting Control Module
Processing Product: Diesel Glow Plug Controller
Processing Product: Power Supply Module
Processing Product: Mass Air Flow Sensor
Processing Product: Powertrain Control Module (PCM)
Processing Product: Fuel Injector Control Module
Processing Product: Vehicle Control Module
Processing Product: Fuel Pump Driver Module
Processing Product: Diesel Fuel Injector Driver Module
File FBG_SKU_Attributes_Cardone Reman.xlsx created successfully
Processing Product: Mechanical Fuel Pump
Processing Product: Fuel Pump Pulsator
Processing Product: Fuel Pump Check Valve
Processing Product: Electric Fuel Pump
Processing Product: Fuel Pump and Strainer Set
Processing Product: Fuel Pump Module Assembly
Processing Product: Fuel Pump and Sender Assembly
Processing Product: Fuel Filter Housing
Processing Product: Fuel Pump Strainer
Processing Product: Direct Injection High Pressure Fuel Pump
Processing Product: Fuel Pump Hanger
Processing Product: Fuel Pump Hanger Assembly
Processing Product: Fuel Tank Sender Assembly
Processing Product: Fuel Sender and Hanger Assembly
Processing Product: Fuel Transfer Unit
Processing Product: Fuel Tank Sending Unit and Fuel Filter Assembly
Processing Product: Fuel Tank and Pump Assembly Combination
Processing Product: Fuel Pump Reservoir
Processing Product: Fuel Pump Push Rod
Processing Product: Engine Timing Belt Kit
Processing Product: Fuel Pump Tank Seal
Processing Product: Fuel Pump Wiring Harness
File FBG_SKU_Attributes_Carquest.xlsx created successfully
Processing Product: Mechanical Fuel Pump
Processing Product: Fuel Pump Fitting
Processing Product: Fuel Pump Check Valve
Processing Product: Fuel Pump Mounting Kit
Processing Product: Fuel Filter Housing
Processing Product: Fuel Filter Cover Gasket
Processing Product: Fuel Filter
Processing Product: Fuel Pressure Regulator
Processing Product: Fuel Line Set
Processing Product: Fuel Pump Wiring Harness
Processing Product: Electric Fuel Pump Repair Kit
Processing Product: Mechanical Fuel Pump Repair Kit
Processing Product: Fuel Pump Vacuum Line
Processing Product: Engine Oil Pressure Switch
Processing Product: Direct Injection High Pressure Fuel Pump
Processing Product: Fuel Pump Spacer
Processing Product: Electric Fuel Pump
Processing Product: Fuel Pump and Strainer Set
Processing Product: Fuel Pump Hanger Assembly
Processing Product: Fuel Pump Module Assembly
Processing Product: Fuel Pump Reservoir
Processing Product: Fuel Tank Sender Assembly
Processing Product: Fuel Tank Sending Unit and Fuel Filter Assembly
Processing Product: Fuel Pump Pulsator
Processing Product: Fuel Pump Push Rod
Processing Product: Fuel Pump Tank Seal
Processing Product: Fuel Pump Strainer
Processing Product: Fuel Tank Lock Ring
Processing Product: Engine Water Pump
Processing Product: Engine Auxiliary Water Pump
Processing Product: Drive Motor Inverter Cooler Water Pump
Processing Product: Electric Engine Water Pump
Processing Product: Engine Water Pump Adapter
Processing Product: Accessory Drive Belt Idler Assembly
File FBG_SKU_Attributes_Carter.xlsx created successfully
Processing Product: Disc Brake Pad Set
Processing Product: Parking Brake Disc Brake Pad Set
Processing Product: Drum Brake Shoe
Processing Product: Parking Brake Shoe
Processing Product: Disc Brake Pad Wear Sensor
Processing Product: Disc Brake Hardware Kit
Processing Product: Parking Brake Hardware Kit
Processing Product: Drum Brake Hardware Kit
Processing Product: Drum Brake Self-Adjuster Repair Kit
Processing Product: Disc Brake Rotor
Processing Product: Disc Brake Rotor and Hub Assembly
Processing Product: Brake Drum
Processing Product: Disc Brake Hub
Processing Product: Wheel Bearing Dust Cap
Processing Product: Brake Master Cylinder
Processing Product: Drum Brake Wheel Cylinder
Processing Product: Disc Brake Caliper Set
Processing Product: Disc Brake Caliper
Processing Product: Disc Brake Caliper Bracket
Processing Product: Brake Hydraulic Hose
Processing Product: Clutch Hydraulic Hose
Processing Product: Clutch Cable