In [1]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np
np.set_printoptions(legacy="1.13")

In [2]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files\HitchPro\Excel'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Import files'

In [3]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsx') in f:

                    file_list.append(f)
file_list

['Bargman_PIES.xlsx',
 'BULLDOG_PIES.xlsx',
 'DRAW-TITE_PIES.xlsx',
 'FULTON_PIES.xlsx',
 'Hopkins_Towing_Solutions_PIES.xlsx',
 'REESE_PIES.xlsx',
 'REESE_TOWPOWER_PIES.xlsx',
 'ROLA_PIES.xlsx',
 'TEKONSHA_PIES.xlsx',
 'Wesbar_PIES.xlsx']

In [4]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [5]:
len(file_link)

10

In [6]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\Documents - Product Support India Romania\\Catalog\\Score card\\Standard\\Import files\\HitchPro\\Excel\\BULLDOG_PIES.xlsx'

In [7]:
cols=['Brand']
df_s = pd.DataFrame(columns=cols)

In [8]:
file_link[1].split("_PIES")[0].split("Excel\\")[1]

'BULLDOG'

In [9]:
for i in range(len(file_link)):
    # workbook=openpyxl.load_workbook(file_link[i])
    BrandName= file_link[i].split("_PIES")[0].split("Excel\\")[1]
    print(i,BrandName)
    df_item=pd.read_excel(file_link[i],sheet_name="Items")
    df_Attr=pd.read_excel(file_link[i],sheet_name="ProductAttributes")
    df_item=df_item.astype(str)
    df_Attr=df_Attr.astype(str)
    df=df_Attr.merge(df_item,how="inner")
    ListColumns=['PartNumber','Description_SHO', 'AttributeID',"Value"]
    df=df[ListColumns]
    df=df.drop_duplicates().reset_index(drop=True)
    df['Brand']=BrandName
    df_s=pd.concat([df_s,df])

0 Bargman
1 BULLDOG
2 DRAW-TITE
3 FULTON
4 Hopkins_Towing_Solutions
5 REESE
6 REESE_TOWPOWER
7 ROLA
8 TEKONSHA
9 Wesbar

In [10]:
df_s

,Brand,PartNumber,Description_SHO,AttributeID,Value
0,Bargman,50-98-003,Wire Holder,Prop 65,Yes
1,Bargman,50-98-003,Wire Holder,Prop 65 Warning,WARNING: Cancer and Reproductive Harm – www.p6...
2,Bargman,50-98-003,Wire Holder,Prop 65 Chemical,DEHP
3,Bargman,50-98-003,Wire Holder,Hardware Included,No
4,Bargman,50-98-003,Wire Holder,Number of Mounting Holes,2
...,...,...,...,...,...
912,Wesbar,54209-002,Worklight,Prop 65 Warning,WARNING: Cancer and Reproductive Harm – www.p6...
913,Wesbar,54209-002,Worklight,Prop 65 Chemical,DEHP
914,Wesbar,54209-002,Worklight,Lens Depth,1.5
915,Wesbar,54209-002,Worklight,Lens Height,4
916,Wesbar,54209-002,Worklight,Lens Length,4

In [11]:
df_autocare=pd.read_csv(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\Standard\Autocare\AutocareAttributes.csv")

In [12]:
df_autocare

,CategoryID,CategoryName,PartTerminologyID,PartTerminologyName,PAID,PAName
0,1.0,Accessories,1020.0,Car Cover,14.0,Length
1,1.0,Accessories,1020.0,Car Cover,24.0,Width
2,1.0,Accessories,1020.0,Car Cover,10.0,Material
3,1.0,Accessories,1020.0,Car Cover,17.0,Color
4,1.0,Accessories,1020.0,Car Cover,513.0,Vented
...,...,...,...,...,...,...
137822,46.0,"Oil, Fluids and Chemicals",68086.0,Intercooler Fluid,3145.0,Universal Or Specific Fit
137823,46.0,"Oil, Fluids and Chemicals",68086.0,Intercooler Fluid,3390.0,Grade Type
137824,46.0,"Oil, Fluids and Chemicals",70868.0,Wheel Tape,14.0,Length
137825,46.0,"Oil, Fluids and Chemicals",70868.0,Wheel Tape,24.0,Width
137826,46.0,"Oil, Fluids and Chemicals",70868.0,Wheel Tape,10787.0,Pre-Cut Valve Tube Hole

In [13]:
df_autocare=df_autocare[['PAID',"PAName"]].drop_duplicates().reset_index(drop=True)
df_autocare
df_autocare["PAID"]=df_autocare["PAID"].astype(str)
for i in range(len(df_autocare)):
    df_autocare.loc[i,"PAID"]=df_autocare["PAID"][i].replace('.0', '')
df_autocare.head()

  PAID    PAName
0   14    Length
1   24     Width
2   10  Material
3   17     Color
4  513    Vented

In [14]:
df_s.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66629 entries, 0 to 916
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            66629 non-null  object
 1   PartNumber       66629 non-null  object
 2   Description_SHO  66629 non-null  object
 3   AttributeID      66629 non-null  object
 4   Value            66629 non-null  object
dtypes: object(5)
memory usage: 3.1+ MB

In [15]:
df_Match=df_s.merge(df_autocare,left_on="AttributeID",right_on="PAID",how='left')

In [16]:
df_Match

,Brand,PartNumber,Description_SHO,AttributeID,Value,PAID,PAName
0,Bargman,50-98-003,Wire Holder,Prop 65,Yes,NaN,NaN
1,Bargman,50-98-003,Wire Holder,Prop 65 Warning,WARNING: Cancer and Reproductive Harm – www.p6...,NaN,NaN
2,Bargman,50-98-003,Wire Holder,Prop 65 Chemical,DEHP,NaN,NaN
3,Bargman,50-98-003,Wire Holder,Hardware Included,No,NaN,NaN
4,Bargman,50-98-003,Wire Holder,Number of Mounting Holes,2,NaN,NaN
...,...,...,...,...,...,...,...
66624,Wesbar,54209-002,Worklight,Prop 65 Warning,WARNING: Cancer and Reproductive Harm – www.p6...,NaN,NaN
66625,Wesbar,54209-002,Worklight,Prop 65 Chemical,DEHP,NaN,NaN
66626,Wesbar,54209-002,Worklight,Lens Depth,1.5,NaN,NaN
66627,Wesbar,54209-002,Worklight,Lens Height,4,NaN,NaN
66628,Wesbar,54209-002,Worklight,Lens Length,4,NaN,NaN

In [17]:
df_Match['PAName']=np.where(df_Match['PAName'].isnull(), df_Match['AttributeID'], df_Match['PAName'])

In [18]:
df_Match.columns

Index(['Brand', 'PartNumber', 'Description_SHO', 'AttributeID', 'Value',
       'PAID', 'PAName'],
      dtype='object')

In [19]:
df_Match.rename(columns={"Description_SHO":"PartTerminologyName"},inplace=True)
df_Match=df_Match[['Brand', 'PartNumber', 'PartTerminologyName',  'PAName', 'Value']]

In [20]:
chunk_size=1000000
# Create a list of DataFrames by splitting the original DataFrame
df_chunks = [df_Match.iloc[i:i + chunk_size] for i in range(0, len(df_Match), chunk_size)]

In [21]:
df_Attributes=df_Match[['Brand', 'PartTerminologyName',  'PAName']].drop_duplicates().reset_index(drop=True)

In [22]:
with pd.ExcelWriter(OFolder+'\\'+'Horizon_Global_Attribute_List.xlsx') as writer:  # doctest: +SKIP
    for i, chunk in enumerate(df_chunks):
        sheet_name = f"Chunk_{i+1}"  # Naming each sheet dynamically
        chunk.to_excel(writer, sheet_name=sheet_name, index=False)
    df_Attributes.to_excel(writer,index=False, sheet_name='FBG_Attributes')