In [1]:
import pandas as pd

In [6]:
Folder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\Amazon_Scrapping\Outputs'
df=pd.read_excel(Folder+'\\'+'AmazonProductDetails_Car Vacuum Cleaner.xlsx')
df.head()

,Sl.No,Name,Cost,Ratings,Detail,Sales,Item_Details,Review_Mentions,Links
0,0,ThisWorx Car Vacuum Cleaner - Car Accessories ...,$26.99,"4.0\n296,771 ratings",-,60K+ bought in past month,About this item\nPRACTICAL: A mini vacuum for ...,"['suction power', 'cord length', 'car wash', '...",https://www.amazon.com/dp/B06ZY896ZM
1,1,"Saker Mini Vacuum Cleaner for Car,3 in 1 Keybo...",$59.99,"4.0\n1,558 ratings",-,10K+ bought in past month,About this item\n【3-In-1 Multifunctional Mini ...,"['little vacuum', 'mini vacuum', 'dog hair', '...",https://www.amazon.com/dp/B0BMP2KQG2
2,2,"DRECELL Car Vacuum, Portable Vacuum Cleaner wi...",$25.98,4.3\n642 ratings,-,4K+ bought in past month,About this item\nPowerful Car Cleaning: The ca...,"['easy to use', 'highly recommend', 'suction p...",https://www.amazon.com/dp/B0CFDYV3RH
3,3,Fanttik Slim V8 Mate Cordless Car Vacuum High ...,$79.99,4.5\n426 ratings,-,4K+ bought in past month,"About this item\nGo Small, Clean Bigger! - Are...","['battery life', 'suction power', 'little vacu...",https://www.amazon.com/dp/B0B9447P5P
4,4,"Handheld Vacuum Cordless, Upbooz Portable Car ...",$41.99,4.7\n255 ratings,-,2K+ bought in past month,About this item\n【Powerful Suction Handheld Va...,"['handheld vacuum', 'highly recommend', 'sucti...",https://www.amazon.com/dp/B0CFTTMTQR

In [85]:
# def pr(df,x,xn,y,z):
#     df[xn]=df[x].str.split(y,expand=True)[1].str.split(z,expand=True)[0].str.replace(',',"").fillna(0)

In [7]:
def tryconvert(value, default, *types):
    for t in types:
        try:
            return t(value)
        except (ValueError, TypeError):
            continue
    return default

In [14]:
df["Star_Rating"]=df["Ratings"].str.split('''\n''',expand=True)[0]
df["No of Ratings"]=df["Ratings"].str.split('''\n''',expand=True)[1].str.split(' ',expand=True)[0].replace(",","")

del df['Ratings']

In [81]:
# df['Name'] = df['Name'].str.lower()
# df['Name'] = df['Name'].str.replace("lb", " lb", case=False, regex=False)
# df['Name'] = df['Name'].str.replace("inch", "  inch", case=False, regex=False)
# df['Name'] = df['Name'].str.replace('"', " inch", case=False, regex=False)
# df['Name'] = df['Name'].str.replace("lbs", "  lbs", case=False, regex=False)
# df['Name'] = df['Name'].str.replace("lbs", "lb", case=False, regex=False)

# df['Name'] = df['Name'].str.replace(r'\s+', ' ', regex=True)

In [82]:
# df['Extended_Length']=df['Name'].str.split(" inch",expand=True)[0].apply(lambda x: x[len(x)-2:]).apply(lambda x: tryconvert(x, 0, int))
# df['Output_Force']=df['Name'].str.split(" lb",expand=True)[0].apply(lambda x: x[len(x)-2:]).apply(lambda x: tryconvert(x, 0, int))

In [83]:
# df[["Name","Extended_Length","Output_Force"]]

,Name,Name_clean1,Name_clean2
0,arana c16-06874 17 inch gas struts shocks ml36...,17,40
1,"arana se180p70 18 inch gas strut 70 lb, 18 inc...",18,70
2,arana 15 inch lift support struts gas spring s...,15,67
3,arana 12 inch 40 lb gas prop struts shock lift...,12,40
4,arana 20 inch 300 n/67 lb gas struts spring sh...,20,67
...,...,...,...
99,arana c16-23833 18 inch 100 lb gas struts spri...,18,0
100,arana c160854 20 inch 100 lb gas strut & car b...,20,0
101,arana cf11966 cabin air filter replacement for...,0,0
102,max-lift 901430 gas charged lift support,0,0
103,st360m112010 36 inch 120 lb gas shocks struts ...,36,20

In [137]:
#df["No of Ratings"]=df["No of Ratings"].replace(" ","").replace(",","").apply(lambda x: tryconvert(x, 0, int))

In [15]:
df["Sales"]=df['Sales'].str.replace("bought in past month","")

In [16]:
df.head()

,Sl.No,Name,Cost,Detail,Sales,Item_Details,Review_Mentions,Links,Star_Rating,No of Ratings
0,0,ThisWorx Car Vacuum Cleaner - Car Accessories ...,$26.99,-,60K+,About this item\nPRACTICAL: A mini vacuum for ...,"['suction power', 'cord length', 'car wash', '...",https://www.amazon.com/dp/B06ZY896ZM,4.0,"296,771"
1,1,"Saker Mini Vacuum Cleaner for Car,3 in 1 Keybo...",$59.99,-,10K+,About this item\n【3-In-1 Multifunctional Mini ...,"['little vacuum', 'mini vacuum', 'dog hair', '...",https://www.amazon.com/dp/B0BMP2KQG2,4.0,"1,558"
2,2,"DRECELL Car Vacuum, Portable Vacuum Cleaner wi...",$25.98,-,4K+,About this item\nPowerful Car Cleaning: The ca...,"['easy to use', 'highly recommend', 'suction p...",https://www.amazon.com/dp/B0CFDYV3RH,4.3,642
3,3,Fanttik Slim V8 Mate Cordless Car Vacuum High ...,$79.99,-,4K+,"About this item\nGo Small, Clean Bigger! - Are...","['battery life', 'suction power', 'little vacu...",https://www.amazon.com/dp/B0B9447P5P,4.5,426
4,4,"Handheld Vacuum Cordless, Upbooz Portable Car ...",$41.99,-,2K+,About this item\n【Powerful Suction Handheld Va...,"['handheld vacuum', 'highly recommend', 'sucti...",https://www.amazon.com/dp/B0CFTTMTQR,4.7,255

In [154]:
Part="Refined"
df.to_excel(Folder+'\\'+'AmazonProductDetails_'+Part+'.xlsx', index=False)