In [2]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

### Fram Sales

In [ ]:
FRAM_Sales=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Archives\SalesData\FramAutolite orders 2024 (1).xlsx'
df_Q1=pd.read_excel(FRAM_Sales,sheet_name="AUS 1 DOMESTIC JAN-MAR 2024", skiprows=1)
print(1)
df_Q2=pd.read_excel(FRAM_Sales,sheet_name="AUS 1 DOMESTIC APR-JUN 2024", skiprows=1)
print(1)
df_Q3=pd.read_excel(FRAM_Sales,sheet_name="AUS 1 DOMESTIC JUL-SEP 2024", skiprows=1)
print(1)
df_Q4=pd.read_excel(FRAM_Sales,sheet_name="AUS 1 DOMESTIC OCT-DEC 2024", skiprows=1)
print(1)
df_FRAM=pd.concat([df_Q1,df_Q2,df_Q3,df_Q4],ignore_index=True)

KeyError: ['Part Number']

In [5]:
df_FRAM

,Sales Org,PO number,Doc. Date,GI Date,Dlv.Date,SaTy,SD Doc.,Item,Sold-to pt,Material,...,ConfirmQty,Rj,Name 1,Net price,S,SGrp,Item,Order qty,ConfirmQty,Material Description
0,AUS 1,26881326OD000ASP64892,2024-01-01,2024-01-02,2024-01-05,ZORT,118306314,10.0,146562,A1111,...,8.0,NaN,MADDEN AUTO SUPPLY DOVER,0.00,NaN,680.0,NaN,NaN,NaN,NaN
1,AUS 1,26881326OD000ASP64892,2024-01-01,2024-01-02,2024-01-04,ZORT,118306314,10.0,146562,A1111,...,0.0,NaN,MADDEN AUTO SUPPLY DOVER,0.00,NaN,680.0,NaN,NaN,NaN,NaN
2,AUS 1,26881326OD000ASP64892,2024-01-01,2024-01-02,2024-01-05,ZORT,118306314,20.0,146562,A1111-03,...,8.0,NaN,MADDEN AUTO SUPPLY DOVER,5.07,C,680.0,NaN,NaN,NaN,NaN
3,AUS 1,26881326OD000ASP64892,2024-01-01,2024-01-02,2024-01-04,ZORT,118306314,20.0,146562,A1111-03,...,0.0,NaN,MADDEN AUTO SUPPLY DOVER,5.07,C,680.0,NaN,NaN,NaN,NaN
4,AUS 1,26881326OD000ASP64892,2024-01-01,2024-01-02,2024-01-04,ZORT,118306314,30.0,146562,A145,...,0.0,NaN,MADDEN AUTO SUPPLY DOVER,0.00,NaN,680.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3378260,AUS 1,B7dgdVxVB,2024-12-31,2025-01-03,2025-01-03,ZROT,112874017,NaN,147609,FTG10060-13,...,NaN,NaN,XXXXX,NaN,NaN,NaN,20.0,2.0,2.0,SPIN-ON OIL FILTER 6PK
3378261,AUS 1,91934263,2024-12-01,2024-12-02,2024-12-10,ZROT,112871881,NaN,135657,FPH3593A,...,NaN,NaN,Angel Estrella,NaN,NaN,NaN,10.0,1.0,1.0,NaN
3378262,AUS 1,91934263,2024-12-01,2024-12-02,2024-12-03,ZROT,112871881,NaN,135657,FPH3593A,...,NaN,NaN,Angel Estrella,NaN,NaN,NaN,10.0,1.0,0.0,NaN
3378263,AUS 1,91934263,2024-12-01,2024-12-02,2024-12-03,ZROT,112871881,NaN,135657,FPH9688-12,...,NaN,NaN,Angel Estrella,NaN,NaN,NaN,20.0,1.0,0.0,NaN
3378264,AUS 1,91934263,2024-12-01,2024-12-02,2024-12-10,ZROT,112871881,NaN,135657,FPH9688-12,...,NaN,NaN,Angel Estrella,NaN,NaN,NaN,20.0,1.0,1.0,NaN

In [7]:
Cardone_Sales=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Archives\SalesData\Cardone 2024.xlsx'
df_cQ1=pd.read_excel(Cardone_Sales,sheet_name="Q1 Data")
print(1)
df_cQ2=pd.read_excel(Cardone_Sales,sheet_name="Q2 Data")
print(1)
df_cQ3=pd.read_excel(Cardone_Sales,sheet_name="Q3 Data")
print(1)
df_cQ4=pd.read_excel(Cardone_Sales,sheet_name="Q4 Data")
print(1)
df_Cardone=pd.concat([df_cQ1,df_cQ2,df_cQ3,df_cQ4],ignore_index=True)
df_Cardone

,SaTy,Sales Doc.,Purchase order no.,Sold-To Pt,Sold-To Name,PO Date,Created On,Net value,Curr.,Item,...,Net weight,WUn5,Ship-To Address,Ship-To City,Ship-To Region,Ship-to Postal Code,Volume,VUn,Created By,Grp4
0,ZPPO,202726888,895694S002769,1000083,O'REILLY,2024-03-19,2024-03-19,79.22,USD,10,...,10.19,LB,233 S PATTERSON AVE,SPRINGFIELD,MO,65802-2210,0.861,FT3,ECCECOM,60.0
1,ZPPO,202726889,108908170235915,1001386,Walmart.com,2024-03-19,2024-03-19,50.02,USD,10,...,19.59,LB,OVERRIDE ADDRESS FOR DROPSHIP,MEMPHIS,TN,38120,0.427,FT3,ECCECOM,0.0
2,ZPPO,202726890,108908170376275,1001386,Walmart.com,2024-03-19,2024-03-19,41.14,USD,10,...,17.25,LB,OVERRIDE ADDRESS FOR DROPSHIP,MEMPHIS,TN,38120,0.427,FT3,ECCECOM,0.0
3,ZPPO,202697754,707674S001418,1000083,O'REILLY,2024-01-02,2024-01-02,126.13,USD,10,...,12.10,LB,233 S PATTERSON AVE,SPRINGFIELD,MO,65802-2210,0.566,FT3,ECCECOM,60.0
4,ZPPO,202697755,707675S002640,1000083,O'REILLY,2024-01-02,2024-01-02,168.86,USD,10,...,13.72,LB,233 S PATTERSON AVE,SPRINGFIELD,MO,65802-2210,0.566,FT3,ECCECOM,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2142274,ZRPO,202814673,5941,1000958,REPUESTOS Y ACCESORIOS,2024-10-21,2024-10-21,14659.05,USD,600,...,10.20,LB,8355 NW 74TH ST,MEDLEY,FL,33166-2323,0.288,FT3,LA80125,0.0
2142275,ZRPO,202814673,5941,1000958,REPUESTOS Y ACCESORIOS,2024-10-21,2024-10-21,14659.05,USD,610,...,21.20,LB,8355 NW 74TH ST,MEDLEY,FL,33166-2323,0.576,FT3,LA80125,0.0
2142276,ZRPO,202814673,5941,1000958,REPUESTOS Y ACCESORIOS,2024-10-21,2024-10-21,14659.05,USD,620,...,21.20,LB,8355 NW 74TH ST,MEDLEY,FL,33166-2323,0.576,FT3,LA80125,0.0
2142277,ZRPO,202814673,5941,1000958,REPUESTOS Y ACCESORIOS,2024-10-21,2024-10-21,14659.05,USD,630,...,18.24,LB,8355 NW 74TH ST,MEDLEY,FL,33166-2323,0.576,FT3,LA80125,0.0
2142278,ZRPO,202814673,5941,1000958,REPUESTOS Y ACCESORIOS,2024-10-21,2024-10-21,14659.05,USD,640,...,18.28,LB,8355 NW 74TH ST,MEDLEY,FL,33166-2323,0.576,FT3,LA80125,0.0

In [3]:
BPI_Sales=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Sales\Product to Customer BPI ASC IBI.csv"
df_BPI=pd.read_csv(BPI_Sales)

In [4]:
df_BPI

,BusinessUnit,OrganizationDesc,CustomerCode,CustomerDesc,CustomerAddress1,CustomerState,CustomerZip,ProductCode,ProductDesc,QTY SHIPPED
0,BPI,MIDWEST DC,1986002,GMSPO WD SHIP TO,4400 Prime Parkway,IL,60050,96-18J4091,BRAKE HOSE,36
1,BPI,MIDWEST DC,2535ST,NAPA WASHINGTON DC,QUAKER CITY MOTOR PARTS,DE,19709,62-683052,BRAKE HOSE,99
2,BPI,MIDWEST DC,Z7097,UNITED AUTO SUPPLY,1200 STATE FAIR BLVD,NY,13209,MC390938,MASTER CYLINDER,2
3,BPI,MIDWEST DC,2120ST,NAPA DENVER,GENUINE PARTS COMPANY,GA,30091-2227,62-48880680SP,BRAKE ROTOR,100
4,BPI,MIDWEST DC,2295ST,NAPA MT VERNON,GENUINE PARTS COMPANY,GA,30091-0349,62-86934CR,BRAKE ROTOR,30
...,...,...,...,...,...,...,...,...,...,...
1221439,BPI,MIDWEST DC,21339,"PARTS WHOLESALERS, INC.",125 S. WALNUT ST,WA,99204,EHT1391AH,PAD SET IM,1
1221440,BPI,MIDWEST DC,40002055,NAPA CARROLLTON DC,"1233 Lincoln Ave, N.W.",OH,44615,62-682897,BRAKE HOSE,1
1221441,Centric,CENTRIC (ORACLE),C2647,TURN 14 DISTRIBUTION,100 TOURNAMENT DRIVE,PA,19044,105.09140,PAD SET IM,1
1221442,BPI,MIDWEST DC,32068011,MODERN SALES CO-OP,293057 JAMES JONES WAY,AB,T4A 0X1,H17344,DRUM BRAKE HDWE,1
1221443,BPI,MIDWEST DC,32068023,MISSISSAUGA DISCOUNT AUTO PARTS,6605 ORDAN DRIVE UNITS 8 & 10,ON,L5T-1X2,EHT1430AH,PAD SET IM,1

In [5]:
df_BPI_customer=pd.read_excel(r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Sales\BUFiles\BPI_Customers.xlsx")
df_BPI_customer

                Customer Customer Cleaned
0       GMSPO WD SHIP TO               GM
1     NAPA WASHINGTON DC             NAPA
2     UNITED AUTO SUPPLY           Others
3            NAPA DENVER             NAPA
4         NAPA MT VERNON             NAPA
...                  ...              ...
6970           RYAN DRAE           Others
6971      BRANDON VALDEZ           Others
6972            DR MAYER           Others
6973     Jeremy Gurganus           Others
6974        GENE SPIEGEL           Others

[6975 rows x 2 columns]

In [6]:
df_merged = pd.merge(df_BPI, df_BPI_customer, left_on='CustomerDesc', right_on='Customer', how='left')

In [7]:
df_merged

,BusinessUnit,OrganizationDesc,CustomerCode,CustomerDesc,CustomerAddress1,CustomerState,CustomerZip,ProductCode,ProductDesc,QTY SHIPPED,Customer,Customer Cleaned
0,BPI,MIDWEST DC,1986002,GMSPO WD SHIP TO,4400 Prime Parkway,IL,60050,96-18J4091,BRAKE HOSE,36,GMSPO WD SHIP TO,GM
1,BPI,MIDWEST DC,2535ST,NAPA WASHINGTON DC,QUAKER CITY MOTOR PARTS,DE,19709,62-683052,BRAKE HOSE,99,NAPA WASHINGTON DC,NAPA
2,BPI,MIDWEST DC,Z7097,UNITED AUTO SUPPLY,1200 STATE FAIR BLVD,NY,13209,MC390938,MASTER CYLINDER,2,UNITED AUTO SUPPLY,Others
3,BPI,MIDWEST DC,2120ST,NAPA DENVER,GENUINE PARTS COMPANY,GA,30091-2227,62-48880680SP,BRAKE ROTOR,100,NAPA DENVER,NAPA
4,BPI,MIDWEST DC,2295ST,NAPA MT VERNON,GENUINE PARTS COMPANY,GA,30091-0349,62-86934CR,BRAKE ROTOR,30,NAPA MT VERNON,NAPA
...,...,...,...,...,...,...,...,...,...,...,...,...
1221439,BPI,MIDWEST DC,21339,"PARTS WHOLESALERS, INC.",125 S. WALNUT ST,WA,99204,EHT1391AH,PAD SET IM,1,"PARTS WHOLESALERS, INC.",Others
1221440,BPI,MIDWEST DC,40002055,NAPA CARROLLTON DC,"1233 Lincoln Ave, N.W.",OH,44615,62-682897,BRAKE HOSE,1,NAPA CARROLLTON DC,NAPA
1221441,Centric,CENTRIC (ORACLE),C2647,TURN 14 DISTRIBUTION,100 TOURNAMENT DRIVE,PA,19044,105.09140,PAD SET IM,1,TURN 14 DISTRIBUTION,Others
1221442,BPI,MIDWEST DC,32068011,MODERN SALES CO-OP,293057 JAMES JONES WAY,AB,T4A 0X1,H17344,DRUM BRAKE HDWE,1,MODERN SALES CO-OP,Others
1221443,BPI,MIDWEST DC,32068023,MISSISSAUGA DISCOUNT AUTO PARTS,6605 ORDAN DRIVE UNITS 8 & 10,ON,L5T-1X2,EHT1430AH,PAD SET IM,1,MISSISSAUGA DISCOUNT AUTO PARTS,Others

In [8]:
Customers=df_merged["Customer Cleaned"].unique().tolist()

In [9]:
df_merged=df_merged[['BusinessUnit', 'OrganizationDesc', 'CustomerCode', 'Customer Cleaned', 'CustomerDesc',
       'CustomerAddress1', 'CustomerState', 'CustomerZip', 'ProductCode',
       'ProductDesc', 'QTY SHIPPED']]

In [11]:
FileName=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Sales\BUFiles\BPI_ASC_IBI_CustomerWise_Sales.xlsx"
with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
    for customer in Customers:
        df_customer = df_merged[df_merged["Customer Cleaned"] == customer]
        if df_customer.empty:
            print(f"No data for {customer}, skipping.")
            continue
        print(f"Saved {customer} with {len(df_customer)} rows.")
        df_customer.to_excel(writer, sheet_name=str(customer), index=False)

Saved GM with 21281 rows.
Saved NAPA with 452738 rows.
Saved Others with 725047 rows.
Saved AUTOZONE with 16883 rows.
Saved Walmart with 1879 rows.
No data for nan, skipping.
Saved O REILLEY with 406 rows.
Saved CAR QUEST with 590 rows.

In [12]:
BusinessUnits=df_merged["BusinessUnit"].unique().tolist()

In [ ]:
df_BPI['CustomerDesc'].unique()

In [13]:
for BusinessUnit in BusinessUnits:
    print(BusinessUnit)
    FileName=rf"C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\EPR\Sales\BUFiles\{BusinessUnit}_CustomerWise_Sales.xlsx"
    with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
        for customer in Customers:
            df_customer = df_merged[(df_merged["Customer Cleaned"] == customer) & (df_merged["BusinessUnit"] == BusinessUnit)]
            if(len(df_customer)!=0):                
                print(f"Saved {customer} with {len(df_customer)} rows.")
                df_customer.to_excel(writer, sheet_name=str(customer), index=False)
            else:
                pass

BPI
Saved GM with 21281 rows.
Saved NAPA with 446818 rows.
Saved Others with 331534 rows.
Saved AUTOZONE with 34 rows.
Saved Walmart with 1879 rows.
Saved O REILLEY with 406 rows.
Saved CAR QUEST with 1 rows.
ASC
Saved Others with 38239 rows.
Saved AUTOZONE with 14977 rows.
Saved CAR QUEST with 589 rows.
Centric
Saved NAPA with 5920 rows.
Saved Others with 286480 rows.
Carter
Saved Others with 350 rows.
IBI
Saved Others with 68444 rows.
Saved AUTOZONE with 1872 rows.
nan