In [33]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import numpy as np

In [34]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor'
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\OReilly'

In [35]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.csv')  in f:
                    file_list.append(f)
file_list

['Aero Rotor Kit_PartCat_Apps.csv',
 'Aero Rotors_PartCat_Apps.csv',
 'Cryo Brake Rotor_PartCat_Apps.csv',
 'Select Sport Brake Rotor_PartCat_Apps.csv',
 'Sport Brake Rotor_PartCat_Apps.csv',
 'Sport Cryo Brake FRotor_PartCat_Apps.csv',
 'Centric Premium Brake Rotors_JNP_Apps.csv',
 'Centric Premium Brake Rotors_PartCat_Apps.csv',
 'CTEK Brake Rotors_JNP_Apps.csv',
 'CTEK Brake Rotors_PartCat_Apps.csv',
 'FMP Rotors_JNP_Apps.csv',
 'FMP Rotors_PartCat_Apps.csv',
 'GCX Disc Brake Rotors_JNP_Apps.csv',
 'GCX Disc Brake Rotors_PartCat_Apps.csv',
 'Painted Rotors_JNP_Apps.csv',
 'Painted Rotors_PartCat_Apps.csv',
 'Premium Brake Rotors_JNP_Apps.csv',
 'Premium Brake Rotors_PartCat_Apps.csv']

In [36]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [37]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.csv')  in f:
                    file_list.append(os.path.join(root, f))
file_list

['C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Aero Rotor Kit_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Aero Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Cryo Brake Rotor_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Select Sport Brake Rotor_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Sport Brake Rotor_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Sport Cryo Brake FRotor_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Centric Premium Brake Rotors\\Centric Premium Brake Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Centric Premium Brake Rotors\\Centric Premium Brake Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\CTEK Brake Rotors\\CTEK Brake Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\CTEK Brake Rotors\\CTEK Brake Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\FMP Rotors\\FMP Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\FMP Rotors\\FMP Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\GCX Disc Brake Rotors\\GCX Disc Brake Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\GCX Disc Brake Rotors\\GCX Disc Brake Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Painted Rotors\\Painted Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Painted Rotors\\Painted Rotors_PartCat_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Premium Brake Rotors\\Premium Brake Rotors_JNP_Apps.csv',
 'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\CSVs\\Premium Brake Rotors\\Premium Brake Rotors_PartCat_Apps.csv']

In [38]:
Brands=[]
for name in file_list:
    Brands.append(name.split("\\")[-1].split("_")[0])

Brands=list(set(Brands))
Brands

['Sport Cryo Brake FRotor',
 'Select Sport Brake Rotor',
 'Aero Rotor Kit',
 'Aero Rotors',
 'Premium Brake Rotors',
 'Cryo Brake Rotor',
 'Centric Premium Brake Rotors',
 'FMP Rotors',
 'Painted Rotors',
 'Sport Brake Rotor',
 'CTEK Brake Rotors',
 'GCX Disc Brake Rotors']

In [42]:
location=r"C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs"

In [85]:
Brands

['Sport Cryo Brake FRotor',
 'Select Sport Brake Rotor',
 'Aero Rotor Kit',
 'Aero Rotors',
 'Premium Brake Rotors',
 'Cryo Brake Rotor',
 'Centric Premium Brake Rotors',
 'FMP Rotors',
 'Painted Rotors',
 'Sport Brake Rotor',
 'CTEK Brake Rotors',
 'GCX Disc Brake Rotors']

In [86]:

for Brand in Brands:
    try:
        #print(location+"\\"+Brand+"\\"+Brand+"_PartCat_Apps.csv")
        #print("Executing for "+Brand)
        df_PartCat=pd.read_csv(location+"\\"+Brand+"\\"+Brand+"_PartCat_Apps.csv").drop_duplicates()
        df_JNP=pd.read_csv(location+"\\"+Brand+"\\"+Brand+"_JNP_Apps.csv").drop_duplicates()
        # del df_PartCat['MfrLabel']
        # del df_JNP['MfrLabel']
        df_merged=df_JNP.merge(df_PartCat, how="outer", on=['Key'], indicator=True ,suffixes=("_JNP", "_PartCat"))
        d={"left_only":"Present Only in JNP", "right_only":"Present only in PartCat","both":"Present in Both Databases"}
        df_merged['_merge'] = df_merged['_merge'].map(d)
        df_merged.to_csv(location+"\\"+Brand+"\\"+Brand+"_Comparison_Output.csv", index=False)
        print("Completed for "+Brand)
    except:
        continue

Completed for Premium Brake Rotors
Completed for Centric Premium Brake Rotors
Completed for FMP Rotors
Completed for Painted Rotors
Completed for CTEK Brake Rotors
Completed for GCX Disc Brake Rotors

In [78]:
df_merged

,BaseVehicleID,Qty,PartType_JNP,MfrLabel_JNP,Position,Part,Make,Model,Year,Key,PartType_PartCat,MfrLabel_PartCat,_merge
0,1,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.48010F,Suzuki,Aerio,2002,320.48010F$Disc Brake Rotor$2002$Suzuki$Aerio$...,Disc Brake Rotor,Centric GCX Elemental Protection Disc Brake Ro...,Present in Both Databases
1,2,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.48010F,Suzuki,Aerio,2003,320.48010F$Disc Brake Rotor$2003$Suzuki$Aerio$...,Disc Brake Rotor,Centric GCX Elemental Protection Disc Brake Ro...,Present in Both Databases
2,7,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.48010F,Suzuki,Esteem,1999,320.48010F$Disc Brake Rotor$1999$Suzuki$Esteem...,Disc Brake Rotor,Centric GCX Elemental Protection Disc Brake Ro...,Present in Both Databases
3,8,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.48010F,Suzuki,Esteem,2000,320.48010F$Disc Brake Rotor$2000$Suzuki$Esteem...,Disc Brake Rotor,Centric GCX Elemental Protection Disc Brake Ro...,Present in Both Databases
4,9,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.48010F,Suzuki,Esteem,2001,320.48010F$Disc Brake Rotor$2001$Suzuki$Esteem...,Disc Brake Rotor,Centric GCX Elemental Protection Disc Brake Ro...,Present in Both Databases
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86550,182475,2,Disc Brake Rotor,Centric GCX FC High Carbon,Rear,320.35205H,Mercedes-Benz,CLA250,2026,320.35205H$Disc Brake Rotor$2026$Mercedes-Benz...,NaN,NaN,Present Only in JNP
86551,182476,2,Disc Brake Rotor,Centric GCX FC High Carbon,Front,320.35170H,Mercedes-Benz,E450,2026,320.35170H$Disc Brake Rotor$2026$Mercedes-Benz...,NaN,NaN,Present Only in JNP
86552,182680,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.47049F,Subaru,Outback,2026,320.47049F$Disc Brake Rotor$2026$Subaru$Outbac...,NaN,NaN,Present Only in JNP
86553,182680,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Rear,320.47037F,Subaru,Outback,2026,320.47037F$Disc Brake Rotor$2026$Subaru$Outbac...,NaN,NaN,Present Only in JNP
86554,184490,2,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.52011F,Tesla,X,2026,320.52011F$Disc Brake Rotor$2026$Tesla$X$Front,NaN,NaN,Present Only in JNP

In [32]:
for file in file_list:
    for brand in Brands:
        if "JNP" in file and brand in file:
            print(file)
            df_JNP=pd.read_csv(file)
        if "PartCat" in file and brand in file:
            print(file+"!")
            df_PartCat=pd.read_csv(file)
        df_output=df_JNP.merge(df_PartCat["Key"], how="outer", on=['Key'], indicator=True)

C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Aero Rotor Kit_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Aero Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Centric Premium Brake Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Centric Premium Brake Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Centric Premium Brake Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Centric Premium Brake Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Cryo Brake Rotor_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\CTEK Brake Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\CTEK Brake Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\FMP Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\FMP Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\GCX Disc Brake Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\GCX Disc Brake Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Painted Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Painted Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Premium Brake Rotors_JNP_Apps.csv
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Premium Brake Rotors_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Select Sport Brake Rotor_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Select Sport Brake Rotor_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Sport Brake Rotor_PartCat_Apps.csv!
C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\99_Downloads\Comparison_File_rotor\CSVs\Sport Cryo Brake FRotor_PartCat_Apps.csv!

In [25]:
df_output

,BaseVehicleID,Qty,PartType,MfrLabel,Position,Part,Make,Model,Year,Key
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.02006CSL$Disc Brake Rotor$1991$Alfa Romeo$...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.02006CSL$Disc Brake Rotor$1992$Alfa Romeo$...
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.02006CSL$Disc Brake Rotor$1993$Alfa Romeo$...
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.02006CSL$Disc Brake Rotor$1994$Alfa Romeo$...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.02006CSL$Disc Brake Rotor$1995$Alfa Romeo$...
...,...,...,...,...,...,...,...,...,...,...
211584,161443.0,2.0,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.86017F,Kenworth,W990,2023.0,320.86017F$Disc Brake Rotor$2023$Kenworth$W990...
211585,161443.0,2.0,Disc Brake Rotor,Centric GCX FC Elemental Protection,Rear,320.86017F,Kenworth,W990,2023.0,320.86017F$Disc Brake Rotor$2023$Kenworth$W990...
211586,162683.0,2.0,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.86017F,Mack,Pinnacle,2023.0,320.86017F$Disc Brake Rotor$2023$Mack$Pinnacle...
211587,162683.0,2.0,Disc Brake Rotor,Centric GCX FC Elemental Protection,Rear,320.86017F,Mack,Pinnacle,2023.0,320.86017F$Disc Brake Rotor$2023$Mack$Pinnacle...
211588,167594.0,2.0,Disc Brake Rotor,Centric GCX FC Elemental Protection,Front,320.86017F,Tiffin,Allegro Red 360,2023.0,320.86017F$Disc Brake Rotor$2023$Tiffin$Allegr...

In [ ]:
df_output

In [15]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\99_Downloads\\Comparison_File_rotor\\JNP\\CSV_Files\\CTEK Brake Rotors_JNP_Apps.csv'

In [8]:
df_in=pd.read_excel(file_link[1],sheet_name="Export")
df_in

,PRODUCT_ID,PRODUCT_NAME,HQ_LINE_ABBREVIATION,ITEM_TYPE,PRODUCT_DESCRIPTION,Supplier Item Number Coverage,Supplier ID Coverage,Item Type Coverage,Expanded Item Number Coverage,Item Number Compressed Coverage,...,Features and Benefits 3 Coverage,Brand Coverage,Prop65 Required Flag Coverage,Is UPC Required? Coverage,Single UPC Coverage,Reason for No UPC Coverage,Height Coverage,Width Coverage,Length/Depth Coverage,Weight Coverage
0,napa_us_7497990,NB 4885502,NB,Brake Rotor and Hub Assembly,BRAKE ROTOR/HUB,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,napa_us_7590613,NB 4885507,NB,Brake Rotor,BRAKE ROTOR ONLY,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,napa_us_7499267,NB 4885508,NB,Brake Rotor and Hub Assembly,BRAKE ROTOR/HUB,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,napa_us_7502730,NB 4885515,NB,Brake Rotor and Hub Assembly,BRAKE ROTOR/HUB,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,napa_us_7730056,NB 4885518,NB,Brake Rotor,BRAKE ROTOR ONLY,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20190,napa_us_88936717,UBQ99100,UBQ,Parking Brake Cable Connector,BRAKE CABLE,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
20191,napa_us_88936719,UBQ99110,UBQ,Parking Brake Cable Connector,BRAKE CABLE,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
20192,napa_us_88935236,UBQBC500A,UBQ,Parking Brake Cable,BRAKE CABLE,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
20193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20194,Applied filters:\nSUPPLIER_NAME is Brake Parts...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_cleaned=pd.melt(df_in,id_vars=['PRODUCT_NAME', 'ITEM_TYPE'], value_vars=[ 'Supplier Item Number Coverage',
       'Supplier ID Coverage', 'Item Type Coverage',
       'Expanded Item Number Coverage', 'Item Number Compressed Coverage',
       'Online Display Name Coverage', 
       'Interchange Coverage', 'OE Interchange Coverage',
       'Shipping Exclusions? Coverage', 'Salability Restrictions Coverage',
       'Shipping Exclusions info Coverage', 'Harmonize Code Coverage',
       'Proper Shipping Name Coverage', 'Hazardous Class or Division Coverage',
       'UN ID Number Coverage', 'Package Group Coverage',
       'Label Codes Coverage', 'Application Item? Coverage',
       'UNSPSC Code Coverage', 'HQ Line Coverage', 'Group Code Coverage',
       'Jobber F.O.Q. Coverage', 'Jobber Std Pkg Coverage',
       'Product Classification Coverage', 'DC Cost (USD) Coverage',
       'Goldenrod Price Coverage', 'Blue Price Coverage',
       'Master Installer Coverage', 'Green Price Coverage',
       'Red/Retail (USD) Coverage', 'List (USD) Coverage',
       'Core Pricing? Coverage', 'Per Car Qty Coverage',
       'Supplier UOM Coverage', 'Disposition Code Coverage',
       'Date Product Available Coverage', 'ORM-D Coverage',
       'Regulated? Coverage', 'Standard Package Coverage',
       'Unit Desg Coverage', 'ws_UPS Coverage',
       'Is Sold To Consumer-US Coverage',
       'Quantity of Eaches in Package Coverage', 'DC Core (USD) Coverage',
       'List Core (USD) Coverage', 'Jobber Core Coverage',
       'Core Code Coverage', 'Primary Image Coverage',
       'Prop65 Statement Coverage', 'Prop 65 PDF Coverage', 'SDS PDF Coverage',
       'Warranty PDF Coverage', 'Product Features Coverage',
       'Features and Benefits 1 Coverage', 'Features and Benefits 2 Coverage',
       'Features and Benefits 3 Coverage', 'Brand Coverage',
       'Prop65 Required Flag Coverage', 'Is UPC Required? Coverage',
       'Single UPC Coverage', 'Reason for No UPC Coverage', 'Height Coverage',
       'Width Coverage', 'Length/Depth Coverage', 'Weight Coverage'],value_name='input_value', ignore_index=False)

In [10]:
df_cleaned

,PRODUCT_NAME,ITEM_TYPE,variable,input_value
0,NB 4885502,Brake Rotor and Hub Assembly,Supplier Item Number Coverage,1.0
1,NB 4885507,Brake Rotor,Supplier Item Number Coverage,1.0
2,NB 4885508,Brake Rotor and Hub Assembly,Supplier Item Number Coverage,1.0
3,NB 4885515,Brake Rotor and Hub Assembly,Supplier Item Number Coverage,1.0
4,NB 4885518,Brake Rotor,Supplier Item Number Coverage,1.0
...,...,...,...,...
20190,UBQ99100,Parking Brake Cable Connector,Weight Coverage,1.0
20191,UBQ99110,Parking Brake Cable Connector,Weight Coverage,1.0
20192,UBQBC500A,Parking Brake Cable,Weight Coverage,1.0
20193,NaN,NaN,Weight Coverage,NaN
20194,NaN,NaN,Weight Coverage,NaN

In [11]:
df_cleaned['Key']="BPI"+df_cleaned['ITEM_TYPE']+df_cleaned['PRODUCT_NAME']+df_cleaned['variable']

In [12]:
df_cleaned=df_cleaned[['PRODUCT_NAME','ITEM_TYPE','variable','Key','input_value']]

In [30]:
df_db1=pd.read_excel(r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Enrichment&Core\WIP\Napa_Core_Smartsheet_Filling.xlsx',sheet_name="Part_1",skiprows=[0],header=[1])
df_db1

,Unnamed: 0,Type,Key,Date
0,NaN,Smartsheet,AutoliteGlow PlugASP1103Application Item? Cove...,2024-11-11
1,NaN,NaN,AutoliteGlow PlugASP1103Blue Price Coverage,2025-01-30
2,NaN,NaN,AutoliteGlow PlugASP1103Brand Coverage,2024-11-11
3,NaN,NaN,AutoliteGlow PlugASP1103Core Code Coverage,2025-01-23
4,NaN,NaN,AutoliteGlow PlugASP1103Core Pricing? Coverage,2024-11-11
...,...,...,...,...
779158,NaN,NaN,TRICOWiper BladeTRINPW28Jobber Std Pkg Coverage,2024-11-11
779159,NaN,NaN,TRICOWiper BladeTRINPW28Label Codes Coverage,2024-11-11
779160,NaN,NaN,TRICOWiper BladeTRINPW28Length/Depth Coverage,2024-11-11
779161,NaN,NaN,TRICOWiper BladeTRINPW28List (USD) Coverage,2024-11-11
779162,NaN,NaN,TRICOWiper BladeTRINPW28List Core (USD) Coverage,2024-11-11

In [31]:
df_db2=pd.read_excel(r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Enrichment&Core\WIP\Napa_Core_Smartsheet_Filling.xlsx',sheet_name="Part_2",skiprows=[0],header=[1])
df_db2

,Unnamed: 0,Type,Key,Date
0,NaN,Smartsheet,BPIBrake HoseUBQ610104Weight Coverage,2024-11-11
1,NaN,NaN,BPIBrake HoseUBQ610104Width Coverage,2024-11-11
2,NaN,NaN,BPIBrake HoseUBQ610104Reason for No UPC Coverage,2024-11-11
3,NaN,NaN,BPIBrake HoseUBQ610104Prop65 Required Flag Cov...,2024-11-11
4,NaN,NaN,BPIBrake HoseUBQ610104Product Features Coverage,2024-11-11
...,...,...,...,...
779158,NaN,NaN,BPIBrake RotorNBO4885573Reason for No UPC Cove...,2024-11-11
779159,NaN,NaN,BPIBrake RotorNBO4885571Reason for No UPC Cove...,2024-11-11
779160,NaN,NaN,BPIBrake RotorNBO4885550Reason for No UPC Cove...,2024-11-11
779161,NaN,NaN,BPIBrake RotorNBO4885518Reason for No UPC Cove...,2024-11-11
779162,NaN,NaN,BPIBrake RotorNBO4885507Reason for No UPC Cove...,2024-11-11

In [32]:
df_db=pd.concat([df_db1, df_db2])

In [33]:
df_db=df_db[df_db['Key'].str.startswith('BPI')]

In [34]:
df_db=df_db[['Key','Date']]
df_db['db_value']=np.where(df_db['Date'].isna(),0,1 )

In [35]:
df_db=df_db[['Key','db_value']]

In [36]:
df_db['db_value'].value_counts()

db_value
1    1284699
0     227031
Name: count, dtype: int64

In [37]:
df=pd.merge(df_db,df_cleaned,how='inner')

In [38]:
df['Difference']=np.where(df['db_value']!=df['input_value'],1,0)

In [39]:
df_final=df[df['Difference']==1]
df_final

,Key,db_value,PRODUCT_NAME,ITEM_TYPE,variable,input_value,Difference
11,BPIBleeder Screw CapUBP23556Features and Benef...,1,UBP23556,Bleeder Screw Cap,Features and Benefits 2 Coverage,0.0,1
12,BPIBleeder Screw CapUBP23556Features and Benef...,1,UBP23556,Bleeder Screw Cap,Features and Benefits 3 Coverage,0.0,1
43,BPIBleeder Screw CapUBP83151Features and Benef...,1,UBP83151,Bleeder Screw Cap,Features and Benefits 2 Coverage,0.0,1
44,BPIBleeder Screw CapUBP83151Features and Benef...,1,UBP83151,Bleeder Screw Cap,Features and Benefits 3 Coverage,0.0,1
75,BPIBleeder Screw CapUBP83152Features and Benef...,1,UBP83152,Bleeder Screw Cap,Features and Benefits 2 Coverage,0.0,1
...,...,...,...,...,...,...,...
1222159,BPIBrake HoseUBQ36527Prop65 Required Flag Cove...,1,UBQ36527,Brake Hose,Prop65 Required Flag Coverage,0.0,1
1222160,BPIBrake HoseUBQ32102Prop65 Required Flag Cove...,1,UBQ32102,Brake Hose,Prop65 Required Flag Coverage,0.0,1
1222161,BPIBrake HoseUBQ23807Prop65 Required Flag Cove...,1,UBQ23807,Brake Hose,Prop65 Required Flag Coverage,0.0,1
1222162,BPIBrake HoseUBQ22700Prop65 Required Flag Cove...,1,UBQ22700,Brake Hose,Prop65 Required Flag Coverage,0.0,1
1222163,BPIBrake HoseUBQ11147Prop65 Required Flag Cove...,1,UBQ11147,Brake Hose,Prop65 Required Flag Coverage,0.0,1

In [40]:
df_final.to_excel(r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Enrichment&Core\Comparison\Core\20250410_BPI_CoreMismatch.xlsx',sheet_name='Comparision')