In [34]:
import os
import pandas as pd
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import re
import openpyxl
import numpy as np

In [35]:
folder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\28_NAPA_Scorecard'
OFolder=r'C:\Users\vikram.vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\28_NAPA_Scorecard\NAPA_Mandatory_Cleaned'

In [36]:
file_list=[]
for (root, dirs, file) in os.walk(folder):
    for f in file:
        if ('.xlsm') in f:
                    file_list.append(f)
file_list

['20250529_Mandatory_Autolite.xlsm',
 '20250529_Mandatory_BPI.xlsm',
 '20250529_Mandatory_Trico.xlsm']

In [37]:
file_link=[]

for i in range(len(file_list)):
     for r,d,f in os.walk(folder):
          for files in f:
               if files == file_list[i]:
                    file_link.append(os.path.join(r,files))

In [38]:
len(file_link)

3

In [39]:
file_link[1]

'C:\\Users\\vikram.vadhirajan\\OneDrive - Trico\\FBG\\01_DRA\\00_Projects\\28_NAPA_Scorecard\\20250529_Mandatory_BPI.xlsm'

In [40]:
df_Mand_Attr=pd.read_excel(r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory_Attributes.xlsx', sheet_name="Mandatory_Attributes")

In [41]:
df_Mand_Attr

,Brand,Part Type,Attribute,Key
0,BPI,Bleeder Screw,Head Diameter,BPIBleeder ScrewHead Diameter
1,BPI,Bleeder Screw,Cap Included,BPIBleeder ScrewCap Included
2,BPI,Bleeder Screw,Bleeder Repair Screw Hex Size,BPIBleeder ScrewBleeder Repair Screw Hex Size
3,BPI,Bleeder Screw,Bleeder Screw Check Valve,BPIBleeder ScrewBleeder Screw Check Valve
4,BPI,Bleeder Screw,Bleeder Screw Head Drive Type,BPIBleeder ScrewBleeder Screw Head Drive Type
...,...,...,...,...
1489,NaN,NaN,NaN,NaN
1490,NaN,NaN,NaN,NaN
1491,NaN,NaN,NaN,NaN
1492,NaN,NaN,NaN,NaN
1493,BPI,Brake Shoe Anchor Spring Lock,SDS Required,BPIBrake Shoe Anchor Spring LockSDS Required

In [42]:
def clean_column_names(col_name):
    col_name = col_name.strip() # Remove leading and trailing whitespaces
    col_name = re.sub(r"[^a-zA-Z0-9()]", " ", col_name).strip() # Replace non-alphanumeric characters with " "
    return col_name

In [43]:
df_Mand_Attr

,Brand,Part Type,Attribute,Key
0,BPI,Bleeder Screw,Head Diameter,BPIBleeder ScrewHead Diameter
1,BPI,Bleeder Screw,Cap Included,BPIBleeder ScrewCap Included
2,BPI,Bleeder Screw,Bleeder Repair Screw Hex Size,BPIBleeder ScrewBleeder Repair Screw Hex Size
3,BPI,Bleeder Screw,Bleeder Screw Check Valve,BPIBleeder ScrewBleeder Screw Check Valve
4,BPI,Bleeder Screw,Bleeder Screw Head Drive Type,BPIBleeder ScrewBleeder Screw Head Drive Type
...,...,...,...,...
1489,NaN,NaN,NaN,NaN
1490,NaN,NaN,NaN,NaN
1491,NaN,NaN,NaN,NaN
1492,NaN,NaN,NaN,NaN
1493,BPI,Brake Shoe Anchor Spring Lock,SDS Required,BPIBrake Shoe Anchor Spring LockSDS Required

In [44]:
df_Mand_Attr['Part Type'].unique()

array(['Bleeder Screw', 'Bleeder Screw Cap',
       'Bleeder Screw Repair / Service Kit',
       'Brake Backing Plate Assembly', 'Brake Caliper',
       'Brake Wheel Cylinder Boot Kit', 'Brake Master Cylinder',
       'Brake Proportioning Valve', 'Brake Master Cylinder Reservoir',
       'Brake Wheel Cylinder Cup', 'Brake Wheel Cylinder Retainer Kit',
       'Caliper Bolt', 'Disc Brake Hardware Kit', 'Brake Wheel Cylinder',
       'Brake Cylinder Repair / Service Kit', 'Brake Shoe Hardware Kit',
       'Caliper Seal and Boot Kit', 'Caliper Bolt Kit',
       'Disc Brake Boot Kit', 'Disc Brake Bushing Kit',
       'Caliper Bolt Sleeve', 'Caliper Damper Kit',
       'Caliper Pin Retainer', 'Caliper Piston', 'Disc Brake Check Valve',
       'Disc Brake Clip', 'Caliper Guide Pin', 'Disc Brake Screw',
       'Caliper Seal Kit', 'Brake Rotor Shim', 'Caliper Spring',
       'Brake Pad Wear Indicator', 'Drum Brake Bolt',
       'Brake Actuating Lever', 'Brake Shoe Adjuster Cable Guide',
       'Brake Shoe Adjuster Cable', 'Brake Backing Plate Hole Cover',
       'Brake Shoe Adjuster Kit', 'Brake Shoe Adjuster Lever',
       'Brake Shoe Adjuster Repair / Service Kit',
       'Brake Shoe Adjuster Screw Assy', 'Brake Shoe Anchor Pin',
       'Glow Plug', 'Spark Plug', 'Wiper Arm', 'Wiper Blade',
       'Wiper Blade Adapter', 'Wiper Blade Refill',
       'Windshield Washer Pump', 'Brake Shoe Anchor Spring Lock',
       'Brake Shoe Anchor Support Bracket', 'Brake Shoe Hold-Down Cup',
       'Brake Shoe Hold-Down Kit', 'Brake Shoe Hold-Down Nails',
       'Brake Shoe Clip', 'Brake Lock System',
       'Brake Shoe Adjuster Screw Kit', 'Brake Shoe Spring',
       'Brake Shoe Spring Kit', 'Brake Shoe Stud', 'Brake Washer',
       'Wheel Cylinder to Brake Shoe Link', 'Trailer Brake Clip',
       'Trailer Brake Installation Kit', 'Trailer Brake Magnet',
       'Trailer Brake Magnet Retainer', 'Trailer Brake Pulse Preventer',
       'Trailer Brake Replacement Cable and Pin', 'Brake Hose Banjo Bolt',
       'Brake Hose', 'Brake Hose Lock', 'Brake Tubing Kit',
       'Parking Brake Cable', 'Parking Brake Cable Connector',
       'Parking Brake Hardware Kit', 'Parking Brake Lever Pivot Pin',
       'Parking Brake Spring', 'Brake Check Valve', 'Brake Drum',
       'Brake Rotor', 'Brake Rotor Hub', 'Brake Rotor and Hub Assembly',
       'Cabinet', 'Cabinet Base', 'Wheel Bearing Dust Cap', 'Lug Nut',
       'Nut Kit', 'Rim Clamp', 'Brake Master Cylinder Cap', 'Bolt',
       'Washer Kit', 'Gasket', 'Sealing Washer', 'Seal', 'Switch',
       'Trailer Brake Controller', 'Electrical Connector',
       'Wiring Harness Kit', 'Wiring Harness', 'Vehicle Battery',
       'Sensor', 'Hub Cleaner Pad', 'Spindle Nut', 'Spindle Locknut Kit',
       'Brake Align Gauge', 'Brake Bleeder', 'Brake Align Hub Cleaner',
       'Brake Align Tool Set', 'Brake Align Washer',
       'Clutch Master Cylinder Repair / Service Kit', nan], dtype=object)

In [45]:
df_FBG_Status=pd.read_excel(r'C:\Users\vikram.vadhirajan\OneDrive - Trico\Documents - Product Support India Romania\Catalog\Score card\NAPA\Mandatory\Reference\Brakes_NAPA_FBG_Base_JNP.xlsx', sheet_name="article-export")

In [46]:
df_FBG_Status

,Article Number,Brand,Region,Product Group,Product Group Overrides,Product Line,Publishing Countries,Article Status Code,Article Status Description,Parent article number,Children article numbers
0,1000,NAPA,Main,Disc Brake Caliper Seal Kit,NaN,None / Blank,NaN,2,Available,1000,NaN
1,1019,NAPA,Main,Disc Brake Caliper Seal Kit,NaN,None / Blank,NaN,2,Available,1019,NaN
2,1020,NAPA,Main,Disc Brake Caliper Seal Kit,NaN,None / Blank,NaN,2,Available,1020,NaN
3,1027,NAPA,Main,Disc Brake Caliper Seal Kit,NaN,None / Blank,NaN,2,Available,1027,NaN
4,1028,NAPA,Main,Disc Brake Caliper Seal Kit,NaN,None / Blank,NaN,2,Available,1028,NaN
...,...,...,...,...,...,...,...,...,...,...,...
41757,89378,NAPA,Main,Disc Brake Caliper Repair Kit,NaN,None / Blank,NaN,2,Available,89378,NaN
41758,22247,NAPA,Main,Brake Master Cylinder Reservoir Cap,NaN,NaN,NaN,A,While Supplies Last,22247,NaN
41759,4073,NAPA,Main,Brake Master Cylinder Reservoir Cap,NaN,NaN,NaN,A,While Supplies Last,4073,NaN
41760,6018,NAPA,Main,Brake Master Cylinder Reservoir Cap,NaN,NaN,NaN,A,While Supplies Last,6018,NaN
41761,57510,NAPA,Main,Brake Hydraulic Line Lock Hardware Kit,NaN,NaN,NaN,2,Available,57510,NaN

In [47]:
df_FBG_Status=df_FBG_Status[['Article Number','Parent article number','Product Group','Article Status Description']]
df_FBG_Status=df_FBG_Status.drop_duplicates()

In [48]:
df_FBG_Status['Article Number'] = df_FBG_Status['Article Number'].astype(str)

In [49]:
df_Mand_Attr

,Brand,Part Type,Attribute,Key
0,BPI,Bleeder Screw,Head Diameter,BPIBleeder ScrewHead Diameter
1,BPI,Bleeder Screw,Cap Included,BPIBleeder ScrewCap Included
2,BPI,Bleeder Screw,Bleeder Repair Screw Hex Size,BPIBleeder ScrewBleeder Repair Screw Hex Size
3,BPI,Bleeder Screw,Bleeder Screw Check Valve,BPIBleeder ScrewBleeder Screw Check Valve
4,BPI,Bleeder Screw,Bleeder Screw Head Drive Type,BPIBleeder ScrewBleeder Screw Head Drive Type
...,...,...,...,...
1489,NaN,NaN,NaN,NaN
1490,NaN,NaN,NaN,NaN
1491,NaN,NaN,NaN,NaN
1492,NaN,NaN,NaN,NaN
1493,BPI,Brake Shoe Anchor Spring Lock,SDS Required,BPIBrake Shoe Anchor Spring LockSDS Required

In [ ]:
## Baseline Combine
df_a=pd.DataFrame()
for i in range(len(file_link)):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    Brand=file_link[i].split("Mandatory_")[1].split(".xlsm")[0]
    FileName=rf"{OFolder}\Baseline\NAPA_SKU_Attributes_Baseline.xlsx"
    for s in sheetname:
        if (("STEP" not in s) and ("Cover" not in s)and ("Promotional Item" not in s)):
            print(s)
            df=pd.read_excel(file_link[i],sheet_name=s, skiprows=9)
            df.rename(columns=clean_column_names, inplace=True)
            #print(df.columns)
            #df["Filename"]=file_link[i].replace(repl,"")
            PartName=df["Parent ID"].mode()[0].split(" (")[0]
            if PartName in df_Mand_Attr['Part Type'].unique():
                df["Part Type"]=PartName
                df.rename(columns={'Name':'PartNumber'}, inplace=True)
                #print(df.columns)
                df = df[df.PartNumber != 'SAMPLE123']
                df['PartNumber']=df['PartNumber'].astype(str)
                df=df.merge(df_FBG_Status, how='left', left_on='PartNumber', right_on='Article Number')
                Column=df_Mand_Attr[df_Mand_Attr['Part Type']==PartName]['Attribute'].tolist()
                Columns = [re.sub(r"[^a-zA-Z0-9()]", ' ', col).strip() for col in Column]
                Columns.insert(0, 'Part Type')
                Columns.insert(1, 'PartNumber')
                Columns.insert(2, 'Parent article number')
                Columns.insert(3, 'Product Group')
                Columns.insert(4, 'Article Status Description')
                df=df[Columns]
                df=df.melt(id_vars=['Part Type', 'PartNumber', 'Parent article number', 'Product Group', 'Article Status Description'],
                        var_name='Attribute', value_name='Value')
                df['Brand']=Brand
                df_a=pd.concat([df_a, df], ignore_index=True)
                #RemoveColumns=['Product ID', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>',]
                # df = df.drop(columns=RemoveColumns)
                # last_column = df.pop(df.columns[-1])
                # df.insert(0, last_column.name, last_column)
            else:
                pass
with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
    df_a.to_excel(writer, sheet_name="Raw", index=False)

['Cover', 'Glow Plug', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'STEPChanges', 'Spark Plug', 'STEPCellStatus']
Glow Plug
Spark Plug
['Cover', 'STEPChanges', 'Hose', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Bleeder Screw', 'Bleeder Screw Cap', 'Bleeder Screw Repair   Service', 'Brake Backing Plate Assembly', 'Brake Caliper', 'Brake Wheel Cylinder Boot Kit', 'Brake Master Cylinder', 'Brake Cylinder Repair   Servic', 'Brake Proportioning Valve', 'Brake Master Cylinder Reservoi', 'Brake Wheel Cylinder', 'Brake Wheel Cylinder Cup', 'Brake Wheel Cylinder Retainer ', 'Caliper Bolt', 'Disc Brake Boot Kit', 'Disc Brake Bushing Kit', 'Caliper Bolt Sleeve', 'Caliper Damper Kit', 'Caliper Pin Retainer', 'Caliper Piston', 'Disc Brake Check Valve', 'Disc Brake Clip', 'Caliper Guide Pin', 'Disc Brake Hardware Kit', 'Disc Brake Screw', 'Caliper Seal and Boot Kit', 'Caliper Seal Kit', 'Brake Rotor Shim', 'Caliper Spring', 'Brake Pad Wear Indicator', 'Caliper Bolt Kit', 'Drum Brake Bolt', 'Brake Actuating Lever', 'Brake Shoe Adjuster Cable Guid', 'Brake Shoe Adjuster Cable', 'Brake Backing Plate Hole Cover', 'Brake Shoe Adjuster Kit', 'Brake Shoe Adjuster Lever', 'Brake Shoe Adjuster Repair   S', 'Brake Shoe Adjuster Screw Assy', 'Brake Shoe Anchor Pin', 'Brake Shoe Anchor Spring Lock', 'Brake Shoe Anchor Support Brac', 'Brake Shoe Hold-Down Cup', 'Brake Shoe Hold-Down Kit', 'Brake Shoe Hold-Down Nails', 'Brake Shoe Clip', 'Brake Shoe Hardware Kit', 'Brake Lock System', 'Brake Shoe Adjuster Screw Kit', 'Brake Shoe Spring', 'Brake Shoe Spring Kit', 'Brake Shoe Stud', 'Brake Washer', 'Wheel Cylinder to Brake Shoe L', 'Trailer Brake Clip', 'Trailer Brake Installation Kit', 'Trailer Brake Magnet', 'Trailer Brake Magnet Retainer', 'Trailer Brake Pulse Preventer', 'Trailer Brake Replacement Cabl', 'Brake Hose Banjo Bolt', 'STEPLogging', 'Brake Hose', 'Brake Hose Lock', 'Brake Tubing Kit', 'Parking Brake Cable', 'Parking Brake Cable Connector', 'Parking Brake Hardware Kit', 'Parking Brake Lever Pivot Pin', 'Parking Brake Spring', 'Brake Check Valve', 'Brake Drum', 'Brake Rotor', 'Brake Rotor Hub', 'Brake Rotor and Hub Assembly', 'Product Assortment', 'Cabinet', 'Cabinet Base', 'Training Video', 'Wheel Bearing Dust Cap', 'Lug Nut', 'Nut Kit', 'Rim Clamp', 'Brake Master Cylinder Cap', 'Bolt', 'Washer Kit', 'Gasket', 'Sealing Washer', 'Seal', 'Switch', 'Trailer Brake Controller', 'Electrical Connector', 'Wiring Harness Kit', 'Wiring Harness', 'Vehicle Battery', 'Sensor', 'Hub Cleaner Pad', 'Spindle Nut', 'Spindle Locknut Kit', 'Brake Align Gauge', 'Brake Bleeder', 'Brake Align Hub Cleaner', 'Brake Align Tool Set', 'Brake Align Washer', 'Clutch Master Cylinder Repair ', 'Promotional Item', 'STEPCellStatus']
Hose
Bleeder Screw
Bleeder Screw Cap
Bleeder Screw Repair   Service
Brake Backing Plate Assembly
Brake Caliper
Brake Wheel Cylinder Boot Kit
Brake Master Cylinder
Brake Cylinder Repair   Servic
Brake Proportioning Valve
Brake Master Cylinder Reservoi
Brake Wheel Cylinder
Brake Wheel Cylinder Cup
Brake Wheel Cylinder Retainer
Caliper Bolt
Disc Brake Boot Kit
Disc Brake Bushing Kit
Caliper Bolt Sleeve
Caliper Damper Kit
Caliper Pin Retainer
Caliper Piston
Disc Brake Check Valve
Disc Brake Clip
Caliper Guide Pin
Disc Brake Hardware Kit
Disc Brake Screw
Caliper Seal and Boot Kit
Caliper Seal Kit
Brake Rotor Shim
Caliper Spring
Brake Pad Wear Indicator
Caliper Bolt Kit
Drum Brake Bolt
Brake Actuating Lever
Brake Shoe Adjuster Cable Guid
Brake Shoe Adjuster Cable
Brake Shoe Adjuster Kit
Brake Shoe Adjuster Lever
Brake Shoe Adjuster Repair   S
Brake Shoe Adjuster Screw Assy
Brake Shoe Anchor Pin
Brake Shoe Anchor Spring Lock
Brake Shoe Anchor Support Brac
Brake Shoe Hold-Down Cup
Brake Shoe Hold-Down Kit
Brake Shoe Hold-Down Nails
Brake Shoe Clip
Brake Shoe Hardware Kit
Brake Lock System
Brake Shoe Adjuster Screw Kit
Brake Shoe Spring
Brake Shoe Spring Kit
Brake Shoe Stud
Brake Washer
Wheel Cylinder to Brake Shoe L
Trailer Brake Clip
Trailer Brake Installation Kit
Trailer Brake Magnet
Trailer Brake Magnet Retainer
Trailer Brake Pulse Preventer
Trailer Brake Replacement Cabl
Brake Hose Banjo Bolt
Brake Hose
Brake Hose Lock
Brake Tubing Kit
Parking Brake Cable
Parking Brake Cable Connector
Parking Brake Hardware Kit
Parking Brake Lever Pivot Pin
Parking Brake Spring
Brake Check Valve
Brake Drum
Brake Rotor
Brake Rotor Hub
Brake Rotor and Hub Assembly
Product Assortment
Cabinet
Cabinet Base
Training Video
Wheel Bearing Dust Cap
Lug Nut
Nut Kit
Rim Clamp
Brake Master Cylinder Cap
Bolt
Washer Kit
Gasket
Sealing Washer
Seal
Switch
Trailer Brake Controller
Electrical Connector
Wiring Harness Kit
Wiring Harness
Vehicle Battery
Sensor
Hub Cleaner Pad
Spindle Nut
Spindle Locknut Kit
Brake Align Gauge
Brake Bleeder
Brake Align Hub Cleaner
Brake Align Tool Set
Brake Align Washer
Clutch Master Cylinder Repair
['Cover', 'STEPChanges', 'Product Assortment', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Display', 'Display Rack', 'Merchandiser', 'Sign', 'Wiper Arm', 'Wiper Blade', 'Wiper Blade Adapter', 'Wiper Blade Refill', 'Windshield Washer Pump', 'Promotional Item', 'STEPCellStatus']
Product Assortment
Display
Display Rack
Merchandiser
Sign
Wiper Arm
Wiper Blade
Wiper Blade Adapter
Wiper Blade Refill
Windshield Washer Pump

In [ ]:
for i in range(len(file_link)):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    Brand=file_link[i].split("Mandatory_")[1].split(".xlsm")[0]
    FileName=rf"{OFolder}\Baseline\NAPA_SKU_Attributes_"+Brand+"_Baseline.xlsx"
    with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
        for s in sheetname:
            if (("STEP" not in s) and ("Cover" not in s)and ("Promotional Item" not in s)):
                print(s)
                df=pd.read_excel(file_link[i],sheet_name=s, skiprows=9)
                df.rename(columns=clean_column_names, inplace=True)
                #print(df.columns)
                #df["Filename"]=file_link[i].replace(repl,"")
                PartName=df["Parent ID"].mode()[0].split(" (")[0]
                if PartName in df_Mand_Attr['Part Type'].unique():
                    df["Part Type"]=PartName
                    df.rename(columns={'Name':'PartNumber'}, inplace=True)
                    #print(df.columns)
                    df = df[df.PartNumber != 'SAMPLE123']
                    df['PartNumber']=df['PartNumber'].astype(str)
                    df=df.merge(df_FBG_Status, how='left', left_on='PartNumber', right_on='Article Number')
                    Column=df_Mand_Attr[df_Mand_Attr['Part Type']==PartName]['Attribute'].tolist()
                    Columns = [re.sub(r"[^a-zA-Z0-9()]", ' ', col).strip() for col in Column]
                    Columns.insert(0, 'Part Type')
                    Columns.insert(1, 'PartNumber')
                    Columns.insert(2, 'Parent article number')
                    Columns.insert(3, 'Product Group')
                    Columns.insert(4, 'Article Status Description')
                    df=df[Columns]
                    #RemoveColumns=['Product ID', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>',]
                    # df = df.drop(columns=RemoveColumns)
                    # last_column = df.pop(df.columns[-1])
                    # df.insert(0, last_column.name, last_column)
                    df.to_excel(writer, sheet_name=str(s), index=False)
                else:
                    pass

['Cover', 'Glow Plug', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'STEPChanges', 'Spark Plug', 'STEPCellStatus']
Glow Plug
Spark Plug
['Cover', 'STEPChanges', 'Hose', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Bleeder Screw', 'Bleeder Screw Cap', 'Bleeder Screw Repair   Service', 'Brake Backing Plate Assembly', 'Brake Caliper', 'Brake Wheel Cylinder Boot Kit', 'Brake Master Cylinder', 'Brake Cylinder Repair   Servic', 'Brake Proportioning Valve', 'Brake Master Cylinder Reservoi', 'Brake Wheel Cylinder', 'Brake Wheel Cylinder Cup', 'Brake Wheel Cylinder Retainer ', 'Caliper Bolt', 'Disc Brake Boot Kit', 'Disc Brake Bushing Kit', 'Caliper Bolt Sleeve', 'Caliper Damper Kit', 'Caliper Pin Retainer', 'Caliper Piston', 'Disc Brake Check Valve', 'Disc Brake Clip', 'Caliper Guide Pin', 'Disc Brake Hardware Kit', 'Disc Brake Screw', 'Caliper Seal and Boot Kit', 'Caliper Seal Kit', 'Brake Rotor Shim', 'Caliper Spring', 'Brake Pad Wear Indicator', 'Caliper Bolt Kit', 'Drum Brake Bolt', 'Brake Actuating Lever', 'Brake Shoe Adjuster Cable Guid', 'Brake Shoe Adjuster Cable', 'Brake Backing Plate Hole Cover', 'Brake Shoe Adjuster Kit', 'Brake Shoe Adjuster Lever', 'Brake Shoe Adjuster Repair   S', 'Brake Shoe Adjuster Screw Assy', 'Brake Shoe Anchor Pin', 'Brake Shoe Anchor Spring Lock', 'Brake Shoe Anchor Support Brac', 'Brake Shoe Hold-Down Cup', 'Brake Shoe Hold-Down Kit', 'Brake Shoe Hold-Down Nails', 'Brake Shoe Clip', 'Brake Shoe Hardware Kit', 'Brake Lock System', 'Brake Shoe Adjuster Screw Kit', 'Brake Shoe Spring', 'Brake Shoe Spring Kit', 'Brake Shoe Stud', 'Brake Washer', 'Wheel Cylinder to Brake Shoe L', 'Trailer Brake Clip', 'Trailer Brake Installation Kit', 'Trailer Brake Magnet', 'Trailer Brake Magnet Retainer', 'Trailer Brake Pulse Preventer', 'Trailer Brake Replacement Cabl', 'Brake Hose Banjo Bolt', 'STEPLogging', 'Brake Hose', 'Brake Hose Lock', 'Brake Tubing Kit', 'Parking Brake Cable', 'Parking Brake Cable Connector', 'Parking Brake Hardware Kit', 'Parking Brake Lever Pivot Pin', 'Parking Brake Spring', 'Brake Check Valve', 'Brake Drum', 'Brake Rotor', 'Brake Rotor Hub', 'Brake Rotor and Hub Assembly', 'Product Assortment', 'Cabinet', 'Cabinet Base', 'Training Video', 'Wheel Bearing Dust Cap', 'Lug Nut', 'Nut Kit', 'Rim Clamp', 'Brake Master Cylinder Cap', 'Bolt', 'Washer Kit', 'Gasket', 'Sealing Washer', 'Seal', 'Switch', 'Trailer Brake Controller', 'Electrical Connector', 'Wiring Harness Kit', 'Wiring Harness', 'Vehicle Battery', 'Sensor', 'Hub Cleaner Pad', 'Spindle Nut', 'Spindle Locknut Kit', 'Brake Align Gauge', 'Brake Bleeder', 'Brake Align Hub Cleaner', 'Brake Align Tool Set', 'Brake Align Washer', 'Clutch Master Cylinder Repair ', 'Promotional Item', 'STEPCellStatus']
Hose
Bleeder Screw
Bleeder Screw Cap
Bleeder Screw Repair   Service
Brake Backing Plate Assembly
Brake Caliper
Brake Wheel Cylinder Boot Kit
Brake Master Cylinder
Brake Cylinder Repair   Servic
Brake Proportioning Valve
Brake Master Cylinder Reservoi
Brake Wheel Cylinder
Brake Wheel Cylinder Cup
Brake Wheel Cylinder Retainer
Caliper Bolt
Disc Brake Boot Kit
Disc Brake Bushing Kit
Caliper Bolt Sleeve
Caliper Damper Kit
Caliper Pin Retainer
Caliper Piston
Disc Brake Check Valve
Disc Brake Clip
Caliper Guide Pin
Disc Brake Hardware Kit
Disc Brake Screw
Caliper Seal and Boot Kit
Caliper Seal Kit
Brake Rotor Shim
Caliper Spring
Brake Pad Wear Indicator
Caliper Bolt Kit
Drum Brake Bolt
Brake Actuating Lever
Brake Shoe Adjuster Cable Guid
Brake Shoe Adjuster Cable
Brake Shoe Adjuster Kit
Brake Shoe Adjuster Lever
Brake Shoe Adjuster Repair   S
Brake Shoe Adjuster Screw Assy
Brake Shoe Anchor Pin
Brake Shoe Anchor Spring Lock
Brake Shoe Anchor Support Brac
Brake Shoe Hold-Down Cup
Brake Shoe Hold-Down Kit
Brake Shoe Hold-Down Nails
Brake Shoe Clip
Brake Shoe Hardware Kit
Brake Lock System
Brake Shoe Adjuster Screw Kit
Brake Shoe Spring
Brake Shoe Spring Kit
Brake Shoe Stud
Brake Washer
Wheel Cylinder to Brake Shoe L
Trailer Brake Clip
Trailer Brake Installation Kit
Trailer Brake Magnet
Trailer Brake Magnet Retainer
Trailer Brake Pulse Preventer
Trailer Brake Replacement Cabl
Brake Hose Banjo Bolt
Brake Hose
Brake Hose Lock
Brake Tubing Kit
Parking Brake Cable
Parking Brake Cable Connector
Parking Brake Hardware Kit
Parking Brake Lever Pivot Pin
Parking Brake Spring
Brake Check Valve
Brake Drum
Brake Rotor
Brake Rotor Hub
Brake Rotor and Hub Assembly
Product Assortment
Cabinet
Cabinet Base
Training Video
Wheel Bearing Dust Cap
Lug Nut
Nut Kit
Rim Clamp
Brake Master Cylinder Cap
Bolt
Washer Kit
Gasket
Sealing Washer
Seal
Switch
Trailer Brake Controller
Electrical Connector
Wiring Harness Kit
Wiring Harness
Vehicle Battery
Sensor
Hub Cleaner Pad
Spindle Nut
Spindle Locknut Kit
Brake Align Gauge
Brake Bleeder
Brake Align Hub Cleaner
Brake Align Tool Set
Brake Align Washer
Clutch Master Cylinder Repair
['Cover', 'STEPChanges', 'Product Assortment', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Display', 'Display Rack', 'Merchandiser', 'Sign', 'Wiper Arm', 'Wiper Blade', 'Wiper Blade Adapter', 'Wiper Blade Refill', 'Windshield Washer Pump', 'Promotional Item', 'STEPCellStatus']
Product Assortment
Display
Display Rack
Merchandiser
Sign
Wiper Arm
Wiper Blade
Wiper Blade Adapter
Wiper Blade Refill
Windshield Washer Pump

In [59]:
cols=['Brand']
df_a = pd.DataFrame(columns=cols)

In [ ]:

for i in range(1,2):
    workbook=openpyxl.load_workbook(file_link[i])
    sheetname=workbook.sheetnames
    print(sheetname)
    Brand=file_link[i].split("Mandatory_")[1].split(".xlsm")[0]
    FileName=rf"{OFolder}\NAPA_SKU_Attributes_"+Brand+".xlsx"
    with pd.ExcelWriter(FileName, engine='xlsxwriter') as writer:
        for s in sheetname:
            if (("STEP" not in s) and ("Cover" not in s)and ("Promotional Item" not in s)):
                print(s)
                df=pd.read_excel(file_link[i],sheet_name=s, skiprows=9)
                df.rename(columns=clean_column_names, inplace=True)
                #print(df.columns)
                #df["Filename"]=file_link[i].replace(repl,"")
                PartName=df["Parent ID"].mode()[0].split(" (")[0]
                if PartName in df_Mand_Attr['Part Type'].unique():
                    df["Part Type"]=PartName
                    df.rename(columns={'Name':'PartNumber'}, inplace=True)
                    #print(df.columns)
                    df = df[df.PartNumber != 'SAMPLE123']
                    df['PartNumber']=df['PartNumber'].astype(str)
                    df=df.merge(df_FBG_Status, how='left', left_on='PartNumber', right_on='Article Number')
                    df=df[['Brand', 'Part Type', 'PartNumber' ,'Parent article number','Product Group','Article Status Description']]
                    #RemoveColumns=['Product ID', 'Working Column','Supplier Classification Reference', 'Manufacturer', 'ASG Vendor Name','<Parent ID>', '<Object Type Name>',]
                    # df = df.drop(columns=RemoveColumns)
                    # last_column = df.pop(df.columns[-1])
                    # df.insert(0, last_column.name, last_column)
                    df_a=pd.concat([df_a,df])
                else:
                    pass

['Cover', 'STEPChanges', 'Hose', 'STEPSettings', 'STEPSmartSheetModelInfo', 'STEPLocalization', 'STEPLOV', 'STEPSmartSheetSettings', 'Bleeder Screw', 'Bleeder Screw Cap', 'Bleeder Screw Repair   Service', 'Brake Backing Plate Assembly', 'Brake Caliper', 'Brake Wheel Cylinder Boot Kit', 'Brake Master Cylinder', 'Brake Cylinder Repair   Servic', 'Brake Proportioning Valve', 'Brake Master Cylinder Reservoi', 'Brake Wheel Cylinder', 'Brake Wheel Cylinder Cup', 'Brake Wheel Cylinder Retainer ', 'Caliper Bolt', 'Disc Brake Boot Kit', 'Disc Brake Bushing Kit', 'Caliper Bolt Sleeve', 'Caliper Damper Kit', 'Caliper Pin Retainer', 'Caliper Piston', 'Disc Brake Check Valve', 'Disc Brake Clip', 'Caliper Guide Pin', 'Disc Brake Hardware Kit', 'Disc Brake Screw', 'Caliper Seal and Boot Kit', 'Caliper Seal Kit', 'Brake Rotor Shim', 'Caliper Spring', 'Brake Pad Wear Indicator', 'Caliper Bolt Kit', 'Drum Brake Bolt', 'Brake Actuating Lever', 'Brake Shoe Adjuster Cable Guid', 'Brake Shoe Adjuster Cable', 'Brake Backing Plate Hole Cover', 'Brake Shoe Adjuster Kit', 'Brake Shoe Adjuster Lever', 'Brake Shoe Adjuster Repair   S', 'Brake Shoe Adjuster Screw Assy', 'Brake Shoe Anchor Pin', 'Brake Shoe Anchor Spring Lock', 'Brake Shoe Anchor Support Brac', 'Brake Shoe Hold-Down Cup', 'Brake Shoe Hold-Down Kit', 'Brake Shoe Hold-Down Nails', 'Brake Shoe Clip', 'Brake Shoe Hardware Kit', 'Brake Lock System', 'Brake Shoe Adjuster Screw Kit', 'Brake Shoe Spring', 'Brake Shoe Spring Kit', 'Brake Shoe Stud', 'Brake Washer', 'Wheel Cylinder to Brake Shoe L', 'Trailer Brake Clip', 'Trailer Brake Installation Kit', 'Trailer Brake Magnet', 'Trailer Brake Magnet Retainer', 'Trailer Brake Pulse Preventer', 'Trailer Brake Replacement Cabl', 'Brake Hose Banjo Bolt', 'STEPLogging', 'Brake Hose', 'Brake Hose Lock', 'Brake Tubing Kit', 'Parking Brake Cable', 'Parking Brake Cable Connector', 'Parking Brake Hardware Kit', 'Parking Brake Lever Pivot Pin', 'Parking Brake Spring', 'Brake Check Valve', 'Brake Drum', 'Brake Rotor', 'Brake Rotor Hub', 'Brake Rotor and Hub Assembly', 'Product Assortment', 'Cabinet', 'Cabinet Base', 'Training Video', 'Wheel Bearing Dust Cap', 'Lug Nut', 'Nut Kit', 'Rim Clamp', 'Brake Master Cylinder Cap', 'Bolt', 'Washer Kit', 'Gasket', 'Sealing Washer', 'Seal', 'Switch', 'Trailer Brake Controller', 'Electrical Connector', 'Wiring Harness Kit', 'Wiring Harness', 'Vehicle Battery', 'Sensor', 'Hub Cleaner Pad', 'Spindle Nut', 'Spindle Locknut Kit', 'Brake Align Gauge', 'Brake Bleeder', 'Brake Align Hub Cleaner', 'Brake Align Tool Set', 'Brake Align Washer', 'Clutch Master Cylinder Repair ', 'Promotional Item', 'STEPCellStatus']
Hose
Bleeder Screw
Bleeder Screw Cap
Bleeder Screw Repair   Service
Brake Backing Plate Assembly
Brake Caliper
Brake Wheel Cylinder Boot Kit
Brake Master Cylinder
Brake Cylinder Repair   Servic
Brake Proportioning Valve
Brake Master Cylinder Reservoi
Brake Wheel Cylinder
Brake Wheel Cylinder Cup
Brake Wheel Cylinder Retainer
Caliper Bolt
Disc Brake Boot Kit
Disc Brake Bushing Kit
Caliper Bolt Sleeve
Caliper Damper Kit
Caliper Pin Retainer
Caliper Piston
Disc Brake Check Valve
Disc Brake Clip
Caliper Guide Pin
Disc Brake Hardware Kit
Disc Brake Screw
Caliper Seal and Boot Kit
Caliper Seal Kit
Brake Rotor Shim
Caliper Spring
Brake Pad Wear Indicator
Caliper Bolt Kit
Drum Brake Bolt
Brake Actuating Lever
Brake Shoe Adjuster Cable Guid
Brake Shoe Adjuster Cable
Brake Shoe Adjuster Kit
Brake Shoe Adjuster Lever
Brake Shoe Adjuster Repair   S
Brake Shoe Adjuster Screw Assy
Brake Shoe Anchor Pin
Brake Shoe Anchor Spring Lock
Brake Shoe Anchor Support Brac
Brake Shoe Hold-Down Cup
Brake Shoe Hold-Down Kit
Brake Shoe Hold-Down Nails
Brake Shoe Clip
Brake Shoe Hardware Kit
Brake Lock System
Brake Shoe Adjuster Screw Kit
Brake Shoe Spring
Brake Shoe Spring Kit
Brake Shoe Stud
Brake Washer
Wheel Cylinder to Brake Shoe L
Trailer Brake Clip
Trailer Brake Installation Kit
Trailer Brake Magnet
Trailer Brake Magnet Retainer
Trailer Brake Pulse Preventer
Trailer Brake Replacement Cabl
Brake Hose Banjo Bolt
Brake Hose
Brake Hose Lock
Brake Tubing Kit
Parking Brake Cable
Parking Brake Cable Connector
Parking Brake Hardware Kit
Parking Brake Lever Pivot Pin
Parking Brake Spring
Brake Check Valve
Brake Drum
Brake Rotor
Brake Rotor Hub
Brake Rotor and Hub Assembly
Product Assortment
Cabinet
Cabinet Base
Training Video
Wheel Bearing Dust Cap
Lug Nut
Nut Kit
Rim Clamp
Brake Master Cylinder Cap
Bolt
Washer Kit
Gasket
Sealing Washer
Seal
Switch
Trailer Brake Controller
Electrical Connector
Wiring Harness Kit
Wiring Harness
Vehicle Battery
Sensor
Hub Cleaner Pad
Spindle Nut
Spindle Locknut Kit
Brake Align Gauge
Brake Bleeder
Brake Align Hub Cleaner
Brake Align Tool Set
Brake Align Washer
Clutch Master Cylinder Repair

In [62]:
df_a

,Brand,Part Type,PartNumber,Parent article number,Product Group,Article Status Description
0,NaN,Bleeder Screw,10591,10591,Brake Bleeder Screw,Available
1,NaN,Bleeder Screw,11410,11410,Brake Bleeder Screw,Available
2,NaN,Bleeder Screw,11596,11596,Brake Bleeder Screw,Available
3,NaN,Bleeder Screw,20089,20089,Brake Bleeder Screw,Available
4,NaN,Bleeder Screw,22066,22066,Brake Bleeder Screw,Available
...,...,...,...,...,...,...
0,NaN,Brake Align Hub Cleaner,BA950400,NaN,NaN,NaN
1,NaN,Brake Align Hub Cleaner,BA951375,BA951375,Wheel Hub Cleaning Tool Kit,Discontinued
0,NaN,Brake Align Tool Set,BA98000,NaN,NaN,NaN
0,NaN,Brake Align Washer,BA950120,NaN,NaN,NaN
0,NaN,Clutch Master Cylinder Repair / Service Kit,278,278,Brake Master Cylinder Repair Kit,Available