In [2]:
import pandas as pd
import datetime
import warnings
import numpy as np
from IPython.display import clear_output
# Ignore all warnings (not recommended in general)
warnings.filterwarnings("ignore")

In [3]:
VIO=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\98_Misc_Codes\VIOdata2023.xlsx",sheet_name='VIOdata2023')

In [4]:
VIO['Keys']=VIO['YearID'].astype(str)+' '+VIO['MakeName']+' '+VIO['ModelName'].astype(str)#+'$'+VIO['Liter'].astype(str)+'$'+VIO['CC'].astype(str)+'$'+VIO['Cylinders'].astype(str)
VIO_Grouped=VIO.groupby('Keys')['VehCount'].sum().reset_index()
VIO_Keys=len(VIO_Grouped['Keys'].unique())
VIO_VehCount=VIO_Grouped['VehCount'].sum()
print(f"In the VIO Dataset, there are {VIO_Keys} unique combination and {VIO_VehCount} Number of Vehicles")

In the VIO Dataset, there are 22199 unique combination and 314320122 Number of Vehicles

In [5]:
for i in range(len(VIO)):
    if "." not in str(VIO['Liter'][i]):
        VIO['Liter'][i]=str(VIO['Liter'][i])+".0"

VIO['Liter']=np.where(VIO['Liter']=='-',0,VIO['Liter'])
VIO['Liter'].astype(float)

0         1.8
1         1.8
2         1.8
3         1.8
4         1.4
         ...
243094    3.0
243095    3.9
243096    3.5
243097    3.5
243098    2.9
Name: Liter, Length: 243099, dtype: float64

In [6]:
VIO['Keys1']=VIO['YearID'].astype(str)+' '+VIO['MakeName'].astype(str)+" "+VIO['ModelName'].astype(str)+' '+VIO['SubModelName'].astype(str)+' '+VIO['Liter'].astype(str)+'L, '+VIO['BlockType'].astype(str)+VIO['Cylinders'].astype(str)+", "+VIO['FuelTypeName']+", VIN "+VIO['EngineVINName'].astype(str)+", Des "+VIO['EngineDesignationName'].astype(str)+", "+VIO['CylinderHeadTypeName'].astype(str)

In [7]:
VIO['Keys1'][11]

'2014 Honda Civic LX 1.8L, L4, GAS, VIN -, Des R18Z1, SOHC'

In [8]:
VIO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243099 entries, 0 to 243098
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Region                     243099 non-null  object
 1   Version                    243099 non-null  int64
 2   VehicleTypeGroupName       243099 non-null  object
 3   VehicleTypeName            243099 non-null  object
 4   MakeName                   243099 non-null  object
 5   ModelName                  243099 non-null  object
 6   YearID                     243099 non-null  int64
 7   BaseVehicleID              243099 non-null  int64
 8   SubModelName               243099 non-null  object
 9   RegionID                   243099 non-null  int64
 10  Liter                      243099 non-null  object
 11  CC                         243099 non-null  object
 12  CID                        243099 non-null  object
 13  Cylinders                  243099 non-null  object
 14  BlockType                  243099 non-null  object
 15  EngBoreIn                  243099 non-null  object
 16  EngBoreMetric              243099 non-null  object
 17  EngStrokeIn                243099 non-null  object
 18  EngStrokeMetric            243099 non-null  object
 19  EngineBaseID               243099 non-null  int64
 20  EngineDesignationName      243092 non-null  object
 21  EngineVINName              243099 non-null  object
 22  AspirationName             243099 non-null  object
 23  CylinderHeadTypeName       243099 non-null  object
 24  FuelTypeName               243099 non-null  object
 25  EngineVersion              240491 non-null  object
 26  IgnitionSystemTypeName     241336 non-null  object
 27  FuelDeliveryTypeName       243099 non-null  object
 28  FuelDeliverySubTypeName    242846 non-null  object
 29  FuelSystemControlTypeName  242005 non-null  object
 30  FuelSystemDesignName       241985 non-null  object
 31  MfrName                    242821 non-null  object
 32  ValvesPerEngine            243099 non-null  object
 33  HorsePower                 243081 non-null  object
 34  BodyNumDoors               243099 non-null  object
 35  BodyTypeName               243099 non-null  object
 36  DriveTypeName              243099 non-null  object
 37  VehCount                   243099 non-null  int64
 38  Keys                       243099 non-null  object
 39  Keys1                      243099 non-null  object
dtypes: int64(6), object(34)
memory usage: 74.2+ MB

In [9]:
OFolder=r'C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\99_Automation_Projects\98_Misc_Codes'

In [9]:
with pd.ExcelWriter(OFolder+'\\'+f'VIO_Data.xlsx') as writer:  # doctest: +SKIP
    VIO.to_excel(writer,index=False, sheet_name='Raw')

In [53]:
def split_with_second_delimiter(text, delimiter):
  """
  Splits a text only once with the second occurrence of the given delimiter.

  Args:
      text: The text to be split.
      delimiter: The delimiter to split on.

  Returns:
      tuple: A tuple containing the parts before and after the second delimiter,
              or (text, '') if no second delimiter is found.
  """

  # Find the first and second occurrences of the delimiter
  first_index = text.find(delimiter)
  second_index = text.find(delimiter, first_index + 2)

  # Check if at least two delimiters exist
  if second_index != -1:
    # Split the text based on the second delimiter
    return text[:second_index], text[second_index + 1:]
  else:
    # No second delimiter found, return the original text
    return text, ''

# Example usage
text = "2013 GMC Sierra 1500 WT 5.3L, V8, Flex, VIN 0, Des LMG, 16V, USA/Canada"
delimiter = ','

result = split_with_second_delimiter(text, delimiter)

print(result[0])  # Output: ('apple, banana', 'orange,grape')

2013 GMC Sierra 1500 WT 5.3L, V8

In [10]:
SPIW=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\10_Spark Plug Wire Set\Inputs\RFQ_Request_Wires 2_Zoren-phase-2.xlsx",sheet_name="Table1")

In [1]:
JNP_coils=pd.read_excel(r"C:\Users\Vikram.Vadhirajan\OneDrive - Trico\FBG\01_DRA\00_Projects\14_Ignition_Coil\Inputs\JNP Ignition Coil Data.xlsx",sheet_name='Sheet1')

NameError: name 'pd' is not defined

In [11]:
VIO['Keys']

0                   2012 Honda Civic
1                  2010 Toyota Prius
2                2020 Toyota Corolla
3                   2013 Honda Civic
4               2014 Chevrolet Cruze
                     ...
243094    2023 Jeep Grand Wagoneer L
243095       2023 Ferrari F8 Tributo
243096              2023 Lexus LS500
243097              2023 Lexus LS500
243098      2023 Bentley Flying Spur
Name: Keys, Length: 243099, dtype: object

In [12]:
SPIW.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Make    326 non-null    object
 1   Model   326 non-null    object
 2   Custom  325 non-null    float64
 3   Keys    326 non-null    object
dtypes: float64(1), object(3)
memory usage: 10.3+ KB

In [13]:
SKU_Coverage_Total=pd.merge(VIO,SPIW[['Keys']], on='Keys',how='inner')

In [14]:
SKU_Coverage_Total

,Region,Version,VehicleTypeGroupName,VehicleTypeName,MakeName,ModelName,YearID,BaseVehicleID,SubModelName,RegionID,...,FuelSystemDesignName,MfrName,ValvesPerEngine,HorsePower,BodyNumDoors,BodyTypeName,DriveTypeName,VehCount,Keys,Keys1
0,US,202301,Light Duty,Car,Chevrolet,Impala,2011,96738,LT,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,89008,2011 Chevrolet Impala,"2011 Chevrolet Impala LT 3.5L, V6, FLEX, VIN K..."
1,US,202301,Light Duty,Car,Chevrolet,Impala,2011,96738,LS,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,32612,2011 Chevrolet Impala,"2011 Chevrolet Impala LS 3.5L, V6, FLEX, VIN K..."
2,US,202301,Light Duty,Car,Chevrolet,Impala,2011,96738,LTZ,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,6780,2011 Chevrolet Impala,"2011 Chevrolet Impala LTZ 3.9L, V6, FLEX, VIN ..."
3,CA,202210,Light Duty,Car,Chevrolet,Impala,2011,96738,LT,2,...,SFI,General Motors,12,U/K,4,Sedan,FWD,4580,2011 Chevrolet Impala,"2011 Chevrolet Impala LT 3.5L, V6, FLEX, VIN K..."
4,US,202301,Light Duty,Car,Chevrolet,Impala,2011,96738,Police,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,3743,2011 Chevrolet Impala,"2011 Chevrolet Impala Police 3.9L, V6, FLEX, V..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3872,CA,202210,Light Duty,Car,Buick,Century,1988,2561,Estate Wagon,2,...,SFI,General Motors,12,U/K,4,Wagon,FWD,1,1988 Buick Century,"1988 Buick Century Estate Wagon 3.8L, V6, GAS,..."
3873,CA,202210,Light Duty,Car,Buick,Century,1988,2561,Estate Wagon,2,...,MPI,General Motors,12,U/K,4,Wagon,FWD,1,1988 Buick Century,"1988 Buick Century Estate Wagon 2.8L, V6, GAS,..."
3874,US,202301,Light Duty,Car,Buick,Century,1988,2561,Limited,1,...,TBI,General Motors,8,U/K,2,Coupe,FWD,1,1988 Buick Century,"1988 Buick Century Limited 2.5L, L4, GAS, VIN ..."
3875,US,202301,Light Duty,Car,Chrysler,300,2023,164793,S,1,...,SFI,Chrysler,24,300,4,Sedan,RWD,3,2023 Chrysler 300,"2023 Chrysler 300 S 3.6L, V6, GAS, VIN G, Des ..."
3876,US,202301,Light Duty,Car,Chrysler,300,2023,164793,C,1,...,SFI,Chrysler,16,485,4,Sedan,RWD,3,2023 Chrysler 300,"2023 Chrysler 300 C 6.4L, V8, GAS, VIN J, Des ..."

In [15]:
SKU_Coverage_Total=SKU_Coverage_Total.sort_values(by='VehCount', ascending=False, inplace=False)
SKU_Coverage_Total.head()

,Region,Version,VehicleTypeGroupName,VehicleTypeName,MakeName,ModelName,YearID,BaseVehicleID,SubModelName,RegionID,...,FuelSystemDesignName,MfrName,ValvesPerEngine,HorsePower,BodyNumDoors,BodyTypeName,DriveTypeName,VehCount,Keys,Keys1
0,US,202301,Light Duty,Car,Chevrolet,Impala,2011,96738,LT,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,89008,2011 Chevrolet Impala,"2011 Chevrolet Impala LT 3.5L, V6, FLEX, VIN K..."
8,US,202301,Light Duty,Car,Chevrolet,Impala,2008,28619,LT,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,63822,2008 Chevrolet Impala,"2008 Chevrolet Impala LT 3.5L, V6, FLEX, VIN K..."
27,US,202301,Light Duty,Truck,Ford,F-150,2004,17874,XL,1,...,SFI,Ford,24,U/K,4,Extended Cab Pickup,4WD,63411,2004 Ford F-150,"2004 Ford F-150 XL 5.4L, V8, GAS, VIN 5, Des -..."
83,US,202301,Light Duty,Car,Chevrolet,Impala,2009,30132,LT,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,52331,2009 Chevrolet Impala,"2009 Chevrolet Impala LT 3.5L, V6, FLEX, VIN K..."
9,US,202301,Light Duty,Car,Chevrolet,Impala,2008,28619,LS,1,...,SFI,General Motors,12,U/K,4,Sedan,FWD,49747,2008 Chevrolet Impala,"2008 Chevrolet Impala LS 3.5L, V6, FLEX, VIN K..."

In [16]:
SKU_Coverage_Total['FuelTypeName'].value_counts()

GAS                          3289
FLEX                          485
BI-FUEL                        44
DIESEL                         40
CNG                            12
FULL HYBRID EV-GAS (FHEV)       6
BATTERY EV (EV/BEV)             1
Name: FuelTypeName, dtype: int64

In [17]:
Cond1=SKU_Coverage_Total['Region']=='US'
Cond2=~SKU_Coverage_Total['FuelTypeName'].isin(['DIESEL','BATTERY EV (EV/BEV)'])
cond=Cond1 & (Cond2)

SKU_Coverage_Total_Filtered=SKU_Coverage_Total[cond]
SKU_Coverage_Total_Filtered.shape

(2042, 40)

In [18]:
with pd.ExcelWriter(OFolder+'\\'+f'SPW_2phase.xlsx') as writer:  # doctest: +SKIP
    SKU_Coverage_Total_Filtered.to_excel(writer,index=False, sheet_name='Raw')